window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Popüler ve Tanınmış Ülkeler
    { kategori: "Başkent", seviye: 1, soru: "Türkiye'nin başkenti neresidir?", secenekler: { A: "İstanbul", B: "Ankara", C: "İzmir", D: "Bursa" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 1, soru: "Fransa'nın başkenti neresidir?", secenekler: { A: "Lyon", B: "Marsilya", C: "Paris", D: "Nice" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 1, soru: "Almanya'nın başkenti neresidir?", secenekler: { A: "Münih", B: "Berlin", C: "Frankfurt", D: "Hamburg" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 2, soru: "İngiltere'nin başkenti neresidir?", secenekler: { A: "Londra", B: "Manchester", C: "Liverpool", D: "Birmingham" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 2, soru: "İtalya'nın başkenti neresidir?", secenekler: { A: "Milano", B: "Venedik", C: "Floransa", D: "Roma" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 2, soru: "İspanya'nın başkenti neresidir?", secenekler: { A: "Barselona", B: "Madrid", C: "Valensiya", D: "Sevilla" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 3, soru: "Rusya'nın başkenti neresidir?", secenekler: { A: "St. Petersburg", B: "Moskova", C: "Kazan", D: "Novosibirsk" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 3, soru: "Amerika Birleşik Devletleri'nin başkenti neresidir?", secenekler: { A: "New York", B: "Washington D.C.", C: "Los Angeles", D: "Chicago" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 3, soru: "Japonya'nın başkenti neresidir?", secenekler: { A: "Osaka", B: "Kyoto", C: "Tokyo", D: "Hiroşima" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 4, soru: "Çin'in başkenti neresidir?", secenekler: { A: "Şanghay", B: "Pekin", C: "Hong Kong", D: "Guangzhou" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 4, soru: "Azerbaycan'ın başkenti neresidir?", secenekler: { A: "Bakü", B: "Gence", C: "Sumgayıt", D: "Nahçıvan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 4, soru: "Yunanistan'ın başkenti neresidir?", secenekler: { A: "Selanik", B: "Atina", C: "Patras", D: "Kandiye" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 5, soru: "Mısır'ın başkenti neresidir?", secenekler: { A: "İskenderiye", B: "Kahire", C: "Luksor", D: "Gize" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 5, soru: "Hollanda'nın başkenti neresidir?", secenekler: { A: "Rotterdam", B: "Lahey", C: "Amsterdam", D: "Utrecht" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 5, soru: "Brezilya'nın başkenti neresidir?", secenekler: { A: "Rio de Janeiro", B: "Sao Paulo", C: "Brasilia", D: "Salvador" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 6, soru: "Güney Kore'nin başkenti neresidir?", secenekler: { A: "Busan", B: "Seul", C: "Incheon", D: "Daegu" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 6, soru: "Arjantin'in başkenti neresidir?", secenekler: { A: "Buenos Aires", B: "Cordoba", C: "Rosario", D: "Mendoza" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 6, soru: "Hindistan'ın başkenti neresidir?", secenekler: { A: "Mumbai", B: "Yeni Delhi", C: "Kalküta", D: "Chennai" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 7, soru: "Kanada'nın başkenti neresidir?", secenekler: { A: "Toronto", B: "Montreal", C: "Ottawa", D: "Vancouver" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 7, soru: "İsviçre'nin başkenti neresidir?", secenekler: { A: "Zürih", B: "Cenevre", C: "Bern", D: "Basel" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 7, soru: "Avusturya'nın başkenti neresidir?", secenekler: { A: "Viyana", B: "Salzburg", C: "Innsbruck", D: "Graz" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 8, soru: "İran'ın başkenti neresidir?", secenekler: { A: "Tebriz", B: "Meşhed", C: "Tahran", D: "İsfahan" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 8, soru: "Irak'ın başkenti neresidir?", secenekler: { A: "Basra", B: "Bağdat", C: "Musul", D: "Erbil" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 8, soru: "Suudi Arabistan'ın başkenti neresidir?", secenekler: { A: "Cidde", B: "Mekke", C: "Riyad", D: "Medine" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 9, soru: "Portekiz'in başkenti neresidir?", secenekler: { A: "Porto", B: "Lizbon", C: "Braga", D: "Coimbra" }, dogruCevap: "B" },

    // 26-50: Avrupa ve Asya Detayları
    { kategori: "Başkent", seviye: 10, soru: "Ukrayna'nın başkenti neresidir?", secenekler: { A: "Harkiv", B: "Kiev", C: "Odessa", D: "Lviv" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 10, soru: "Belçika'nın başkenti neresidir?", secenekler: { A: "Brüksel", B: "Anvers", C: "Gent", D: "Brugge" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 11, soru: "Polonya'nın başkenti neresidir?", secenekler: { A: "Krakov", B: "Varşova", C: "Gdansk", D: "Wroclaw" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 11, soru: "Macaristan'ın başkenti neresidir?", secenekler: { A: "Budapeşte", B: "Debrecen", C: "Pecs", D: "Segedin" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 12, soru: "Çek Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Prag", B: "Brno", C: "Ostrava", D: "Plzen" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 12, soru: "Slovakya'nın başkenti neresidir?", secenekler: { A: "Bratislava", B: "Kosice", C: "Nitra", D: "Zilina" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 13, soru: "Hırvatistan'ın başkenti neresidir?", secenekler: { A: "Split", B: "Zagreb", C: "Dubrovnik", D: "Zadar" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 13, soru: "Sırbistan'ın başkenti neresidir?", secenekler: { A: "Belgrad", B: "Novi Sad", C: "Niş", D: "Kragujevac" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 14, soru: "Bulgaristan'ın başkenti neresidir?", secenekler: { A: "Filibe", B: "Sofya", C: "Varna", D: "Burgas" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 14, soru: "Romanya'nın başkenti neresidir?", secenekler: { A: "Bükreş", B: "Kaloşvar", C: "Köstence", D: "Yaş" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 15, soru: "İrlanda'nın başkenti neresidir?", secenekler: { A: "Dublin", B: "Cork", C: "Galway", D: "Belfast" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 15, soru: "İskoçya'nın başkenti neresidir?", secenekler: { A: "Glasgow", B: "Edinburgh", C: "Aberdeen", D: "Dundee" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 16, soru: "Norveç'in başkenti neresidir?", secenekler: { A: "Bergen", B: "Oslo", C: "Trondheim", D: "Stavanger" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 16, soru: "İsveç'in başkenti neresidir?", secenekler: { A: "Goteborg", B: "Stockholm", C: "Malmö", D: "Uppsala" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 17, soru: "Finlandiya'nın başkenti neresidir?", secenekler: { A: "Tampere", B: "Helsinki", C: "Turku", D: "Oulu" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 17, soru: "Danimarka'nın başkenti neresidir?", secenekler: { A: "Kopenhag", B: "Aarhus", C: "Odense", D: "Aalborg" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 18, soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Phuket", B: "Bangkok", C: "Chiang Mai", D: "Pattaya" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 18, soru: "Endonezya'nın başkenti neresidir?", secenekler: { A: "Cakarta", B: "Bali", C: "Surabaya", D: "Bandung" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 19, soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Ho Chi Minh", B: "Hanoi", C: "Da Nang", D: "Hue" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 19, soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "Karaçi", B: "Lahor", C: "İslamabad", D: "Peşaver" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 20, soru: "Kazakistan'ın başkenti neresidir?", secenekler: { A: "Almati", B: "Astana", C: "Çimkent", D: "Aktau" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 20, soru: "Özbekistan'ın başkenti neresidir?", secenekler: { A: "Semerkant", B: "Taşkent", C: "Buhara", D: "Hiva" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 21, soru: "Türkmenistan'ın başkenti neresidir?", secenekler: { A: "Aşkabat", B: "Merv", C: "Türkmenbaşı", D: "Daşoğuz" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 21, soru: "Kırgızistan'ın başkenti neresidir?", secenekler: { A: "Oş", B: "Bişkek", C: "Celal-Abad", D: "Narın" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 22, soru: "Gürcistan'ın başkenti neresidir?", secenekler: { A: "Batum", B: "Tiflis", C: "Kutaisi", D: "Gori" }, dogruCevap: "B" },

    // 51-75: Orta Doğu, Afrika ve Amerika Kıtası
    { kategori: "Başkent", seviye: 23, soru: "Suriye'nın başkenti neresidir?", secenekler: { A: "Halep", B: "Şam", C: "Humus", D: "Lazkiye" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 23, soru: "Lübnan'ın başkenti neresidir?", secenekler: { A: "Trablusşam", B: "Beyrut", C: "Sayda", D: "Zahle" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 24, soru: "Ürdün'ün başkenti neresidir?", secenekler: { A: "Akabe", B: "Amman", C: "İrbid", D: "Zarka" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 24, soru: "İsrail'in başkenti (uluslararası tanınırlığa göre en büyük şehri) neresidir?", secenekler: { A: "Kudüs", B: "Tel Aviv", C: "Hayfa", D: "Eylat" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 25, soru: "Fas'ın başkenti neresidir?", secenekler: { A: "Kazablanka", B: "Marakeş", C: "Rabat", D: "Fes" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 25, soru: "Cezayir'in başkenti neresidir?", secenekler: { A: "Oran", B: "Cezayir", C: "Konstantin", D: "Annabe" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 26, soru: "Tunus'un başkenti neresidir?", secenekler: { A: "Susa", B: "Tunus", C: "Kayrevan", D: "Bizerte" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 26, soru: "Güney Afrika Cumhuriyeti'nin üç başkentinden biri hangisidir?", secenekler: { A: "Johannesburg", B: "Cape Town", C: "Durban", D: "Soweto" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 27, soru: "Nijerya'nın başkenti neresidir?", secenekler: { A: "Lagos", B: "Abuja", C: "Kano", D: "Ibadan" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 27, soru: "Kenya'nın başkenti neresidir?", secenekler: { A: "Mombasa", B: "Nairobi", C: "Kisumu", D: "Nakuru" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 28, soru: "Etiyopya'nın başkenti neresidir?", secenekler: { A: "Addis Ababa", B: "Dire Dawa", C: "Gondar", D: "Lalibela" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 28, soru: "Meksika'nın başkenti neresidir?", secenekler: { A: "Cancun", B: "Meksiko", C: "Guadalajara", D: "Monterrey" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 29, soru: "Küba'nın başkenti neresidir?", secenekler: { A: "Santiago", B: "Havana", C: "Varadero", D: "Holguin" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 29, soru: "Kolombiya'nın başkenti neresidir?", secenekler: { A: "Medellin", B: "Bogota", C: "Cali", D: "Cartagena" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 30, soru: "Peru'nun başkenti neresidir?", secenekler: { A: "Cusco", B: "Lima", C: "Arequipa", D: "Iquitos" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 30, soru: "Şili'nin başkenti neresidir?", secenekler: { A: "Valparaiso", B: "Santiago", C: "Concepcion", D: "Antofagasta" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 31, soru: "Uruguay'ın başkenti neresidir?", secenekler: { A: "Montevideo", B: "Punta del Este", C: "Salto", D: "Colonia" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 31, soru: "Avustralya'nın başkenti neresidir?", secenekler: { A: "Sidney", B: "Melbourne", C: "Canberra", D: "Perth" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 32, soru: "Yeni Zelanda'nın başkenti neresidir?", secenekler: { A: "Auckland", B: "Wellington", C: "Christchurch", D: "Queenstown" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 32, soru: "Güney Kıbrıs Rum Yönetimi'nin başkenti neresidir?", secenekler: { A: "Limasol", B: "Larnaka", C: "Lefkoşa", D: "Baf" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 33, soru: "Kuzey Kıbrıs Türk Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Girne", B: "Gazimağusa", C: "Lefkoşa", D: "Güzelyurt" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 33, soru: "Afganistan'ın başkenti neresidir?", secenekler: { A: "Kandahar", B: "Kabil", C: "Herat", D: "Mezar-ı Şerif" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 34, soru: "Filipinler'in başkenti neresidir?", secenekler: { A: "Manila", B: "Cebu", C: "Davao", D: "Quezon" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 34, soru: "Malezya'nın başkenti neresidir?", secenekler: { A: "Kuala Lumpur", B: "George Town", C: "Johor Bahru", D: "Melaka" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 35, soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Ulanbatur", B: "Erdenet", C: "Darhan", D: "Ölgii" }, dogruCevap: "A" },

    // 76-100: Zor ve Daha Az Bilinenler
    { kategori: "Başkent", seviye: 36, soru: "İzlanda'nın başkenti neresidir?", secenekler: { A: "Reykjavik", B: "Akureyri", C: "Keflavik", D: "Vík" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 36, soru: "Malta'nın başkenti neresidir?", secenekler: { A: "Valletta", B: "Sliema", C: "Mdina", D: "St. Julian's" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 37, soru: "Lüksemburg'un başkenti neresidir?", secenekler: { A: "Lüksemburg", B: "Esch", C: "Diekirch", D: "Echternach" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 37, soru: "Estonya'nın başkenti neresidir?", secenekler: { A: "Tallinn", B: "Tartu", C: "Pärnu", D: "Narva" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 38, soru: "Letonya'nın başkenti neresidir?", secenekler: { A: "Riga", B: "Liepaja", C: "Daugavpils", D: "Jurmala" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 38, soru: "Litvanya'nın başkenti neresidir?", secenekler: { A: "Vilnius", B: "Kaunas", C: "Klaipeda", D: "Siauliai" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 39, soru: "Slovenya'nın başkenti neresidir?", secenekler: { A: "Ljubljana", B: "Maribor", C: "Celje", D: "Koper" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 39, soru: "Arnavutluk'un başkenti neresidir?", secenekler: { A: "Tiran", B: "Durres", C: "Vlora", D: "İşkodra" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 40, soru: "Makedonya'nın (Kuzey Makedonya) başkenti neresidir?", secenekler: { A: "Üsküp", B: "Manastır", C: "Ohrid", D: "Tetovo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 40, soru: "Karadağ'ın başkenti neresidir?", secenekler: { A: "Podgorica", B: "Kotor", C: "Budva", D: "Çetine" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 41, soru: "Bosna-Hersek'in başkenti neresidir?", secenekler: { A: "Saraybosna", B: "Mostar", C: "Banja Luka", D: "Tuzla" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 41, soru: "Ermenistan'ın başkenti neresidir?", secenekler: { A: "Erivan", B: "Gümrü", C: "Vanadzor", D: "Dilican" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 42, soru: "Bangladeş'in başkenti neresidir?", secenekler: { A: "Dakka", B: "Chittagong", C: "Sylhet", D: "Rajshahi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 42, soru: "Nepal'in başkenti neresidir?", secenekler: { A: "Katmandu", B: "Pokhara", C: "Lalitpur", D: "Biratnagar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 43, soru: "Sri Lanka'nın başkenti neresidir?", secenekler: { A: "Kolombo", B: "Kandy", C: "Galle", D: "Jaffna" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 43, soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Doha", B: "Al Wakrah", C: "Al Khor", D: "Lusail" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 44, soru: "Kuveyt'in başkenti neresidir?", secenekler: { A: "Kuveyt", B: "Jahra", C: "Ahmadi", D: "Salmiya" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 44, soru: "Umman'ın başkenti neresidir?", secenekler: { A: "Muskat", B: "Salalah", C: "Nizwa", D: "Sohar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 45, soru: "Yemen'in başkenti neresidir?", secenekler: { A: "Sana", B: "Aden", C: "Taiz", D: "Hodeida" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 45, soru: "Libya'nın başkenti neresidir?", secenekler: { A: "Trablus", B: "Bingazi", C: "Misrata", D: "Tobruk" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 46, soru: "Senegal'in başkenti neresidir?", secenekler: { A: "Dakar", B: "Saint-Louis", C: "Thies", D: "Ziguinchor" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 46, soru: "Gana'nın başkenti neresidir?", secenekler: { A: "Akra", B: "Kumasi", C: "Tamale", D: "Sekondi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 47, soru: "Madagaskar'ın başkenti neresidir?", secenekler: { A: "Antananarivo", B: "Toamasina", C: "Mahajanga", D: "Antsirabe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 48, soru: "Ekvador'un başkenti neresidir?", secenekler: { A: "Quito", B: "Guayaquil", C: "Cuenca", D: "Manta" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 49, soru: "Venezuela'nın başkenti neresidir?", secenekler: { A: "Karakas", B: "Maracaibo", C: "Valencia", D: "Merida" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 50, soru: "Sudan'ın başkenti neresidir?", secenekler: { A: "Hartum", B: "Omdurman", C: "Port Sudan", D: "Kassala" }, dogruCevap: "A" }, 
    // Başkent Soruları Devamı (51 - 150)
    { kategori: "Başkent", seviye: 51, soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Phuket", B: "Bangkok", C: "Chiang Mai", D: "Pattaya" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 52, soru: "Güney Afrika Cumhuriyeti'nin yürütme başkenti hangisidir?", secenekler: { A: "Johannesburg", B: "Pretoria", C: "Cape Town", D: "Durban" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 53, soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Ho Chi Minh", B: "Hanoi", C: "Da Nang", D: "Hue" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 54, soru: "Küba'nın başkenti neresidir?", secenekler: { A: "Havana", B: "Santiago", C: "Varadero", D: "Holguin" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 55, soru: "Norveç'in başkenti neresidir?", secenekler: { A: "Bergen", B: "Oslo", C: "Trondheim", D: "Stavanger" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 56, soru: "İsveç'in başkenti neresidir?", secenekler: { A: "Stockholm", B: "Goteborg", C: "Malmö", D: "Uppsala" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 57, soru: "Finlandiya'nın başkenti neresidir?", secenekler: { A: "Tampere", B: "Turku", C: "Helsinki", D: "Espoo" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 58, soru: "Danimarka'nın başkenti neresidir?", secenekler: { A: "Kopenhag", B: "Aarhus", C: "Odense", D: "Aalborg" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 59, soru: "İrlanda'nın başkenti neresidir?", secenekler: { A: "Belfast", B: "Dublin", C: "Cork", D: "Galway" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 60, soru: "İsviçre'nin başkenti neresidir?", secenekler: { A: "Zürih", B: "Cenevre", C: "Bern", D: "Basel" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 61, soru: "Avusturya'nın başkenti neresidir?", secenekler: { A: "Viyana", B: "Salzburg", C: "Innsbruck", D: "Graz" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 62, soru: "Belçika'nın başkenti neresidir?", secenekler: { A: "Brüksel", B: "Anvers", C: "Gent", D: "Brugge" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 63, soru: "Macaristan'ın başkenti neresidir?", secenekler: { A: "Debrecen", B: "Budapeşte", C: "Pécs", D: "Szeged" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 64, soru: "Çek Cumhuriyeti'nın başkenti neresidir?", secenekler: { A: "Prag", B: "Brno", C: "Ostrava", D: "Plzeň" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 65, soru: "Polonya'nın başkenti neresidir?", secenekler: { A: "Krakov", B: "Gdańsk", C: "Varşova", D: "Wrocław" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 66, soru: "Romanya'nın başkenti neresidir?", secenekler: { A: "Bükreş", B: "Kaloşvar", C: "Köstence", D: "Yaş" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 67, soru: "Bulgaristan'ın başkenti neresidir?", secenekler: { A: "Filibe", B: "Varna", C: "Sofya", D: "Burgaz" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 68, soru: "Sırbistan'ın başkenti neresidir?", secenekler: { A: "Belgrad", B: "Novi Sad", C: "Niş", D: "Kragujevac" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 69, soru: "Hırvatistan'ın başkenti neresidir?", secenekler: { A: "Split", B: "Zagreb", C: "Dubrovnik", D: "Rijeka" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 70, soru: "Slovenya'nın başkenti neresidir?", secenekler: { A: "Ljubljana", B: "Maribor", C: "Celje", D: "Koper" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 71, soru: "Lüksemburg'un başkenti neresidir?", secenekler: { A: "Lüksemburg", B: "Esch", C: "Diekirch", D: "Echternach" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 72, soru: "Monako'nun başkenti neresidir?", secenekler: { A: "Monako", B: "Monte Carlo", C: "Cannes", D: "Nice" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 73, soru: "Vatikan'ın başkenti neresidir?", secenekler: { A: "Vatikan", B: "Roma", C: "Floransa", D: "Milano" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 74, soru: "Malta'nın başkenti neresidir?", secenekler: { A: "Valletta", B: "Sliema", C: "Mdina", D: "Gozo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 75, soru: "İzlanda'nın başkenti neresidir?", secenekler: { A: "Reykjavik", B: "Akureyri", C: "Keflavik", D: "Vik" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 76, soru: "Fas'ın başkenti neresidir?", secenekler: { A: "Kazablanka", B: "Marakeş", C: "Rabat", D: "Fes" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 77, soru: "Cezayir'in başkenti neresidir?", secenekler: { A: "Oran", B: "Cezayir", C: "Konstantin", D: "Annabe" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 78, soru: "Tunus'un başkenti neresidir?", secenekler: { A: "Susa", B: "Tunus", C: "Safakes", D: "Kayrevan" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 79, soru: "Libya'nın başkenti neresidir?", secenekler: { A: "Bingazi", B: "Misrata", C: "Trablus", D: "Tobruk" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 80, soru: "Sudan'ın başkenti neresidir?", secenekler: { A: "Hartum", B: "Cub", C: "Omdurman", D: "Port Sudan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 81, soru: "Etiyopya'nın başkenti neresidir?", secenekler: { A: "Addis Ababa", B: "Dire Dawa", C: "Gondar", D: "Lalibela" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 82, soru: "Kenya'nın başkenti neresidir?", secenekler: { A: "Mombasa", B: "Nairobi", C: "Kisumu", D: "Eldoret" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 83, soru: "Nijerya'nın başkenti neresidir?", secenekler: { A: "Lagos", B: "Kano", C: "Abuja", D: "Ibadan" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 84, soru: "Gana'nın başkenti neresidir?", secenekler: { A: "Kumasi", B: "Akra", C: "Tamale", D: "Sekondi" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 85, soru: "Senegal'in başkenti neresidir?", secenekler: { A: "Dakar", B: "Saint-Louis", C: "Thiès", D: "Ziguinchor" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 86, soru: "Somali'nin başkenti neresidir?", secenekler: { A: "Hargeisa", B: "Mogadişu", C: "Kismayo", D: "Berbera" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 87, soru: "Lübnan'ın başkenti neresidir?", secenekler: { A: "Trablusşam", B: "Beyrut", C: "Sayda", D: "Zahle" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 88, soru: "Ürdün'ün başkenti neresidir?", secenekler: { A: "Akabe", B: "Zarka", C: "Amman", D: "İrbid" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 89, soru: "Kuveyt'in başkenti neresidir?", secenekler: { A: "Kuveyt City", B: "Al Jahra", C: "Ahmadi", D: "Salmiya" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 90, soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Doha", B: "Al Khor", C: "Al Wakrah", D: "Lusail" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 91, soru: "Birleşik Arap Emirlikleri'nin başkenti neresidir?", secenekler: { A: "Dubai", B: "Abu Dabi", C: "Şarika", D: "Acman" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 92, soru: "Umman'ın başkenti neresidir?", secenekler: { A: "Maskat", B: "Salalah", C: "Nizwa", D: "Sohar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 93, soru: "Yemen'in başkenti neresidir?", secenekler: { A: "Aden", B: "Taiz", C: "Sana", D: "Hudeyde" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 94, soru: "Afganistan'ın başkenti neresidir?", secenekler: { A: "Kandahar", B: "Mezar-ı Şerif", C: "Kabil", D: "Herat" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 95, soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "Karaçi", B: "İslamabad", C: "Lahor", D: "Peşaver" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 96, soru: "Bangladeş'in başkenti neresidir?", secenekler: { A: "Dakka", B: "Chittagong", C: "Sylhet", D: "Rajshahi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 97, soru: "Nepal'in başkenti neresidir?", secenekler: { A: "Pokhara", B: "Katmandu", C: "Lalitpur", D: "Biratnagar" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 98, soru: "Sri Lanka'nın idari başkenti neresidir?", secenekler: { A: "Kolombo", B: "Kandy", C: "Sri Jayawardenepura Kotte", D: "Galle" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 99, soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Ulanbatur", B: "Erdenet", C: "Darhan", D: "Ölgii" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 100, soru: "Kuzey Kore'nin başkenti neresidir?", secenekler: { A: "Pyongyang", B: "Kaesong", C: "Wonsan", D: "Hamhung" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 101, soru: "Filipinler'in başkenti neresidir?", secenekler: { A: "Cebu", B: "Davao", C: "Manila", D: "Quezon" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 102, soru: "Malezya'nın başkenti neresidir?", secenekler: { A: "Kuala Lumpur", B: "George Town", C: "Kota Kinabalu", D: "Kuching" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 103, soru: "Endonezya'nın başkenti neresidir?", secenekler: { A: "Bali", B: "Cakarta", C: "Surabaya", D: "Bandung" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 104, soru: "Yeni Zelanda'nın başkenti neresidir?", secenekler: { A: "Auckland", B: "Wellington", C: "Christchurch", D: "Hamilton" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 105, soru: "Avustralya'nın başkenti neresidir?", secenekler: { A: "Sidney", B: "Melbourne", C: "Canberra", D: "Brisbane" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 106, soru: "Kolombiya'nın başkenti neresidir?", secenekler: { A: "Medellin", B: "Bogota", C: "Cali", D: "Cartagena" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 107, soru: "Venezuela'nın başkenti neresidir?", secenekler: { A: "Karakas", B: "Maracaibo", C: "Valencia", D: "Barquisimeto" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 108, soru: "Peru'nun başkenti neresidir?", secenekler: { A: "Cusco", B: "Arequipa", C: "Lima", D: "Trujillo" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 109, soru: "Şili'nin başkenti neresidir?", secenekler: { A: "Valparaiso", B: "Santiago", C: "Concepcion", D: "Antofagasta" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 110, soru: "Uruguay'ın başkenti neresidir?", secenekler: { A: "Montevideo", B: "Punta del Este", C: "Salto", D: "Paysandu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 111, soru: "Paraguay'ın başkenti neresidir?", secenekler: { A: "Asuncion", B: "Ciudad del Este", C: "Encarnacion", D: "Luque" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 112, soru: "Bolivya'nın idari başkenti neresidir?", secenekler: { A: "Sucre", B: "La Paz", C: "Santa Cruz", D: "Cochabamba" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 113, soru: "Ekvador'un başkenti neresidir?", secenekler: { A: "Guayaquil", B: "Cuenca", C: "Quito", D: "Manta" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 114, soru: "Panama'nın başkenti neresidir?", secenekler: { A: "Panama City", B: "Colon", C: "David", D: "Chitré" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 115, soru: "Kosta Rika'nın başkenti neresidir?", secenekler: { A: "San Jose", B: "Limon", C: "Alajuela", D: "Heredia" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 116, soru: "Guatemala'nın başkenti neresidir?", secenekler: { A: "Guatemala City", B: "Antigua", C: "Quetzaltenango", D: "Escuintla" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 117, soru: "Meksika'nın başkenti neresidir?", secenekler: { A: "Cancun", B: "Meksiko", C: "Guadalajara", D: "Monterrey" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 118, soru: "Jamaika'nın başkenti neresidir?", secenekler: { A: "Kingston", B: "Montego Bay", C: "Ocho Rios", D: "Negril" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 119, soru: "Haiti'nin başkenti neresidir?", secenekler: { A: "Cap-Haitien", B: "Port-au-Prince", C: "Les Cayes", D: "Jacmel" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 120, soru: "Dominik Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Punta Cana", B: "Santo Domingo", C: "Santiago", D: "La Romana" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 121, soru: "Estonya'nın başkenti neresidir?", secenekler: { A: "Tallinn", B: "Tartu", C: "Pärnu", D: "Narva" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 122, soru: "Letonya'nın başkenti neresidir?", secenekler: { A: "Riga", B: "Liepaja", C: "Daugavpils", D: "Jurmala" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 123, soru: "Litvanya'nın başkenti neresidir?", secenekler: { A: "Kaunas", B: "Vilnius", C: "Klaipeda", D: "Siauliai" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 124, soru: "Beyaz Rusya (Belarus)'nun başkenti neresidir?", secenekler: { A: "Minsk", B: "Brest", C: "Gomel", D: "Grodno" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 125, soru: "Moldova'nın başkenti neresidir?", secenekler: { A: "Tiraspol", B: "Kişinev", C: "Balti", D: "Bender" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 126, soru: "Gürcistan'ın başkenti neresidir?", secenekler: { A: "Batum", B: "Tiflis", C: "Kutaisi", D: "Gori" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 127, soru: "Ermenistan'ın başkenti neresidir?", secenekler: { A: "Gümrü", B: "Vanadzor", C: "Erivan", D: "Dilican" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 128, soru: "Arnavutluk'un başkenti neresidir?", secenekler: { A: "Tiran", B: "Durrës", C: "Vlorë", D: "İşkodra" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 129, soru: "Bosna-Hersek'in başkenti neresidir?", secenekler: { A: "Mostar", B: "Saraybosna", C: "Banja Luka", D: "Tuzla" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 130, soru: "Karadağ'ın başkenti neresidir?", secenekler: { A: "Podgorica", B: "Kotor", C: "Budva", D: "Çetine" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 131, soru: "Kuzey Makedonya'nın başkenti neresidir?", secenekler: { A: "Manastır", B: "Ohrid", C: "Üsküp", D: "Tetovo" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 132, soru: "Kıbrıs Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Lefkoşa", B: "Limasol", C: "Larnaka", D: "Baf" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 133, soru: "Slovakya'nın başkenti neresidir?", secenekler: { A: "Bratislava", B: "Košice", C: "Nitra", D: "Žilina" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 134, soru: "Kamboçya'nın başkenti neresidir?", secenekler: { A: "Siem Reap", B: "Phnom Penh", C: "Sihanoukville", D: "Battambang" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 135, soru: "Laos'un başkenti neresidir?", secenekler: { A: "Vientiane", B: "Luang Prabang", C: "Pakse", D: "Savannakhet" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 136, soru: "Myanmar'ın başkenti neresidir?", secenekler: { A: "Yangon", B: "Mandalay", C: "Naypyidaw", D: "Bago" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 137, soru: "Brunei'nin başkenti neresidir?", secenekler: { A: "Bandar Seri Begawan", B: "Kuala Belait", C: "Seria", D: "Tutong" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 138, soru: "Tanzanya'nın başkenti neresidir?", secenekler: { A: "Darüsselam", B: "Zanzibar", C: "Dodoma", D: "Arusha" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 139, soru: "Uganda'nın başkenti neresidir?", secenekler: { A: "Kampala", B: "Entebbe", C: "Jinja", D: "Mbarara" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 140, soru: "Ruanda'nın başkenti neresidir?", secenekler: { A: "Kigali", B: "Butare", C: "Gisenyi", D: "Ruhengeri" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 141, soru: "Angola'nın başkenti neresidir?", secenekler: { A: "Luanda", B: "Huambo", C: "Lobito", D: "Benguela" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 142, soru: "Zambiya'nın başkenti neresidir?", secenekler: { A: "Ndola", B: "Lusaka", C: "Kitwe", D: "Livingstone" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 143, soru: "Zimbabve'nin başkenti neresidir?", secenekler: { A: "Harare", B: "Bulawayo", C: "Mutare", D: "Gweru" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 144, soru: "Botsvana'nın başkenti neresidir?", secenekler: { A: "Gaborone", B: "Francistown", C: "Maun", D: "Kasane" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 145, soru: "Namibya'nın başkenti neresidir?", secenekler: { A: "Windhoek", B: "Swakopmund", C: "Walvis Bay", D: "Lüderitz" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 146, soru: "Mali'nin başkenti neresidir?", secenekler: { A: "Bamako", B: "Timbuktu", C: "Gao", D: "Mopti" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 147, soru: "Fildişi Sahili'nin idari başkenti neresidir?", secenekler: { A: "Abidjan", B: "Yamoussoukro", C: "Bouaké", D: "San-Pédro" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 148, soru: "Kamerun'un başkenti neresidir?", secenekler: { A: "Douala", B: "Yaoundé", C: "Garoua", D: "Bamenda" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 149, soru: "Madagaskar'ın başkenti neresidir?", secenekler: { A: "Antananarivo", B: "Toamasina", C: "Mahajanga", D: "Antsirabe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 150, soru: "Mauritius'un başkenti neresidir?", secenekler: { A: "Port Louis", B: "Curepipe", C: "Quatre Bornes", D: "Vacoas" }, dogruCevap: "A" }, 
    // 151-350: Yeni Eklenen Başkent Soruları
    { kategori: "Başkent", seviye: 151, soru: "Senegal'in başkenti neresidir?", secenekler: { A: "Dakar", B: "Saint-Louis", C: "Thiès", D: "Ziguinchor" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 152, soru: "Gine'nin başkenti neresidir?", secenekler: { A: "Conakry", B: "Nzérékoré", C: "Kankan", D: "Kindia" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 153, soru: "Liberya'nın başkenti neresidir?", secenekler: { A: "Monrovia", B: "Gbarnga", C: "Buchanan", D: "Harper" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 154, soru: "Sierra Leone'nin başkenti neresidir?", secenekler: { A: "Freetown", B: "Bo", C: "Kenema", D: "Makeni" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 155, soru: "Burkina Faso'nun başkenti neresidir?", secenekler: { A: "Ouagadougou", B: "Bobo-Dioulasso", C: "Koudougou", D: "Ouahigouya" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 156, soru: "Nijer'in başkenti neresidir?", secenekler: { A: "Niamey", B: "Zinder", C: "Maradi", D: "Agadez" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 157, soru: "Çad'ın başkenti neresidir?", secenekler: { A: "N'Djamena", B: "Moundou", C: "Sarh", D: "Abéché" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 158, soru: "Orta Afrika Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Bangui", B: "Bimbo", C: "Berbérati", D: "Bouar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 159, soru: "Gabon'un başkenti neresidir?", secenekler: { A: "Libreville", B: "Port-Gentil", C: "Franceville", D: "Oyem" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 160, soru: "Kongo Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Brazzaville", B: "Pointe-Noire", C: "Dolisie", D: "Madingou" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 161, soru: "Demokratik Kongo Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Kinşasa", B: "Lubumbashi", C: "Mbuji-Mayi", D: "Goma" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 162, soru: "Eritre'nin başkenti neresidir?", secenekler: { A: "Asmara", B: "Massawa", C: "Keren", D: "Assab" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 163, soru: "Cibuti'nin başkenti neresidir?", secenekler: { A: "Cibuti", B: "Ali Sabieh", C: "Tadjoura", D: "Dikhil" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 164, soru: "Malavi'nın başkenti neresidir?", secenekler: { A: "Lilongwe", B: "Blantyre", C: "Mzuzu", D: "Zomba" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 165, soru: "Burundi'nin başkenti neresidir?", secenekler: { A: "Gitega", B: "Bujumbura", C: "Ngozi", D: "Kayanza" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 166, soru: "Esvatini'nin (Svaziland) idari başkenti neresidir?", secenekler: { A: "Mbabane", B: "Lobamba", C: "Manzini", D: "Big Bend" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 167, soru: "Lesotho'nun başkenti neresidir?", secenekler: { A: "Maseru", B: "Teyateyaneng", C: "Mafeteng", D: "Hlotse" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 168, soru: "Moritanya'nın başkenti neresidir?", secenekler: { A: "Nouakchott", B: "Nouadhibou", C: "Kiffa", D: "Rosso" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 169, soru: "Gine-Bissau'nun başkenti neresidir?", secenekler: { A: "Bissau", B: "Bafatá", C: "Gabú", D: "Catió" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 170, soru: "Gambiya'nın başkenti neresidir?", secenekler: { A: "Banjul", B: "Serekunda", C: "Brikama", D: "Bakau" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 171, soru: "Cape Verde'nin (Yeşil Burun Adaları) başkenti neresidir?", secenekler: { A: "Praia", B: "Mindelo", C: "Santa Maria", D: "Assomada" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 172, soru: "Seyşeller'in başkenti neresidir?", secenekler: { A: "Victoria", B: "Anse Royale", C: "Beau Vallon", D: "Cascade" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 173, soru: "Komorlar'ın başkenti neresidir?", secenekler: { A: "Moroni", B: "Mutsamudu", C: "Fomboni", D: "Domoni" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 174, soru: "Bahreyn'in başkenti neresidir?", secenekler: { A: "Manama", B: "Riffa", C: "Muharrak", D: "Hamad" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 175, soru: "Maldivler'in başkenti neresidir?", secenekler: { A: "Male", B: "Addu City", C: "Fuvahmulah", D: "Kulhudhuffushi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 176, soru: "Bhutan'ın başkenti neresidir?", secenekler: { A: "Thimphu", B: "Phuntsholing", C: "Paro", D: "Punakha" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 177, soru: "Tacikistan'ın başkenti neresidir?", secenekler: { A: "Duşanbe", B: "Hucend", C: "Kulob", D: "Bohtar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 178, soru: "Doğu Timor'un başkenti neresidir?", secenekler: { A: "Dili", B: "Baucau", C: "Maliana", D: "Suai" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 179, soru: "Papua Yeni Gine'nin başkenti neresidir?", secenekler: { A: "Port Moresby", B: "Lae", C: "Arawa", D: "Mt Hagen" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 180, soru: "Solomon Adaları'nın başkenti neresidir?", secenekler: { A: "Honiara", B: "Gizo", C: "Auki", D: "Tulagi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 181, soru: "Fiji'nin başkenti neresidir?", secenekler: { A: "Suva", B: "Nadi", C: "Lautoka", D: "Labasa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 182, soru: "Vanuatu'nun başkenti neresidir?", secenekler: { A: "Port Vila", B: "Luganville", C: "Isangel", D: "Sola" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 183, soru: "Samoa'nın başkenti neresidir?", secenekler: { A: "Apia", B: "Vaitele", C: "Faleasiu", D: "Vailele" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 184, soru: "Tonga'nın başkenti neresidir?", secenekler: { A: "Nuku'alofa", B: "Neiafu", C: "Haveluloto", D: "Vaini" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 185, soru: "Kiribati'nin başkenti neresidir?", secenekler: { A: "Güney Tarava", B: "Betio", B: "Bairiki", D: "Abaiang" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 186, soru: "Mikronezya Federal Devletleri'nin başkenti neresidir?", secenekler: { A: "Palikir", B: "Weno", C: "Kolonia", D: "Tol" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 187, soru: "Marshall Adaları'nın başkenti neresidir?", secenekler: { A: "Majuro", B: "Ebeye", C: "Jaluit", D: "Wotje" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 188, soru: "Palau'nun başkenti neresidir?", secenekler: { A: "Ngerulmud", B: "Koror", C: "Meyuns", D: "Airai" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 189, soru: "Nauru'nun başkenti (resmi başkenti olmasa da hükümet merkezi) neresidir?", secenekler: { A: "Yaren", B: "Denigomodu", C: "Meneng", D: "Aiwo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 190, soru: "Tuvalu'nun başkenti neresidir?", secenekler: { A: "Funafuti", B: "Nanumea", C: "Niutao", D: "Vaitupu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 191, soru: "Andorra'nın başkenti neresidir?", secenekler: { A: "Andorra la Vella", B: "Encamp", C: "Canillo", D: "Escaldes" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 192, soru: "Liechtenstein'ın başkenti neresidir?", secenekler: { A: "Vaduz", B: "Schaan", C: "Triesen", D: "Balzers" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 193, soru: "San Marino'nun başkenti neresidir?", secenekler: { A: "San Marino", B: "Dogana", C: "Borgo Maggiore", D: "Serravalle" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 194, soru: "Malta'nın başkenti neresidir?", secenekler: { A: "Valletta", B: "Birkirkara", C: "Sliema", D: "Mosta" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 195, soru: "Kıbrıs'ın başkenti neresidir?", secenekler: { A: "Lefkoşa", B: "Limasol", C: "Larnaka", D: "Baf" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 196, soru: "Bahamalar'ın başkenti neresidir?", secenekler: { A: "Nassau", B: "Freeport", C: "West End", D: "Coopers Town" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 197, soru: "Barbados'un başkenti neresidir?", secenekler: { A: "Bridgetown", B: "Speightstown", C: "Oistins", D: "Holetown" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 198, soru: "Grenada'nın başkenti neresidir?", secenekler: { A: "St. George's", B: "Gouyave", C: "Grenville", D: "Victoria" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 199, soru: "Guyana'nın başkenti neresidir?", secenekler: { A: "Georgetown", B: "Linden", C: "New Amsterdam", D: "Anna Regina" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 200, soru: "Surinam'ın başkenti neresidir?", secenekler: { A: "Paramaribo", B: "Lelydorp", C: "Nieuw Nickerie", D: "Moengo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 201, soru: "Belize'nin başkenti neresidir?", secenekler: { A: "Belmopan", B: "Belize City", C: "San Ignacio", D: "Orange Walk" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 202, soru: "El Salvador'un başkenti neresidir?", secenekler: { A: "San Salvador", B: "Santa Ana", C: "San Miguel", D: "Soyapango" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 203, soru: "Honduras'ın başkenti neresidir?", secenekler: { A: "Tegucigalpa", B: "San Pedro Sula", C: "La Ceiba", D: "Choluteca" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 204, soru: "Nikaragua'nın başkenti neresidir?", secenekler: { A: "Managua", B: "Leon", C: "Masaya", D: "Tipitapa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 205, soru: "Trinidad ve Tobago'nun başkenti neresidir?", secenekler: { A: "Port of Spain", B: "San Fernando", C: "Chaguanas", D: "Arima" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 206, soru: "Dominika'nın başkenti neresidir?", secenekler: { A: "Roseau", B: "Portsmouth", C: "Marigot", D: "Berekua" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 207, soru: "Saint Lucia'nın başkenti neresidir?", secenekler: { A: "Castries", B: "Vieux Fort", C: "Micoud", D: "Soufrière" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 208, soru: "Saint Vincent ve Grenadinler'in başkenti neresidir?", secenekler: { A: "Kingstown", B: "Georgetown", C: "Byera", D: "Barrouallie" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 209, soru: "Saint Kitts ve Nevis'in başkenti neresidir?", secenekler: { A: "Basseterre", B: "Charlestown", C: "Saddlers", D: "Cayon" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 210, soru: "Antigua ve Barbuda'nın başkenti neresidir?", secenekler: { A: "St. John's", B: "All Saints", C: "Liberta", D: "Potters Village" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 211, soru: "Ekvator Ginesi'nin başkenti neresidir?", secenekler: { A: "Malabo", B: "Bata", C: "Ebebiyín", D: "Mongomo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 212, soru: "Sao Tome ve Principe'nin başkenti neresidir?", secenekler: { A: "São Tomé", B: "Trindade", C: "Santana", D: "Neves" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 213, soru: "Benin'in resmi başkenti neresidir?", secenekler: { A: "Porto-Novo", B: "Cotonou", C: "Djougou", D: "Parakou" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 214, soru: "Togo'nun başkenti neresidir?", secenekler: { A: "Lomé", B: "Sokodé", C: "Kara", D: "Atakpamé" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 215, soru: "Cibuti'nin başkenti neresidir?", secenekler: { A: "Cibuti City", B: "Ali Sabieh", C: "Dikhil", D: "Arta" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 216, soru: "Mauritius'un başkenti neresidir?", secenekler: { A: "Port Louis", B: "Beau Bassin", C: "Vacoas", D: "Curepipe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 217, soru: "Slovenya'nın başkenti neresidir?", secenekler: { A: "Ljubljana", B: "Maribor", C: "Celje", D: "Kranj" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 218, soru: "Slovakya'nın başkenti neresidir?", secenekler: { A: "Bratislava", B: "Kosice", C: "Presov", D: "Zilina" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 219, soru: "Estonya'nın başkenti neresidir?", secenekler: { A: "Tallinn", B: "Tartu", C: "Narva", D: "Pärnu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 220, soru: "Letonya'nın başkenti neresidir?", secenekler: { A: "Riga", B: "Daugavpils", C: "Liepaja", D: "Jelgava" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 221, soru: "Litvanya'nın başkenti neresidir?", secenekler: { A: "Vilnius", B: "Kaunas", C: "Klaipeda", D: "Siauliai" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 222, soru: "Karadağ'ın başkenti neresidir?", secenekler: { A: "Podgorica", B: "Nikšić", C: "Herceg Novi", D: "Pljevlja" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 223, soru: "Kuzey Makedonya'nın başkenti neresidir?", secenekler: { A: "Üsküp", B: "Bitola", C: "Kumanovo", D: "Prilep" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 224, soru: "Bosna-Hersek'in başkenti neresidir?", secenekler: { A: "Saraybosna", B: "Banja Luka", C: "Tuzla", D: "Zenica" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 225, soru: "Arnavutluk'un başkenti neresidir?", secenekler: { A: "Tiran", B: "Durrës", C: "Vlorë", D: "Elbasan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 226, soru: "Moldova'nın başkenti neresidir?", secenekler: { A: "Kişinev", B: "Tiraspol", C: "Bălți", D: "Bender" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 227, soru: "Ermenistan'ın başkenti neresidir?", secenekler: { A: "Erivan", B: "Gümrü", C: "Vanadzor", D: "Hrazdan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 228, soru: "Gürcistan'ın başkenti neresidir?", secenekler: { A: "Tiflis", B: "Kutaisi", C: "Batum", D: "Rustavi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 229, soru: "Azerbaycan'ın başkenti neresidir?", secenekler: { A: "Bakü", B: "Gence", C: "Sumgayıt", D: "Mingeçevir" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 230, soru: "Türkmenistan'ın başkenti neresidir?", secenekler: { A: "Aşkabat", B: "Türkmenabat", C: "Daşoğuz", D: "Merv" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 231, soru: "Özbekistan'ın başkenti neresidir?", secenekler: { A: "Taşkent", B: "Semerkant", C: "Nemengan", D: "Buhara" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 232, soru: "Kırgızistan'ın başkenti neresidir?", secenekler: { A: "Bişkek", B: "Oş", C: "Celal-Abad", D: "Karakol" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 233, soru: "Tacikistan'ın başkenti neresidir?", secenekler: { A: "Duşanbe", B: "Hucend", C: "Kulob", D: "Bohtar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 234, soru: "Kazakistan'ın başkenti neresidir?", secenekler: { A: "Astana", B: "Almatı", C: "Çimkent", D: "Karagandı" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 235, soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Ulanbatur", B: "Erdenet", C: "Darhan", D: "Çoybalsan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 236, soru: "Kuzey Kore'nin başkenti neresidir?", secenekler: { A: "Pyongyang", B: "Hamhung", C: "Chongjin", D: "Nampo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 237, soru: "Güney Kore'nin başkenti neresidir?", secenekler: { A: "Seul", B: "Busan", C: "Incheon", D: "Daegu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 238, soru: "Japonya'nın başkenti neresidir?", secenekler: { A: "Tokyo", B: "Yokohama", C: "Osaka", D: "Nagoya" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 239, soru: "Tayvan'ın başkenti neresidir?", secenekler: { A: "Taipei", B: "Kaohsiung", C: "Taichung", D: "Tainan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 240, soru: "Filipinler'in başkenti neresidir?", secenekler: { A: "Manila", B: "Quezon City", C: "Davao City", D: "Cebu City" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 241, soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Hanoi", B: "Ho Chi Minh City", C: "Da Nang", D: "Hai Phong" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 242, soru: "Kamboçya'nın başkenti neresidir?", secenekler: { A: "Phnom Penh", B: "Siem Reap", C: "Battambang", D: "Sihanoukville" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 243, soru: "Laos'un başkenti neresidir?", secenekler: { A: "Vientiane", B: "Pakse", C: "Savannakhet", D: "Luang Prabang" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 244, soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Bangkok", B: "Nonthaburi", C: "Nakhon Ratchasima", D: "Chiang Mai" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 245, soru: "Myanmar'ın başkenti neresidir?", secenekler: { A: "Naypyidaw", B: "Yangon", C: "Mandalay", D: "Bago" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 246, soru: "Malezya'nın başkenti neresidir?", secenekler: { A: "Kuala Lumpur", B: "George Town", C: "Ipoh", D: "Shah Alam" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 247, soru: "Singapur'un başkenti neresidir?", secenekler: { A: "Singapur", B: "Jurong", C: "Tampines", D: "Bedok" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 248, soru: "Brunei'nin başkenti neresidir?", secenekler: { A: "Bandar Seri Begawan", B: "Kuala Belait", C: "Seria", D: "Tutong" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 249, soru: "Endonezya'nın başkenti neresidir?", secenekler: { A: "Cakarta", B: "Surabaya", C: "Bandung", D: "Medan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 250, soru: "Doğu Timor'un başkenti neresidir?", secenekler: { A: "Dili", B: "Baucau", C: "Ermera", D: "Lospalos" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 251, soru: "Sri Lanka'nın ticari başkenti neresidir?", secenekler: { A: "Kolombo", B: "Sri Jayawardenepura Kotte", C: "Kandy", D: "Galle" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 252, soru: "Maldivler'in başkenti neresidir?", secenekler: { A: "Male", B: "Addu City", C: "Fuvahmulah", D: "Kulhudhuffushi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 253, soru: "Hindistan'ın başkenti neresidir?", secenekler: { A: "Yeni Delhi", B: "Mumbai", C: "Kalküta", D: "Bangalor" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 254, soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "İslamabad", B: "Karaçi", C: "Lahor", D: "Faysalabad" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 255, soru: "Bangladeş'in başkenti neresidir?", secenekler: { A: "Dakka", B: "Chittagong", C: "Khulna", D: "Rajshahi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 256, soru: "Bhutan'ın başkenti neresidir?", secenekler: { A: "Thimphu", B: "Phuntsholing", C: "Punakha", D: "Samdrup Jongkhar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 257, soru: "Nepal'in başkenti neresidir?", secenekler: { A: "Katmandu", B: "Pokhara", C: "Lalitpur", D: "Biratnagar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 258, soru: "Afganistan'ın başkenti neresidir?", secenekler: { A: "Kabil", B: "Kandahar", C: "Herat", D: "Mezar-ı Şerif" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 259, soru: "İran'ın başkenti neresidir?", secenekler: { A: "Tahran", B: "Meşhed", C: "İsfahan", D: "Tebriz" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 260, soru: "Irak'ın başkenti neresidir?", secenekler: { A: "Bağdat", B: "Basra", C: "Musul", D: "Erbil" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 261, soru: "Suriye'nin başkenti neresidir?", secenekler: { A: "Şam", B: "Halep", C: "Humus", D: "Lazkiye" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 262, soru: "Lübnan'ın başkenti neresidir?", secenekler: { A: "Beyrut", B: "Trablusşam", C: "Sayda", D: "Zahle" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 263, soru: "Ürdün'ün başkenti neresidir?", secenekler: { A: "Amman", B: "Zarka", C: "İrbid", D: "Rusayfe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 264, soru: "İsrail'in başkenti neresidir?", secenekler: { A: "Kudüs", B: "Tel Aviv", C: "Hayfa", D: "Rişon LeTsiyon" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 265, soru: "Filistin'in ilan edilen başkenti neresidir?", secenekler: { A: "Kudüs", B: "Ramallah", C: "Gazze", D: "Nablus" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 266, soru: "Suudi Arabistan'ın başkenti neresidir?", secenekler: { A: "Riyad", B: "Cidde", C: "Mekke", D: "Medine" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 267, soru: "Yemen'in başkenti neresidir?", secenekler: { A: "Sana", B: "Aden", C: "Taiz", D: "Hudeyde" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 268, soru: "Umman'ın başkenti neresidir?", secenekler: { A: "Maskat", B: "Seeb", C: "Salalah", D: "Bawshar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 269, soru: "Birleşik Arap Emirlikleri'nin başkenti neresidir?", secenekler: { A: "Abu Dabi", B: "Dubai", C: "Şarika", D: "Al Ain" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 270, soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Doha", B: "Al Rayyan", C: "Umm Salal Muhammed", D: "Al Vakrah" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 271, soru: "Bahreyn'in başkenti neresidir?", secenekler: { A: "Manama", B: "Al Muharraq", C: "Ar Rifa'", D: "Hamad Town" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 272, soru: "Kuveyt'in başkenti neresidir?", secenekler: { A: "Kuveyt", B: "Al Ahmadi", D: "Hawalli", D: "As Salimiyah" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 273, soru: "Mısır'ın başkenti neresidir?", secenekler: { A: "Kahire", B: "İskenderiye", C: "Gize", D: "Şubra el-Hayma" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 274, soru: "Libya'nın başkenti neresidir?", secenekler: { A: "Trablus", B: "Bingazi", C: "Misrata", D: "Bayda" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 275, soru: "Tunus'un başkenti neresidir?", secenekler: { A: "Tunus", B: "Safakes", C: "Susa", D: "Ettadhamen" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 276, soru: "Cezayir'in başkenti neresidir?", secenekler: { A: "Cezayir", B: "Oran", C: "Konstantin", D: "Annâbe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 277, soru: "Fas'ın başkenti neresidir?", secenekler: { A: "Rabat", B: "Kazablanka", C: "Fes", D: "Tanca" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 278, soru: "Sudan'ın başkenti neresidir?", secenekler: { A: "Hartum", B: "Omdurman", C: "Hartum Bahri", D: "Nyala" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 279, soru: "Güney Sudan'ın başkenti neresidir?", secenekler: { A: "Cuba", B: "Yei", C: "Wau", D: "Malakal" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 280, soru: "Etiyopya'nın başkenti neresidir?", secenekler: { A: "Addis Ababa", B: "Dire Dawa", C: "Adama", D: "Gondar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 281, soru: "Eritre'nin başkenti neresidir?", secenekler: { A: "Asmara", B: "Keren", C: "Teseney", D: "Mendefera" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 282, soru: "Cibuti'nin başkenti neresidir?", secenekler: { A: "Cibuti", B: "Ali Sabieh", C: "Dikhil", D: "Tadjoura" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 283, soru: "Somali'nin başkenti neresidir?", secenekler: { A: "Mogadişu", B: "Hargeisa", C: "Berbera", D: "Kismayo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 284, soru: "Kenya'nın başkenti neresidir?", secenekler: { A: "Nairobi", B: "Mombasa", C: "Nakuru", D: "Kisumu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 285, soru: "Uganda'nın başkenti neresidir?", secenekler: { A: "Kampala", B: "Nansana", C: "Kira", D: "Makindye Ssabagabo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 286, soru: "Ruanda'nın başkenti neresidir?", secenekler: { A: "Kigali", B: "Butare", C: "Gisenyi", D: "Gitarama" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 287, soru: "Burundi'nin başkenti neresidir?", secenekler: { A: "Gitega", B: "Bujumbura", C: "Muyinga", D: "Ngozi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 288, soru: "Tanzanya'nın başkenti neresidir?", secenekler: { A: "Dodoma", B: "Darüsselam", C: "Mwanza", D: "Arusha" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 289, soru: "Malavi'nin başkenti neresidir?", secenekler: { A: "Lilongwe", B: "Blantyre", C: "Mzuzu", D: "Zomba" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 290, soru: "Mozambik'in başkenti neresidir?", secenekler: { A: "Maputo", B: "Matola", C: "Beira", D: "Nampula" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 291, soru: "Zambiya'nın başkenti neresidir?", secenekler: { A: "Lusaka", B: "Kitwe", C: "Ndola", D: "Kabwe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 292, soru: "Zimbabve'nin başkenti neresidir?", secenekler: { A: "Harare", B: "Bulawayo", C: "Chitungwiza", D: "Mutare" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 293, soru: "Botsvana'nın başkenti neresidir?", secenekler: { A: "Gaborone", B: "Francistown", C: "Molepolole", D: "Selibe Phikwe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 294, soru: "Namibya'nın başkenti neresidir?", secenekler: { A: "Windhoek", B: "Rundu", C: "Walvis Bay", D: "Swakopmund" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 295, soru: "Güney Afrika Cumhuriyeti'nin yasama başkenti neresidir?", secenekler: { A: "Cape Town", B: "Pretoria", C: "Bloemfontein", D: "Johannesburg" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 296, soru: "Lesotho'nun başkenti neresidir?", secenekler: { A: "Maseru", B: "Teyateyaneng", C: "Mafeteng", D: "Hlotse" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 297, soru: "Esvatini'nin yasama başkenti neresidir?", secenekler: { A: "Lobamba", B: "Mbabane", C: "Manzini", D: "Big Bend" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 298, soru: "Madagaskar'ın başkenti neresidir?", secenekler: { A: "Antananarivo", B: "Toamasina", C: "Antsirabe", D: "Fianarantsoa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 299, soru: "Mauritius'un başkenti neresidir?", secenekler: { A: "Port Louis", B: "Beau Bassin-Rose Hill", C: "Vacoas-Phoenix", D: "Curepipe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 300, soru: "Seyşeller'in başkenti neresidir?", secenekler: { A: "Victoria", B: "De Quincey", C: "Anse Boileau", D: "Bel Ombre" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 301, soru: "Komorlar'ın başkenti neresidir?", secenekler: { A: "Moroni", B: "Mutsamudu", C: "Domoni", D: "Fomboni" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 302, soru: "Angola'nın başkenti neresidir?", secenekler: { A: "Luanda", B: "Huambo", C: "Lobito", D: "Benguela" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 303, soru: "Gabon'un başkenti neresidir?", secenekler: { A: "Libreville", B: "Port-Gentil", C: "Franceville", D: "Oyem" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 304, soru: "Ekvator Ginesi'nin başkenti neresidir?", secenekler: { A: "Malabo", B: "Bata", C: "Ebebiyín", D: "Aconibe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 305, soru: "Sao Tome ve Principe'nin başkenti neresidir?", secenekler: { A: "Sao Tome", B: "Santo Amaro", C: "Neves", D: "Santana" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 306, soru: "Kamerun'un başkenti neresidir?", secenekler: { A: "Yaoundé", B: "Douala", C: "Garoua", D: "Bamenda" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 307, soru: "Orta Afrika Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Bangui", B: "Bimbo", C: "Berberati", D: "Carnot" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 308, soru: "Çad'ın başkenti neresidir?", secenekler: { A: "N'Djamena", B: "Moundou", C: "Sarh", D: "Abéché" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 309, soru: "Nijer'in başkenti neresidir?", secenekler: { A: "Niamey", B: "Zinder", C: "Maradi", D: "Tahoua" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 310, soru: "Nijerya'nın başkenti neresidir?", secenekler: { A: "Abuja", B: "Lagos", C: "Kano", D: "Ibadan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 311, soru: "Benin'in başkenti neresidir?", secenekler: { A: "Porto-Novo", B: "Cotonou", C: "Abomey-Calavi", D: "Djaugou" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 312, soru: "Togo'nın başkenti neresidir?", secenekler: { A: "Lomé", B: "Sokodé", C: "Kara", D: "Atakpamé" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 313, soru: "Gana'nın başkenti neresidir?", secenekler: { A: "Akra", B: "Kumasi", C: "Tamale", D: "Ashiaman" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 314, soru: "Fildişi Sahili'nin başkenti neresidir?", secenekler: { A: "Yamoussoukro", B: "Abidjan", C: "Bouaké", D: "Daloa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 315, soru: "Liberya'nın başkenti neresidir?", secenekler: { A: "Monrovia", B: "Gbarnga", C: "Kakata", D: "Bensonville" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 316, soru: "Sierra Leone'nin başkenti neresidir?", secenekler: { A: "Freetown", B: "Bo", C: "Kenema", D: "Makeni" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 317, soru: "Gine'nin başkenti neresidir?", secenekler: { A: "Konakri", B: "Nzérékoré", C: "Kankan", D: "Kindia" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 318, soru: "Gine-Bissau'nun başkenti neresidir?", secenekler: { A: "Bissau", B: "Bafatá", C: "Gabú", D: "Bissorã" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 319, soru: "Gambiya'nın başkenti neresidir?", secenekler: { A: "Banjul", B: "Serekunda", C: "Brikama", D: "Bakau" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 320, soru: "Senegal'in başkenti neresidir?", secenekler: { A: "Dakar", B: "Pikine", C: "Touba", D: "Guediawaye" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 321, soru: "Mali'nin başkenti neresidir?", secenekler: { A: "Bamako", B: "Sikasso", C: "Mopti", D: "Koutiala" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 322, soru: "Moritanya'nın başkenti neresidir?", secenekler: { A: "Nuakşot", B: "Nuadhibou", C: "Kiffa", D: "M'Bout" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 323, soru: "Yeşil Burun Adaları'nın başkenti neresidir?", secenekler: { A: "Praia", B: "Mindelo", C: "Santa Maria", D: "Cova Figueira" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 324, soru: "Meksika'nın başkenti neresidir?", secenekler: { A: "Meksiko", B: "Ecatepec", C: "Guadalajara", D: "Puebla" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 325, soru: "Guatemala'nın başkenti neresidir?", secenekler: { A: "Guatemala", B: "Mixco", C: "Villa Nueva", D: "Quetzaltenango" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 326, soru: "Belize'nin başkenti neresidir?", secenekler: { A: "Belmopan", B: "Belize City", C: "San Ignacio", D: "Orange Walk Town" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 327, soru: "El Salvador'un başkenti neresidir?", secenekler: { A: "San Salvador", B: "Santa Ana", C: "San Miguel", D: "Santa Tecla" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 328, soru: "Honduras'ın başkenti neresidir?", secenekler: { A: "Tegucigalpa", B: "San Pedro Sula", C: "Choloma", D: "La Ceiba" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 329, soru: "Nikaragua'nın başkenti neresidir?", secenekler: { A: "Managua", B: "Leon", C: "Masaya", D: "Chinandega" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 330, soru: "Kosta Rika'nın başkenti neresidir?", secenekler: { A: "San Jose", B: "Alajuela", C: "Cartago", D: "Heredia" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 331, soru: "Panama'nın başkenti neresidir?", secenekler: { A: "Panama", B: "San Miguelito", C: "Tocumen", D: "David" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 332, soru: "Küba'nın başkenti neresidir?", secenekler: { A: "Havana", B: "Santiago de Cuba", C: "Camagüey", D: "Holguín" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 333, soru: "Bahamalar'ın başkenti neresidir?", secenekler: { A: "Nassau", B: "Lucaya", C: "Freeport", D: "West End" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 334, soru: "Jamaika'nın başkenti neresidir?", secenekler: { A: "Kingston", B: "Spanish Town", C: "Portmore", D: "Montego Bay" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 335, soru: "Haiti'nin başkenti neresidir?", secenekler: { A: "Port-au-Prince", B: "Carrefour", C: "Delmas", D: "Pétion-Ville" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 336, soru: "Dominik Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Santo Domingo", B: "Santiago de los Caballeros", C: "Santo Domingo Este", D: "Santo Domingo Oeste" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 337, soru: "Saint Kitts ve Nevis'in başkenti neresidir?", secenekler: { A: "Basseterre", B: "Fig Tree", C: "Market Shop", D: "Saint Paul's" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 338, soru: "Antigua ve Barbuda'nın başkenti neresidir?", secenekler: { A: "St. John's", B: "All Saints", C: "Liberta", D: "Potters Village" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 339, soru: "Dominika'nın başkenti neresidir?", secenekler: { A: "Roseau", B: "Portsmouth", C: "Marigot", D: "Berekua" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 340, soru: "Saint Lucia'nın başkenti neresidir?", secenekler: { A: "Castries", B: "Bexon", C: "Babonneau", D: "Ciceron" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 341, soru: "Saint Vincent ve Grenadinler'in başkenti neresidir?", secenekler: { A: "Kingstown", B: "Georgetown", C: "Byera Hill", D: "Biabou" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 342, soru: "Barbados'un başkenti neresidir?", secenekler: { A: "Bridgetown", B: "Speightstown", C: "Oistins", D: "Bathsheba" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 343, soru: "Grenada'nın başkenti neresidir?", secenekler: { A: "St. George's", B: "Gouyave", C: "Grenville", D: "Victoria" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 344, soru: "Trinidad ve Tobago'nun başkenti neresidir?", secenekler: { A: "Port of Spain", B: "Chaguanas", C: "San Fernando", D: "Rio Claro" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 345, soru: "Kolombiya'nın başkenti neresidir?", secenekler: { A: "Bogota", B: "Medellín", C: "Cali", D: "Barranquilla" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 346, soru: "Venezuela'nın başkenti neresidir?", secenekler: { A: "Karakas", B: "Maracaibo", C: "Valencia", D: "Barquisimeto" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 347, soru: "Guyana'nın başkenti neresidir?", secenekler: { A: "Georgetown", B: "Linden", C: "New Amsterdam", D: "Anna Regina" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 348, soru: "Surinam'ın başkenti neresidir?", secenekler: { A: "Paramaribo", B: "Lelydorp", C: "Nieuw Nickerie", D: "Moengo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 349, soru: "Ekvador'un başkenti neresidir?", secenekler: { A: "Quito", B: "Guayaquil", C: "Cuenca", D: "Santo Domingo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 350, soru: "Peru'nun başkenti neresidir?", secenekler: { A: "Lima", B: "Arequipa", C: "Trujillo", D: "Chiclayo" }, dogruCevap: "A" }, 
    // 351-449: Eklenen Yeni Başkent Soruları
    { kategori: "Başkent", seviye: 351, soru: "Bolivya'nın idari başkenti neresidir?", secenekler: { A: "La Paz", B: "Sucre", C: "Santa Cruz", D: "Cochabamba" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 352, soru: "Bolivya'nın resmi başkenti neresidir?", secenekler: { A: "Sucre", B: "La Paz", C: "Potosi", D: "Oruro" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 353, soru: "Paraguay'ın başkenti neresidir?", secenekler: { A: "Asuncion", B: "Ciudad del Este", C: "Encarnacion", D: "Luque" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 354, soru: "Uruguay'ın başkenti neresidir?", secenekler: { A: "Montevideo", B: "Salto", C: "Paysandu", D: "Las Piedras" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 355, soru: "Şili'nin başkenti neresidir?", secenekler: { A: "Santiago", B: "Valparaiso", C: "Concepcion", D: "Antofagasta" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 356, soru: "İzlanda'nın başkenti neresidir?", secenekler: { A: "Reykjavik", B: "Akureyri", C: "Kopavogur", D: "Hafnarfjörður" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 357, soru: "İrlanda'nın başkenti neresidir?", secenekler: { A: "Dublin", B: "Cork", C: "Limerick", D: "Galway" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 358, soru: "Lüksemburg'un başkenti neresidir?", secenekler: { A: "Lüksemburg", B: "Esch-sur-Alzette", C: "Differdange", D: "Dudelange" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 359, soru: "Monako'nun başkenti neresidir?", secenekler: { A: "Monako", B: "Monte Carlo", C: "La Condamine", D: "Fontvieille" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 360, soru: "Vatikan'ın başkenti neresidir?", secenekler: { A: "Vatikan", B: "Roma", C: "Milano", D: "Napoli" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 361, soru: "Kuveyt'in başkenti neresidir?", secenekler: { A: "Kuveyt", B: "Salmiya", C: "Jahra", D: "Fahaheel" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 362, soru: "Yemen'in geçici başkenti neresidir?", secenekler: { A: "Aden", B: "Sana", C: "Taiz", D: "Mukalla" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 363, soru: "Umman'ın başkenti neresidir?", secenekler: { A: "Maskat", B: "Salalah", C: "Sohar", D: "Nizwa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 364, soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Doha", B: "Al Wakrah", C: "Al Khor", D: "Madinat ash Shamal" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 365, soru: "Bahreyn'in başkenti neresidir?", secenekler: { A: "Manama", B: "Muharrak", C: "Riffa", D: "Hamad" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 366, soru: "Lübnan'ın başkenti neresidir?", secenekler: { A: "Beyrut", B: "Trablusşam", C: "Sidon", D: "Tyre" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 367, soru: "Ürdün'ün başkenti neresidir?", secenekler: { A: "Amman", B: "Zarka", C: "İrbid", D: "Akabe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 368, soru: "Suriye'nin başkenti neresidir?", secenekler: { A: "Şam", B: "Halep", C: "Humus", D: "Lazkiye" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 369, soru: "Irak'ın başkenti neresidir?", secenekler: { A: "Bağdat", B: "Musul", C: "Basra", D: "Erbil" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 370, soru: "Afganistan'ın başkenti neresidir?", secenekler: { A: "Kabil", B: "Kandahar", C: "Herat", D: "Mezar-ı Şerif" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 371, soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "İslamabad", B: "Karaçi", C: "Lahor", D: "Peşaver" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 372, soru: "Nepal'in başkenti neresidir?", secenekler: { A: "Katmandu", B: "Pokhara", C: "Lalitpur", D: "Biratnagar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 373, soru: "Bhutan'ın başkenti neresidir?", secenekler: { A: "Thimphu", B: "Paro", C: "Punakha", D: "Phuntsholing" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 374, soru: "Bangladeş'in başkenti neresidir?", secenekler: { A: "Dakka", B: "Chittagong", C: "Khulna", D: "Sylhet" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 375, soru: "Sri Lanka'nın resmi başkenti neresidir?", secenekler: { A: "Sri Jayawardenepura Kotte", B: "Kolombo", C: "Kandy", D: "Galle" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 376, soru: "Maldivler'in başkenti neresidir?", secenekler: { A: "Male", B: "Hulhumale", C: "Maafushi", D: "Gan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 377, soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Ulanbatur", B: "Erdenet", C: "Darhan", D: "Mörön" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 378, soru: "Kuzey Kore'nin başkenti neresidir?", secenekler: { A: "Pyongyang", B: "Kaesong", C: "Wonsan", D: "Nampo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 379, soru: "Güney Kore'nin başkenti neresidir?", secenekler: { A: "Seul", B: "Busan", C: "Incheon", D: "Daegu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 380, soru: "Tayvan'ın başkenti neresidir?", secenekler: { A: "Taipei", B: "Kaohsiung", C: "Taichung", D: "Tainan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 381, soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Hanoi", B: "Ho Chi Minh City", C: "Da Nang", D: "Hue" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 382, soru: "Laos'un başkenti neresidir?", secenekler: { A: "Vientiane", B: "Luang Prabang", C: "Pakse", D: "Savannakhet" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 383, soru: "Kamboçya'nın başkenti neresidir?", secenekler: { A: "Phnom Penh", B: "Siem Reap", C: "Battambang", D: "Sihanoukville" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 384, soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Bangkok", B: "Chiang Mai", C: "Phuket", D: "Pattaya" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 385, soru: "Myanmar'ın (Burma) başkenti neresidir?", secenekler: { A: "Naypyidaw", B: "Yangon", C: "Mandalay", D: "Bago" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 386, soru: "Malezya'nın başkenti neresidir?", secenekler: { A: "Kuala Lumpur", B: "Putrajaya", C: "George Town", D: "Johor Bahru" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 387, soru: "Singapur'un başkenti neresidir?", secenekler: { A: "Singapur", B: "Sentosa", C: "Changi", D: "Jurong" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 388, soru: "Brunei'nin başkenti neresidir?", secenekler: { A: "Bandar Seri Begawan", B: "Kuala Belait", C: "Seria", D: "Tutong" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 389, soru: "Endonezya'nın başkenti neresidir?", secenekler: { A: "Cakarta", B: "Bali", C: "Surabaya", D: "Bandung" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 390, soru: "Filipinler'in başkenti neresidir?", secenekler: { A: "Manila", B: "Quezon City", C: "Davao City", D: "Cebu City" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 391, soru: "Papua Yeni Gine'nin başkenti neresidir?", secenekler: { A: "Port Moresby", B: "Lae", C: "Madang", D: "Goroka" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 392, soru: "Yeni Zelanda'nın başkenti neresidir?", secenekler: { A: "Wellington", B: "Auckland", C: "Christchurch", D: "Hamilton" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 393, soru: "Fiji'nin başkenti neresidir?", secenekler: { A: "Suva", B: "Nadi", C: "Lautoka", D: "Labasa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 394, soru: "Samoa'nın başkenti neresidir?", secenekler: { A: "Apia", B: "Vaitele", C: "Faleasiu", D: "Vailele" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 395, soru: "Tonga'nın başkenti neresidir?", secenekler: { A: "Nuku'alofa", B: "Neiafu", C: "Haveluloto", D: "Vaini" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 396, soru: "Vanuatu'nun başkenti neresidir?", secenekler: { A: "Port Vila", B: "Luganville", C: "Norsup", D: "Port Olry" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 397, soru: "Solomon Adaları'nın başkenti neresidir?", secenekler: { A: "Honiara", B: "Gizo", C: "Auki", D: "Tulagi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 398, soru: "Mikronezya'nın başkenti neresidir?", secenekler: { A: "Palikir", B: "Weno", C: "Kolonia", D: "Tol" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 399, soru: "Palau'nın başkenti neresidir?", secenekler: { A: "Ngerulmud", B: "Koror", C: "Meyuns", D: "Airai" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 400, soru: "Marshall Adaları'nın başkenti neresidir?", secenekler: { A: "Majuro", B: "Ebeye", C: "Arno", D: "Jabor" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 401, soru: "Kiribati'nin başkenti neresidir?", secenekler: { A: "Güney Tarava", B: "Betio", C: "Bairiki", D: "Abaiang" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 402, soru: "Nauru'nun hükümet merkezi neresidir?", secenekler: { A: "Yaren", B: "Denigomodu", C: "Meneng", D: "Aiwo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 403, soru: "Tuvalu'nun başkenti neresidir?", secenekler: { A: "Funafuti", B: "Nanumea", C: "Niutao", D: "Vaitupu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 404, soru: "Madagaskar'ın başkenti neresidir?", secenekler: { A: "Antananarivo", B: "Toamasina", C: "Antsirabe", D: "Mahajanga" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 405, soru: "Mauritius'un başkenti neresidir?", secenekler: { A: "Port Louis", B: "Beau Bassin", C: "Vacoas", D: "Curepipe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 406, soru: "Seyşeller'in başkenti neresidir?", secenekler: { A: "Victoria", B: "Anse Royale", C: "Beau Vallon", D: "Cascade" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 407, soru: "Komorlar'ın başkenti neresidir?", secenekler: { A: "Moroni", B: "Mutsamudu", C: "Fomboni", D: "Domoni" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 408, soru: "Cape Verde'nin (Yeşil Burun) başkenti neresidir?", secenekler: { A: "Praia", B: "Mindelo", C: "Santa Maria", D: "Espargos" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 409, soru: "Sao Tome ve Principe'nin başkenti neresidir?", secenekler: { A: "Sao Tome", B: "Santo Amaro", C: "Neves", D: "Santana" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 410, soru: "Gambiya'nın başkenti neresidir?", secenekler: { A: "Banjul", B: "Serekunda", C: "Brikama", D: "Bakau" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 411, soru: "Gine-Bissau'nun başkenti neresidir?", secenekler: { A: "Bissau", B: "Bafata", C: "Gabu", D: "Catio" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 412, soru: "Sierra Leone'nin başkenti neresidir?", secenekler: { A: "Freetown", B: "Bo", C: "Kenema", D: "Makeni" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 413, soru: "Liberya'nın başkenti neresidir?", secenekler: { A: "Monrovia", B: "Gbarnga", C: "Buchanan", D: "Kakata" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 414, soru: "Fildişi Sahili'nin başkenti neresidir?", secenekler: { A: "Yamoussoukro", B: "Abidjan", C: "Bouake", D: "Daloa" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 415, soru: "Burkina Faso'nun başkenti neresidir?", secenekler: { A: "Ouagadougou", B: "Bobo-Dioulasso", C: "Koudougou", D: "Ouahigouya" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 416, soru: "Togo'nun başkenti neresidir?", secenekler: { A: "Lome", B: "Sokode", C: "Kara", D: "Atakpame" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 417, soru: "Benin'in başkenti neresidir?", secenekler: { A: "Porto-Novo", B: "Cotonou", C: "Abomey-Calavi", D: "Parakou" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 418, soru: "Ekvator Ginesi'nin başkenti neresidir?", secenekler: { A: "Malabo", B: "Bata", C: "Ebebiyin", D: "Mongomo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 419, soru: "Gabon'un başkenti neresidir?", secenekler: { A: "Libreville", B: "Port-Gentil", C: "Franceville", D: "Oyem" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 420, soru: "Kongo Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Brazzaville", B: "Pointe-Noire", C: "Dolisie", D: "Madingou" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 421, soru: "Orta Afrika Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Bangui", B: "Bimbo", C: "Berberati", D: "Carnot" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 422, soru: "Çad'ın başkenti neresidir?", secenekler: { A: "N'Djamena", B: "Moundou", C: "Sarh", D: "Abeche" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 423, soru: "Sudan'ın başkenti neresidir?", secenekler: { A: "Hartum", B: "Omdurman", C: "Hartum Bahri", D: "Nyala" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 424, soru: "Güney Sudan'ın başkenti neresidir?", secenekler: { A: "Cuba", B: "Yei", C: "Wau", D: "Malakal" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 425, soru: "Eritre'nin başkenti neresidir?", secenekler: { A: "Asmara", B: "Keren", C: "Massawa", D: "Assab" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 426, soru: "Cibuti'nın başkenti neresidir?", secenekler: { A: "Cibuti", B: "Ali Sabieh", C: "Dikhil", D: "Tadjoura" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 427, soru: "Somali'nin başkenti neresidir?", secenekler: { A: "Mogadişu", B: "Hargeisa", C: "Berbera", D: "Kismayo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 428, soru: "Uganda'nın başkenti neresidir?", secenekler: { A: "Kampala", B: "Entebbe", C: "Jinja", D: "Mbarara" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 429, soru: "Ruanda'nın başkenti neresidir?", secenekler: { A: "Kigali", B: "Butare", C: "Gisenyi", D: "Gitarama" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 330, soru: "Burundi'nin başkenti neresidir?", secenekler: { A: "Gitega", B: "Bujumbura", C: "Muyinga", D: "Ngozi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 431, soru: "Malavi'nin başkenti neresidir?", secenekler: { A: "Lilongwe", B: "Blantyre", C: "Mzuzu", D: "Zomba" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 432, soru: "Zambiya'nın başkenti neresidir?", secenekler: { A: "Lusaka", B: "Kitwe", C: "Ndola", D: "Livingstone" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 433, soru: "Zimbabve'nin başkenti neresidir?", secenekler: { A: "Harare", B: "Bulawayo", C: "Mutare", D: "Gweru" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 434, soru: "Botsvana'nın başkenti neresidir?", secenekler: { A: "Gaborone", B: "Francistown", C: "Molepolole", D: "Maun" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 435, soru: "Namibya'nın başkenti neresidir?", secenekler: { A: "Windhoek", B: "Walvis Bay", C: "Swakopmund", D: "Rundu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 436, soru: "Lesotho'nun başkenti neresidir?", secenekler: { A: "Maseru", B: "Teyateyaneng", C: "Mafeteng", D: "Hlotse" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 437, soru: "Esvatini'nin (Svaziland) başkenti neresidir?", secenekler: { A: "Mbabane", B: "Lobamba", C: "Manzini", D: "Big Bend" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 438, soru: "Moritanya'nın başkenti neresidir?", secenekler: { A: "Nuakşot", B: "Nuadhibou", C: "Kiffa", D: "Rosso" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 439, soru: "Estonya'nın başkenti neresidir?", secenekler: { A: "Tallinn", B: "Tartu", C: "Narva", D: "Pärnu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 440, soru: "Letonya'nın başkenti neresidir?", secenekler: { A: "Riga", B: "Daugavpils", C: "Liepaja", D: "Jelgava" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 441, soru: "Litvanya'nın başkenti neresidir?", secenekler: { A: "Vilnius", B: "Kaunas", C: "Klaipeda", D: "Siauliai" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 442, soru: "Slovakya'nın başkenti neresidir?", secenekler: { A: "Bratislava", B: "Kosice", C: "Presov", D: "Zilina" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 443, soru: "Slovenya'nın başkenti neresidir?", secenekler: { A: "Ljubljana", B: "Maribor", C: "Celje", D: "Kranj" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 444, soru: "Hırvatistan'ın başkenti neresidir?", secenekler: { A: "Zagreb", B: "Split", C: "Rijeka", D: "Osijek" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 445, soru: "Bosna Hersek'in başkenti neresidir?", secenekler: { A: "Saraybosna", B: "Banja Luka", C: "Tuzla", D: "Zenica" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 446, soru: "Sırbistan'ın başkenti neresidir?", secenekler: { A: "Belgrad", B: "Novi Sad", C: "Niş", D: "Kragujevac" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 447, soru: "Karadağ'ın başkenti neresidir?", secenekler: { A: "Podgorica", B: "Nikšić", C: "Çetine", D: "Pljevlja" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 448, soru: "Arnavutluk'un başkenti neresidir?", secenekler: { A: "Tiran", B: "Durrës", C: "Vlorë", D: "Elbasan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 449, soru: "Makedonya'nın (Kuzey Makedonya) başkenti neresidir?", secenekler: { A: "Üsküp", B: "Bitola", C: "Kumanovo", D: "Prilep" }, dogruCevap: "A" }
 
 
 
);
