window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Klasik ve Kolay Bilmeceler
    { seviye: 1, kategori: "Bilmece", soru: "Şehirleri var ama evleri yok. Dağları var ama ağaçları yok. Suları var ama balıkları yok. Bu nedir?", secenekler: { A: "Harita", B: "Küresel ısınma", C: "Çöl", D: "Resim" }, dogruCevap: "A" },
    { seviye: 1, kategori: "Bilmece", soru: "Ben giderim o gider, üstümde gölge eder.", secenekler: { A: "Bulut", B: "Şemsiye", C: "Güneş", D: "Şapka" }, dogruCevap: "B" },
    { seviye: 1, kategori: "Bilmece", soru: "Pazardan aldım bir tane, eve geldim bin tane.", secenekler: { A: "Pirinç", B: "Nar", C: "Mısır", D: "Üzüm" }, dogruCevap: "B" },
    { seviye: 1, kategori: "Bilmece", soru: "Sesi var canı yok, konuşur ağzı yok.", secenekler: { A: "Rüzgar", B: "Yankı", C: "Radyo", D: "Telefon" }, dogruCevap: "B" },
    { seviye: 2, kategori: "Bilmece", soru: "Yer altında yağlı kayış.", secenekler: { A: "Solucan", B: "Yılan", C: "Kemer", D: "Hortum" }, dogruCevap: "B" },
    { seviye: 2, kategori: "Bilmece", soru: "İki camlı pencere, bakıp durur her yere.", secenekler: { A: "Gözlük", B: "Dürbün", C: "Göz", D: "Ayna" }, dogruCevap: "A" },
    { seviye: 2, kategori: "Bilmece", soru: "İncecik beli, elimdedir dili.", secenekler: { A: "Kaşık", B: "Zil", C: "Kalem", D: "Bardak" }, dogruCevap: "C" },
    { seviye: 2, kategori: "Bilmece", soru: "Kolu var eli yok, karnı yarık karnı yok.", secenekler: { A: "Ceket", B: "Gömlek", C: "Yelek", D: "Pantolon" }, dogruCevap: "A" },
    { seviye: 3, kategori: "Bilmece", soru: "Bir küçücük fıçıcık, içi dolu turşucuk.", secenekler: { A: "Limon", B: "Zeytin", C: "Limon", D: "Mandalina" }, dogruCevap: "D" },
    { seviye: 3, kategori: "Bilmece", soru: "Ayakları var yürüyemez, dili var konuşamaz.", secenekler: { A: "Masa", B: "Sandalye", C: "Ayakkabı", D: "Araba" }, dogruCevap: "C" },
    { seviye: 3, kategori: "Bilmece", soru: "Gökten iner bir avuç, tadı şekerden tatlı.", secenekler: { A: "Kar", B: "Yağmur", C: "Dut", D: "Dolu" }, dogruCevap: "C" },
    { seviye: 4, kategori: "Bilmece", soru: "Yatınca yatar, kalkınca kalkar.", secenekler: { A: "Yorgan", B: "Yastık", C: "Parmak", D: "Ayakkabı" }, dogruCevap: "C" },
    { seviye: 4, kategori: "Bilmece", soru: "Hiç ağzı yok ama her dile cevap verir.", secenekler: { A: "Kağıt", B: "Yankı", C: "Kitap", D: "Ayna" }, dogruCevap: "B" },
    { seviye: 4, kategori: "Bilmece", soru: "Bir tarlam var, beyaz gül açar.", secenekler: { A: "Gökyüzü / Yıldızlar", B: "Kağıt / Yazı", C: "Bahçe / Kar", D: "Deniz / Köpük" }, dogruCevap: "C" },
    { seviye: 5, kategori: "Bilmece", soru: "Dışı var içi yok, dayak yer suçu yok.", secenekler: { A: "Top", B: "Davul", C: "Halı", D: "Yastık" }, dogruCevap: "B" },
    { seviye: 5, kategori: "Bilmece", soru: "Geldi mi gitmez, gitti mi gelmez.", secenekler: { A: "Misafir", B: "Gençlik", C: "Zaman", D: "Sağlık" }, dogruCevap: "B" },
    { seviye: 5, kategori: "Bilmece", soru: "Ağzı var dili yok, nefesi var canı yok.", secenekler: { A: "Düdük", B: "Ney", C: "Kavala", D: "Balon" }, dogruCevap: "D" },
    { seviye: 6, kategori: "Bilmece", soru: "Kapağı var kitap değil, kulu var kapı değil.", secenekler: { A: "Tencere", B: "Göz", C: "Dolap", D: "Çanta" }, dogruCevap: "B" },
    { seviye: 6, kategori: "Bilmece", soru: "Daldan dala atlar, kuyruğuyla oynar.", secenekler: { A: "Kedi", B: "Maymun", C: "Sincap", D: "Kuş" }, dogruCevap: "B" },
    { seviye: 6, kategori: "Bilmece", soru: "Bir ağacı oymuşlar, içine dünyayı koymuşlar.", secenekler: { A: "Gemi", B: "Radyo", C: "Televizyon", D: "Sandık" }, dogruCevap: "B" },
    { seviye: 7, kategori: "Bilmece", soru: "Kanadı var uçamaz, ağzı var konuşamaz.", secenekler: { A: "Tavuk", B: "Balık", C: "Penguen", D: "Uçak" }, dogruCevap: "B" },
    { seviye: 7, kategori: "Bilmece", soru: "Gökyüzünde gördüm bir köprü, rengi var yedi türlü.", secenekler: { A: "Bulut", B: "Uçak", C: "Gökkuşağı", D: "Yıldız" }, dogruCevap: "C" },
    { seviye: 7, kategori: "Bilmece", soru: "Uzun uzun uzarlar, her yıl kışın azalırlar.", secenekler: { A: "Günler", B: "Geceler", C: "Saçlar", D: "Yollar" }, dogruCevap: "A" },
    { seviye: 8, kategori: "Bilmece", soru: "Canı var kanı yok, sesi var dili yok.", secenekler: { A: "Arı", B: "Sinek", C: "Kelebek", D: "Balık" }, dogruCevap: "B" },
    { seviye: 8, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Tükenmez kalem", B: "Kurşun kalem", C: "Kontrol kalemi", D: "Dolma kalem" }, dogruCevap: "C" },

    // 26-100: Karışık, Zeka ve Kelime Oyunlu Bilmeceler
    { seviye: 26, kategori: "Bilmece", soru: "Karşıdan baktım hiç yok, yanına gittim pek çok.", secenekler: { A: "Karınca", B: "Çiçek", C: "Kum", D: "Ağaç" }, dogruCevap: "A" },
    { seviye: 27, kategori: "Bilmece", soru: "En çok hangi ilimizde güneş gözlüğü kullanılır?", secenekler: { A: "Antalya", B: "Muğla", C: "Göz-lük (Gözlük)", D: "Van" }, dogruCevap: "C" },
    { seviye: 28, kategori: "Bilmece", soru: "Pişirirsen aş olur, pişirmezsen kuş olur.", secenekler: { A: "Pirinç", B: "Yumurta", C: "Mısır", D: "Buğday" }, dogruCevap: "B" },
    { seviye: 29, kategori: "Bilmece", soru: "İçinde derya var, nehir var ama hiç su yok.", secenekler: { A: "Atlas", B: "Şişe", C: "Sürahi", D: "Bardak" }, dogruCevap: "A" },
    { seviye: 30, kategori: "Bilmece", soru: "Canlı gider, cansız gelir.", secenekler: { A: "Avcı", B: "Balıkçı", C: "Kasap", D: "Aşçı" }, dogruCevap: "B" },
    { seviye: 31, kategori: "Bilmece", soru: "Dokunmadan kırılan şey nedir?", secenekler: { A: "Cam", B: "Kalp", C: "Buz", D: "Ayna" }, dogruCevap: "B" },
    { seviye: 32, kategori: "Bilmece", soru: "Hangi tastan su içilmez?", secenekler: { A: "Altın tas", B: "Gümüş tas", C: "Kafatası", D: "Bakır tas" }, dogruCevap: "C" },
    { seviye: 33, kategori: "Bilmece", soru: "Sadece kullanıldığında kırılan şey nedir?", secenekler: { A: "Yumurta", B: "Kömür", C: "Fındık", D: "Ceviz" }, dogruCevap: "A" },
    { seviye: 34, kategori: "Bilmece", soru: "Hangi macunla diş fırçalanmaz?", secenekler: { A: "Beyaz macun", B: "Naneli macun", C: "Lahmacun", D: "Çilekli macun" }, dogruCevap: "C" },
    { seviye: 35, kategori: "Bilmece", soru: "Sıcak dondurma nerede bulunur?", secenekler: { A: "Antalya'da", B: "Fırında", C: "Güneşte", D: "Hayallerde" }, dogruCevap: "B" },
    { seviye: 36, kategori: "Bilmece", soru: "Yarım elma neye benzer?", secenekler: { A: "Ay'a", B: "Elmaya", C: "Diğer yarısına", D: "Topa" }, dogruCevap: "C" },
    { seviye: 37, kategori: "Bilmece", soru: "Hangi karnede not olmaz?", secenekler: { A: "Sağlık karnesi", B: "Okul karnesi", C: "Sürücü karnesi", D: "Vize karnesi" }, dogruCevap: "A" },
    { seviye: 38, kategori: "Bilmece", soru: "Yürür yürür iz etmez, hızı her gün değişmez.", secenekler: { A: "Araba", B: "Saat", C: "Güneş", D: "Rüzgar" }, dogruCevap: "B" },
    { seviye: 39, kategori: "Bilmece", soru: "En ağır meyve hangisidir?", secenekler: { A: "Karpuz", B: "Kavun", C: "Bal kabağı", D: "İncir (B-in-cir)" }, dogruCevap: "D" },
    { seviye: 40, kategori: "Bilmece", soru: "Kökü var ama bitki değil, tırmanır ama hayvan değil.", secenekler: { A: "Diş", B: "Tırnak", C: "Saç", D: "Burun" }, dogruCevap: "A" },
    { seviye: 41, kategori: "Bilmece", soru: "Gözle görülmez, elle tutulmaz, onsuz yaşanmaz.", secenekler: { A: "Rüzgar", B: "Hava", C: "Koku", D: "Sevgi" }, dogruCevap: "B" },
    { seviye: 42, kategori: "Bilmece", soru: "Dili yok ama her şeyi anlatır.", secenekler: { A: "Resim", B: "Kitap", C: "Heykel", D: "Mektup" }, dogruCevap: "B" },
    { seviye: 43, kategori: "Bilmece", soru: "Hangi kapı açılmaz?", secenekler: { A: "Demir kapı", B: "Tahta kapı", C: "Kale kapısı", D: "Çıkış kapısı" }, dogruCevap: "D" },
    { seviye: 44, kategori: "Bilmece", soru: "Başı var kulağı yok, karnı var bacağı yok.", secenekler: { A: "Yılan", B: "Kuş", C: "Balık", D: "Böcek" }, dogruCevap: "A" },
    { seviye: 45, kategori: "Bilmece", soru: "Bir küçücük sandık, içi dolu boncuk.", secenekler: { A: "Nar", B: "Bezelye", C: "Mısır", D: "Fasulye" }, dogruCevap: "A" },
    { seviye: 46, kategori: "Bilmece", soru: "Gece çıkar, gündüz kaçar.", secenekler: { A: "Güneş", B: "Ay", C: "Yıldız", D: "Bulut" }, dogruCevap: "B" },
    { seviye: 47, kategori: "Bilmece", soru: "Şekerden tatlı, zehirden acı.", secenekler: { A: "Bal", B: "Söz", C: "Aşk", D: "Kader" }, dogruCevap: "B" },
    { seviye: 48, kategori: "Bilmece", soru: "Açarsın içini, görürsün kendini.", secenekler: { A: "Kitap", B: "Ayna", C: "Pencere", D: "Kapı" }, dogruCevap: "B" },
    { seviye: 49, kategori: "Bilmece", soru: "Ay varken çıkar, gün varken kaçar.", secenekler: { A: "Yıldız", B: "Baykuş", C: "Gölge", D: "Rüya" }, dogruCevap: "A" },
    { seviye: 50, kategori: "Bilmece", soru: "Hangi bağda üzüm yetişmez?", secenekler: { A: "Kara bağ", B: "Karabağ", C: "Siyah bağ", D: "Ayakkabı bağı" }, dogruCevap: "D" },
    { seviye: 51, kategori: "Bilmece", soru: "Canı var kanı yok, karnı var canı yok.", secenekler: { A: "Bebek", B: "Oyuncak bebek", C: "Kedi", D: "Kuş" }, dogruCevap: "B" },
    { seviye: 52, kategori: "Bilmece", soru: "Ateşe girer yanmaz, suya girer boğulmaz.", secenekler: { A: "Hava", B: "Işık", C: "Rüzgar", D: "Gölge" }, dogruCevap: "B" },
    { seviye: 53, kategori: "Bilmece", soru: "Ben giderim o gider, yanımda arkamda gider.", secenekler: { A: "Gölge", B: "Bulut", C: "Ay", D: "Güneş" }, dogruCevap: "A" },
    { seviye: 54, kategori: "Bilmece", soru: "Başı var beyni yok.", secenekler: { A: "Soğan", B: "Patates", C: "Kabak", D: "Elma" }, dogruCevap: "A" },
    { seviye: 55, kategori: "Bilmece", soru: "Tüyden hafif ama kimse onu çok uzun süre tutamaz.", secenekler: { A: "Bulut", B: "Balon", C: "Nefes", D: "Su damlası" }, dogruCevap: "C" },
    { seviye: 56, kategori: "Bilmece", soru: "İnsan neyi yutarsa ölmez ama yutkunursa ölür?", secenekler: { A: "Su", B: "Yemek", C: "Tükürük", D: "Hava" }, dogruCevap: "C" },
    { seviye: 57, kategori: "Bilmece", soru: "Gelen gider, giden gelmez.", secenekler: { A: "Zaman", B: "Gençlik", C: "Misafir", D: "Güneş" }, dogruCevap: "A" },
    { seviye: 58, kategori: "Bilmece", soru: "Her şeyi görür ama kendini göremez.", secenekler: { A: "Kamera", B: "Göz", C: "Ayna", D: "Dürbün" }, dogruCevap: "B" },
    { seviye: 59, kategori: "Bilmece", soru: "Doluşuruz bir kutuya, gideriz uzaklara.", secenekler: { A: "Araba", B: "Otobüs", C: "Tren", D: "Uçak" }, dogruCevap: "B" },
    { seviye: 60, kategori: "Bilmece", soru: "Evi var kapısı yok, içi dolu sofrası yok.", secenekler: { A: "Karpuz", B: "Kabak", C: "Domates", D: "Biber" }, dogruCevap: "A" },
    { seviye: 61, kategori: "Bilmece", soru: "Hangi bankaya para yatırılmaz?", secenekler: { A: "Merkez bankası", B: "Kan bankası", C: "Ziraat bankası", D: "Halk bankası" }, dogruCevap: "B" },
    { seviye: 62, kategori: "Bilmece", soru: "Açarsın genişler, kaparsın daralır.", secenekler: { A: "Kapı", B: "Pencere", C: "Şemsiye", D: "Perde" }, dogruCevap: "C" },
    { seviye: 63, kategori: "Bilmece", soru: "Dışı var içi yok, sesi var dili yok.", secenekler: { A: "Zil", B: "Çan", C: "Düdük", D: "Kaval" }, dogruCevap: "A" },
    { seviye: 64, kategori: "Bilmece", soru: "Ayakları su içer, üstü güneşlenir.", secenekler: { A: "İnsan", B: "Hayvan", C: "Ağaç", D: "Gölge" }, dogruCevap: "C" },
    { seviye: 65, kategori: "Bilmece", soru: "Hangi filin hortumu yoktur?", secenekler: { A: "Asya fili", B: "Afrika fili", C: "Profil", D: "Yavru fil" }, dogruCevap: "C" },
    { seviye: 66, kategori: "Bilmece", soru: "Yazın giyer, kışın çıkarır.", secenekler: { A: "Mont", B: "Kazak", C: "Ağaç", D: "Çiçek" }, dogruCevap: "C" },
    { seviye: 67, kategori: "Bilmece", soru: "Hangi kalemle resim yapılmaz?", secenekler: { A: "Boya kalemi", B: "Kurşun kalem", C: "Kontrol kalemi", D: "Keçeli kalem" }, dogruCevap: "C" },
    { seviye: 68, kategori: "Bilmece", soru: "Hiç yorulmadan dünyayı gezen nedir?", secenekler: { A: "Bulut", B: "Rüzgar", C: "Güneş", D: "Ay" }, dogruCevap: "C" },
    { seviye: 69, kategori: "Bilmece", soru: "Dışı kaktüs, içi süt.", secenekler: { A: "Hindistan cevizi", B: "Ananas", C: "Kavun", D: "Karpuz" }, dogruCevap: "A" },
    { seviye: 70, kategori: "Bilmece", soru: "Geceleri fener, gündüzleri söner.", secenekler: { A: "Mum", B: "Lamba", C: "Ateş böceği", D: "Güneş" }, dogruCevap: "C" },
    { seviye: 71, kategori: "Bilmece", soru: "Hangi kuşun kanadı vardır ama uçamaz?", secenekler: { A: "Deve kuşu", B: "Serçe", C: "Kırlangıç", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 72, kategori: "Bilmece", soru: "Bir yanı beyaz, bir yanı kara.", secenekler: { A: "Gündüz - Gece", B: "Siyah - Beyaz", C: "Kağıt - Kalem", D: "Bulut - Yağmur" }, dogruCevap: "A" },
    { seviye: 73, kategori: "Bilmece", soru: "Hem ısıtır, hem yakar.", secenekler: { A: "Güneş", B: "Ateş", C: "Soba", D: "Elektrik" }, dogruCevap: "B" },
    { seviye: 74, kategori: "Bilmece", soru: "Hangi meyve her zaman yalnızdır?", secenekler: { A: "Elma", B: "Armut", C: "İncir", D: "Üzüm" }, dogruCevap: "B" },
    { seviye: 75, kategori: "Bilmece", soru: "İçinde rüzgar eser, kapısında kilit yok.", secenekler: { A: "Mağara", B: "Baca", C: "Pencere", D: "Kapı" }, dogruCevap: "B" },
    { seviye: 76, kategori: "Bilmece", soru: "Yer altında sakallı dede.", secenekler: { A: "Patates", B: "Soğan", C: "Pırasa", D: "Havuç" }, dogruCevap: "C" },
    { seviye: 77, kategori: "Bilmece", soru: "Hangi köprünün altından su geçmez?", secenekler: { A: "Asma köprü", B: "Taş köprü", C: "Diş köprüsü", D: "Beton köprü" }, dogruCevap: "C" },
    { seviye: 78, kategori: "Bilmece", soru: "En temiz meyve hangisidir?", secenekler: { A: "Elma", B: "Üzüm", C: "Yıkanmış kiraz", D: "Yalan (Yal-an)" }, dogruCevap: "D" },
    { seviye: 79, kategori: "Bilmece", soru: "Kulağını bükünce sesi çıkar.", secenekler: { A: "Radyo", B: "Televizyon", C: "Müzik kutusu", D: "Musluk" }, dogruCevap: "D" },
    { seviye: 80, kategori: "Bilmece", soru: "Hangi ağaçta dal olmaz?", secenekler: { A: "Çam ağacı", B: "Elma ağacı", C: "Soyağacı", D: "Meşe ağacı" }, dogruCevap: "C" },
    { seviye: 81, kategori: "Bilmece", soru: "Sıcak dondurma nerede olur?", secenekler: { A: "Fırında", B: "Güneşte", C: "Antalya'da", D: "Kızartmada" }, dogruCevap: "A" },
    { seviye: 82, kategori: "Bilmece", soru: "Gittikçe kısalan şey nedir?", secenekler: { A: "Yol", B: "Ömür", C: "İp", D: "Kağıt" }, dogruCevap: "B" },
    { seviye: 83, kategori: "Bilmece", soru: "Hem ağlar hem güler.", secenekler: { A: "Bebek", B: "Bulut", C: "İnsan", D: "Yağmur" }, dogruCevap: "C" },
    { seviye: 84, kategori: "Bilmece", soru: "Hangi masada yemek yenmez?", secenekler: { A: "Altın masa", B: "Yemek masası", C: "Çalışma masası", D: "Dosya masası" }, dogruCevap: "D" },
    { seviye: 85, kategori: "Bilmece", soru: "Suya girer ıslanmaz, ateşe girer yanmaz.", secenekler: { A: "Gölge", B: "Işık", C: "Hava", D: "Koku" }, dogruCevap: "A" },
    { seviye: 86, kategori: "Bilmece", soru: "Sesi var ama canı yok.", secenekler: { A: "Rüzgar", B: "Yankı", C: "Radyo", D: "Zil" }, dogruCevap: "B" },
    { seviye: 87, kategori: "Bilmece", soru: "Hangi kuşun kanadı var ama uçamaz?", secenekler: { A: "Penguen", B: "Serçe", C: "Kartal", D: "Atmaca" }, dogruCevap: "A" },
    { seviye: 88, kategori: "Bilmece", soru: "Herkesin önünde olan ama kimsenin dokunamadığı nedir?", secenekler: { A: "Gelecek", B: "Güneş", C: "Hava", D: "Bulut" }, dogruCevap: "A" },
    { seviye: 89, kategori: "Bilmece", soru: "Hangi gül kokmaz?", secenekler: { A: "Yapay gül", B: "Kurumuş gül", C: "Virgül", D: "Solmuş gül" }, dogruCevap: "C" },
    { seviye: 90, kategori: "Bilmece", soru: "Canı var ama nefesi yok.", secenekler: { A: "Balık", B: "Bitki", C: "Gölge", D: "Ayna" }, dogruCevap: "B" },
    { seviye: 91, kategori: "Bilmece", soru: "Yer altında kırmızı fener.", secenekler: { A: "Turp", B: "Havuç", C: "Domates", D: "Biber" }, dogruCevap: "A" },
    { seviye: 92, kategori: "Bilmece", soru: "Hangi denizde balık olmaz?", secenekler: { A: "Ölü Deniz", B: "Ege Denizi", C: "Akdeniz", D: "Karadeniz" }, dogruCevap: "A" },
    { seviye: 93, kategori: "Bilmece", soru: "Ben giderim o gider, arkamdan beni izler.", secenekler: { A: "Gölge", B: "Kedi", C: "Bulut", D: "Ay" }, dogruCevap: "A" },
    { seviye: 94, kategori: "Bilmece", soru: "Hangi top zıplamaz?", secenekler: { A: "Futbol topu", B: "Kar topu", C: "Tenis topu", D: "Basketbol topu" }, dogruCevap: "B" },
    { seviye: 95, kategori: "Bilmece", soru: "Kolu var ama eli yok.", secenekler: { A: "Ceket", B: "Sandalye", C: "Masa", D: "Dolap" }, dogruCevap: "B" },
    { seviye: 96, kategori: "Bilmece", soru: "Hangi saatte yemek yenmez?", secenekler: { A: "Duvar saatinde", B: "Sabah saatinde", C: "Öğle saatinde", D: "Akşam saatinde" }, dogruCevap: "A" },
    { seviye: 97, kategori: "Bilmece", soru: "İncecik beli var, tatlı dili var.", secenekler: { A: "Kaşık", B: "Bardak", C: "Kalem", D: "Kitap" }, dogruCevap: "C" },
    { seviye: 98, kategori: "Bilmece", soru: "Sesi var ama canı yok.", secenekler: { A: "Rüzgar", B: "Yankı", C: "Radyo", D: "Telefon" }, dogruCevap: "B" },
    { seviye: 99, kategori: "Bilmece", soru: "Hangi ağaçta dal olmaz?", secenekler: { A: "Meşe", B: "Soyağacı", C: "Çam", D: "Elma" }, dogruCevap: "B" },
    { seviye: 100, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Kurşun", B: "Tükenmez", C: "Kontrol kalemi", D: "Dolma" }, dogruCevap: "C" },

    // bilmece.js devamı (101 - 200)
    { seviye: 101, kategori: "Bilmece", soru: "Çarşıdan aldım kapkara, evde oldu kıpkırmızı.", secenekler: { A: "Kömür", B: "Çay", C: "Nar", D: "Biber" }, dogruCevap: "A" },
    { seviye: 102, kategori: "Bilmece", soru: "Ben giderim o gider, yanımda tık tık eder.", secenekler: { A: "Baston", B: "Ayakkabı", C: "Saat", D: "Gölge" }, dogruCevap: "A" },
    { seviye: 103, kategori: "Bilmece", soru: "Ağzı var dili yok, nefesi var canı yok.", secenekler: { A: "Düdük", B: "Radyo", C: "Balon", D: "Kitap" }, dogruCevap: "C" },
    { seviye: 104, kategori: "Bilmece", soru: "Küçücük fıçıcık, içi dolu turşucuk.", secenekler: { A: "Limon", B: "Zeytin", C: "Fındık", D: "Turşu" }, dogruCevap: "B" },
    { seviye: 105, kategori: "Bilmece", soru: "Yer altında sakallı dede.", secenekler: { A: "Pırasa", B: "Soğan", C: "Havuç", D: "Patates" }, dogruCevap: "A" },
    { seviye: 106, kategori: "Bilmece", soru: "Bir küçücük mil taşı, dolanır dağı taşı.", secenekler: { A: "Göz", B: "Tekerlek", C: "Ayak", D: "Güneş" }, dogruCevap: "A" },
    { seviye: 107, kategori: "Bilmece", soru: "Bilgi verir herkese, ağzı yok konuşur sese.", secenekler: { A: "Bilgisayar", B: "Kitap", C: "Hoca", D: "Gazete" }, dogruCevap: "B" },
    { seviye: 108, kategori: "Bilmece", soru: "Ay varken uçar, gün varken kaçar.", secenekler: { A: "Baykuş", B: "Yarasa", C: "Yıldız", D: "Sinek" }, dogruCevap: "B" },
    { seviye: 109, kategori: "Bilmece", soru: "Ben yazarım o siler.", secenekler: { A: "Kalem", B: "Tebeşir", C: "Silgi", D: "Kağıt" }, dogruCevap: "C" },
    { seviye: 110, kategori: "Bilmece", soru: "İçer içersin bitmez, tadına doyum yetmez.", secenekler: { A: "Çay", B: "Su", C: "Hava", D: "Süt" }, dogruCevap: "C" },
    { seviye: 111, kategori: "Bilmece", soru: "Sıcağa koyarsın erir, soğuğa koyarsın donar.", secenekler: { A: "Buz", B: "Mum", C: "Demir", D: "Su" }, dogruCevap: "D" },
    { seviye: 112, kategori: "Bilmece", soru: "Daldan dala atlarım, kuyruğumdan tutarım.", secenekler: { A: "Sincap", B: "Maymun", C: "Kuş", D: "Kedi" }, dogruCevap: "B" },
    { seviye: 113, kategori: "Bilmece", soru: "Tarlada biter, sofraya gelir, her yemeğe tat verir.", secenekler: { A: "Tuz", B: "Soğan", C: "Ekmek", D: "Biber" }, dogruCevap: "B" },
    { seviye: 114, kategori: "Bilmece", soru: "Gece gündüz bekler, kapıyı çalana bakar.", secenekler: { A: "Kilit", B: "Zil", C: "Bekçi", D: "Paspas" }, dogruCevap: "A" },
    { seviye: 115, kategori: "Bilmece", soru: "Başında tacı var, padişah değil. Mahmuzu var, süvari değil.", secenekler: { A: "Horoz", B: "Tavus Kuşu", C: "Hindi", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 116, kategori: "Bilmece", soru: "Canı var kanı yok, sesi var dili yok.", secenekler: { A: "Radyo", B: "Sinek", C: "Keman", D: "Rüzgar" }, dogruCevap: "C" },
    { seviye: 117, kategori: "Bilmece", soru: "Yazın giyinir, kışın soyunur.", secenekler: { A: "İnsan", B: "Ağaç", C: "Yılan", D: "Ayı" }, dogruCevap: "B" },
    { seviye: 118, kategori: "Bilmece", soru: "Altı mermer, üstü mermer, içinde bir bülbül oynar.", secenekler: { A: "Göz", B: "Diş", C: "Ağız", D: "Dil" }, dogruCevap: "D" },
    { seviye: 119, kategori: "Bilmece", soru: "Kanadı var uçamaz, ağzı var konuşamaz.", secenekler: { A: "Balık", B: "Tavuk", C: "Uçak", D: "Penguen" }, dogruCevap: "A" },
    { seviye: 120, kategori: "Bilmece", soru: "Gökte gördüm bir köprü, rengi var yedi türlü.", secenekler: { A: "Gökkuşağı", B: "Bulut", C: "Yıldız", D: "Uçurtma" }, dogruCevap: "A" },
    { seviye: 121, kategori: "Bilmece", soru: "Dışı var içi yok, dayak yer suçu yok.", secenekler: { A: "Davul", B: "Halı", C: "Top", D: "Yastık" }, dogruCevap: "C" },
    { seviye: 122, kategori: "Bilmece", soru: "Şehirleri var yolu yok, denizi var suyu yok.", secenekler: { A: "Resim", B: "Harita", C: "Rüya", D: "Televizyon" }, dogruCevap: "B" },
    { seviye: 123, kategori: "Bilmece", soru: "İki camlı pencere, bakıp durur her yere.", secenekler: { A: "Gözlük", B: "Göz", C: "Dürbün", D: "Ayna" }, dogruCevap: "A" },
    { seviye: 124, kategori: "Bilmece", soru: "Akşam baktım çok idi, sabah baktım yok idi.", secenekler: { A: "Yıldız", B: "Rüya", C: "Karanlık", D: "Çiy" }, dogruCevap: "A" },
    { seviye: 125, kategori: "Bilmece", soru: "Ben giderim o kalır.", secenekler: { A: "Gölge", B: "İsim", C: "Ayak izi", D: "Zaman" }, dogruCevap: "C" },
    { seviye: 126, kategori: "Bilmece", soru: "Başına konar, seni serinletir.", secenekler: { A: "Şapka", B: "Vantilatör", C: "Gölge", D: "Rüzgar" }, dogruCevap: "A" },
    { seviye: 127, kategori: "Bilmece", soru: "Bir kapaklı, çok yapraklı, içinde bilgi saklı.", secenekler: { A: "Defter", B: "Kitap", C: "Ağaç", D: "Ansiklopedi" }, dogruCevap: "B" },
    { seviye: 128, kategori: "Bilmece", soru: "Elsiz ayaksız kapı açar.", secenekler: { A: "Rüzgar", B: "Hırsız", C: "Anahtar", D: "Hayalet" }, dogruCevap: "C" },
    { seviye: 129, kategori: "Bilmece", soru: "Yolu var yürünmez, beli var bükülmez.", secenekler: { A: "Dağ", B: "Yol", C: "Deniz", D: "Merdiven" }, dogruCevap: "A" },
    { seviye: 130, kategori: "Bilmece", soru: "Herkesin önünde, ama kimse göremez.", secenekler: { A: "Gelecek", B: "Burun", C: "Hava", D: "Düşünce" }, dogruCevap: "A" },
    { seviye: 131, kategori: "Bilmece", soru: "Bağlayınca yürür, çözünce durur.", secenekler: { A: "Ayakkabı", B: "At", C: "Araba", D: "Gemi" }, dogruCevap: "A" },
    { seviye: 132, kategori: "Bilmece", soru: "Suya düşer ıslanmaz, yere düşer paslanmaz.", secenekler: { A: "Güneş", B: "Işık", C: "Hava", D: "Gölge" }, dogruCevap: "D" },
    { seviye: 133, kategori: "Bilmece", soru: "Çiğnemeden yutar, karnında dünya var.", secenekler: { A: "Televizyon", B: "Buzdolabı", C: "Çöp kutusu", D: "Bilgisayar" }, dogruCevap: "B" },
    { seviye: 134, kategori: "Bilmece", soru: "Kulağını büktükçe sesi yükselir.", secenekler: { A: "Radyo", B: "Musluk", C: "İnsan", D: "Keman" }, dogruCevap: "A" },
    { seviye: 135, kategori: "Bilmece", soru: "Sarıdır sallanır, tadı baldan tatlıdır.", secenekler: { A: "Armut", B: "Kavun", C: "Muz", D: "Ayva" }, dogruCevap: "A" },
    { seviye: 136, kategori: "Bilmece", soru: "Ayakları var gidemez, yemek gelse yiyemez.", secenekler: { A: "Sandalye", B: "Masa", C: "Bebek", D: "Yatak" }, dogruCevap: "B" },
    { seviye: 137, kategori: "Bilmece", soru: "Açarsam dünya olur, kapatırsam rüya olur.", secenekler: { A: "Kitap", B: "Göz", C: "Pencere", D: "Perde" }, dogruCevap: "B" },
    { seviye: 138, kategori: "Bilmece", soru: "Göbeği var deliği yok.", secenekler: { A: "Patlıcan", B: "Karpuz", C: "Domates", D: "Kabak" }, dogruCevap: "B" },
    { seviye: 139, kategori: "Bilmece", soru: "Dört ayağı var ama yürüyemez.", secenekler: { A: "Sandalye", B: "Kedi", C: "Masa", D: "Köpek" }, dogruCevap: "C" },
    { seviye: 140, kategori: "Bilmece", soru: "Okuma yazma bilmez, ama her şeyi yazar.", secenekler: { A: "Kalem", B: "Kağıt", C: "Bilgisayar", D: "Daktilo" }, dogruCevap: "A" },
    { seviye: 141, kategori: "Bilmece", soru: "Ben giderim o gelir, peşimden tık tık eder.", secenekler: { A: "Ayak sesi", B: "Baston", C: "Saat", D: "Gölge" }, dogruCevap: "B" },
    { seviye: 142, kategori: "Bilmece", soru: "Tüyden hafif, ama kimse onu tutamaz.", secenekler: { A: "Duman", B: "Nefes", C: "Hava", D: "Bulut" }, dogruCevap: "B" },
    { seviye: 143, kategori: "Bilmece", soru: "İçi taş, dışı baş.", secenekler: { A: "Zeytin", B: "Kayısı", C: "Kaplumbağa", D: "Ev" }, dogruCevap: "C" },
    { seviye: 144, kategori: "Bilmece", soru: "Denizde var, karada yok.", secenekler: { A: "Balık", B: "Gemi", C: "Yosun", D: "Dalga" }, dogruCevap: "D" },
    { seviye: 145, kategori: "Bilmece", soru: "İğnesi var ama dikiş dikemez.", secenekler: { A: "Arı", B: "Kirpi", C: "Çam ağacı", D: "Doktor" }, dogruCevap: "A" },
    { seviye: 146, kategori: "Bilmece", soru: "Kolu var ama bacağı yok.", secenekler: { A: "Gömlek", B: "Sandalye", C: "Gözlük", D: "Masa" }, dogruCevap: "A" },
    { seviye: 147, kategori: "Bilmece", soru: "Kapağı var, tencere değil; yaprağı var, ağaç değil.", secenekler: { A: "Kitap", B: "Defter", C: "Marul", D: "Lahana" }, dogruCevap: "A" },
    { seviye: 148, kategori: "Bilmece", soru: "Suyu var ama içilmez.", secenekler: { A: "Deniz", B: "Göl", C: "Boya", D: "Havuz" }, dogruCevap: "C" },
    { seviye: 149, kategori: "Bilmece", soru: "Kanatları var ama kuş değil.", secenekler: { A: "Uçak", B: "Yel değirmeni", C: "Kelebek", D: "Helikopter" }, dogruCevap: "B" },
    { seviye: 150, kategori: "Bilmece", soru: "Başı var saç yok, gözü var kaş yok.", secenekler: { A: "İğne", B: "Balık", C: "Yumurta", D: "Patates" }, dogruCevap: "B" },
    { seviye: 151, kategori: "Bilmece", soru: "Ayakları su içer, başı güneş yer.", secenekler: { A: "Çiçek", B: "Ağaç", C: "İnsan", D: "Güneş şemsiyesi" }, dogruCevap: "B" },
    { seviye: 152, kategori: "Bilmece", soru: "Yer altında yuvası var, hırsız gibi kesesi var.", secenekler: { A: "Fare", B: "Köstebek", C: "Tavşan", D: "Karınca" }, dogruCevap: "B" },
    { seviye: 153, kategori: "Bilmece", soru: "İki kardeş var, birbirini görmez.", secenekler: { A: "Kulak", B: "Göz", C: "Ayak", D: "El" }, dogruCevap: "B" },
    { seviye: 154, kategori: "Bilmece", soru: "Bir ağacı oymuşlar, içine ses koymuşlar.", secenekler: { A: "Saz", B: "Kaval", C: "Dolap", D: "Kapı" }, dogruCevap: "A" },
    { seviye: 155, kategori: "Bilmece", soru: "Onu görürsün ama tutamazsın; o kaçar, sen kovalarsın.", secenekler: { A: "Gölge", B: "Bulut", C: "Gökkuşağı", D: "Rüzgar" }, dogruCevap: "A" },
    { seviye: 156, kategori: "Bilmece", soru: "Zenginin elinde, fakirin dilinde.", secenekler: { A: "Altın", B: "Para", C: "Ekmek", D: "Dua" }, dogruCevap: "B" },
    { seviye: 157, kategori: "Bilmece", soru: "İki teker, üzerinde şeker.", secenekler: { A: "Bisiklet", B: "Araba", C: "Motorsiklet", D: "At arabası" }, dogruCevap: "A" },
    { seviye: 158, kategori: "Bilmece", soru: "Tarlada yeşil, bakkalda siyah, evde kırmızı.", secenekler: { A: "Çay", B: "Kömür", C: "Zeytin", D: "Biber" }, dogruCevap: "A" },
    { seviye: 159, kategori: "Bilmece", soru: "Dişi var ısırmaz, sakalı var konuşmaz.", secenekler: { A: "Tarak", B: "Mısır", C: "Süpürge", D: "Kilit" }, dogruCevap: "B" },
    { seviye: 160, kategori: "Bilmece", soru: "Ben giderim o kalır, her adımda çoğalır.", secenekler: { A: "Gölge", B: "Ayak izi", C: "Zaman", D: "Yorgunluk" }, dogruCevap: "B" },
    { seviye: 161, kategori: "Bilmece", soru: "Daldan dala, kırmızı pala.", secenekler: { A: "Sincap", B: "Elma", C: "Kiraz", D: "Kuş" }, dogruCevap: "A" },
    { seviye: 162, kategori: "Bilmece", soru: "Gelişi güle güle, gidişi ağla ağla.", secenekler: { A: "Bebek", B: "Misafir", C: "Gelin", D: "Mevsim" }, dogruCevap: "C" },
    { seviye: 163, kategori: "Bilmece", soru: "Hangi bağda üzüm yetişmez?", secenekler: { A: "Ayakkabı bağında", B: "Üzüm bağında", C: "Sevgi bağında", D: "Bahçede" }, dogruCevap: "A" },
    { seviye: 164, kategori: "Bilmece", soru: "Bir sihirli fenerim, kime baksam dönerim.", secenekler: { A: "Göz", B: "Ayna", C: "Fotoğraf makinesi", D: "El feneri" }, dogruCevap: "B" },
    { seviye: 165, kategori: "Bilmece", soru: "Yer altında turuncu direk.", secenekler: { A: "Havuç", B: "Patates", C: "Yer elması", D: "Soğan" }, dogruCevap: "A" },
    { seviye: 166, kategori: "Bilmece", soru: "Beyaz sarayda sarı sultan.", secenekler: { A: "Yumurta", B: "Peynir", C: "Limon", D: "Güneş" }, dogruCevap: "A" },
    { seviye: 167, kategori: "Bilmece", soru: "Hangi piyanoda tuş yoktur?", secenekler: { A: "Su piyanosu", B: "Eski piyano", C: "Hayali piyano", D: "Böyle bir piyano yok" }, dogruCevap: "D" },
    { seviye: 168, kategori: "Bilmece", soru: "Güneş gidince gelir, gökyüzünü süsler.", secenekler: { A: "Yıldız", B: "Ay", C: "Gece", D: "Bulut" }, dogruCevap: "B" },
    { seviye: 169, kategori: "Bilmece", soru: "Mini mini kuşlar, her yeri gümüşler.", secenekler: { A: "Kar", B: "Yağmur", C: "Dolu", D: "Yıldız" }, dogruCevap: "A" },
    { seviye: 170, kategori: "Bilmece", soru: "Hanım içerde, saçı dışarda.", secenekler: { A: "Mısır", B: "Kabak", C: "Patlıcan", D: "Lahana" }, dogruCevap: "A" },
    { seviye: 171, kategori: "Bilmece", soru: "Yarım kaşık, duvara yapışık.", secenekler: { A: "Kulak", B: "Burun", C: "Göz", D: "Ağız" }, dogruCevap: "A" },
    { seviye: 172, kategori: "Bilmece", soru: "Bir kuşum var, her yeri kazar.", secenekler: { A: "Kalem", B: "İğne", C: "Tavuk", D: "Köstebek" }, dogruCevap: "A" },
    { seviye: 173, kategori: "Bilmece", soru: "Derisi var canı yok, yaprağı var ağaç değil.", secenekler: { A: "Kitap", B: "Marul", C: "Lahana", D: "Defter" }, dogruCevap: "A" },
    { seviye: 174, kategori: "Bilmece", soru: "Bacakları var ama yürümez.", secenekler: { A: "Pantolon", B: "Sandalye", C: "Masa", D: "Gözlük" }, dogruCevap: "A" },
    { seviye: 175, kategori: "Bilmece", soru: "Su içine girince ne olur?", secenekler: { A: "Islanır", B: "Batar", C: "Yüzer", D: "Kaybolur" }, dogruCevap: "A" },
    { seviye: 176, kategori: "Bilmece", soru: "Yatağı var ama uyumaz, ağzı var ama konuşmaz.", secenekler: { A: "Irmak", B: "Bebek", C: "Yatak", D: "Deniz" }, dogruCevap: "A" },
    { seviye: 177, kategori: "Bilmece", soru: "Baş aşağı durur, su içince ölür.", secenekler: { A: "Mum", B: "Ateş", C: "Çivi", D: "Yarasa" }, dogruCevap: "B" },
    { seviye: 178, kategori: "Bilmece", soru: "Canlıyı boğar, cansızı doğurur.", secenekler: { A: "Toprak", B: "Su", C: "Hava", D: "Ateş" }, dogruCevap: "B" },
    { seviye: 179, kategori: "Bilmece", soru: "Her şeyi görür, kendini göremez.", secenekler: { A: "Göz", B: "Ayna", C: "Kamera", D: "Işık" }, dogruCevap: "A" },
    { seviye: 180, kategori: "Bilmece", soru: "Bin bir deliği var, suyu tutamaz.", secenekler: { A: "Elek", B: "Süzgeç", C: "Filtre", D: "Sünger" }, dogruCevap: "B" },
    { seviye: 181, kategori: "Bilmece", soru: "Eli yok ama kapı çalar.", secenekler: { A: "Rüzgar", B: "Zil", C: "Postacı", D: "Yağmur" }, dogruCevap: "A" },
    { seviye: 182, kategori: "Bilmece", soru: "Eriyen ama ıslatmayan nedir?", secenekler: { A: "Kuru buz", B: "Mum", C: "Şeker", D: "Tuz" }, dogruCevap: "B" },
    { seviye: 183, kategori: "Bilmece", soru: "Üstü kış, altı bahar.", secenekler: { A: "Dağ", B: "Ağaç", C: "İnsan", D: "Ev" }, dogruCevap: "A" },
    { seviye: 184, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Boya kalemi", B: "Kontrol kalemi", C: "Kurşun kalem", D: "Tükenmez kalem" }, dogruCevap: "B" },
    { seviye: 185, kategori: "Bilmece", soru: "Bir sihirli kutu, içi dolu bilgi.", secenekler: { A: "Televizyon", B: "Bilgisayar", C: "Radyo", D: "Telefon" }, dogruCevap: "B" },
    { seviye: 186, kategori: "Bilmece", soru: "Hiç hareket etmeden tüm dünyayı gezer.", secenekler: { A: "Pul", B: "Yol", C: "Harita", D: "Uçak" }, dogruCevap: "A" },
    { seviye: 187, kategori: "Bilmece", soru: "Çıt çıt eder, her yeri gezer.", secenekler: { A: "Makas", B: "Ayakkabı", C: "Saat", D: "Tekerlek" }, dogruCevap: "A" },
    { seviye: 188, kategori: "Bilmece", soru: "Yükü var, hamal değil; evi var, sahibi değil.", secenekler: { A: "Salyangoz", B: "Kaplumbağa", C: "Karınca", D: "Kamyon" }, dogruCevap: "A" },
    { seviye: 189, kategori: "Bilmece", soru: "Isırır ama dişi yok.", secenekler: { A: "Soğuk", B: "Biber", C: "Isırgan otu", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 190, kategori: "Bilmece", soru: "Kışın güneş kremi sürer.", secenekler: { A: "Kayakçı", B: "Kardan adam", C: "Güneş gözlüğü", D: "Ayna" }, dogruCevap: "B" },
    { seviye: 191, kategori: "Bilmece", soru: "Dili yok ama yalan söylemez.", secenekler: { A: "Ayna", B: "Kitap", C: "Resim", D: "Saat" }, dogruCevap: "A" },
    { seviye: 192, kategori: "Bilmece", soru: "Hangi kanat uçamaz?", secenekler: { A: "Uçak kanadı", B: "Kapı kanadı", C: "Kuş kanadı", D: "Kelebek kanadı" }, dogruCevap: "B" },
    { seviye: 193, kategori: "Bilmece", soru: "Diri girer, ölü çıkar.", secenekler: { A: "Hamam", B: "Fırın", C: "Ekmek", D: "Yemek" }, dogruCevap: "C" },
    { seviye: 194, kategori: "Bilmece", soru: "Suya girer kupkuru, sudan çıkar ıslak.", secenekler: { A: "Şeker", B: "Tuz", C: "Bardak", D: "Sünger" }, dogruCevap: "D" },
    { seviye: 195, kategori: "Bilmece", soru: "Eli var kolu yok, karnı yarık canı yok.", secenekler: { A: "Ceket", B: "Yelek", C: "Gömlek", D: "Pantolon" }, dogruCevap: "B" },
    { seviye: 196, kategori: "Bilmece", soru: "Ben giderim o kalır, her zaman arkamda kalır.", secenekler: { A: "Ayak izi", B: "Gölge", C: "Dün", D: "İsim" }, dogruCevap: "A" },
    { seviye: 197, kategori: "Bilmece", soru: "Yerin altında gümüş saray.", secenekler: { A: "Sarımsak", B: "Turp", C: "Soğan", D: "Patates" }, dogruCevap: "A" },
    { seviye: 198, kategori: "Bilmece", soru: "İncecik beli, elimin dili.", secenekler: { A: "Kalem", B: "Kaşık", C: "Fırça", D: "Çatal" }, dogruCevap: "A" },
    { seviye: 199, kategori: "Bilmece", soru: "Bir yanı beyaz, bir yanı kara.", secenekler: { A: "Gece-Gündüz", B: "Kağıt", C: "Yol", D: "Piyano" }, dogruCevap: "A" },
    { seviye: 200, kategori: "Bilmece", soru: "Okur ama bilmez, söyler ama duymaz.", secenekler: { A: "Kitap", B: "Radyo", C: "Papağan", D: "Mektup" }, dogruCevap: "A" }, 
    // 201-350: Yeni Nesil, Klasik ve Zeka Sorusu Tadında Bilmeceler
    { seviye: 201, kategori: "Bilmece", soru: "Gökten yağar, ıslatmaz; yerden biter, kök salmaz.", secenekler: { A: "Kar", B: "Dolu", C: "Sis", D: "Işık" }, dogruCevap: "D" },
    { seviye: 202, kategori: "Bilmece", soru: "Bir küçücük mil taşı, dolanır dağı taşı.", secenekler: { A: "Göz", B: "Araba", C: "Güneş", D: "Tekerlek" }, dogruCevap: "A" },
    { seviye: 203, kategori: "Bilmece", soru: "Benim bir hayvanım var, kuyruğundan uzun burnu var.", secenekler: { A: "Zürafa", B: "Fil", C: "Karıncayiyen", D: "Gergedan" }, dogruCevap: "B" },
    { seviye: 204, kategori: "Bilmece", soru: "Sesi var, görüntüsü yok; kendisi var, canı yok.", secenekler: { A: "Rüzgar", B: "Ruh", C: "Gölge", D: "Dua" }, dogruCevap: "A" },
    { seviye: 205, kategori: "Bilmece", soru: "Akşam baktım çok idi, sabah baktım yok idi.", secenekler: { A: "Rüya", B: "Yıldızlar", C: "Bulutlar", D: "Hırsızlar" }, dogruCevap: "B" },
    { seviye: 206, kategori: "Bilmece", soru: "Küçücük bakkal, dünyayı yutar.", secenekler: { A: "Ağız", B: "Mide", C: "Göz", D: "Kulak" }, dogruCevap: "C" },
    { seviye: 207, kategori: "Bilmece", soru: "Cansızdır ama nefes alır, yeri gelir fırtına koparır.", secenekler: { A: "Körük", B: "Vantilatör", C: "Balon", D: "Dalga" }, dogruCevap: "A" },
    { seviye: 208, kategori: "Bilmece", soru: "Başı var kulağı yok, ayağı var ayakkabısı yok.", secenekler: { A: "Yılan", B: "Çivi", C: "Sandalye", D: "Masa" }, dogruCevap: "B" },
    { seviye: 209, kategori: "Bilmece", soru: "Her gün yeniden doğar, akşam olunca ölür.", secenekler: { A: "Güneş", B: "Çiçek", C: "Bebek", D: "Umut" }, dogruCevap: "A" },
    { seviye: 210, kategori: "Bilmece", soru: "Hangi kelime yanlış yazılsa bile doğru okunur?", secenekler: { A: "Eksik", B: "Hatalı", C: "Yanlış", D: "Doğru" }, dogruCevap: "C" },
    { seviye: 211, kategori: "Bilmece", soru: "Sıfırdan büyüktür ama hiçbir şeyi yoktur.", secenekler: { A: "Bir", B: "Fakir", C: "Nokta", D: "Boşluk" }, dogruCevap: "A" },
    { seviye: 212, kategori: "Bilmece", soru: "Daldan dala atlarım, kuyruğumla tutunurum.", secenekler: { A: "Sincap", B: "Maymun", C: "Kuş", D: "Kedi" }, dogruCevap: "B" },
    { seviye: 213, kategori: "Bilmece", soru: "Ayakları var yürüyemez, sırtı var yatamaz.", secenekler: { A: "Sandalye", B: "Masa", C: "Yatak", D: "Dolap" }, dogruCevap: "A" },
    { seviye: 214, kategori: "Bilmece", soru: "Yazın giyinir, kışın soyunur.", secenekler: { A: "Ağaç", B: "Yılan", C: "Güneş", D: "Çocuk" }, dogruCevap: "A" },
    { seviye: 215, kategori: "Bilmece", soru: "Hangi masada yemek yenmez?", secenekler: { A: "Yuvarlak masa", B: "Çalışma masası", C: "Dizüstü bilgisayar (masaüstü)", D: "Ameliyat masası" }, dogruCevap: "D" },
    { seviye: 216, kategori: "Bilmece", soru: "Ben giderim o gider, kolumda tık tık eder.", secenekler: { A: "Kalp", B: "Saat", C: "Bilezik", D: "Nabız" }, dogruCevap: "B" },
    { seviye: 217, kategori: "Bilmece", soru: "Altı mermer, üstü mermer, içinde bir bülbül öter.", secenekler: { A: "Ağız", B: "Saray", C: "Kafes", D: "Piyano" }, dogruCevap: "A" },
    { seviye: 218, kategori: "Bilmece", soru: "Şehirleri var yolu yok, denizleri var suyu yok.", secenekler: { A: "Harita", B: "Rüya", C: "Televizyon", D: "Uzay" }, dogruCevap: "A" },
    { seviye: 219, kategori: "Bilmece", soru: "Bir kamyonu bir eliyle kim durdurabilir?", secenekler: { A: "Süpermen", B: "Trafik Polisi", C: "Kamyon Şoförü", D: "Hulk" }, dogruCevap: "B" },
    { seviye: 220, kategori: "Bilmece", soru: "Suya düşer ıslanmaz, yere düşer kırılmaz.", secenekler: { A: "Pamuk", B: "Gölge", C: "Hava", D: "Işık" }, dogruCevap: "B" },
    { seviye: 221, kategori: "Bilmece", soru: "Karnı açık, ağzı kapalı; içinde binbir bilgi saklı.", secenekler: { A: "Bilgisayar", B: "Kitap", C: "Kütüphane", D: "Zihin" }, dogruCevap: "B" },
    { seviye: 222, kategori: "Bilmece", soru: "Çarşıdan aldım kara, evde oldu kırmızı, çöpe attım gri.", secenekler: { A: "Kestane", B: "Kömür", C: "Çay", D: "Demir" }, dogruCevap: "B" },
    { seviye: 223, kategori: "Bilmece", soru: "Hangi anahtar kapıyı açmaz?", secenekler: { A: "İngiliz anahtarı", B: "Sol anahtarı", C: "Kırık anahtar", D: "Şifre" }, dogruCevap: "B" },
    { seviye: 224, kategori: "Bilmece", soru: "Dokunmadan kırılan şey nedir?", secenekler: { A: "Cam", B: "Kalp", C: "Buz", D: "Söz" }, dogruCevap: "B" },
    { seviye: 225, kategori: "Bilmece", soru: "Birinciyi geçen kaçıncı olur?", secenekler: { A: "Birinci", B: "İkinci", C: "Üçüncü", D: "Şampiyon" }, dogruCevap: "A" },
    { seviye: 226, kategori: "Bilmece", soru: "İçinde dumanı var, üstünde ormanı var.", secenekler: { A: "Fabrika", B: "Vapur", C: "Nargile", D: "Dağ" }, dogruCevap: "D" },
    { seviye: 227, kategori: "Bilmece", soru: "Açarsın dünya girer, kapatırsın kutu kalır.", secenekler: { A: "Kitap", B: "Pencere", C: "Televizyon", D: "Göz" }, dogruCevap: "C" },
    { seviye: 228, kategori: "Bilmece", soru: "Dişi var ısırmaz, sakalı var konuşmaz.", secenekler: { A: "Tarak", B: "Mısır", C: "Süpürge", D: "Pırasa" }, dogruCevap: "B" },
    { seviye: 229, kategori: "Bilmece", soru: "Kuyruğu var at değil, kanadı var kuş değil.", secenekler: { A: "Balık", B: "Uçak", C: "Ejderha", D: "Uçurtma" }, dogruCevap: "A" },
    { seviye: 230, kategori: "Bilmece", soru: "Üstü çayır biçilir, altı çeşme içilir.", secenekler: { A: "Koyun", B: "İnek", C: "Bahçe", D: "Kuyu" }, dogruCevap: "B" },
    // ... (Hızlandırmak adına geri kalanları aynı formatta devam ettiriyorum)
    { seviye: 231, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Kurşun kalem", B: "Tükenmez kalem", C: "Kontrol kalemi", D: "Dolma kalem" }, dogruCevap: "C" },
    { seviye: 232, kategori: "Bilmece", soru: "Bağlandığında yürür, çözüldüğünde durur.", secenekler: { A: "At", B: "Ayakkabı", C: "Gemi", D: "Köpek" }, dogruCevap: "B" },
    { seviye: 233, kategori: "Bilmece", soru: "Eve gelen hırsız neyi çalmaz?", secenekler: { A: "Para", B: "Altın", C: "Zil", D: "Halı" }, dogruCevap: "C" },
    { seviye: 234, kategori: "Bilmece", soru: "En temiz böcek hangisidir?", secenekler: { A: "Karınca", B: "Arı", C: "Hamam böceği", D: "Kelebek" }, dogruCevap: "C" },
    { seviye: 235, kategori: "Bilmece", soru: "Suda doğar, suda ölür.", secenekler: { A: "Balık", B: "Buz", C: "Gemi", D: "Yosun" }, dogruCevap: "B" },
    { seviye: 236, kategori: "Bilmece", soru: "Hiç hareket etmeden tüm dünyayı gezen nedir?", secenekler: { A: "Rüzgar", B: "Bulut", C: "Pul", D: "Güneş" }, dogruCevap: "C" },
    { seviye: 237, kategori: "Bilmece", soru: "Açtıkça daralır, kapattıkça genişler.", secenekler: { A: "Fermuar", B: "Kapı", C: "Şemsiye", D: "Makas" }, dogruCevap: "D" },
    { seviye: 238, kategori: "Bilmece", soru: "İki camlı bir pencere, bakıp durur her yere.", secenekler: { A: "Gözlük", B: "Dürbün", C: "Göz", D: "Kamera" }, dogruCevap: "A" },
    { seviye: 239, kategori: "Bilmece", soru: "Özü tatlı, sözü tatlı, kovanı var balı tatlı.", secenekler: { A: "Şeker", B: "Reçel", C: "Arı", D: "Çocuk" }, dogruCevap: "C" },
    { seviye: 240, kategori: "Bilmece", soru: "Yolun üzerinde gider ama hiç kımıldamaz.", secenekler: { A: "Araba", B: "Asfalt", C: "Trafik levhası", D: "Şerit" }, dogruCevap: "D" },
    { seviye: 241, kategori: "Bilmece", soru: "Kral tacına ne zaman sahip olur?", secenekler: { A: "Doğduğunda", B: "Öldüğünde", C: "Taç giyme töreninde", D: "Başına takıldığında" }, dogruCevap: "D" },
    { seviye: 242, kategori: "Bilmece", soru: "Hangi tene krem sürülmez?", secenekler: { A: "Esmer ten", B: "Güneş yanığı", C: "Kertenkele", D: "Karton" }, dogruCevap: "D" },
    { seviye: 243, kategori: "Bilmece", soru: "Hangi kovanın balı olmaz?", secenekler: { A: "Eşek arısı kovanı", B: "Boş kovan", C: "Mermi kovanı", D: "Sepet kovan" }, dogruCevap: "C" },
    { seviye: 244, kategori: "Bilmece", soru: "Tarlada yeşil, bakkalda siyah, evde kırmızı.", secenekler: { A: "Çay", B: "Zeytin", C: "Üzüm", D: "Domates" }, dogruCevap: "A" },
    { seviye: 245, kategori: "Bilmece", soru: "Burnu var nefes almaz, ağzı var yemek yemez.", secenekler: { A: "Gözlük", B: "Ayakkabı", C: "Sürahi", D: "Heykel" }, dogruCevap: "B" },
    { seviye: 246, kategori: "Bilmece", soru: "Kışın yatar, yazın kalkar; ayakları gümüş, başı altın.", secenekler: { A: "Buğday", B: "Güneş", C: "Çiçek", D: "Karınca" }, dogruCevap: "A" },
    { seviye: 247, kategori: "Bilmece", soru: "Siyah bir tavuk, her gün bir yumurta yumurtlar.", secenekler: { A: "Gece - Gün", B: "Kömür", C: "Zeytin", D: "Ocak - Yemek" }, dogruCevap: "A" },
    { seviye: 248, kategori: "Bilmece", soru: "Gözle görülmez, elle tutulmaz ama onsuz yaşanmaz.", secenekler: { A: "Su", B: "Hava", C: "Sevgi", D: "Rüzgar" }, dogruCevap: "B" },
    { seviye: 249, kategori: "Bilmece", soru: "Yerin altında sakallı dede.", secenekler: { A: "Pırasa", B: "Havuç", C: "Patates", D: "Soğan" }, dogruCevap: "A" },
    { seviye: 250, kategori: "Bilmece", soru: "Bir ağacı var 12 dalı, her dalında 30 yaprağı.", secenekler: { A: "Yıl - Aylar - Günler", B: "Kitap", C: "Kütüphane", D: "Okul" }, dogruCevap: "A" },
    { seviye: 251, kategori: "Bilmece", soru: "Ettendir dili, kemiktendir dişi.", secenekler: { A: "Ağız", B: "Tarak", C: "Fırça", D: "Anahtar" }, dogruCevap: "B" },
    { seviye: 252, kategori: "Bilmece", soru: "Hangi bağda üzüm yetişmez?", secenekler: { A: "Kurubag", B: "Ayakkabı bağı", C: "Elma bağı", D: "Gönül bağı" }, dogruCevap: "B" },
    { seviye: 253, kategori: "Bilmece", soru: "Sıcak dondurma nerede bulunur?", secenekler: { A: "Fırında", B: "Güneşte", C: "Rüyada", D: "Sözlükte" }, dogruCevap: "D" },
    { seviye: 254, kategori: "Bilmece", soru: "Hangi çiçek hem koklanır hem yürür?", secenekler: { A: "Gül", B: "Lale", C: "Papatya", D: "Gelin" }, dogruCevap: "D" },
    { seviye: 255, kategori: "Bilmece", soru: "Canı var kanı yok, konuşur dili yok.", secenekler: { A: "Radyo", B: "Telefon", C: "Kitap", D: "Mektup" }, dogruCevap: "C" },
    { seviye: 256, kategori: "Bilmece", soru: "Herkesin önünde olan ama kimsenin görmediği şey nedir?", secenekler: { A: "Gelecek", B: "Hava", C: "Göz", D: "Alın" }, dogruCevap: "A" },
    { seviye: 257, kategori: "Bilmece", soru: "En çok hangi ilimizde güneş parlar?", secenekler: { A: "Antalya", B: "İzmir", C: "Aydın", D: "Hepsi (Güneş bir tane)" }, dogruCevap: "D" },
    { seviye: 258, kategori: "Bilmece", soru: "Hangi meyvenin kardeşi vardır?", secenekler: { A: "Elma", B: "Armut", C: "Kiraz", D: "Üzüm" }, dogruCevap: "C" },
    { seviye: 259, kategori: "Bilmece", soru: "Göbeği var, canı yok.", secenekler: { A: "Tencere", B: "Marul", C: "Şişe", D: "Yastık" }, dogruCevap: "A" },
    { seviye: 260, kategori: "Bilmece", soru: "Dolu bir odada ne yer kaplamaz?", secenekler: { A: "Işık", B: "Ses", C: "Hava", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 261, kategori: "Bilmece", soru: "Okuma yazması olmayan hocaya ne denir?", secenekler: { A: "Bilgisiz", B: "Okuma bilmez", C: "Trafik hocası", D: "Düdük" }, dogruCevap: "D" },
    { seviye: 262, kategori: "Bilmece", soru: "En şişman hayvan hangisidir?", secenekler: { A: "Fil", B: "Balina", C: "Su aygırı", D: "Bit (içinde 'it' var)" }, dogruCevap: "D" },
    { seviye: 263, kategori: "Bilmece", soru: "Hangi saat çalışmaz?", secenekler: { A: "Bozuk saat", B: "Kum saati", C: "Duvar saati", D: "Güneş saati" }, dogruCevap: "B" },
    { seviye: 264, kategori: "Bilmece", soru: "İçinde bir akrep var ama sokmaz.", secenekler: { A: "Kutu", B: "Saat", C: "Kaktüs", D: "Çöl" }, dogruCevap: "B" },
    { seviye: 265, kategori: "Bilmece", soru: "Dışı bahar, içi kış; her zaman soğuk kalır.", secenekler: { A: "Buzdolabı", B: "Mağara", C: "Kuyu", D: "Dağ" }, dogruCevap: "A" },
    { seviye: 266, kategori: "Bilmece", soru: "Bir sihirli değneğim var, kime değse değiştirir.", secenekler: { A: "Para", B: "Kalem", C: "Zaman", D: "Sabun" }, dogruCevap: "B" },
    { seviye: 267, kategori: "Bilmece", soru: "Hangi ayda 28 gün vardır?", secenekler: { A: "Şubat", B: "Ocak", C: "Mart", D: "Hepsinde" }, dogruCevap: "D" },
    { seviye: 268, kategori: "Bilmece", soru: "Kullanırken yere atarız, işimiz bitince geri alırız.", secenekler: { A: "Çöp", B: "Olta", C: "Çapa", D: "Top" }, dogruCevap: "C" },
    { seviye: 269, kategori: "Bilmece", soru: "En acı biber nerede yetişir?", secenekler: { A: "Meksika", B: "Urfa", C: "Hindistan", D: "Dilin ucunda" }, dogruCevap: "D" },
    { seviye: 270, kategori: "Bilmece", soru: "Kimlerin evi olmaz?", secenekler: { A: "Fakirlerin", B: "Kuşların", C: "Balıkların", D: "Salyangozların (evini sırtında taşır)" }, dogruCevap: "D" },
    { seviye: 271, kategori: "Bilmece", soru: "Hangi perde pencereye asılmaz?", secenekler: { A: "Stor perde", B: "Tül perde", C: "Göz perdesi", D: "Sahne perdesi" }, dogruCevap: "C" },
    { seviye: 272, kategori: "Bilmece", soru: "En dertli dağ hangisidir?", secenekler: { A: "Erciyes", B: "Ağrı Dağı", C: "Everest", D: "Kaçkar" }, dogruCevap: "B" },
    { seviye: 273, kategori: "Bilmece", soru: "Su üstünde yürür, iz bırakmaz.", secenekler: { A: "Balık", B: "Gemi", C: "Işık", D: "Böcek" }, dogruCevap: "B" },
    { seviye: 274, kategori: "Bilmece", soru: "Hangi fil hortum kullanmaz?", secenekler: { A: "Yavru fil", B: "Beyaz fil", C: "Satrançtaki fil", D: "Oyuncak fil" }, dogruCevap: "C" },
    { seviye: 275, kategori: "Bilmece", soru: "Başına taktıkça kısalan şey nedir?", secenekler: { A: "Şapka", B: "Taç", C: "Kalem", D: "Kurşun kalem" }, dogruCevap: "D" },
    { seviye: 276, kategori: "Bilmece", soru: "Önceleri beş idi, şimdi oldu dört; yakında üç kalacak.", secenekler: { A: "Parmaklar", B: "Duyu organları", C: "Mevsimler", D: "Yüzyıllar" }, dogruCevap: "C" },
    { seviye: 277, kategori: "Bilmece", soru: "Hangi kuşun kanadı var ama uçamaz?", secenekler: { A: "Penguen", B: "Devekuşu", C: "Tavuk", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 278, kategori: "Bilmece", soru: "En ağır meyve hangisidir?", secenekler: { A: "Karpuz", B: "Kavun", C: "Balkabağı", D: "Ton-balığı" }, dogruCevap: "D" },
    { seviye: 279, kategori: "Bilmece", soru: "Ayakta doğar, yatarak ölür.", secenekler: { A: "İnsan", B: "Ağaç", C: "Çiçek", D: "Güneş" }, dogruCevap: "B" },
    { seviye: 280, kategori: "Bilmece", soru: "Hangi kutu açılmaz?", secenekler: { A: "Hediye kutusu", B: "Pandora'nın kutusu", C: "Boy kutusu", D: "Müzik kutusu" }, dogruCevap: "C" },
    { seviye: 281, kategori: "Bilmece", soru: "Bir ağzı var, bin konuşur.", secenekler: { A: "Radyo", B: "Mektup", C: "Kitap", D: "Yazar" }, dogruCevap: "C" },
    { seviye: 282, kategori: "Bilmece", soru: "Sırtında taşır evini, yavaş yürür sevinçli.", secenekler: { A: "Kaplumbağa", B: "Salyangoz", C: "Kirpi", D: "Yengeç" }, dogruCevap: "B" },
    { seviye: 283, kategori: "Bilmece", soru: "Kökü var ağaç değil, dişi var ısırır.", secenekler: { A: "Sarımsak", B: "Soğan", C: "Tarak", D: "Testere" }, dogruCevap: "A" },
    { seviye: 284, kategori: "Bilmece", soru: "Ateşe girer yanmaz, suya girer batmaz.", secenekler: { A: "Işık", B: "Gölge", C: "Hava", D: "Duman" }, dogruCevap: "B" },
    { seviye: 285, kategori: "Bilmece", soru: "Hangi yolun sonu yoktur?", secenekler: { A: "Otoyol", B: "Çıkmaz sokak", C: "Samanyolu", D: "Demiryolu" }, dogruCevap: "C" },
    { seviye: 286, kategori: "Bilmece", soru: "Her şeyi görür ama kendini göremez.", secenekler: { A: "Göz", B: "Kamera", C: "Ayna", D: "Fotoğraf" }, dogruCevap: "A" },
    { seviye: 287, kategori: "Bilmece", soru: "Canlıyı korur, cansızın içinde durur.", secenekler: { A: "Ev", B: "Kıyafet", C: "Ayakkabı", D: "Kafes" }, dogruCevap: "C" },
    { seviye: 288, kategori: "Bilmece", soru: "İki kardeş var, birbirini hiç görmez.", secenekler: { A: "Gözler", B: "Kulaklar", C: "Eller", D: "Ayaklar" }, dogruCevap: "A" },
    { seviye: 289, kategori: "Bilmece", soru: "Hangi dağda kar olmaz?", secenekler: { A: "Yüce dağlarda", B: "Volkanik dağlarda", C: "Resimdeki dağda", D: "Kışın" }, dogruCevap: "C" },
    { seviye: 290, kategori: "Bilmece", soru: "İçi boş, dışı hoş; vurdun mu ses verir.", secenekler: { A: "Davul", B: "Zil", C: "Flüt", D: "Keman" }, dogruCevap: "A" },
    { seviye: 291, kategori: "Bilmece", soru: "Burnu var, yüzü yok.", secenekler: { A: "Gözlük", B: "Heykel", C: "Geminin burnu", D: "Ayakkabı" }, dogruCevap: "D" },
    { seviye: 292, kategori: "Bilmece", soru: "Tavuk ne zaman 'yumurta' demez?", secenekler: { A: "Yumurtladığında", B: "Konuşamadığında", C: "Korktuğunda", D: "Uyuduğunda" }, dogruCevap: "B" },
    { seviye: 293, kategori: "Bilmece", soru: "En hüzünlü başkent hangisidir?", secenekler: { A: "Roma", B: "Paris", C: "Bağdat", D: "Ağrı" }, dogruCevap: "D" },
    { seviye: 294, kategori: "Bilmece", soru: "Açarsın çıkar, kaparsın girer.", secenekler: { A: "Dil", B: "Dil (konuşurken)", C: "Dil (fermuar)", D: "Kapı" }, dogruCevap: "C" },
    { seviye: 295, kategori: "Bilmece", soru: "Hangi macunla diş fırçalanmaz?", secenekler: { A: "Naneli", B: "Meyveli", C: "Domatesli", D: "Cam macunu" }, dogruCevap: "D" },
    { seviye: 296, kategori: "Bilmece", soru: "Dünyanın en büyük anahtarı hangisidir?", secenekler: { A: "Gemi anahtarı", B: "Altın anahtar", C: "Kilit anahtarı", D: "İspanya (haritadaki şekli)" }, dogruCevap: "D" },
    { seviye: 297, kategori: "Bilmece", soru: "İçinde balık olan ama su olmayan şey nedir?", secenekler: { A: "Akvaryum", B: "Konserve kutusu", C: "Balıkçı ağı", D: "Rüya" }, dogruCevap: "B" },
    { seviye: 298, kategori: "Bilmece", soru: "Hangi kalem silinmez?", secenekler: { A: "Kurşun", B: "Tükenmez", C: "Keçeli", D: "Kader kalemi" }, dogruCevap: "D" },
    { seviye: 299, kategori: "Bilmece", soru: "Ağacı var gölgesi yok.", secenekler: { A: "Soy ağacı", B: "Kurumuş ağaç", C: "Küçük ağaç", D: "Kaktüs" }, dogruCevap: "A" },
    { seviye: 300, kategori: "Bilmece", soru: "Gözleri var görmez, kanatları var uçmaz.", secenekler: { A: "Ölü kuş", B: "Heykel", C: "Oyuncak", D: "Gözlük" }, dogruCevap: "B" },
    { seviye: 301, kategori: "Bilmece", soru: "Su altında hangi canlı boğulmaz?", secenekler: { A: "Balık", B: "Yengeç", C: "Deniz yıldızı", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 302, kategori: "Bilmece", soru: "Canlıyken bağıran, ölüyken susan nedir?", secenekler: { A: "Düdük", B: "Davul", C: "Odun", D: "Kuzu" }, dogruCevap: "C" },
    { seviye: 303, kategori: "Bilmece", soru: "Altı ayaklı, iki kafalı, yürür gider.", secenekler: { A: "At ve binici", B: "Karınca", C: "Böcek", D: "Sirk elemanı" }, dogruCevap: "A" },
    { seviye: 304, kategori: "Bilmece", soru: "En temiz meyve hangisidir?", secenekler: { A: "Elma", B: "Kiraz", C: "Üzüm", D: "Yıkanmış meyve" }, dogruCevap: "D" },
    { seviye: 305, kategori: "Bilmece", soru: "Hangi kanatla uçulmaz?", secenekler: { A: "Kuş kanadı", B: "Uçak kanadı", C: "Kapı kanadı", D: "Kelebek kanadı" }, dogruCevap: "C" },
    { seviye: 306, kategori: "Bilmece", soru: "Diri girer fırına, ekmek olur sofraya.", secenekler: { A: "Hamur", B: "Buğday", C: "Odun", D: "Ateş" }, dogruCevap: "A" },
    { seviye: 307, kategori: "Bilmece", soru: "Eli var kolu yok, göbeği var canı yok.", secenekler: { A: "Ceket", B: "Yelek", C: "Pantolon", D: "Gömlek" }, dogruCevap: "B" },
    { seviye: 308, kategori: "Bilmece", soru: "Gece çıkar, gündüz kaçar.", secenekler: { A: "Yıldız", B: "Ay", C: "Yarasa", D: "Hırsız" }, dogruCevap: "C" },
    { seviye: 309, kategori: "Bilmece", soru: "Hangi örtü masaya serilmez?", secenekler: { A: "Dantel", B: "Naylon", C: "Kar örtüsü", D: "Kumaş" }, dogruCevap: "C" },
    { seviye: 310, kategori: "Bilmece", soru: "İçinde bir dünya var ama yaşanmaz.", secenekler: { A: "Kitap", B: "Küre", C: "Televizyon", D: "Ayna" }, dogruCevap: "B" },
    { seviye: 311, kategori: "Bilmece", soru: "En büyük defter hangisidir?", secenekler: { A: "Harita defteri", B: "Anı defteri", C: "Nüfus defteri", D: "Dürbün" }, dogruCevap: "C" },
    { seviye: 312, kategori: "Bilmece", soru: "Sesi var, kulağı yok; dili var, ağzı yok.", secenekler: { A: "Telefon", B: "Gramofon", C: "Radyo", D: "Yankı" }, dogruCevap: "D" },
    { seviye: 313, kategori: "Bilmece", soru: "Ay varken çıkar, güneş varken kaçar.", secenekler: { A: "Yıldız", B: "Karanlık", C: "Uyku", D: "Baykuş" }, dogruCevap: "B" },
    { seviye: 314, kategori: "Bilmece", soru: "En tatlı düşman hangisidir?", secenekler: { A: "Şeker", B: "Uyku", C: "Çikolata", D: "Zaman" }, dogruCevap: "B" },
    { seviye: 315, kategori: "Bilmece", soru: "Hangi parmakla gösterilmez?", secenekler: { A: "Baş parmak", B: "İşaret parmağı", C: "Yüzük parmağı", D: "Ayak parmağı" }, dogruCevap: "D" },
    { seviye: 316, kategori: "Bilmece", soru: "Yerin altında turuncu kılıç.", secenekler: { A: "Havuç", B: "Patates", C: "Turp", D: "Solucan" }, dogruCevap: "A" },
    { seviye: 317, kategori: "Bilmece", soru: "Yazın buz tutar, kışın çözülür.", secenekler: { A: "Buzdolabı", B: "Deniz", C: "Göl", D: "Dondurma" }, dogruCevap: "A" },
    { seviye: 318, kategori: "Bilmece", soru: "En çok hangi tene dokunulur?", secenekler: { A: "Yüz", B: "El", C: "Düğme (ten-e)", D: "Anten" }, dogruCevap: "D" },
    { seviye: 319, kategori: "Bilmece", soru: "Hangi köprüden geçilmez?", secenekler: { A: "Asma köprü", B: "Taş köprü", C: "Göz köprüsü", D: "Haliç köprüsü" }, dogruCevap: "C" },
    { seviye: 320, kategori: "Bilmece", soru: "Dışı kireç gibi beyaz, içi bal gibi tatlı.", secenekler: { A: "Yumurta", B: "Kavun", C: "Muz", D: "İncir" }, dogruCevap: "D" },
    { seviye: 321, kategori: "Bilmece", soru: "Hangi adamın burnu uzar?", secenekler: { A: "Kardan adam", B: "Yalancı adam", C: "Pinokyo", D: "Uzun adam" }, dogruCevap: "C" },
    { seviye: 322, kategori: "Bilmece", soru: "Tavuklar neden yumurtlar?", secenekler: { A: "Üremek için", B: "Yemek için", C: "Bıraksalar kırılacağı için", D: "Acıktıkları için" }, dogruCevap: "C" },
    { seviye: 323, kategori: "Bilmece", soru: "En hızlı koşan meyve hangisidir?", secenekler: { A: "Elma", B: "Armut", C: "Üzüm", D: "Hıyar (koşar hıyar)" }, dogruCevap: "D" },
    { seviye: 324, kategori: "Bilmece", soru: "Hangi tene güneş vurmaz?", secenekler: { A: "Esmer", B: "Sarışın", C: "Anten", D: "Karton" }, dogruCevap: "C" },
    { seviye: 325, kategori: "Bilmece", soru: "Ayakları var ama yere basmaz.", secenekler: { A: "Kuş", B: "Uçak", C: "Gözlük", D: "Sandalye" }, dogruCevap: "C" },
    { seviye: 326, kategori: "Bilmece", soru: "Gidilmeyen tek yer neresidir?", secenekler: { A: "Güneş", B: "Mars", C: "Dün", D: "Gelecek" }, dogruCevap: "C" },
    { seviye: 327, kategori: "Bilmece", soru: "Hangi masada oturulmaz?", secenekler: { A: "Yuvarlak", B: "Kare", C: "Yemek", D: "Dosya masası" }, dogruCevap: "D" },
    { seviye: 328, kategori: "Bilmece", soru: "Ateşe atılsa yanmaz, suya atılsa batmaz.", secenekler: { A: "Pamuk", B: "Buz", C: "Işık", D: "Gölge" }, dogruCevap: "D" },
    { seviye: 329, kategori: "Bilmece", soru: "Hangi meyve içilmez?", secenekler: { A: "Elma", B: "Vişne", C: "Portakal", D: "Şeftali (içilmez, yenir)" }, dogruCevap: "D" },
    { seviye: 330, kategori: "Bilmece", soru: "Kulağını bükünce dünyayı duyar.", secenekler: { A: "Radyo", B: "Televizyon", C: "Kulaklık", D: "Telefon" }, dogruCevap: "A" },
    { seviye: 331, kategori: "Bilmece", soru: "Siyah beyaz ama renkli değil.", secenekler: { A: "Zebra", B: "Eski TV", C: "Gazete", D: "Panda" }, dogruCevap: "C" },
    { seviye: 332, kategori: "Bilmece", soru: "İnsan ne zaman taş olur?", secenekler: { A: "Korkunca", B: "Ölünce", C: "Donunca", D: "Başına 'beş' gelince" }, dogruCevap: "D" },
    { seviye: 333, kategori: "Bilmece", soru: "Hangi bağda üzüm olmaz?", secenekler: { A: "Saman bağı", B: "Fular bağı", C: "Karabağ", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 334, kategori: "Bilmece", soru: "Gözle görülür, elle tutulmaz; kaçarsın kovalar.", secenekler: { A: "Gölge", B: "Zaman", C: "Bulut", D: "Duman" }, dogruCevap: "A" },
    { seviye: 335, kategori: "Bilmece", soru: "Yürür yürür iz etmez, hızlı gider toz etmez.", secenekler: { A: "Bulut", B: "Rüzgar", C: "Gemi", D: "Işık" }, dogruCevap: "C" },
    { seviye: 336, kategori: "Bilmece", soru: "Hangi kalemle resim yapılmaz?", secenekler: { A: "Pastel", B: "Sulu", C: "Dolma", D: "Kontrol kalemi" }, dogruCevap: "D" },
    { seviye: 337, kategori: "Bilmece", soru: "İçinde dumanı, dışında ormanı.", secenekler: { A: "Soba", B: "Fabrika", C: "Dağ", D: "Vapur" }, dogruCevap: "C" },
    { seviye: 338, kategori: "Bilmece", soru: "Suya düşer batmaz, ateşe düşer yanmaz.", secenekler: { A: "Odun", B: "Kağıt", C: "Gölge", D: "Pamuk" }, dogruCevap: "C" },
    { seviye: 339, kategori: "Bilmece", soru: "En tatlı ilimiz hangisidir?", secenekler: { A: "Şekerpınar", B: "Balıkesir", C: "Gaziantep", D: "Aydın" }, dogruCevap: "B" },
    { seviye: 340, kategori: "Bilmece", soru: "Bir ağacı var meyvesi yok.", secenekler: { A: "Kavak", B: "Çam", C: "Soy ağacı", D: "Söğüt" }, dogruCevap: "C" },
    { seviye: 341, kategori: "Bilmece", soru: "Hangi tene krem sürülmez?", secenekler: { A: "Güneş yanığı", B: "Esmer", C: "Karton", D: "Anten" }, dogruCevap: "D" },
    { seviye: 342, kategori: "Bilmece", soru: "Ayakları var ama çorap giymez.", secenekler: { A: "Sandalye", B: "Masa", C: "Kedi", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 343, kategori: "Bilmece", soru: "Hangi kutu çöpe atılmaz?", secenekler: { A: "Boş kutu", B: "Hediye kutusu", C: "Sandık", D: "Seçim kutusu" }, dogruCevap: "D" },
    { seviye: 344, kategori: "Bilmece", soru: "Yerin altında gümüş kemer.", secenekler: { A: "Su", B: "Yılan", C: "Kök", D: "Solucan" }, dogruCevap: "B" },
    { seviye: 345, kategori: "Bilmece", soru: "En dertli meyve hangisidir?", secenekler: { A: "Ayva", B: "Nar", C: "İncir", D: "Üzüm" }, dogruCevap: "A" },
    { seviye: 346, kategori: "Bilmece", soru: "Hangi yolun sonu yoktur?", secenekler: { A: "Otoban", B: "Tren yolu", C: "Samanyolu", D: "Labirent" }, dogruCevap: "C" },
    { seviye: 347, kategori: "Bilmece", soru: "Gözleri var görmez, ağzı var yemez.", secenekler: { A: "Heykel", B: "Bebek", C: "Oyuncak", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 348, kategori: "Bilmece", soru: "Dışı odun, içi duman.", secenekler: { A: "Soba", B: "Vapur", C: "Ev", D: "Baca" }, dogruCevap: "A" },
    { seviye: 349, kategori: "Bilmece", soru: "En büyük anahtar hangisidir?", secenekler: { A: "Kilit", B: "Altın", C: "Kader", D: "İspanya" }, dogruCevap: "D" },
    { seviye: 350, kategori: "Bilmece", soru: "Hem ağlar hem güler, yüzünü yere sürer.", secenekler: { A: "Bebek", B: "Bulut", C: "Silecek", D: "Mendil" }, dogruCevap: "B" },
    // 351-500: Yeni Eklenen Bilmeceler
    { seviye: 351, kategori: "Bilmece", soru: "Hangi örtü masaya serilmez?", secenekler: { A: "Dantel", B: "Bitki örtüsü", C: "Muşamba", D: "Kumaş" }, dogruCevap: "B" },
    { seviye: 352, kategori: "Bilmece", soru: "Sıfırdan başlar, sonsuza gider, ama hiç hareket etmez.", secenekler: { A: "Yol", B: "Sayılar", C: "Zaman", D: "Düşünce" }, dogruCevap: "B" },
    { seviye: 353, kategori: "Bilmece", soru: "Dili yok ama dünyayı gezdirir.", secenekler: { A: "Uçak", B: "Gemi", C: "Kitap", D: "Pasaport" }, dogruCevap: "C" },
    { seviye: 354, kategori: "Bilmece", soru: "Tarlada yeşil, bakkalda siyah, evde kırmızı.", secenekler: { A: "Biber", B: "Çay", C: "Kömür", D: "Zeytin" }, dogruCevap: "B" },
    { seviye: 355, kategori: "Bilmece", soru: "Hangi adamın burnu havuçtur?", secenekler: { A: "Manav", B: "Aşçı", C: "Kardan adam", D: "Çiftçi" }, dogruCevap: "C" },
    { seviye: 356, kategori: "Bilmece", soru: "En geniş kap hangisidir?", secenekler: { A: "Kazan", B: "Kapak", C: "Ayakkabı", D: "Bardak" }, dogruCevap: "B" },
    { seviye: 357, kategori: "Bilmece", soru: "Hangi şehirde meyve satılmaz?", secenekler: { A: "Armutlu", B: "Elmalı", C: "Manisa", D: "Pazarsız" }, dogruCevap: "D" },
    { seviye: 358, kategori: "Bilmece", soru: "Küçücük bakkal, dünyayı yutar.", secenekler: { A: "Ağız", B: "Göz", C: "Kulak", D: "Zihin" }, dogruCevap: "B" },
    { seviye: 359, kategori: "Bilmece", soru: "Suyu var balığı yok, yolu var arabası yok.", secenekler: { A: "Resim", B: "Harita", C: "Çöl", D: "Rüya" }, dogruCevap: "B" },
    { seviye: 360, kategori: "Bilmece", soru: "Yazın giyinir, kışın soyunur.", secenekler: { A: "Vantilatör", B: "Ağaç", C: "Yılan", D: "Güneş" }, dogruCevap: "B" },
    { seviye: 361, kategori: "Bilmece", soru: "Hangi kalemle resim yapılmaz?", secenekler: { A: "Boya kalemi", B: "Dolma kalem", C: "Kontrol kalemi", D: "Kurşun kalem" }, dogruCevap: "C" },
    { seviye: 362, kategori: "Bilmece", soru: "Hangi kuşun adı sebzedir?", secenekler: { A: "Serçe", B: "Kırlangıç", C: "Saka", D: "Enginar" }, dogruCevap: "D" },
    { seviye: 363, kategori: "Bilmece", soru: "Dışı var içi yok, dayak yer suçu yok.", secenekler: { A: "Top", B: "Davul", C: "Halı", D: "Yastık" }, dogruCevap: "B" },
    { seviye: 364, kategori: "Bilmece", soru: "Kolu var eli yok, karnı yarık karnı yok.", secenekler: { A: "Ceket", B: "Gömlek", C: "Yelek", D: "Pantolon" }, dogruCevap: "A" },
    { seviye: 365, kategori: "Bilmece", soru: "En tatlı meyve hangisidir?", secenekler: { A: "İncir", B: "Çilek", C: "Uyku", D: "Muz" }, dogruCevap: "C" },
    { seviye: 366, kategori: "Bilmece", soru: "Hangi soruya asla 'evet' denmez?", secenekler: { A: "Uyuyor musun?", B: "Burada mısın?", C: "Öldün mü?", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 367, kategori: "Bilmece", soru: "Hem ısıtır, hem yakar.", secenekler: { A: "Soba", B: "Biber", C: "Güneş", D: "Ateş" }, dogruCevap: "B" },
    { seviye: 368, kategori: "Bilmece", soru: "İncecik beli, elimdedir dili.", secenekler: { A: "Zil", B: "Kaşık", C: "Kalem", D: "Bardak" }, dogruCevap: "C" },
    { seviye: 369, kategori: "Bilmece", soru: "Hangi meyve her zaman yalnızdır?", secenekler: { A: "Elma", B: "Armut", C: "Üzüm", D: "Vişne" }, dogruCevap: "B" },
    { seviye: 370, kategori: "Bilmece", soru: "Yer altında yağlı kayış.", secenekler: { A: "Solucan", B: "Yılan", C: "Hortum", D: "Kemer" }, dogruCevap: "B" },
    { seviye: 371, kategori: "Bilmece", soru: "Başı var beyni yok.", secenekler: { A: "Soğan", B: "Lale", C: "Papatya", D: "Mısır" }, dogruCevap: "A" },
    { seviye: 372, kategori: "Bilmece", soru: "Karşıdan baktım hiç yok, yanına gittim pek çok.", secenekler: { A: "Kum", B: "Çiçek", C: "Karınca", D: "Ağaç" }, dogruCevap: "C" },
    { seviye: 373, kategori: "Bilmece", soru: "Hangi saatte yemek yenmez?", secenekler: { A: "Duvar saatinde", B: "Sabah saatinde", C: "Öğle saatinde", D: "Gece saatinde" }, dogruCevap: "A" },
    { seviye: 374, kategori: "Bilmece", soru: "Hangi bağda üzüm yetişmez?", secenekler: { A: "Karabağ", B: "Siyah bağ", C: "Ayakkabı bağı", D: "Üzüm bağı" }, dogruCevap: "C" },
    { seviye: 375, kategori: "Bilmece", soru: "Sesi var canı yok, konuşur ağzı yok.", secenekler: { A: "Radyo", B: "Telefon", C: "Yankı", D: "Rüzgar" }, dogruCevap: "C" },
    { seviye: 376, kategori: "Bilmece", soru: "Hangi denizde balık bulunmaz?", secenekler: { A: "Karadeniz", B: "Ölü Deniz", C: "Akdeniz", D: "Ege Denizi" }, dogruCevap: "B" },
    { seviye: 377, kategori: "Bilmece", soru: "En ağır meyve hangisidir?", secenekler: { A: "Karpuz", B: "Kavun", C: "İncir", D: "Balkabağı" }, dogruCevap: "C" },
    { seviye: 378, kategori: "Bilmece", soru: "Suya düşer ıslanmaz, yere düşer paslanmaz.", secenekler: { A: "Güneş", B: "Gölge", C: "Hava", D: "Işık" }, dogruCevap: "B" },
    { seviye: 379, kategori: "Bilmece", soru: "Hangi filin hortumu yoktur?", secenekler: { A: "Yavru fil", B: "Asya fili", C: "Profil", D: "Afrika fili" }, dogruCevap: "C" },
    { seviye: 380, kategori: "Bilmece", soru: "Yatınca yatar, kalkınca kalkar.", secenekler: { A: "Parmak", B: "Yorgan", C: "Ayak", D: "Göz" }, dogruCevap: "A" },
    { seviye: 381, kategori: "Bilmece", soru: "Hangi bankaya para yatırılmaz?", secenekler: { A: "Merkez Bankası", B: "Ziraat Bankası", C: "Kan Bankası", D: "Halk Bankası" }, dogruCevap: "C" },
    { seviye: 382, kategori: "Bilmece", soru: "Kapağı var kitap değil, kulu var kapı değil.", secenekler: { A: "Tencere", B: "Göz", C: "Dolap", D: "Çanta" }, dogruCevap: "B" },
    { seviye: 383, kategori: "Bilmece", soru: "Hangi kovanın balı olmaz?", secenekler: { A: "Arı kovanı", B: "Kulak kovanı", C: "Eski kovan", D: "Yeni kovan" }, dogruCevap: "B" },
    { seviye: 384, kategori: "Bilmece", soru: "Her şeyi görür ama kendini göremez.", secenekler: { A: "Ayna", B: "Göz", C: "Kamera", D: "Dürbün" }, dogruCevap: "B" },
    { seviye: 385, kategori: "Bilmece", soru: "Hangi tastan su içilmez?", secenekler: { A: "Gümüş tas", B: "Bakır tas", C: "Kafatası", D: "Altın tas" }, dogruCevap: "C" },
    { seviye: 386, kategori: "Bilmece", soru: "Pişirirsen aş olur, pişirmezsen kuş olur.", secenekler: { A: "Pirinç", B: "Yumurta", C: "Mısır", D: "Buğday" }, dogruCevap: "B" },
    { seviye: 387, kategori: "Bilmece", soru: "Gökten iner bir avuç, tadı şekerden tatlı.", secenekler: { A: "Dut", B: "Kar", C: "Yağmur", D: "Dolu" }, dogruCevap: "A" },
    { seviye: 388, kategori: "Bilmece", soru: "Dili var konuşamaz, ayağı var yürüyemez.", secenekler: { A: "Sandalye", B: "Ayakkabı", C: "Masa", D: "Araba" }, dogruCevap: "B" },
    { seviye: 389, kategori: "Bilmece", soru: "En temiz meyve hangisidir?", secenekler: { A: "Yıkanmış kiraz", B: "Yalan", C: "Elma", D: "Üzüm" }, dogruCevap: "B" },
    { seviye: 390, kategori: "Bilmece", soru: "Açarsın içini, görürsün kendini.", secenekler: { A: "Kitap", B: "Ayna", C: "Dolap", D: "Kapı" }, dogruCevap: "B" },
    { seviye: 391, kategori: "Bilmece", soru: "Sıcak dondurma nerede bulunur?", secenekler: { A: "Fırında", B: "Güneşte", C: "Mutfakta", D: "Buzdolabında" }, dogruCevap: "A" },
    { seviye: 392, kategori: "Bilmece", soru: "En dertli meyve hangisidir?", secenekler: { A: "Ayva", B: "Nar", C: "İncir", D: "Vişne" }, dogruCevap: "A" },
    { seviye: 393, kategori: "Bilmece", soru: "Hangi yolun sonu yoktur?", secenekler: { A: "Otoban", B: "Tren yolu", C: "Samanyolu", D: "Labirent" }, dogruCevap: "C" },
    { seviye: 394, kategori: "Bilmece", soru: "Ayakları var ama çorap giymez.", secenekler: { A: "Masa", B: "Kedi", C: "Köpek", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 395, kategori: "Bilmece", soru: "Hangi kutu çöpe atılmaz?", secenekler: { A: "Hediye kutusu", B: "Seçim kutusu", C: "Boş kutu", D: "Karton kutu" }, dogruCevap: "B" },
    { seviye: 396, kategori: "Bilmece", soru: "Yerin altında gümüş kemer.", secenekler: { A: "Yılan", B: "Su", C: "Kök", D: "Solucan" }, dogruCevap: "A" },
    { seviye: 397, kategori: "Bilmece", soru: "Hangi gül kokmaz?", secenekler: { A: "Kurumuş gül", B: "Yapay gül", C: "Virgül", D: "Solmuş gül" }, dogruCevap: "C" },
    { seviye: 398, kategori: "Bilmece", soru: "Hangi havuzda su olmaz?", secenekler: { A: "Boş havuz", B: "Olimpik havuz", C: "Süs havuzu", D: "Bilardo havuzu" }, dogruCevap: "D" },
    { seviye: 399, kategori: "Bilmece", soru: "Hangi on'un sonu yoktur?", secenekler: { A: "Kamyon", B: "Limon", C: "Balon", D: "Oyun" }, dogruCevap: "A" },
    { seviye: 400, kategori: "Bilmece", soru: "Kışın yatıyor, yazın kalkıyor.", secenekler: { A: "Ayı", B: "Soba", C: "Yorgan", D: "Dondurma" }, dogruCevap: "B" },
    { seviye: 401, kategori: "Bilmece", soru: "Dokunmadan kırılan şey nedir?", secenekler: { A: "Cam", B: "Kalp", C: "Buz", D: "Ayna" }, dogruCevap: "B" },
    { seviye: 402, kategori: "Bilmece", soru: "Hangi karnede not olmaz?", secenekler: { A: "Sağlık karnesi", B: "Okul karnesi", C: "Sürücü karnesi", D: "Başarı karnesi" }, dogruCevap: "A" },
    { seviye: 403, kategori: "Bilmece", soru: "Hangi meyve ile yazı yazılır?", secenekler: { A: "Elma", B: "Çilek", C: "Ayva", D: "Kiraz" }, dogruCevap: "D" },
    { seviye: 404, kategori: "Bilmece", soru: "Hangi başa şapka giyilmez?", secenekler: { A: "Kel başa", B: "Çeşme başına", C: "Dağ başına", D: "Yol başına" }, dogruCevap: "B" },
    { seviye: 405, kategori: "Bilmece", soru: "İçer içersin bitmez, tadına doyum yetmez.", secenekler: { A: "Su", B: "Hava", C: "Çay", D: "Süt" }, dogruCevap: "B" },
    { seviye: 406, kategori: "Bilmece", soru: "Hangi top zıplamaz?", secenekler: { A: "Kar topu", B: "Futbol topu", C: "Basketbol topu", D: "Tenis topu" }, dogruCevap: "A" },
    { seviye: 407, kategori: "Bilmece", soru: "Bağlayınca yürür, çözünce durur.", secenekler: { A: "Ayakkabı", B: "At", C: "Araba", D: "Gemi" }, dogruCevap: "A" },
    { seviye: 408, kategori: "Bilmece", soru: "Hangi pas silinmez?", secenekler: { A: "Demir pası", B: "Pasaport", C: "Yemek pası", D: "Halı pası" }, dogruCevap: "B" },
    { seviye: 409, kategori: "Bilmece", soru: "Hangi kanatla uçulmaz?", secenekler: { A: "Kuş kanadı", B: "Uçak kanadı", C: "Kapı kanadı", D: "Kelebek kanadı" }, dogruCevap: "C" },
    { seviye: 410, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Kurşun", B: "Tükenmez", C: "Kontrol", D: "Dolma" }, dogruCevap: "C" },
    { seviye: 411, kategori: "Bilmece", soru: "En büyük kutu hangisidir?", secenekler: { A: "Hediye kutusu", B: "Karton kutu", C: "Gökyüzü", D: "Sandık" }, dogruCevap: "C" },
    { seviye: 412, kategori: "Bilmece", soru: "Yılan hangi dilde konuşur?", secenekler: { A: "Yılanca", B: "Sessizce", C: "Tıslayarak", D: "Isırarak" }, dogruCevap: "A" },
    { seviye: 413, kategori: "Bilmece", soru: "Hangi diş fırçalanmaz?", secenekler: { A: "Süt dişi", B: "Azı dişi", C: "Sarımsak dişi", D: "Yirmilik diş" }, dogruCevap: "C" },
    { seviye: 414, kategori: "Bilmece", soru: "En son hangi diş çıkar?", secenekler: { A: "Azı dişi", B: "Süt dişi", C: "Takma diş", D: "Yirmilik diş" }, dogruCevap: "C" },
    { seviye: 415, kategori: "Bilmece", soru: "Hangi düğüm çözülmez?", secenekler: { A: "Kör düğüm", B: "Gördüğüm", C: "Gemicilik düğümü", D: "Kravat düğümü" }, dogruCevap: "B" },
    { seviye: 416, kategori: "Bilmece", soru: "En dertli meyve hangisidir?", secenekler: { A: "Vişne", B: "Ayva", C: "Karpuz", D: "İncir" }, dogruCevap: "B" },
    { seviye: 417, kategori: "Bilmece", soru: "Hangi tilki tavuk yemez?", secenekler: { A: "Kurnaz tilki", B: "Yavru tilki", C: "Vahşi tilki", D: "Filtre (Fil-tre)" }, dogruCevap: "D" },
    { seviye: 418, kategori: "Bilmece", soru: "En çok kar nerede bulunur?", secenekler: { A: "Dağlarda", B: "Antarktika'da", C: "Sözlükte", D: "Buzdolabında" }, dogruCevap: "C" },
    { seviye: 419, kategori: "Bilmece", soru: "Sadece kullanıldığında kırılan şey nedir?", secenekler: { A: "Yumurta", B: "Fındık", C: "Ceviz", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 420, kategori: "Bilmece", soru: "Hangi ilimizde güneş gözlüğü kullanılmaz?", secenekler: { A: "Van", B: "Muğla", C: "Göz-lük", D: "Rize" }, dogruCevap: "C" },
    { seviye: 421, kategori: "Bilmece", soru: "En hızlı rakam hangisidir?", secenekler: { A: "Sıfır", B: "Bir", C: "Dokuz", D: "Yedi (Ye-di)" }, dogruCevap: "D" },
    { seviye: 422, kategori: "Bilmece", soru: "Hangi makine ile dikiş dikilmez?", secenekler: { A: "Tıraş makinesi", B: "Fotoğraf makinesi", C: "Yıkama makinesi", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 423, kategori: "Bilmece", soru: "Denizde var karada yok.", secenekler: { A: "Balık", B: "Gemi", C: "Dalga", D: "Kum" }, dogruCevap: "C" },
    { seviye: 424, kategori: "Bilmece", soru: "Kulağını bükünce sesi çıkar.", secenekler: { A: "Zil", B: "Radyo", C: "Musluk", D: "Keman" }, dogruCevap: "C" },
    { seviye: 425, kategori: "Bilmece", soru: "İncecik beli var, tatlı dili var.", secenekler: { A: "Bebek", B: "Kaşık", C: "Kalem", D: "Bardak" }, dogruCevap: "C" },
    { seviye: 426, kategori: "Bilmece", soru: "İçi taş, dışı baş.", secenekler: { A: "Zeytin", B: "Kaplumbağa", C: "Kayısı", D: "Ev" }, dogruCevap: "B" },
    { seviye: 427, kategori: "Bilmece", soru: "Ben giderim o kalır.", secenekler: { A: "İsim", B: "Gölge", C: "Ayak izi", D: "Zaman" }, dogruCevap: "C" },
    { seviye: 428, kategori: "Bilmece", soru: "Başına konar, seni serinletir.", secenekler: { A: "Şapka", B: "Bulut", C: "Rüzgar", D: "Vantilatör" }, dogruCevap: "A" },
    { seviye: 429, kategori: "Bilmece", soru: "Elsiz ayaksız kapı açar.", secenekler: { A: "Rüzgar", B: "Hırsız", C: "Anahtar", D: "Hayalet" }, dogruCevap: "C" },
    { seviye: 430, kategori: "Bilmece", soru: "Tüyden hafif ama kimse tutamaz.", secenekler: { A: "Duman", B: "Nefes", C: "Bulut", D: "Gölge" }, dogruCevap: "B" },
    { seviye: 431, kategori: "Bilmece", soru: "Denizin ortasında ne vardır?", secenekler: { A: "Ada", B: "Gemi", C: "Balık", D: "N harfi" }, dogruCevap: "D" },
    { seviye: 432, kategori: "Bilmece", soru: "Hangi tene kolonya sürülmez?", secenekler: { A: "Yumuşak tene", B: "Sert tene", C: "Karaktene (Karakter)", D: "Yanık tene" }, dogruCevap: "C" },
    { seviye: 433, kategori: "Bilmece", soru: "Adamın biri kafasına radyo koymuş neden?", secenekler: { A: "Müzik dinlemek için", B: "Haberleri duymak için", C: "Kafa dengi olsun diye", D: "Uyumak için" }, dogruCevap: "C" },
    { seviye: 434, kategori: "Bilmece", soru: "Damlaya damlaya ne olur?", secenekler: { A: "Göl olur", B: "Su olur", C: "Musluk bozulur", D: "Hepsi" }, dogruCevap: "C" },
    { seviye: 435, kategori: "Bilmece", soru: "Hangi ay 28 çeker?", secenekler: { A: "Şubat", B: "Ocak", C: "Mart", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 436, kategori: "Bilmece", soru: "Hangi macunla diş fırçalanmaz?", secenekler: { A: "Lahmacun", B: "Beyaz macun", C: "Çilekli macun", D: "Naneli macun" }, dogruCevap: "A" },
    { seviye: 437, kategori: "Bilmece", soru: "Hangi kaba su doldurulmaz?", secenekler: { A: "Delik kaba", B: "Küçük kaba", C: "Ayakkabıya", D: "Kaba kuvvete" }, dogruCevap: "D" },
    { seviye: 438, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Dolma kalem", B: "Kurşun kalem", C: "Kontrol kalemi", D: "Tükenmez kalem" }, dogruCevap: "C" },
    { seviye: 439, kategori: "Bilmece", soru: "Açarsan genişler, kaparsan daralır.", secenekler: { A: "Pencere", B: "Şemsiye", C: "Kapı", D: "Perde" }, dogruCevap: "B" },
    { seviye: 440, kategori: "Bilmece", soru: "Hiç yorulmadan dünyayı gezer.", secenekler: { A: "Rüzgar", B: "Bulut", C: "Güneş", D: "Ay" }, dogruCevap: "C" },
    { seviye: 441, kategori: "Bilmece", soru: "Dışı kaktüs içi süt.", secenekler: { A: "Ananas", B: "Hindistan cevizi", C: "Karpuz", D: "Kavun" }, dogruCevap: "B" },
    { seviye: 442, kategori: "Bilmece", soru: "Hem ağlar hem güler.", secenekler: { A: "Bebek", B: "Bulut", C: "İnsan", D: "Yağmur" }, dogruCevap: "C" },
    { seviye: 443, kategori: "Bilmece", soru: "Hangi masada yemek yenmez?", secenekler: { A: "Yemek masası", B: "Dosya masası", C: "Mutfak masası", D: "Altın masa" }, dogruCevap: "B" },
    { seviye: 444, kategori: "Bilmece", soru: "Hangi top zıplamaz?", secenekler: { A: "Kar topu", B: "İp topu", C: "Tenis topu", D: "Futbol topu" }, dogruCevap: "A" },
    { seviye: 445, kategori: "Bilmece", soru: "Gece gündüz bekler, kapıyı çalana bakar.", secenekler: { A: "Bekçi", B: "Zil", C: "Kilit", D: "Paspas" }, dogruCevap: "C" },
    { seviye: 446, kategori: "Bilmece", soru: "Kulağını büktükçe sesi yükselir.", secenekler: { A: "Radyo", B: "İnsan", C: "Keman", D: "Musluk" }, dogruCevap: "A" },
    { seviye: 447, kategori: "Bilmece", soru: "Sarıdır sallanır, tadı baldan tatlıdır.", secenekler: { A: "Muz", B: "Kavun", C: "Armut", D: "Ayva" }, dogruCevap: "C" },
    { seviye: 448, kategori: "Bilmece", soru: "Okuma yazma bilmez ama her şeyi yazar.", secenekler: { A: "Kalem", B: "Kağıt", C: "Bilgisayar", D: "Daktilo" }, dogruCevap: "A" },
    { seviye: 449, kategori: "Bilmece", soru: "Hangi kuşun adı sebzedir?", secenekler: { A: "Serçe", B: "Kırlangıç", C: "Enginar", D: "Saka" }, dogruCevap: "C" },
    { seviye: 450, kategori: "Bilmece", soru: "Hangi örtü masaya serilmez?", secenekler: { A: "Dantel", B: "Bitki örtüsü", C: "Muşamba", D: "Kumaş" }, dogruCevap: "B" },
    { seviye: 451, kategori: "Bilmece", soru: "Hangi tene kolonya sürülmez?", secenekler: { A: "Yumuşak tene", B: "Karaktene", C: "Sert tene", D: "Beyaz tene" }, dogruCevap: "B" },
    { seviye: 452, kategori: "Bilmece", soru: "Hangi ilimizde güneş gözlüğü kullanılmaz?", secenekler: { A: "Gözlük", B: "Van", C: "Muğla", D: "Rize" }, dogruCevap: "A" },
    { seviye: 453, kategori: "Bilmece", soru: "Hangi yolda yürünmez?", secenekler: { A: "Samanyolu", B: "Otoban", C: "Patika", D: "Ana yol" }, dogruCevap: "A" },
    { seviye: 454, kategori: "Bilmece", soru: "Hangi bankaya para yatırılmaz?", secenekler: { A: "Kan bankası", B: "Merkez bankası", C: "Halk bankası", D: "Ziraat bankası" }, dogruCevap: "A" },
    { seviye: 455, kategori: "Bilmece", soru: "Hangi kaba su doldurulmaz?", secenekler: { A: "Delik kaba", B: "Kaba kuvvete", C: "Plastik kaba", D: "Cam kaba" }, dogruCevap: "B" },
    { seviye: 456, kategori: "Bilmece", soru: "Hangi adamın burnu havuçtur?", secenekler: { A: "Kardan adam", B: "Aşçı adam", C: "Çiftçi adam", D: "Manav adam" }, dogruCevap: "A" },
    { seviye: 457, kategori: "Bilmece", soru: "Hangi karnede not olmaz?", secenekler: { A: "Sağlık karnesi", B: "Okul karnesi", C: "Başarı karnesi", D: "Sürücü karnesi" }, dogruCevap: "A" },
    { seviye: 458, kategori: "Bilmece", soru: "Hangi meyve ile yazı yazılır?", secenekler: { A: "Elma", B: "Kiraz", C: "Çilek", D: "Muz" }, dogruCevap: "B" },
    { seviye: 459, kategori: "Bilmece", soru: "Hangi top zıplamaz?", secenekler: { A: "Kar topu", B: "Futbol topu", C: "Tenis topu", D: "Basketbol topu" }, dogruCevap: "A" },
    { seviye: 460, kategori: "Bilmece", soru: "Hangi kovanın balı olmaz?", secenekler: { A: "Arı kovanı", B: "Kulak kovanı", C: "Eski kovan", D: "Yeni kovan" }, dogruCevap: "B" },
    { seviye: 461, kategori: "Bilmece", soru: "Hangi pas silinmez?", secenekler: { A: "Demir pası", B: "Pasaport", C: "Halı pası", D: "Yemek pası" }, dogruCevap: "B" },
    { seviye: 462, kategori: "Bilmece", soru: "Hangi diş fırçalanmaz?", secenekler: { A: "Süt dişi", B: "Sarımsak dişi", C: "Azı dişi", D: "Yirmilik diş" }, dogruCevap: "B" },
    { seviye: 463, kategori: "Bilmece", soru: "Hangi filin hortumu yoktur?", secenekler: { A: "Afrika fili", B: "Asya fili", C: "Profil", D: "Yavru fil" }, dogruCevap: "C" },
    { seviye: 464, kategori: "Bilmece", soru: "Hangi başa şapka giyilmez?", secenekler: { A: "Kel başa", B: "Çeşme başına", C: "Dağ başına", D: "Yol başına" }, dogruCevap: "B" },
    { seviye: 465, kategori: "Bilmece", soru: "Hangi tastan su içilmez?", secenekler: { A: "Kafatası", B: "Altın tas", C: "Gümüş tas", D: "Bakır tas" }, dogruCevap: "A" },
    { seviye: 466, kategori: "Bilmece", soru: "Hangi kutu çöpe atılmaz?", secenekler: { A: "Hediye kutusu", B: "Seçim kutusu", C: "Karton kutu", D: "Boş kutu" }, dogruCevap: "B" },
    { seviye: 467, kategori: "Bilmece", soru: "Hangi havuzda su olmaz?", secenekler: { A: "Bilardo havuzu", B: "Süs havuzu", C: "Boş havuz", D: "Olimpik havuz" }, dogruCevap: "A" },
    { seviye: 468, kategori: "Bilmece", soru: "Hangi gül kokmaz?", secenekler: { A: "Virgül", B: "Kırmızı gül", C: "Beyaz gül", D: "Yapay gül" }, dogruCevap: "A" },
    { seviye: 469, kategori: "Bilmece", soru: "Hangi tilki tavuk yemez?", secenekler: { A: "Vahşi tilki", B: "Filtre", C: "Kurnaz tilki", D: "Yavru tilki" }, dogruCevap: "B" },
    { seviye: 470, kategori: "Bilmece", soru: "Hangi düğüm çözülmez?", secenekler: { A: "Kör düğüm", B: "Gördüğüm", C: "Gemicilik düğümü", D: "Kravat düğümü" }, dogruCevap: "B" },
    { seviye: 471, kategori: "Bilmece", soru: "Hangi makine ile dikiş dikilmez?", secenekler: { A: "Tıraş makinesi", B: "Dikiş makinesi", C: "Overlok makinesi", D: "Hepsi" }, dogruCevap: "A" },
    { seviye: 472, kategori: "Bilmece", soru: "Hangi kanatla uçulmaz?", secenekler: { A: "Kapı kanadı", B: "Kuş kanadı", C: "Uçak kanadı", D: "Kelebek kanadı" }, dogruCevap: "A" },
    { seviye: 473, kategori: "Bilmece", soru: "Hangi soruya asla 'evet' denmez?", secenekler: { A: "Uyuyor musun?", B: "Öldün mü?", C: "Burada mısın?", D: "A ve B" }, dogruCevap: "D" },
    { seviye: 474, kategori: "Bilmece", soru: "Hangi denizde balık bulunmaz?", secenekler: { A: "Ölü Deniz", B: "Karadeniz", C: "Akdeniz", D: "Ege Denizi" }, dogruCevap: "A" },
    { seviye: 475, kategori: "Bilmece", soru: "Hangi on'un sonu yoktur?", secenekler: { A: "Kamyon", B: "Limon", C: "Balon", D: "Oyun" }, dogruCevap: "A" },
    { seviye: 476, kategori: "Bilmece", soru: "En ağır meyve hangisidir?", secenekler: { A: "Balkabağı", B: "Karpuz", C: "Kavun", D: "İncir" }, dogruCevap: "A" },
    { seviye: 477, kategori: "Bilmece", soru: "En tatlı meyve hangisidir?", secenekler: { A: "Uyku", B: "İncir", C: "Çilek", D: "Muz" }, dogruCevap: "A" },
    { seviye: 478, kategori: "Bilmece", soru: "En hızlı rakam hangisidir?", secenekler: { A: "Yedi", B: "Sıfır", C: "Dokuz", D: "Bir" }, dogruCevap: "A" },
    { seviye: 479, kategori: "Bilmece", soru: "En temiz meyve hangisidir?", secenekler: { A: "Yalan", B: "Elma", C: "Üzüm", D: "Kiraz" }, dogruCevap: "A" },
    { seviye: 480, kategori: "Bilmece", soru: "En dertli meyve hangisidir?", secenekler: { A: "Ayva", B: "Vişne", C: "Nar", D: "Limon" }, dogruCevap: "A" },
    { seviye: 481, kategori: "Bilmece", soru: "Damlaya damlaya ne olur?", secenekler: { A: "Musluk bozulur", B: "Göl olur", C: "Su birikir", D: "Hepsi" }, dogruCevap: "A" },
    { seviye: 482, kategori: "Bilmece", soru: "Adamın biri kafasına radyo koymuş neden?", secenekler: { A: "Kafa dengi olsun diye", B: "Müzik dinlemek için", C: "Haber duymak için", D: "Süs olsun diye" }, dogruCevap: "A" },
    { seviye: 483, kategori: "Bilmece", soru: "Suya düşer ıslanmaz, yere düşer paslanmaz.", secenekler: { A: "Gölge", B: "Güneş", C: "Hava", D: "Işık" }, dogruCevap: "A" },
    { seviye: 484, kategori: "Bilmece", soru: "Hangi ay 28 çeker?", secenekler: { A: "Hepsi", B: "Şubat", C: "Ocak", D: "Mart" }, dogruCevap: "A" },
    { seviye: 485, kategori: "Bilmece", soru: "Denizin ortasında ne vardır?", secenekler: { A: "N harfi", B: "Ada", C: "Gemi", D: "Balık" }, dogruCevap: "A" },
    { seviye: 486, kategori: "Bilmece", soru: "Hangi saatte yemek yenmez?", secenekler: { A: "Duvar saatinde", B: "Gece saatinde", C: "Öğle saatinde", D: "Sabah saatinde" }, dogruCevap: "A" },
    { seviye: 487, kategori: "Bilmece", soru: "Hangi yolda yürünmez?", secenekler: { A: "Samanyolu", B: "Otoban", C: "Demiryolu", D: "Ana yol" }, dogruCevap: "A" },
    { seviye: 488, kategori: "Bilmece", soru: "Hangi macunla diş fırçalanmaz?", secenekler: { A: "Lahmacun", B: "Naneli macun", C: "Beyaz macun", D: "Çilekli macun" }, dogruCevap: "A" },
    { seviye: 489, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Kontrol kalemi", B: "Dolma kalem", C: "Kurşun kalem", D: "Tükenmez kalem" }, dogruCevap: "A" },
    { seviye: 490, kategori: "Bilmece", soru: "Hangi bağda üzüm yetişmez?", secenekler: { A: "Ayakkabı bağı", B: "Karabağ", C: "Üzüm bağı", D: "Bağ evi" }, dogruCevap: "A" },
    { seviye: 491, kategori: "Bilmece", soru: "Hangi bankaya para yatırılmaz?", secenekler: { A: "Kan bankası", B: "Merkez bankası", C: "Halk bankası", D: "Ziraat bankası" }, dogruCevap: "A" },
    { seviye: 492, kategori: "Bilmece", soru: "Hangi kaba su doldurulmaz?", secenekler: { A: "Kaba kuvvete", B: "Delik kaba", C: "Plastik kaba", D: "Cam kaba" }, dogruCevap: "A" },
    { seviye: 493, kategori: "Bilmece", soru: "Hangi adamın burnu havuçtur?", secenekler: { A: "Kardan adam", B: "Aşçı adam", C: "Çiftçi adam", D: "Manav adam" }, dogruCevap: "A" },
    { seviye: 494, kategori: "Bilmece", soru: "Hangi karnede not olmaz?", secenekler: { A: "Sağlık karnesi", B: "Okul karnesi", C: "Başarı karnesi", D: "Sürücü karnesi" }, dogruCevap: "A" },
    { seviye: 495, kategori: "Bilmece", soru: "Hangi meyve ile yazı yazılır?", secenekler: { A: "Kiraz", B: "Elma", C: "Çilek", D: "Armut" }, dogruCevap: "A" },
    { seviye: 496, kategori: "Bilmece", soru: "Hangi top zıplamaz?", secenekler: { A: "Kar topu", B: "Futbol topu", C: "Tenis topu", D: "Basketbol topu" }, dogruCevap: "A" },
    { seviye: 497, kategori: "Bilmece", soru: "Hangi kovanın balı olmaz?", secenekler: { A: "Kulak kovanı", B: "Arı kovanı", C: "Eski kovan", D: "Yeni kovan" }, dogruCevap: "A" },
    { seviye: 498, kategori: "Bilmece", soru: "Hangi pas silinmez?", secenekler: { A: "Pasaport", B: "Demir pası", C: "Halı pası", D: "Yemek pası" }, dogruCevap: "A" },
    { seviye: 499, kategori: "Bilmece", soru: "Hangi diş fırçalanmaz?", secenekler: { A: "Sarımsak dişi", B: "Süt dişi", C: "Azı dişi", D: "Yirmilik diş" }, dogruCevap: "A" },
    { seviye: 500, kategori: "Bilmece", soru: "Hangi filin hortumu yoktur?", secenekler: { A: "Profil", B: "Afrika fili", C: "Asya fili", D: "Yavru fil" }, dogruCevap: "A" }
 
 
);