window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Memeliler ve Türkiye'nin İkonik Hayvanları
    { seviye: 1, kategori: "Canlılar", soru: "Farklı renkli gözleriyle ünlü, Van ilimize özgü kedi türü hangisidir?", secenekler: { A: "Ankara Kedisi", B: "Van Kedisi", C: "Tekir", D: "Siyam" }, dogruCevap: "B" },
    { seviye: 2, kategori: "Canlılar", soru: "Türkiye'nin en büyük vahşi kedi türü olan ve nesli tehlike altında bulunan canlı hangisidir?", secenekler: { A: "Anadolu Parsı", B: "Vaşak", C: "Sırtlan", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 3, kategori: "Canlılar", soru: "Denizli ilimizin simgesi haline gelen, uzun ötüşüyle bilinen canlı hangisidir?", secenekler: { A: "Tavus Kuşu", B: "Denizli Horozu", C: "Güvercin", D: "Keklik" }, dogruCevap: "B" },
    { seviye: 4, kategori: "Canlılar", soru: "Şanlıurfa Birecik'te koruma altına alınan, nesli tükenme tehlikesindeki kuş türü?", secenekler: { A: "Kelaynak", B: "Pelikan", C: "Flamingo", D: "Turna" }, dogruCevap: "A" },
    { seviye: 5, kategori: "Canlılar", soru: "Yumurtalarını Akdeniz sahillerine (özellikle İztuzu) bırakan deniz kaplumbağası?", secenekler: { A: "Caretta Caretta", B: "Nil Kaplumbağası", C: "Kara Kaplumbağası", D: "Deri Sırtlı" }, dogruCevap: "A" },
    { seviye: 6, kategori: "Canlılar", soru: "Ankara'ya özgü, uzun tüyleriyle bilinen keçi türü hangisidir?", secenekler: { A: "Tiftik Keçisi", B: "Dağ Keçisi", C: "Kıl Keçisi", D: "Yaban Keçisi" }, dogruCevap: "A" },
    { seviye: 7, kategori: "Canlılar", soru: "Türkiye'nin tek endemik deniz memelisi olan ve Akdeniz'de yaşayan canlı?", secenekler: { A: "Akdeniz Foku", B: "Yunus", C: "Balina", D: "Deniz Fili" }, dogruCevap: "A" },
    { seviye: 8, kategori: "Canlılar", soru: "Kangallarıyla meşhur olan ilimiz hangisidir?", secenekler: { A: "Sivas", B: "Kayseri", C: "Yozgat", D: "Tokat" }, dogruCevap: "A" },
    { seviye: 9, kategori: "Canlılar", soru: "Sadece Aksaray çevresinde yetişen ve dünyaca ünlü çoban köpeği türü?", secenekler: { A: "Kangal", B: "Malaklı", C: "Akbaş", D: "Çatalburun" }, dogruCevap: "B" },
    { seviye: 10, kategori: "Canlılar", soru: "Tarsus'a özgü, avcılık yetenekleriyle bilinen köpek türü hangisidir?", secenekler: { A: "Çatalburun", B: "Dogo", C: "Terrier", D: "Kangal" }, dogruCevap: "A" },
    { seviye: 11, kategori: "Canlılar", soru: "Eskişehir'de koruma altında olan, beyaz tüyleriyle ünlü çoban köpeği?", secenekler: { A: "Akbaş", B: "Karabaş", C: "Kangal", D: "Bulldog" }, dogruCevap: "A" },
    { seviye: 12, kategori: "Canlılar", soru: "Türkiye'deki en büyük kemirgen türü hangisidir?", secenekler: { A: "Hint Oku", B: "Kunduz", C: "Oklu Kirpi", D: "Tarla Faresi" }, dogruCevap: "C" },
    { seviye: 13, kategori: "Canlılar", soru: "Anadolu yaban koyunu en çok hangi ilimizde bulunur?", secenekler: { A: "Konya (Bozdağlar)", B: "Ankara", C: "Niğde", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 14, kategori: "Canlılar", soru: "Doğu Anadolu'da yaşayan ve 'dağ faresi' olarak da bilinen canlı?", secenekler: { A: "Kör Fare", B: "Avurtlak", C: "Yediuyur", D: "Dağ Tavşanı" }, dogruCevap: "B" },
    { seviye: 15, kategori: "Canlılar", soru: "Türkiye'nin en yaygın geyik türü hangisidir?", secenekler: { A: "Kızıl Geyik", B: "Alageyik", C: "Karaca", D: "Sığın" }, dogruCevap: "A" },
    { seviye: 16, kategori: "Canlılar", soru: "Genellikle bozkırlarda yaşayan ve hızlı koşmasıyla bilinen Anadolu memelisi?", secenekler: { A: "Anadolu Yaban Eşeği", B: "Ceylan", C: "Kurt", D: "Tilki" }, dogruCevap: "B" },
    { seviye: 17, kategori: "Canlılar", soru: "Artvin çevresinde yoğun olarak bulunan Türkiye'nin en büyük yırtıcı memelisi?", secenekler: { A: "Boz Ayı", B: "Sırtlan", C: "Çakal", D: "Porsuk" }, dogruCevap: "A" },
    { seviye: 18, kategori: "Canlılar", soru: "Göller yöresinde ve sulak alanlarda yaşayan, 'su iti' olarak da bilinen canlı?", secenekler: { A: "Su Samuru", B: "Fok", C: "Yunus", D: "Kunduz" }, dogruCevap: "A" },
    { seviye: 19, kategori: "Canlılar", soru: "Anadolu'da nesli tükendiği sanılan ancak son yıllarda tekrar görülen çizgili canlı?", secenekler: { A: "Çizgili Sırtlan", B: "Zebra", C: "Kaplan", D: "Pars" }, dogruCevap: "A" },
    { seviye: 20, kategori: "Canlılar", soru: "Türkiye'nin her bölgesinde bulunan, usta bir avcı olan küçük memeli?", secenekler: { A: "Gelincik", B: "Sincap", C: "Fare", D: "Kirpi" }, dogruCevap: "A" },
    { seviye: 21, kategori: "Canlılar", soru: "Ağaçlara tırmanma yeteneğiyle bilinen kuyruğu tüylü kemirgen?", secenekler: { A: "Sincap", B: "Tavşan", C: "Hamster", D: "Kobay" }, dogruCevap: "A" },
    { seviye: 22, kategori: "Canlılar", soru: "Vücudu dikenlerle kaplı, savunma amaçlı top haline gelen canlı?", secenekler: { A: "Kirpi", B: "Kaplumbağa", C: "Porsuk", D: "Köstebek" }, dogruCevap: "A" },
    { seviye: 23, kategori: "Canlılar", soru: "Yer altında tüneller kazarak yaşayan gözleri çok küçük memeli?", secenekler: { A: "Köstebek", B: "Tarla Faresi", C: "Yılan", D: "Kertenkele" }, dogruCevap: "A" },
    { seviye: 24, kategori: "Canlılar", soru: "Kulakları uzun, arka ayakları güçlü, hızlı zıplayan memeli?", secenekler: { A: "Tavşan", B: "Kanguru", C: "Geyik", D: "Keçi" }, dogruCevap: "A" },
    { seviye: 25, kategori: "Canlılar", soru: "Gece avlanan, kurnazlığıyla masallara konu olan canlı?", secenekler: { A: "Tilki", B: "Kurt", C: "Çakal", D: "Ayı" }, dogruCevap: "A" },

    // 26-50: Türkiye Endemik Bitkileri ve Doğa
    { seviye: 26, kategori: "Canlılar", soru: "Sadece Muğla Köyceğiz çevresinde yetişen dünyaca ünlü ağaç?", secenekler: { A: "Sığla (Günlük)", B: "Çınar", C: "Sedir", D: "Ladin" }, dogruCevap: "A" },
    { seviye: 27, kategori: "Canlılar", soru: "Dünyada sadece Şanlıurfa Halfeti'de yetişen çiçek hangisidir?", secenekler: { A: "Kara Gül", B: "Lale", C: "Nergis", D: "Papatya" }, dogruCevap: "A" },
    { seviye: 28, kategori: "Canlılar", soru: "Antalya ve çevresinde yetişen, boyu 40 metreyi bulan anıt ağaç türü?", secenekler: { A: "Lübnan Sediri", B: "Sarıçam", C: "Meşe", D: "Gürgen" }, dogruCevap: "A" },
    { seviye: 29, kategori: "Canlılar", soru: "İstanbul'un simgesi olan ve her yıl festivali yapılan çiçek?", secenekler: { A: "Lale", B: "Erguvan", C: "Gül", D: "Karanfil" }, dogruCevap: "A" },
    { seviye: 30, kategori: "Canlılar", soru: "Türkiye'de yetişen ve dondurma yapımında kullanılan bitki kökü?", secenekler: { A: "Salep (Orkide)", B: "Zencefil", C: "Tarçın", D: "Zerdeçal" }, dogruCevap: "A" },
    { seviye: 31, kategori: "Canlılar", soru: "Kaz Dağları'na özgü endemik göknar türü hangisidir?", secenekler: { A: "Kazdağı Göknarı", B: "Ladin", C: "Ardıç", D: "Kızılçam" }, dogruCevap: "A" },
    { seviye: 32, kategori: "Canlılar", soru: "Türkiye'nin en çok orman alanına sahip bölgesi hangisidir?", secenekler: { A: "Karadeniz", B: "Ege", C: "Akdeniz", D: "Marmara" }, dogruCevap: "A" },
    { seviye: 33, kategori: "Canlılar", soru: "Mantar türleri içinde en değerli olan ve Anadolu'da da yetişen tür?", secenekler: { A: "Trüf Mantarı", B: "Kuzu Göbeği", C: "İstiridye", D: "Kültür Mantarı" }, dogruCevap: "A" },
    { seviye: 34, kategori: "Canlılar", soru: "Çukurova'nın en önemli tarımsal bitkisi (canlısı)?", secenekler: { A: "Pamuk", B: "Buğday", C: "Arpa", D: "Pirinç" }, dogruCevap: "A" },
    { seviye: 35, kategori: "Canlılar", soru: "Anadolu lalesi olarak da bilinen ve koruma altında olan bitki?", secenekler: { A: "Ters Lale", B: "Ağlayan Gelin", C: "Manisa Lalesi", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 36, kategori: "Canlılar", soru: "Karadeniz'in simgesi olan, iğne yapraklı ve çok uzun yaşayan ağaç?", secenekler: { A: "Ladin", B: "Meşe", C: "Kavak", D: "Söğüt" }, dogruCevap: "A" },
    { seviye: 37, kategori: "Canlılar", soru: "Ege ve Akdeniz mutfağının vazgeçilmezi olan meyve ağacı?", secenekler: { A: "Zeytin", B: "Elma", C: "Armut", D: "Vişne" }, dogruCevap: "A" },
    { seviye: 38, kategori: "Canlılar", soru: "Dünyaca ünlü fındık üretimi hangi bölgemizde yapılır?", secenekler: { A: "Doğu Karadeniz", B: "Ege", C: "Akdeniz", D: "Güneydoğu" }, dogruCevap: "A" },
    { seviye: 39, kategori: "Canlılar", soru: "Isparta ilimizin dünya çapında tanınan çiçeği?", secenekler: { A: "Gül", B: "Lale", C: "Lavanta", D: "Papatya" }, dogruCevap: "A" },
    { seviye: 40, kategori: "Canlılar", soru: "Toros Dağları'nda yetişen ve kokusuyla bilinen şifalı ot?", secenekler: { A: "Kekik", B: "Nane", C: "Dereotu", D: "Maydanoz" }, dogruCevap: "A" },
    { seviye: 41, kategori: "Canlılar", soru: "Türkiye'nin en yüksek noktalarında yetişen dayanıklı ağaç?", secenekler: { A: "Ardıç", B: "Ladin", C: "Çınar", D: "Kavak" }, dogruCevap: "A" },
    { seviye: 42, kategori: "Canlılar", soru: "Meyvesinden yağ elde edilen ve Anadolu'da yaygın olan ağaç?", secenekler: { A: "Zeytin", B: "Çam", C: "Meşe", D: "Gürgen" }, dogruCevap: "A" },
    { seviye: 43, kategori: "Canlılar", soru: "Sulu alanlarda yetişen ve hızlı büyüyen uzun ağaç?", secenekler: { A: "Kavak", B: "Sedir", C: "Göknar", D: "Palamut" }, dogruCevap: "A" },
    { seviye: 44, kategori: "Canlılar", soru: "Yol kenarlarında ve su boylarında sarkan dallarıyla ünlü ağaç?", secenekler: { A: "Salkım Söğüt", B: "Meşe", C: "Kayın", D: "Gürgen" }, dogruCevap: "A" },
    { seviye: 45, kategori: "Canlılar", soru: "Sonbaharda yapraklarını dökmeyen, iğne yapraklı orman ağacı?", secenekler: { A: "Çam", B: "Çınar", C: "Ihlamur", D: "Kestane" }, dogruCevap: "A" },
    { seviye: 46, kategori: "Canlılar", soru: "Kabuklarından çay yapılan ve güzel kokulu çiçekleri olan ağaç?", secenekler: { A: "Ihlamur", B: "Ladin", C: "Meşe", D: "Kavak" }, dogruCevap: "A" },
    { seviye: 47, kategori: "Canlılar", soru: "Anadolu'da heybetiyle bilinen ve bin yıl yaşayabilen ağaç?", secenekler: { A: "Çınar", B: "Söğüt", C: "Elma", D: "Erik" }, dogruCevap: "A" },
    { seviye: 48, kategori: "Canlılar", soru: "Meyveleri dikenli bir kabuk içinde olan orman ağacı?", secenekler: { A: "Kestane", B: "Ceviz", C: "Fındık", D: "Badem" }, dogruCevap: "A" },
    { seviye: 49, kategori: "Canlılar", soru: "İç Anadolu bozkırlarında en çok görülen küçük bitki örtüsü?", secenekler: { A: "Geven", B: "Orkide", C: "Papatya", D: "Gül" }, dogruCevap: "A" },
    { seviye: 50, kategori: "Canlılar", soru: "Bahar aylarında kırlarda sarı-beyaz açan çiçek?", secenekler: { A: "Papatya", B: "Lale", C: "Menekşe", D: "Sümbül" }, dogruCevap: "A" },

    // 51-75: Kuşlar, Böcekler ve Sürüngenler (Türkiye Odaklı)
    { seviye: 51, kategori: "Canlılar", soru: "Türkiye'nin en büyük yırtıcı kuşu hangisidir?", secenekler: { A: "Kızıl Akbaba", B: "Kaya Kartalı", C: "Şahin", D: "Atmaca" }, dogruCevap: "A" },
    { seviye: 52, kategori: "Canlılar", soru: "Baharın müjdecisi olarak bilinen ve çatılara yuva yapan kuş?", secenekler: { A: "Leylek", B: "Kırlangıç", C: "Saka", D: "Serçe" }, dogruCevap: "A" },
    { seviye: 53, kategori: "Canlılar", soru: "Türkiye'deki en zehirli yılan türü hangisidir?", secenekler: { A: "Koca Engerek", B: "Su Yılanı", C: "Kör Yılan", D: "Kara Yılan" }, dogruCevap: "A" },
    { seviye: 54, kategori: "Canlılar", soru: "Ege ve Akdeniz sahillerinde görülen, şarkılara konu olan canlı?", secenekler: { A: "Ağustos Böceği", B: "Ateş Böceği", C: "Arı", D: "Kelebek" }, dogruCevap: "A" },
    { seviye: 55, kategori: "Canlılar", soru: "Sadece gökyüzünde uyuyan ve ömrünün çoğunu uçarak geçiren kuş?", secenekler: { A: "Ebubekil (Sağan)", B: "Martı", C: "Kartal", D: "Doğan" }, dogruCevap: "A" },
    { seviye: 56, kategori: "Canlılar", soru: "Türkiye'de üretilen en kaliteli bal hangi canlıdan elde edilir?", secenekler: { A: "Anzer Arısı", B: "Eşek Arısı", C: "Bombus Arısı", D: "Yaban Arısı" }, dogruCevap: "A" },
    { seviye: 57, kategori: "Canlılar", soru: "Siyah beyaz renkli, zeki ve parlak nesnelere ilgisi olan kuş?", secenekler: { A: "Saksağan", B: "Karga", C: "Güvercin", D: "Kumru" }, dogruCevap: "A" },
    { seviye: 58, kategori: "Canlılar", soru: "Kırmızı göğsüyle bilinen, kışın bahçelerde görülen küçük kuş?", secenekler: { A: "Nar Bülbülü (Narçın)", B: "Serçe", C: "Kanarya", D: "Florya" }, dogruCevap: "A" },
    { seviye: 59, kategori: "Canlılar", soru: "Mavi-yeşil parlak tüyleri olan, dere kenarlarında avlanan kuş?", secenekler: { A: "Yalıçapkını", B: "Ördek", C: "Kaz", D: "Karabatak" }, dogruCevap: "A" },
    { seviye: 60, kategori: "Canlılar", soru: "Geceleri öten, sesiyle ünlü küçük kahverengi kuş?", secenekler: { A: "Bülbül", B: "Saka", C: "İspinoz", D: "Çavuşkuşu" }, dogruCevap: "A" },
    { seviye: 61, kategori: "Canlılar", soru: "Türkiye'nin en renkli ve ibikli kuşlarından biri?", secenekler: { A: "İbibik (Çavuşkuşu)", B: "Keklik", C: "Sülün", D: "Turaç" }, dogruCevap: "A" },
    { seviye: 62, kategori: "Canlılar", soru: "Dağlık bölgelerde yaşayan, eti için avlanan ötücü kuş?", secenekler: { A: "Keklik", B: "Bıldırcın", C: "Güvercin", D: "Atmaca" }, dogruCevap: "A" },
    { seviye: 63, kategori: "Canlılar", soru: "Sert gagasıyla ağaç gövdelerini oyan kuş?", secenekler: { A: "Ağaçkakan", B: "Saka", C: "Serçe", D: "Kırlangıç" }, dogruCevap: "A" },
    { seviye: 64, kategori: "Canlılar", soru: "Dünyanın en hızlı dalış yapan yırtıcı kuşu?", secenekler: { A: "Gökdoğan", B: "Kartal", C: "Akbaba", D: "Şahin" }, dogruCevap: "A" },
    { seviye: 65, kategori: "Canlılar", soru: "İnsanların evlerine yuva yapan, çatallı kuyruklu küçük kuş?", secenekler: { A: "Kırlangıç", B: "Serçe", C: "Saka", D: "Arıkuşu" }, dogruCevap: "A" },
    { seviye: 66, kategori: "Canlılar", soru: "Üzerindeki benekli deseniyle bilinen faydalı böcek?", secenekler: { A: "Uğur Böceği", B: "Hamam Böceği", C: "Bit", D: "Pire" }, dogruCevap: "A" },
    { seviye: 67, kategori: "Canlılar", soru: "Yazın akşamları ışık saçarak uçan böcek?", secenekler: { A: "Ateş Böceği", B: "Sinek", C: "Arı", D: "Güve" }, dogruCevap: "A" },
    { seviye: 68, kategori: "Canlılar", soru: "Renkleri ve kanat desenleriyle doğanın en güzel böceği?", secenekler: { A: "Kelebek", B: "Çekirge", C: "Karınca", D: "Örümcek" }, dogruCevap: "A" },
    { seviye: 69, kategori: "Canlılar", soru: "Kendi boyunun yüzlerce katı zıplayabilen yeşil böcek?", secenekler: { A: "Çekirge", B: "Arı", C: "Bit", D: "Kene" }, dogruCevap: "A" },
    { seviye: 70, kategori: "Canlılar", soru: "Sekiz bacağı olan ve ağ kurarak avlanan canlı?", secenekler: { A: "Örümcek", B: "Karınca", C: "Sinek", D: "Arı" }, dogruCevap: "A" },
    { seviye: 71, kategori: "Canlılar", soru: "Kuyruğu koptuğunda yeniden çıkabilen sürüngen?", secenekler: { A: "Kertenkele", B: "Yılan", C: "Timsah", D: "Kurbağa" }, dogruCevap: "A" },
    { seviye: 72, kategori: "Canlılar", soru: "Sert kabuğuyla yavaş hareket eden sürüngen?", secenekler: { A: "Kaplumbağa", B: "Salyangoz", C: "Yengeç", D: "İstakoz" }, dogruCevap: "A" },
    { seviye: 73, kategori: "Canlılar", soru: "Ayakları olmayan, sürünerek hareket eden uzun canlı?", secenekler: { A: "Yılan", B: "Solucan", C: "Kertenkele", D: "Tırtıl" }, dogruCevap: "A" },
    { seviye: 74, kategori: "Canlılar", soru: "Suda ve karada yaşayan, zıplayan ve vıraklayan canlı?", secenekler: { A: "Kurbağa", B: "Balık", C: "Kaplumbağa", D: "Semender" }, dogruCevap: "A" },
    { seviye: 75, kategori: "Canlılar", soru: "Güneşlenmeyi çok seven, küçük ve hızlı bir kertenkele türü?", secenekler: { A: "Keler", B: "Bukalemun", C: "Varan", D: "İguana" }, dogruCevap: "A" },

    // 76-100: Genel Biyoloji ve Dünya Canlıları
    { seviye: 76, kategori: "Canlılar", soru: "Dünyanın en büyük memeli hayvanı hangisidir?", secenekler: { A: "Mavi Balina", B: "Fil", C: "Zürafa", D: "Balina Köpekbalığı" }, dogruCevap: "A" },
    { seviye: 77, kategori: "Canlılar", soru: "Kendi ağırlığının 50 katını taşıyabilen böcek?", secenekler: { A: "Karınca", B: "Arı", C: "Sinek", D: "Örümcek" }, dogruCevap: "A" },
    { seviye: 78, kategori: "Canlılar", soru: "Kan grubu olmayan ve her şeyi yiyebilen deniz canlısı?", secenekler: { A: "Deniz Yıldızı", B: "Ahtapot", C: "Mürekkep Balığı", D: "Yengeç" }, dogruCevap: "A" },
    { seviye: 79, kategori: "Canlılar", soru: "Işık kirliliğinden en çok etkilenen, ışık saçan böcek?", secenekler: { A: "Ateş Böceği", B: "Uğur Böceği", C: "Çekirge", D: "Hamam Böceği" }, dogruCevap: "A" },
    { seviye: 80, kategori: "Canlılar", soru: "Vücudunda kemik yerine kıkırdak bulunan deniz avcısı?", secenekler: { A: "Köpekbalığı", B: "Balina", C: "Yunus", D: "Palamut" }, dogruCevap: "A" },
    { seviye: 81, kategori: "Canlılar", soru: "Dünyanın en hızlı koşan kara hayvanı?", secenekler: { A: "Çita", B: "Aslan", C: "Tazı", D: "At" }, dogruCevap: "A" },
    { seviye: 82, kategori: "Canlılar", soru: "Renk değiştirme özelliğiyle bilinen sürüngen?", secenekler: { A: "Bukalemun", B: "İguana", C: "Kertenkele", D: "Timsah" }, dogruCevap: "A" },
    { seviye: 83, kategori: "Canlılar", soru: "Yumurta ile çoğalan tek memeli türü?", secenekler: { A: "Ornitorenk", B: "Kanguru", C: "Koala", D: "Yarasa" }, dogruCevap: "A" },
    { seviye: 84, kategori: "Canlılar", soru: "Gözleri kafasından büyük olan gece avcısı kuş?", secenekler: { A: "Baykuş", B: "Atmaca", C: "Kartal", D: "Kuzgun" }, dogruCevap: "A" },
    { seviye: 85, kategori: "Canlılar", soru: "Dünyanın en uzun ömürlü canlısı olarak bilinen denizanası türü?", secenekler: { A: "Ölümsüz Denizanası", B: "Mavi Denizanası", C: "Kutu Denizanası", D: "Aslan Yelesi" }, dogruCevap: "A" },
    { seviye: 86, kategori: "Canlılar", soru: "Bitkilerin nefes almasını sağlayan yaprak bölgesi?", secenekler: { A: "Stoma", B: "Kök", C: "Gövde", D: "Çiçek" }, dogruCevap: "A" },
    { seviye: 87, kategori: "Canlılar", soru: "Arıların bal yapmak için çiçeklerden topladığı sıvı?", secenekler: { A: "Nektar", B: "Polen", C: "Su", D: "Reçine" }, dogruCevap: "A" },
    { seviye: 88, kategori: "Canlılar", soru: "Fotosentez yapabilen tek hücreli canlılara örnek?", secenekler: { A: "Algler", B: "Bakteriler", C: "Virüsler", D: "Mantarlar" }, dogruCevap: "A" },
    { seviye: 89, kategori: "Canlılar", soru: "Kalbi vücudunun dışında olan tek canlı?", secenekler: { A: "Sinek Kuşu", B: "Mavi Balina", C: "Karınca", D: "Yoktur" }, dogruCevap: "D" },
    { seviye: 90, kategori: "Canlılar", soru: "Kış uykusuna yatan bir hayvan örneği?", secenekler: { A: "Ayı", B: "Köpek", C: "At", D: "Zürafa" }, dogruCevap: "A" },
    { seviye: 91, kategori: "Canlılar", soru: "Bitkilerde yeşil rengi veren madde hangisidir?", secenekler: { A: "Klorofil", B: "Hemoglobin", C: "Melanin", D: "Keratin" }, dogruCevap: "A" },
    { seviye: 92, kategori: "Canlılar", soru: "Dünyanın en küçük kuşu hangisidir?", secenekler: { A: "Arı Sinek Kuşu", B: "Serçe", C: "Saka", D: "Güvercin" }, dogruCevap: "A" },
    { seviye: 93, kategori: "Canlılar", soru: "Hangi canlı türü sosyal bir topluluk (koloni) halinde yaşamaz?", secenekler: { A: "Kaplan", B: "Karınca", C: "Arı", D: "Termit" }, dogruCevap: "A" },
    { seviye: 94, kategori: "Canlılar", soru: "İnsan vücudundaki en büyük organ hangisidir?", secenekler: { A: "Deri", B: "Karaciğer", C: "Akciğer", D: "Beyin" }, dogruCevap: "A" },
    { seviye: 95, kategori: "Canlılar", soru: "Böceklerin kaç adet bacağı bulunur?", secenekler: { A: "6", B: "8", C: "4", D: "10" }, dogruCevap: "A" },
    { seviye: 96, kategori: "Canlılar", soru: "Sürüngenlerin vücudu ne ile kaplıdır?", secenekler: { A: "Pullar", B: "Tüyler", C: "Kıl", D: "Deri" }, dogruCevap: "A" },
    { seviye: 97, kategori: "Canlılar", soru: "Balıklar hangi organları ile solunum yaparlar?", secenekler: { A: "Solungaç", B: "Akciğer", C: "Deri", D: "Burun" }, dogruCevap: "A" },
    { seviye: 98, kategori: "Canlılar", soru: "Hem karada hem suda yaşayabilen canlı grubu?", secenekler: { A: "Amfibiler", B: "Memeliler", C: "Kuşlar", D: "Balıklar" }, dogruCevap: "A" },
    { seviye: 99, kategori: "Canlılar", soru: "Bitkilerin güneş ışığını enerjiye dönüştürmesi olayına ne denir?", secenekler: { A: "Fotosentez", B: "Solunum", C: "Terleme", D: "Boşaltım" }, dogruCevap: "A" },
    { seviye: 100, kategori: "Canlılar", soru: "Doğadaki en büyük hücre hangisidir?", secenekler: { A: "Devekuşu Yumurtası", B: "Sinir Hücresi", C: "Yumurta Hücresi", D: "Bakteri" }, dogruCevap: "A" }, 
    { seviye: 100, kategori: "Canlılar", soru: "Hangi kuş türü uçamadığı halde çok hızlı koşabilir?", secenekler: { A: "Deve Kuşu", B: "Kartal", C: "Şahin", D: "Leylek" }, dogruCevap: "A" },
    { seviye: 101, kategori: "Canlılar", soru: "Bukalemunların en bilinen özelliği nedir?", secenekler: { A: "Renk değiştirmeleri", B: "Uçabilmeleri", C: "Suda yaşamaları", D: "Çok hızlı koşmaları" }, dogruCevap: "A" },
    { seviye: 102, kategori: "Canlılar", soru: "Karıncaların iletişim kurmak için salgıladığı kimyasal maddeye ne denir?", secenekler: { A: "Feromon", B: "Zehir", C: "Enzim", D: "Hormon" }, dogruCevap: "A" },
    { seviye: 103, kategori: "Canlılar", soru: "Hangi hayvan türü yavrularını kesesinde taşır?", secenekler: { A: "Kanguru", B: "Maymun", C: "Zürafa", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 104, kategori: "Canlılar", soru: "Bitkilerin güneş ışığını kullanarak besin üretmesine ne ad verilir?", secenekler: { A: "Fotosentez", B: "Solunum", C: "Terleme", D: "Mayalanma" }, dogruCevap: "A" },
    { seviye: 105, kategori: "Canlılar", soru: "Yılanların koku almak için kullandığı organ hangisidir?", secenekler: { A: "Dil", B: "Burun", C: "Göz", D: "Deri" }, dogruCevap: "A" },
    { seviye: 106, kategori: "Canlılar", soru: "Dünyanın en hızlı kara hayvanı hangisidir?", secenekler: { A: "Çita", B: "At", C: "Tavşan", D: "Kaplan" }, dogruCevap: "A" },
    { seviye: 107, kategori: "Canlılar", soru: "Hangi canlı türü hem karada hem de suda yaşayabilir?", secenekler: { A: "Kurbağa", B: "Yılan", C: "Balık", D: "Kuş" }, dogruCevap: "A" },
    { seviye: 108, kategori: "Canlılar", soru: "Arıların bal yaptığı peteklerin şekli nedir?", secenekler: { A: "Altıgen", B: "Kare", C: "Üçgen", D: "Daire" }, dogruCevap: "A" },
    { seviye: 109, kategori: "Canlılar", soru: "Kış uykusuna yatmasıyla bilinen iri cüsseli memeli hayvan hangisidir?", secenekler: { A: "Ayı", B: "Kurt", C: "Geyik", D: "Fil" }, dogruCevap: "A" },
    { seviye: 110, kategori: "Canlılar", soru: "Denizatı hangi grupta yer alan bir canlıdır?", secenekler: { A: "Balık", B: "Memeli", C: "Sürüngen", D: "Böcek" }, dogruCevap: "A" },
    { seviye: 111, kategori: "Canlılar", soru: "Mantar hangi canlı grubuna girer?", secenekler: { A: "Kendi başına bir alemdir", B: "Bitki", C: "Hayvan", D: "Bakteri" }, dogruCevap: "A" },
    { seviye: 112, kategori: "Canlılar", soru: "Ahtapotların kaç adet kalbi vardır?", secenekler: { A: "3", B: "1", C: "2", D: "4" }, dogruCevap: "A" },
    { seviye: 113, kategori: "Canlılar", soru: "Hangi kuş türü kutuplarda yaşar ve uçamaz?", secenekler: { A: "Penguen", B: "Martı", C: "Pelikan", D: "Kuzgun" }, dogruCevap: "A" },
    { seviye: 114, kategori: "Canlılar", soru: "Balinalar hangi organları ile solunum yaparlar?", secenekler: { A: "Akciğer", B: "Solungaç", C: "Deri", D: "Yüzgeç" }, dogruCevap: "A" },
    { seviye: 115, kategori: "Canlılar", soru: "Vücudunda kemik yerine kıkırdak bulunan deniz canlısı hangisidir?", secenekler: { A: "Köpek Balığı", B: "Yunus", C: "Hamsi", D: "Lüfer" }, dogruCevap: "A" },
    { seviye: 116, kategori: "Canlılar", soru: "Kendi vücut ağırlığının 50 katını taşıyabilen böcek hangisidir?", secenekler: { A: "Karınca", B: "Sinek", C: "Arı", D: "Hamam Böceği" }, dogruCevap: "A" },
    { seviye: 117, kategori: "Canlılar", soru: "Zürafaların dilleri ne renktir?", secenekler: { A: "Siyah/Koyu Mor", B: "Pembe", C: "Kırmızı", D: "Beyaz" }, dogruCevap: "A" },
    { seviye: 118, kategori: "Canlılar", soru: "Hangi hayvanın sütü pembe renklidir?", secenekler: { A: "Su Aygırı", B: "Gergedan", C: "Fil", D: "Zebra" }, dogruCevap: "A" },
    { seviye: 119, kategori: "Canlılar", soru: "Gözleri beyinlerinden daha büyük olan kuş hangisidir?", secenekler: { A: "Deve Kuşu", B: "Baykuş", C: "Kartal", D: "Papağan" }, dogruCevap: "A" },
    { seviye: 120, kategori: "Canlılar", soru: "Ayaktayken uyuyabilen hayvan hangisidir?", secenekler: { A: "At", B: "Kedi", C: "Köpek", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 121, kategori: "Canlılar", soru: "Parmak izi insana en çok benzeyen hayvan hangisidir?", secenekler: { A: "Koala", B: "Şempanze", C: "Goril", D: "Orangutan" }, dogruCevap: "A" },
    { seviye: 122, kategori: "Canlılar", soru: "Hangi canlı türü başını 270 derece döndürebilir?", secenekler: { A: "Baykuş", B: "Atmaca", C: "Yılan", D: "Kedi" }, dogruCevap: "A" },
    { seviye: 123, kategori: "Canlılar", soru: "Dili vücudundan daha uzun olabilen canlı hangisidir?", secenekler: { A: "Bukalemun", B: "Kurbağa", C: "Kertenkele", D: "Zürafa" }, dogruCevap: "A" },
    { seviye: 124, kategori: "Canlılar", soru: "Vücudundaki tüm kanı bir tüp içinde toplayabilen, sülük benzeri canlı?", secenekler: { A: "Sülük", B: "Solucan", C: "Kene", D: "Bit" }, dogruCevap: "A" },
    { seviye: 125, kategori: "Canlılar", soru: "Su altında en uzun süre nefes almadan kalabilen memeli hangisidir?", secenekler: { A: "İspermeçet Balinası", B: "Yunus", C: "Fok", D: "Su Aygırı" }, dogruCevap: "A" },
    { seviye: 126, kategori: "Canlılar", soru: "Hangi hayvanın kalbi kafasındadır?", secenekler: { A: "Karides", B: "Yengeç", C: "Istakoz", D: "Deniz Yıldızı" }, dogruCevap: "A" },
    { seviye: 127, kategori: "Canlılar", soru: "İnsan vücudunda bakteri miktarının en yoğun olduğu yer neresidir?", secenekler: { A: "Bağırsaklar", B: "Ağız", C: "Eller", D: "Mide" }, dogruCevap: "A" },
    { seviye: 128, kategori: "Canlılar", soru: "Işık kirliliğinden en çok etkilenen, denizden karaya çıkan canlı?", secenekler: { A: "Caretta Caretta", B: "Yengeç", C: "Fok", D: "Deniz Anası" }, dogruCevap: "A" },
    { seviye: 129, kategori: "Canlılar", soru: "Hangi kuş türü geri geri uçabilir?", secenekler: { A: "Sinek Kuşu (Hummingbird)", B: "Serçe", C: "Kırlangıç", D: "Arı Kuşu" }, dogruCevap: "A" },
    { seviye: 130, kategori: "Canlılar", soru: "Göz kapakları olmayan ve gözlerini diliyle temizleyen canlı?", secenekler: { A: "Geko (Kertenkele)", B: "Yılan", C: "Bukalemun", D: "Timsah" }, dogruCevap: "A" },
    { seviye: 131, kategori: "Canlılar", soru: "Dünyanın en zehirli yılanı hangisidir?", secenekler: { A: "İç Bölge Taypanı", B: "Kobra", C: "Engerek", D: "Kara Mamba" }, dogruCevap: "A" },
    { seviye: 132, kategori: "Canlılar", soru: "Fillerin en çok korktuğu küçük canlı hangisidir?", secenekler: { A: "Arı", B: "Fare", C: "Karınca", D: "Örümcek" }, dogruCevap: "A" },
    { seviye: 133, kategori: "Canlılar", soru: "Kutup ayılarının derisi aslında ne renktir?", secenekler: { A: "Siyah", B: "Beyaz", C: "Pembe", D: "Gri" }, dogruCevap: "A" },
    { seviye: 134, kategori: "Canlılar", soru: "Hangi hayvanın terisi güneş kremi görevi görür ve kırmızımsıdır?", secenekler: { A: "Su Aygırı", B: "Fil", C: "Domuz", D: "Gergedan" }, dogruCevap: "A" },
    { seviye: 135, kategori: "Canlılar", soru: "Deniz yıldızlarının kaç tane beyni vardır?", secenekler: { A: "Beyni yoktur", B: "1", C: "5", D: "2" }, dogruCevap: "A" },
    { seviye: 136, kategori: "Canlılar", soru: "Hangi canlı türü öldükten sonra bile sokabilir?", secenekler: { A: "Arı", B: "Yılan", C: "Akrep", D: "Örümcek" }, dogruCevap: "A" },
    { seviye: 137, kategori: "Canlılar", soru: "Kargaların ortalama ömrü ne kadardır?", secenekler: { A: "15-20 yıl", B: "100 yıl", C: "200 yıl", D: "50 yıl" }, dogruCevap: "A" },
    { seviye: 138, kategori: "Canlılar", soru: "Hangi memeli yumurtlayarak çoğalır?", secenekler: { A: "Ornitorenk", B: "Kanguru", C: "Yunus", D: "Yarasa" }, dogruCevap: "A" },
    { seviye: 139, kategori: "Canlılar", soru: "Kedilerin vücudunda kaç adet kemik bulunur?", secenekler: { A: "230", B: "206", C: "150", D: "300" }, dogruCevap: "A" },
    { seviye: 140, kategori: "Canlılar", soru: "Mavi balinaların dili yaklaşık ne kadar ağırlıktadır?", secenekler: { A: "Bir fil kadar", B: "Bir ton", C: "500 kg", D: "100 kg" }, dogruCevap: "A" },
    { seviye: 141, kategori: "Canlılar", soru: "Hangi hayvanın üç adet göz kapağı vardır?", secenekler: { A: "Deve", B: "Kedi", C: "Kartal", D: "Timsah" }, dogruCevap: "A" },
    { seviye: 142, kategori: "Canlılar", soru: "Bir ıstakozun kanı ne renktir?", secenekler: { A: "Mavi", B: "Kırmızı", C: "Şeffaf", D: "Yeşil" }, dogruCevap: "C" },
    { seviye: 143, kategori: "Canlılar", soru: "Hangi canlı havayı duymak için bacaklarını kullanır?", secenekler: { A: "Cırcır Böceği", B: "Örümcek", C: "Çekirge", D: "Kelebek" }, dogruCevap: "A" },
    { seviye: 144, kategori: "Canlılar", soru: "Dünyanın en küçük kuşu hangisidir?", secenekler: { A: "Arı Sinek Kuşu", B: "Serçe", C: "Kanarya", D: "Saka" }, dogruCevap: "A" },
    { seviye: 145, kategori: "Canlılar", soru: "Hangi hayvanın sütü dondurma yapımında kullanılmaz?", secenekler: { A: "Balina", B: "Keçi", C: "İnek", D: "Manda" }, dogruCevap: "A" },
    { seviye: 146, kategori: "Canlılar", soru: "Penguenlerin sadece neresinde ter bezleri bulunur?", secenekler: { A: "Ter bezleri yoktur", B: "Ayaklarında", C: "Gagalarında", D: "Kanatlarında" }, dogruCevap: "A" },
    { seviye: 147, kategori: "Canlılar", soru: "Yarasalar yönlerini ne ile bulurlar?", secenekler: { A: "Ses dalgaları (Ekolokasyon)", B: "Gözleri", C: "Koku", D: "Isı" }, dogruCevap: "A" },
    { seviye: 148, kategori: "Canlılar", soru: "Hangi hayvan asla unutmamasıyla ünlüdür?", secenekler: { A: "Fil", B: "Köpek", C: "Maymun", D: "Karga" }, dogruCevap: "A" },
    { seviye: 149, kategori: "Canlılar", soru: "Yılanların derisi neyden yapılmıştır?", secenekler: { A: "Keratin", B: "Kalsiyum", C: "Kıkırdak", D: "Lif" }, dogruCevap: "A" },
    { seviye: 150, kategori: "Canlılar", soru: "Kelebeklerin tat alma organları nerededir?", secenekler: { A: "Ayaklarında", B: "Hortumlarında", C: "Antenlerinde", D: "Kanatlarında" }, dogruCevap: "A" },
    { seviye: 151, kategori: "Canlılar", soru: "Bir salyangoz yaklaşık ne kadar süre uyuyabilir?", secenekler: { A: "3 yıl", B: "3 ay", C: "3 hafta", D: "3 gün" }, dogruCevap: "A" },
    { seviye: 152, kategori: "Canlılar", soru: "Hangi hayvanın gözleri dilediği yöne birbirinden bağımsız hareket edebilir?", secenekler: { A: "Bukalemun", B: "Baykuş", C: "Kedi", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 153, kategori: "Canlılar", soru: "Köpeklerin koku alma yeteneği insanınkinden kaç kat daha güçlüdür?", secenekler: { A: "40 kat", B: "5 kat", C: "10 kat", D: "100 kat" }, dogruCevap: "A" },
    { seviye: 154, kategori: "Canlılar", soru: "Karıncaların akciğerleri var mıdır?", secenekler: { A: "Hayır", B: "Evet", C: "Sadece kraliçe karıncanın", D: "Yarısında vardır" }, dogruCevap: "A" },
    { seviye: 155, kategori: "Canlılar", soru: "Bir inek günde yaklaşık kaç litre su tüketir?", secenekler: { A: "100-150 litre", B: "10 litre", C: "50 litre", D: "300 litre" }, dogruCevap: "A" },
    { seviye: 156, kategori: "Canlılar", soru: "Hangi canlı türünün erkekleri doğum yapar (yavruları taşır)?", secenekler: { A: "Denizatı", B: "Penguen", C: "Kangaroo", D: "Kaplumbağa" }, dogruCevap: "A" },
    { seviye: 157, kategori: "Canlılar", soru: "Timsahlar neden taş yutarlar?", secenekler: { A: "Daha derine dalabilmek için", B: "Aç oldukları için", C: "Dişlerini bilemek için", D: "Yuva yapmak için" }, dogruCevap: "A" },
    { seviye: 158, kategori: "Canlılar", soru: "Hangi kuş türü havada uyuyabilir?", secenekler: { A: "Ebabiller", B: "Güvercinler", C: "Serçeler", D: "Kargalar" }, dogruCevap: "A" },
    { seviye: 159, kategori: "Canlılar", soru: "Arılar birbirlerine çiçeklerin yerini nasıl tarif ederler?", secenekler: { A: "Dans ederek", B: "Ses çıkararak", C: "Dokunarak", D: "Renk değiştirerek" }, dogruCevap: "A" },
    { seviye: 160, kategori: "Canlılar", soru: "Tarantulalar ne kadar süre yemek yemeden yaşayabilirler?", secenekler: { A: "2 yıl", B: "2 ay", C: "2 hafta", D: "2 gün" }, dogruCevap: "A" },
    { seviye: 161, kategori: "Canlılar", soru: "Dünyanın en uzun yaşayan hayvanı hangisidir (bilinen)?", secenekler: { A: "Grönland Köpek Balığı", B: "Dev Kaplumbağa", C: "Fil", D: "Mavi Balina" }, dogruCevap: "A" },
    { seviye: 162, kategori: "Canlılar", soru: "Bir sineğin kaç tane gözü vardır?", secenekler: { A: "Binlerce (Petek göz)", B: "2", C: "4", D: "8" }, dogruCevap: "A" },
    { seviye: 163, kategori: "Canlılar", soru: "Kedilerin mırlaması ne anlama gelebilir?", secenekler: { A: "Hepsi (Mutluluk, stres, iyileşme)", B: "Sadece mutluluk", C: "Sadece açlık", D: "Sadece kızgınlık" }, dogruCevap: "A" },
    { seviye: 164, kategori: "Canlılar", soru: "Ayıların yürürken önce hangi tarafın ayaklarını attığı bilinir?", secenekler: { A: "Önce aynı tarafın (sağ ön-sağ arka)", B: "Çapraz", C: "Sadece önler", D: "Sadece arkalar" }, dogruCevap: "A" },
    { seviye: 165, kategori: "Canlılar", soru: "Hangi hayvanın dişleri ömrü boyunca uzamaya devam eder?", secenekler: { A: "Tavşan", B: "Kedi", C: "Köpek", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 166, kategori: "Canlılar", soru: "Zürafalar günde ortalama kaç saat uyurlar?", secenekler: { A: "30 dakika - 2 saat", B: "8 saat", C: "12 saat", D: "5 saat" }, dogruCevap: "A" },
    { seviye: 167, kategori: "Canlılar", soru: "Bir dev mürekkep balığının gözü yaklaşık ne büyüklüktedir?", secenekler: { A: "Plaj topu kadar", B: "Tenis topu kadar", C: "Misket kadar", D: "Portakal kadar" }, dogruCevap: "A" },
    { seviye: 168, kategori: "Canlılar", soru: "Hangi canlı türü su içmeden en uzun süre yaşayabilir?", secenekler: { A: "Kanguru Faresi", B: "Deve", C: "Akrep", D: "Yılan" }, dogruCevap: "A" },
    { seviye: 169, kategori: "Canlılar", soru: "Hangi kuşun kanat açıklığı en büyüktür?", secenekler: { A: "Albatros", B: "Kartal", C: "Pelikan", D: "Akbaba" }, dogruCevap: "A" },
    { seviye: 170, kategori: "Canlılar", soru: "Köpeklerin ter bezleri nerededir?", secenekler: { A: "Pati altlarında", B: "Dillerinde", C: "Kulaklarında", D: "Sırtlarında" }, dogruCevap: "A" },
    { seviye: 171, kategori: "Canlılar", soru: "Dünyanın en ağır böceği hangisidir?", secenekler: { A: "Golyat Böceği", B: "Hamam Böceği", C: "Geyik Böceği", D: "Uğur Böceği" }, dogruCevap: "A" },
    { seviye: 172, kategori: "Canlılar", soru: "Hangi hayvanın sesi yankı yapmaz (şehir efsanesi)?", secenekler: { A: "Ördek", B: "Kaz", C: "Tavuk", D: "Kuğu" }, dogruCevap: "A" },
    { seviye: 173, kategori: "Canlılar", soru: "Kaplanların derisindeki çizgiler sadece tüylerinde mi bulunur?", secenekler: { A: "Hayır, derilerinde de vardır", B: "Evet, sadece tüylerinde", C: "Sadece yavrularında", D: "Sadece kuyruklarında" }, dogruCevap: "A" },
    { seviye: 174, kategori: "Canlılar", soru: "Deve kuşunun beyni mi daha büyüktür gözü mü?", secenekler: { A: "Gözü", B: "Beyni", C: "İkisi de eşittir", D: "Türüne göre değişir" }, dogruCevap: "A" },
    { seviye: 175, kategori: "Canlılar", soru: "Hangi hayvanın kalbi dakikada sadece 9 kez atar?", secenekler: { A: "Mavi Balina", B: "Fil", C: "Kaplumbağa", D: "Timsah" }, dogruCevap: "A" },
    { seviye: 176, kategori: "Canlılar", soru: "Deniz analarının vücudunun yüzde kaçı sudur?", secenekler: { A: "%95", B: "%70", C: "%50", D: "%30" }, dogruCevap: "A" },
    { seviye: 177, kategori: "Canlılar", soru: "Hamam böcekleri kafaları kopsa bile kaç gün yaşayabilirler?", secenekler: { A: "1 hafta", B: "1 saat", C: "1 gün", D: "1 ay" }, dogruCevap: "A" },
    { seviye: 178, kategori: "Canlılar", soru: "Aslanlar bir günde ortalama kaç saat uyurlar?", secenekler: { A: "20 saat", B: "5 saat", C: "10 saat", D: "2 saat" }, dogruCevap: "A" },
    { seviye: 179, kategori: "Canlılar", soru: "Hangi hayvanın dört tane midesi vardır?", secenekler: { A: "İnek", B: "At", C: "Domuz", D: "Köpek" }, dogruCevap: "A" },
    { seviye: 180, kategori: "Canlılar", soru: "Filler neden hortumlarını kullanırlar?", secenekler: { A: "Hepsi (Nefes alma, su içme, nesne taşıma)", B: "Sadece su içmek", C: "Sadece nefes almak", D: "Sadece koku almak" }, dogruCevap: "A" },
    { seviye: 181, kategori: "Canlılar", soru: "Hangi canlı türü DNA olarak insana %98.8 oranında benzer?", secenekler: { A: "Şempanze", B: "Goril", C: "Yunus", D: "Fare" }, dogruCevap: "A" },
    { seviye: 182, kategori: "Canlılar", soru: "Hangi balık türü suyun dışında da nefes alabilir?", secenekler: { A: "Akciğerli Balık", B: "Sazan", C: "Palamut", D: "Uskumru" }, dogruCevap: "A" },
    { seviye: 183, kategori: "Canlılar", soru: "Yılanların kulakları var mıdır?", secenekler: { A: "Dış kulakları yoktur (titreşim hissederler)", B: "Evet, vardır", C: "Sadece büyük yılanlarda", D: "Sadece zehirli olanlarda" }, dogruCevap: "A" },
    { seviye: 184, kategori: "Canlılar", soru: "Kuşların kemiklerinin içi neden boştur?", secenekler: { A: "Hafif olup uçabilmek için", B: "Daha hızlı koşmak için", C: "Daha iyi duymak için", D: "Daha çok yemek yemek için" }, dogruCevap: "A" },
    { seviye: 185, kategori: "Canlılar", soru: "Hangi canlı türü dünyadaki en büyük göçü yapar?", secenekler: { A: "Kuzey Sumrusu (Artic Tern)", B: "Balina", C: "Fil", D: "Geyik" }, dogruCevap: "A" },
    { seviye: 186, kategori: "Canlılar", soru: "Bebekken ağlamayan hayvan hangisidir?", secenekler: { A: "Timsah", B: "Maymun", C: "Kedi", D: "İnsan" }, dogruCevap: "A" },
    { seviye: 187, kategori: "Canlılar", soru: "Baykuşlar neden sessiz uçarlar?", secenekler: { A: "Tüylerinin özel yapısı sayesinde", B: "Çok küçük oldukları için", C: "Çok hızlı uçtukları için", D: "Gece uçtukları için" }, dogruCevap: "A" },
    { seviye: 188, kategori: "Canlılar", soru: "Pireler kendi boylarının kaç katı yükseğe zıplayabilir?", secenekler: { A: "200 kat", B: "10 kat", C: "50 kat", D: "1000 kat" }, dogruCevap: "A" },
    { seviye: 189, kategori: "Canlılar", soru: "Mavi balinaların kalbi ne büyüklüktedir?", secenekler: { A: "Küçük bir araba kadar", B: "Basketbol topu kadar", C: "Bir ev kadar", D: "Bir kova kadar" }, dogruCevap: "A" },
    { seviye: 190, kategori: "Canlılar", soru: "Penguenler neden grup halinde dururlar?", secenekler: { A: "Isınmak için", B: "Oyun oynamak için", C: "Uyumak için", D: "Yemek yemek için" }, dogruCevap: "A" },
    { seviye: 191, kategori: "Canlılar", soru: "Hangi hayvanın dilleri vücutlarından daha uzundur?", secenekler: { A: "Bukalemun", B: "Kurbağa", C: "Zürafa", D: "Kedi" }, dogruCevap: "A" },
    { seviye: 192, kategori: "Canlılar", soru: "Deniz yıldızları kopan kollarını yenileyebilir mi?", secenekler: { A: "Evet", B: "Hayır", C: "Sadece yavrular", D: "Sadece belirli türler" }, dogruCevap: "A" },
    { seviye: 193, kategori: "Canlılar", soru: "Hangi kuş türü yuva yapmaz, yumurtasını başka kuşun yuvasına bırakır?", secenekler: { A: "Guguk Kuşu", B: "Serçe", C: "Kırlangıç", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 194, kategori: "Canlılar", soru: "Kedilerin bıyıkları ne işe yarar?", secenekler: { A: "Denge ve boşluk algısı", B: "Süs", C: "Koku alma", D: "Sadece duymak" }, dogruCevap: "A" },
    { seviye: 195, kategori: "Canlılar", soru: "Balinalar neden su fışkırtırlar?", secenekler: { A: "Nefes vermek için", B: "Oyun oynamak için", C: "Serinlemek için", D: "Yıkanmak için" }, dogruCevap: "A" },
    { seviye: 196, kategori: "Canlılar", soru: "Hangi canlı türü suyun altında en hızlı yüzer?", secenekler: { A: "Yelken Balığı", B: "Yunus", C: "Köpek Balığı", D: "Balina" }, dogruCevap: "A" },
    { seviye: 197, kategori: "Canlılar", soru: "Fillerin hortumunda kaç tane kemik bulunur?", secenekler: { A: "Sıfır", B: "10", C: "100", D: "1" }, dogruCevap: "A" },
    { seviye: 198, kategori: "Canlılar", soru: "İpek böceği hangi ağacın yaprağıyla beslenir?", secenekler: { A: "Dut", B: "Elma", C: "Çam", D: "Kavak" }, dogruCevap: "A" },
    { seviye: 199, kategori: "Canlılar", soru: "Hangi hayvanın sütü en yağlıdır?", secenekler: { A: "Mavi Balina", B: "İnek", C: "Keçi", D: "Koyun" }, dogruCevap: "A" },
    { seviye: 200, kategori: "Canlılar", soru: "Hangi canlı türü yaşlandıkça küçülebilir?", secenekler: { A: "Bazı deniz anası türleri", B: "Fare", C: "Kuş", D: "Yılan" }, dogruCevap: "A" },
    { seviye: 201, kategori: "Canlılar", soru: "Arı kuşu günde yaklaşık kaç böcek yer?", secenekler: { A: "Binlerce", B: "10", C: "100", D: "50" }, dogruCevap: "A" },
    { seviye: 202, kategori: "Canlılar", soru: "Yunuslar neden birbirlerine ıslık çalarlar?", secenekler: { A: "İletişim ve isim niyetine", B: "Korkutmak için", C: "Şarkı söylemek için", D: "Uyumak için" }, dogruCevap: "A" },
    { seviye: 203, kategori: "Canlılar", soru: "Hangi hayvanın kanı şeffaftır?", secenekler: { A: "Çekirge", B: "Kedi", C: "Yılan", D: "Balık" }, dogruCevap: "A" },
    { seviye: 204, kategori: "Canlılar", soru: "Karıncalar uyur mu?", secenekler: { A: "Kısa süreli şekerlemeler yaparlar", B: "Hayır, hiç uyumazlar", C: "Sadece kışın uyurlar", D: "İnsanlar gibi 8 saat uyurlar" }, dogruCevap: "A" },
    { seviye: 205, kategori: "Canlılar", soru: "Hangi hayvanın bakış açısı 360 derecedir?", secenekler: { A: "Bukalemun", B: "Kedi", C: "Baykuş", D: "At" }, dogruCevap: "A" },
    { seviye: 206, kategori: "Canlılar", soru: "Deniz analarının beyni var mıdır?", secenekler: { A: "Hayır", B: "Evet", C: "Sadece büyüklerde", D: "Yarısında vardır" }, dogruCevap: "A" },
    { seviye: 207, kategori: "Canlılar", soru: "Bir tavuğun bilinen en uzun uçuş süresi ne kadardır?", secenekler: { A: "13 saniye", B: "1 dakika", C: "10 dakika", D: "1 saat" }, dogruCevap: "A" },
    { seviye: 208, kategori: "Canlılar", soru: "Hangi hayvanın gözleri kafasından büyüktür?", secenekler: { A: "Deve Kuşu", B: "Sinek", C: "Kedi", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 209, kategori: "Canlılar", soru: "İneklerin kaç tane dişleri vardır?", secenekler: { A: "32", B: "20", C: "10", D: "40" }, dogruCevap: "A" },
    { seviye: 210, kategori: "Canlılar", soru: "Hangi hayvanın grubu 'parlament' olarak adlandırılır?", secenekler: { A: "Baykuşlar", B: "Aslanlar", C: "Kargalar", D: "Filler" }, dogruCevap: "A" },
    { seviye: 211, kategori: "Canlılar", soru: "Su aygırları su altında ne kadar kalabilir?", secenekler: { A: "5 dakika", B: "1 saat", C: "20 dakika", D: "2 dakika" }, dogruCevap: "A" },
    { seviye: 212, kategori: "Canlılar", soru: "Hangi hayvanın kalbi vücuduna göre en büyüğüdür?", secenekler: { A: "Sinek Kuşu", B: "Mavi Balina", C: "Zürafa", D: "Fil" }, dogruCevap: "A" },
    { seviye: 213, kategori: "Canlılar", soru: "Hangi balık türü elektrik üretebilir?", secenekler: { A: "Elektrikli Yılan Balığı", B: "Hamsi", C: "Lüfer", D: "Sazan" }, dogruCevap: "A" },
    { seviye: 214, kategori: "Canlılar", soru: "Kelebeklerin ömrü gerçekten 1 gün müdür?", secenekler: { A: "Hayır, haftalarca hatta aylarca yaşayabilirler", B: "Evet", C: "Sadece bazıları", D: "Sadece kışın" }, dogruCevap: "A" },
    { seviye: 215, kategori: "Canlılar", soru: "Hangi canlı türü kendisini klonlayabilir?", secenekler: { A: "Bazı deniz anası ve kertenkele türleri", B: "Fare", C: "Kuş", D: "Köpek" }, dogruCevap: "A" },
    { seviye: 216, kategori: "Canlılar", soru: "Arılar hangi rengi göremezler?", secenekler: { A: "Kırmızı", B: "Mavi", C: "Sarı", D: "Yeşil" }, dogruCevap: "A" },
    { seviye: 217, kategori: "Canlılar", soru: "Hangi hayvanın kulakları bacaklarındadır?", secenekler: { A: "Çekirge", B: "Örümcek", C: "Karınca", D: "Sinek" }, dogruCevap: "A" },
    { seviye: 218, kategori: "Canlılar", soru: "Zürafalar nasıl ses çıkarırlar?", secenekler: { A: "İnsan kulağının duyamayacağı düşük frekansta", B: "Havlayarak", C: "Miyavlayarak", D: "Kükreyerek" }, dogruCevap: "A" },
    { seviye: 219, kategori: "Canlılar", soru: "Dünyanın en büyük çiçeği hangisidir?", secenekler: { A: "Rafflesia", B: "Gül", C: "Lale", D: "Papatya" }, dogruCevap: "A" },
    { seviye: 220, kategori: "Canlılar", soru: "Hangi ağaç türü binlerce yıl yaşayabilir?", secenekler: { A: "Zeytin ağacı", B: "Kavak", C: "Söğüt", D: "Erik" }, dogruCevap: "A" },
    { seviye: 221, kategori: "Canlılar", soru: "Bambu bir ağaç mıdır ot mudur?", secenekler: { A: "Ot (Buğdaygiller)", B: "Ağaç", C: "Mantar", D: "Çalı" }, dogruCevap: "A" },
    { seviye: 222, kategori: "Canlılar", soru: "Hangi hayvanın kemikleri siyahtır?", secenekler: { A: "Ayam Cemani Tavuğu", B: "Karga", C: "Yarasa", D: "Fare" }, dogruCevap: "A" },
    { seviye: 223, kategori: "Canlılar", soru: "Hangi canlı türü uzay boşluğunda yaşayabilir?", secenekler: { A: "Tardigrat (Su Ayısı)", B: "Hamam Böceği", C: "Bakteri", D: "Virüs" }, dogruCevap: "A" },
    { seviye: 224, kategori: "Canlılar", soru: "Bir ağaçkakan saniyede kaç kez ağaca vurabilir?", secenekler: { A: "20 kez", B: "5 kez", C: "50 kez", D: "100 kez" }, dogruCevap: "A" },
    { seviye: 225, kategori: "Canlılar", soru: "Hangi canlı türü sadece uyurken rüya görmez?", secenekler: { A: "Sürüngenler (çoğunlukla)", B: "Memeliler", C: "Kuşlar", D: "İnsanlar" }, dogruCevap: "A" },
    { seviye: 226, kategori: "Canlılar", soru: "Deniz kaplumbağaları yumurtalarını nereye bırakırlar?", secenekler: { A: "Kuma gömerler", B: "Denize", C: "Kayalıklara", D: "Yuvaya" }, dogruCevap: "A" },
    { seviye: 227, kategori: "Canlılar", soru: "Hangi hayvanın dili bir insan boyundadır?", secenekler: { A: "Mavi Balina", B: "Zürafa", C: "Fil", D: "Dev Karıncayiyen" }, dogruCevap: "A" },
    { seviye: 228, kategori: "Canlılar", soru: "Kangurular neden geri geri yürüyemezler?", secenekler: { A: "Kuyruk ve bacak yapısı nedeniyle", B: "Korktukları için", C: "Çok ağır oldukları için", D: "Gözleri görmediği için" }, dogruCevap: "A" },
    { seviye: 229, kategori: "Canlılar", soru: "Köpek balıkları yüzerken neden ağızlarını açık tutarlar?", secenekler: { A: "Oksijen almak için", B: "Korkutmak için", C: "Yemek yemek için", D: "Uyumak için" }, dogruCevap: "A" },
    { seviye: 230, kategori: "Canlılar", soru: "Hangi hayvanın burnunun izi insanların parmak izi gibi eşsizdir?", secenekler: { A: "Köpek", B: "Kedi", C: "İnek", D: "At" }, dogruCevap: "A" },
    { seviye: 231, kategori: "Canlılar", soru: "Su samurları uyurken neden birbirlerinin elini tutarlar?", secenekler: { A: "Akıntıda sürüklenmemek için", B: "Sevdikleri için", C: "Oyun için", D: "Korktukları için" }, dogruCevap: "A" },
    { seviye: 232, kategori: "Canlılar", soru: "Hangi kuş türü kendi ağırlığının iki katı kadar yemek yiyebilir?", secenekler: { A: "Sinek Kuşu", B: "Kartal", C: "Pelikan", D: "Akbaba" }, dogruCevap: "A" },
    { seviye: 233, kategori: "Canlılar", soru: "Hamsterlar yemeklerini nerede saklarlar?", secenekler: { A: "Yanak keselerinde", B: "Yuvalarında", C: "Toprağın altında", D: "Midelerinde" }, dogruCevap: "A" },
    { seviye: 234, kategori: "Canlılar", soru: "Hangi canlı türü dünyada en çok insana zarar veren canlıdır?", secenekler: { A: "Sivrisinek", B: "Köpek Balığı", C: "Yılan", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 235, kategori: "Canlılar", soru: "Ahtapotların kanı neden mavidir?", secenekler: { A: "Bakır içerdiği için", B: "Demir içerdiği için", C: "Su olduğu için", D: "Mürekkep olduğu için" }, dogruCevap: "A" },
    { seviye: 236, kategori: "Canlılar", soru: "Hangi hayvanın sütü en az yağlıdır?", secenekler: { A: "Eşek", B: "İnek", C: "Manda", D: "Koyun" }, dogruCevap: "A" },
    { seviye: 237, kategori: "Canlılar", soru: "Kediler neden dar yerlerden geçebilirler?", secenekler: { A: "Köprücük kemikleri olmadığı için", B: "Çok esnek oldukları için", C: "Tüyleri sayesinde", D: "Hızlı oldukları için" }, dogruCevap: "A" },
    { seviye: 238, kategori: "Canlılar", soru: "Hangi kuşun yumurtası en küçüktür?", secenekler: { A: "Sinek Kuşu", B: "Serçe", C: "Kanarya", D: "Saka" }, dogruCevap: "A" },
    { seviye: 239, kategori: "Canlılar", soru: "Hangi hayvanın gözbebekleri dikdörtgen şeklindedir?", secenekler: { A: "Keçi", B: "Kedi", C: "Köpek", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 240, kategori: "Canlılar", soru: "Arılar kaç tane göze sahiptir?", secenekler: { A: "5", B: "2", C: "4", D: "10" }, dogruCevap: "A" },
    { seviye: 241, kategori: "Canlılar", soru: "Hangi canlı türü kalbi durunca ölmüş sayılmaz?", secenekler: { A: "Bazı kurbağa türleri (donunca)", B: "Fare", C: "Kuş", D: "Yılan" }, dogruCevap: "A" },
    { seviye: 242, kategori: "Canlılar", soru: "Balinalar uyurken boğulmamak için ne yaparlar?", secenekler: { A: "Beyinlerinin yarısı uyanık kalır", B: "Hiç uyumazlar", C: "Suyun üstünde uyurlar", D: "Nefeslerini tutarlar" }, dogruCevap: "A" },
    { seviye: 243, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile vücut sıcaklıklarını dengelerler?", secenekler: { A: "Köpek", B: "Kedi", C: "At", D: "İnek" }, dogruCevap: "A" },
    { seviye: 244, kategori: "Canlılar", soru: "Hangi böcek türü suyun üstünde yürüyebilir?", secenekler: { A: "Su Örümceği", B: "Sinek", C: "Arı", D: "Karınca" }, dogruCevap: "A" },
    { seviye: 245, kategori: "Canlılar", soru: "Bir istiridye yaklaşık kaç tane inci yapabilir?", secenekler: { A: "Hayatı boyunca çok az (nadirdir)", B: "Binlerce", C: "Yüzlerce", D: "Her gün bir tane" }, dogruCevap: "A" },
    { seviye: 246, kategori: "Canlılar", soru: "Hangi kuş türü sadece pembe yiyecekler yediği için pembedir?", secenekler: { A: "Flamingo", B: "Pelikan", C: "Papağan", D: "Martı" }, dogruCevap: "A" },
    { seviye: 247, kategori: "Canlılar", soru: "Dünyanın en büyük kara memelisi hangisidir?", secenekler: { A: "Afrika Fili", B: "Zürafa", C: "Su Aygırı", D: "Gergedan" }, dogruCevap: "A" },
    { seviye: 248, kategori: "Canlılar", soru: "Hangi canlı türü hem bitki hem hayvan özelliği gösterebilir?", secenekler: { A: "Öglena", B: "Bakteri", C: "Mantar", D: "Virüs" }, dogruCevap: "A" },
    { seviye: 249, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'nehir atı' anlamına gelir?", secenekler: { A: "Su Aygırı", B: "Timsah", C: "Yunus", D: "Fok" }, dogruCevap: "A" }, 

    { seviye: 250, kategori: "Canlılar", soru: "Karıncaların liderine ne ad verilir?", secenekler: { A: "Kraliçe", B: "Kral", C: "Başkan", D: "İşçi" }, dogruCevap: "A" },
    { seviye: 251, kategori: "Canlılar", soru: "Yarasalar hangi canlı grubuna girer?", secenekler: { A: "Memeliler", B: "Kuşlar", C: "Sürüngenler", D: "Böcekler" }, dogruCevap: "A" },
    { seviye: 252, kategori: "Canlılar", soru: "Zürafaların ses telleri var mıdır?", secenekler: { A: "Hayır (Çok zayıftır/yoktur)", B: "Evet", C: "Sadece yavrularında", D: "Sadece erkeklerinde" }, dogruCevap: "A" },
    { seviye: 253, kategori: "Canlılar", soru: "Hangi hayvanın sütü koyu pembe renklidir?", secenekler: { A: "Su Aygırı", B: "Zürafa", C: "Fil", D: "Gergedan" }, dogruCevap: "A" },
    { seviye: 254, kategori: "Canlılar", soru: "Deniz atlarında yavruları hangi ebeveyn taşır?", secenekler: { A: "Erkek", B: "Dişi", C: "İkisi birden", D: "Hiçbiri" }, dogruCevap: "A" },
    { seviye: 255, kategori: "Canlılar", soru: "Hangi kuş türü uçarken uyuyabilir?", secenekler: { A: "Ebabil", B: "Serçe", C: "Güvercin", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 256, kategori: "Canlılar", soru: "Bir ahtapotun kaç tane kalbi vardır?", secenekler: { A: "3", B: "1", C: "2", D: "4" }, dogruCevap: "A" },
    { seviye: 257, kategori: "Canlılar", soru: "Bukalemunlar neden renk değiştirir?", secenekler: { A: "Hepsi (Duygular, sıcaklık, gizlenme)", B: "Sadece gizlenmek için", C: "Sadece korkunca", D: "Sadece uyurken" }, dogruCevap: "A" },
    { seviye: 258, kategori: "Canlılar", soru: "Dünyanın en hızlı balığı hangisidir?", secenekler: { A: "Yelken Balığı", B: "Köpek Balığı", C: "Yunus", D: "Palamut" }, dogruCevap: "A" },
    { seviye: 259, kategori: "Canlılar", soru: "Kutup ayılarının derisi ne renktir?", secenekler: { A: "Siyah", B: "Beyaz", C: "Pembe", D: "Gri" }, dogruCevap: "A" },
    { seviye: 260, kategori: "Canlılar", soru: "Karıncalar kendi ağırlıklarının kaç katını kaldırabilir?", secenekler: { A: "50 kat", B: "10 kat", C: "5 kat", D: "100 kat" }, dogruCevap: "A" },
    { seviye: 261, kategori: "Canlılar", soru: "Kedilerin vücudundaki en esnek yer neresidir?", secenekler: { A: "Omurga", B: "Bacaklar", C: "Kuyruk", D: "Boyun" }, dogruCevap: "A" },
    { seviye: 262, kategori: "Canlılar", soru: "Hangi hayvan su içmeden deveden daha uzun süre yaşayabilir?", secenekler: { A: "Kanguru Faresi", B: "Fil", C: "Zürafa", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 263, kategori: "Canlılar", soru: "Baykuşlar başlarını kaç derece döndürebilir?", secenekler: { A: "270 derece", B: "180 derece", C: "360 derece", D: "90 derece" }, dogruCevap: "A" },
    { seviye: 264, kategori: "Canlılar", soru: "Yılanların koku alma organı hangisidir?", secenekler: { A: "Dili", B: "Burnu", C: "Gözü", D: "Derisi" }, dogruCevap: "A" },
    { seviye: 265, kategori: "Canlılar", soru: "Hangi memeli hayvan yumurtlar?", secenekler: { A: "Ornitorenk", B: "Balina", C: "Yarasa", D: "Kanguru" }, dogruCevap: "A" },
    { seviye: 266, kategori: "Canlılar", soru: "Timsahlar dillerini dışarı çıkarabilir mi?", secenekler: { A: "Hayır", B: "Evet", C: "Sadece yemek yerken", D: "Sadece suda" }, dogruCevap: "A" },
    { seviye: 267, kategori: "Canlılar", soru: "Hangi kuşun gözü beyninden daha büyüktür?", secenekler: { A: "Deve Kuşu", B: "Kartal", C: "Papağan", D: "Baykuş" }, dogruCevap: "A" },
    { seviye: 268, kategori: "Canlılar", soru: "Deniz yıldızlarının kaç beyni vardır?", secenekler: { A: "Beyinleri yoktur", B: "1", C: "5", D: "2" }, dogruCevap: "A" },
    { seviye: 269, kategori: "Canlılar", soru: "Hangi böcek kafası kopsa bile bir hafta yaşayabilir?", secenekler: { A: "Hamam Böceği", B: "Karınca", C: "Sinek", D: "Arı" }, dogruCevap: "A" },
    { seviye: 270, kategori: "Canlılar", soru: "İnsan DNA'sı ile %98 oranında benzerlik gösteren hayvan?", secenekler: { A: "Şempanze", B: "Köpek", C: "Fare", D: "At" }, dogruCevap: "A" },
    { seviye: 271, kategori: "Canlılar", soru: "Mavi balinaların kalbi ne büyüklüktedir?", secenekler: { A: "Küçük bir araba kadar", B: "Futbol topu kadar", C: "İnsan kalbi kadar", D: "Bir kova kadar" }, dogruCevap: "A" },
    { seviye: 272, kategori: "Canlılar", soru: "Arıların kaç gözü vardır?", secenekler: { A: "5", B: "2", C: "4", D: "8" }, dogruCevap: "A" },
    { seviye: 273, kategori: "Canlılar", soru: "Kediler tatlı tadını alabilir mi?", secenekler: { A: "Hayır", B: "Evet", C: "Sadece bazı türler", D: "Sadece yaşlanınca" }, dogruCevap: "A" },
    { seviye: 274, kategori: "Canlılar", soru: "Salyangozlar ne kadar süre uyuyabilir?", secenekler: { A: "3 yıl", B: "3 ay", C: "3 hafta", D: "3 gün" }, dogruCevap: "A" },
    { seviye: 275, kategori: "Canlılar", soru: "Hangi hayvanın parmak izi insanınkine çok benzer?", secenekler: { A: "Koala", B: "Maymun", C: "Ayı", D: "Rakun" }, dogruCevap: "A" },
    { seviye: 276, kategori: "Canlılar", soru: "Zürafalar günde ne kadar uyur?", secenekler: { A: "Yaklaşık 30 dakika", B: "8 saat", C: "12 saat", D: "5 saat" }, dogruCevap: "A" },
    { seviye: 277, kategori: "Canlılar", soru: "Hangi kuş türü geri geri uçabilir?", secenekler: { A: "Sinek Kuşu", B: "Kırlangıç", C: "Serçe", D: "Martı" }, dogruCevap: "A" },
    { seviye: 278, kategori: "Canlılar", soru: "İstakozların kanı ne renktir?", secenekler: { A: "Şeffaf (Oksijen alınca mavi olur)", B: "Kırmızı", C: "Yeşil", D: "Sarı" }, dogruCevap: "A" },
    { seviye: 279, kategori: "Canlılar", soru: "Karideslerin kalbi vücutlarının neresindedir?", secenekler: { A: "Kafasında", B: "Kuyruğunda", C: "Göğsünde", D: "Sırtında" }, dogruCevap: "A" },
    { seviye: 280, kategori: "Canlılar", soru: "Domuzlar fiziksel olarak nereye bakamazlar?", secenekler: { A: "Gökyüzüne", B: "Yere", C: "Arkalarına", D: "Yanlarına" }, dogruCevap: "A" },
    { seviye: 281, kategori: "Canlılar", soru: "Fareler neden sürekli bir şeyleri kemirir?", secenekler: { A: "Dişleri sürekli uzadığı için", B: "Aç oldukları için", C: "Oyun oynamak için", D: "Yuva yapmak için" }, dogruCevap: "A" },
    { seviye: 282, kategori: "Canlılar", soru: "Köpek balıklarının kemiği var mıdır?", secenekler: { A: "Hayır (Kıkırdaktır)", B: "Evet", C: "Sadece kafasında", D: "Sadece yüzgeçlerinde" }, dogruCevap: "A" },
    { seviye: 283, kategori: "Canlılar", soru: "Bir inek ömrü boyunca yaklaşık kaç bardak süt verir?", secenekler: { A: "200.000", B: "10.000", C: "50.000", D: "1.000.000" }, dogruCevap: "A" },
    { seviye: 284, kategori: "Canlılar", soru: "Hangi hayvanın grubu 'parlament' olarak adlandırılır?", secenekler: { A: "Baykuş", B: "Aslan", C: "Karga", D: "Kurt" }, dogruCevap: "A" },
    { seviye: 285, kategori: "Canlılar", soru: "Fillerin hortumunda kaç kemik bulunur?", secenekler: { A: "0 (Sıfır)", B: "10", C: "100", D: "1" }, dogruCevap: "A" },
    { seviye: 286, kategori: "Canlılar", soru: "Pireler kendi boylarının kaç katı uzağa zıplayabilir?", secenekler: { A: "200 kat", B: "10 kat", C: "50 kat", D: "1000 kat" }, dogruCevap: "A" },
    { seviye: 287, kategori: "Canlılar", soru: "Deniz analarının vücudunun yüzde kaçı sudur?", secenekler: { A: "%95", B: "%70", C: "%50", D: "%30" }, dogruCevap: "A" },
    { seviye: 288, kategori: "Canlılar", soru: "Kaplanların derisi de çizgili midir?", secenekler: { A: "Evet", B: "Hayır", C: "Sadece yaşlılarda", D: "Sadece erkeklerde" }, dogruCevap: "A" },
    { seviye: 289, kategori: "Canlılar", soru: "Kelebekler tadı neresiyle alır?", secenekler: { A: "Ayakları", B: "Dili", C: "Anteni", D: "Kanadı" }, dogruCevap: "A" },
    { seviye: 290, kategori: "Canlılar", soru: "Atlar ve fareler kusabilir mi?", secenekler: { A: "Hayır", B: "Evet", C: "Sadece atlar", D: "Sadece fareler" }, dogruCevap: "A" },
    { seviye: 291, kategori: "Canlılar", soru: "Dünyanın en büyük böceği hangisidir?", secenekler: { A: "Golyat Böceği", B: "Hamam Böceği", C: "Karınca", D: "Sinek" }, dogruCevap: "A" },
    { seviye: 292, kategori: "Canlılar", soru: "Penguenler nerede yaşar?", secenekler: { A: "Güney Kutbu", B: "Kuzey Kutbu", C: "Ekvator", D: "Asya" }, dogruCevap: "A" },
    { seviye: 293, kategori: "Canlılar", soru: "Hangi kuş türü kendi yuvasını yapmaz?", secenekler: { A: "Guguk Kuşu", B: "Serçe", C: "Kırlangıç", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 294, kategori: "Canlılar", soru: "Kedilerin bıyıkları ne işe yarar?", secenekler: { A: "Denge ve mesafe ölçümü", B: "Koku alma", C: "Güzellik", D: "Isı ölçümü" }, dogruCevap: "A" },
    { seviye: 295, kategori: "Canlılar", soru: "Balinalar nasıl nefes alır?", secenekler: { A: "Tepelerindeki delikten (Akciğer solunumu)", B: "Solungaçlarıyla", C: "Ağızlarıyla", D: "Derileriyle" }, dogruCevap: "A" },
    { seviye: 296, kategori: "Canlılar", soru: "Bir tavuk yılda yaklaşık kaç yumurta yumurtlar?", secenekler: { A: "250-300", B: "50", C: "100", D: "500" }, dogruCevap: "A" },
    { seviye: 297, kategori: "Canlılar", soru: "Deve hörgüçlerinde ne depolar?", secenekler: { A: "Yağ", B: "Su", C: "Besin", D: "Hava" }, dogruCevap: "A" },
    { seviye: 298, kategori: "Canlılar", soru: "Hangi hayvanın dilleri vücutlarından daha uzundur?", secenekler: { A: "Bukalemun", B: "Zürafa", C: "Fil", D: "Kedi" }, dogruCevap: "A" },
    { seviye: 299, kategori: "Canlılar", soru: "Arılar hangi rengi göremezler?", secenekler: { A: "Kırmızı", B: "Mavi", C: "Sarı", D: "Yeşil" }, dogruCevap: "A" },
    { seviye: 300, kategori: "Canlılar", soru: "Hangi canlı türü sonsuza kadar yaşayabilir (biyolojik olarak)?", secenekler: { A: "Turritopsis dohrnii (Ölümsüz Deniz Anası)", B: "Kaplumbağa", C: "Balina", D: "Fil" }, dogruCevap: "A" },
    { seviye: 301, kategori: "Canlılar", soru: "Köpeklerin koku alma duyusu insandan kaç kat güçlüdür?", secenekler: { A: "10.000 - 100.000 kat", B: "10 kat", C: "100 kat", D: "1000 kat" }, dogruCevap: "A" },
    { seviye: 302, kategori: "Canlılar", soru: "Su aygırları terlediğinde terleri ne renk olur?", secenekler: { A: "Kırmızı", B: "Şeffaf", C: "Mavi", D: "Sarı" }, dogruCevap: "A" },
    { seviye: 303, kategori: "Canlılar", soru: "Hangi hayvanın gözbebekleri dikdörtgendir?", secenekler: { A: "Keçi", B: "Kedi", C: "Baykuş", D: "At" }, dogruCevap: "A" },
    { seviye: 304, kategori: "Canlılar", soru: "Karıncaların akciğerleri var mıdır?", secenekler: { A: "Hayır", B: "Evet", C: "Sadece kraliçede", D: "Yarısında" }, dogruCevap: "A" },
    { seviye: 305, kategori: "Canlılar", soru: "Filler neden hortumlarına su doldurup üzerlerine püskürtür?", secenekler: { A: "Serinlemek için", B: "Oyun için", C: "Temizlenmek için", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 306, kategori: "Canlılar", soru: "Hangi hayvanın kalbi dakikada 1000 kez atabilir?", secenekler: { A: "Sinek Kuşu", B: "Fare", C: "Tavşan", D: "Kedi" }, dogruCevap: "A" },
    { seviye: 307, kategori: "Canlılar", soru: "Aslanlar bir günde kaç saat uyurlar?", secenekler: { A: "16-20 saat", B: "5 saat", C: "10 saat", D: "2 saat" }, dogruCevap: "A" },
    { seviye: 308, kategori: "Canlılar", soru: "Deniz kaplumbağaları yumurtalarını nereye bırakır?", secenekler: { A: "Kumsala", B: "Denize", C: "Kayalıklara", D: "Yuvaya" }, dogruCevap: "A" },
    { seviye: 309, kategori: "Canlılar", soru: "Hangi hayvanın sütü en yağlıdır?", secenekler: { A: "Mavi Balina", B: "İnek", C: "Keçi", D: "Manda" }, dogruCevap: "A" },
    { seviye: 310, kategori: "Canlılar", soru: "Eşek arıları bal yapar mı?", secenekler: { A: "Hayır", B: "Evet", C: "Sadece yazın", D: "Sadece bazı türleri" }, dogruCevap: "A" },
    { seviye: 311, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile kemiklerini bile temizleyebildiği söylenir?", secenekler: { A: "Kaplan", B: "Kedi", C: "Köpek", D: "Ayı" }, dogruCevap: "A" },
    { seviye: 312, kategori: "Canlılar", soru: "Kargalar kaç yıl yaşayabilir?", secenekler: { A: "20-30 yıl (Doğada)", B: "100 yıl", C: "200 yıl", D: "10 yıl" }, dogruCevap: "A" },
    { seviye: 313, kategori: "Canlılar", soru: "Hamsterlar yemeklerini nerede taşır?", secenekler: { A: "Yanaklarında", B: "Midelerinde", C: "Ellerinde", D: "Sırtlarında" }, dogruCevap: "A" },
    { seviye: 314, kategori: "Canlılar", soru: "Hangi kuşun kanat çırpışı duyulmaz?", secenekler: { A: "Baykuş", B: "Kartal", C: "Serçe", D: "Atmaca" }, dogruCevap: "A" },
    { seviye: 315, kategori: "Canlılar", soru: "Yılanların göz kapakları var mıdır?", secenekler: { A: "Hayır", B: "Evet", C: "Sadece bazı türlerde", D: "Sadece uyurken" }, dogruCevap: "A" },
    { seviye: 316, kategori: "Canlılar", soru: "Bir salyangozun kaç tane dişi olabilir?", secenekler: { A: "Binlerce (Radula üzerinde)", B: "0", C: "4", D: "32" }, dogruCevap: "A" },
    { seviye: 317, kategori: "Canlılar", soru: "Hangi hayvanın ter bezleri sadece ayaklarındadır?", secenekler: { A: "Köpek", B: "At", C: "İnsan", D: "Fil" }, dogruCevap: "A" },
    { seviye: 318, kategori: "Canlılar", soru: "Deniz yıldızları kollarını yenileyebilir mi?", secenekler: { A: "Evet", B: "Hayır", C: "Sadece bir kez", D: "Yıllar sürer" }, dogruCevap: "A" },
    { seviye: 319, kategori: "Canlılar", soru: "Arılar birbirlerine yemeğin yerini nasıl söyler?", secenekler: { A: "Dans ederek", B: "Ses çıkararak", C: "Dokunarak", D: "Renk değiştirerek" }, dogruCevap: "A" },
    { seviye: 320, kategori: "Canlılar", soru: "Mavi balinaların dili ne kadar ağırdır?", secenekler: { A: "Bir fil kadar", B: "Bir insan kadar", C: "100 kg", D: "Bir ton" }, dogruCevap: "A" },
    { seviye: 321, kategori: "Canlılar", soru: "Hangi hayvanın dilleri vücut sıcaklığını ayarlamaya yardımcı olur?", secenekler: { A: "Köpek", B: "Kedi", C: "Kuş", D: "Yılan" }, dogruCevap: "A" },
    { seviye: 322, kategori: "Canlılar", soru: "Iskozlar kaç yıl yaşayabilir?", secenekler: { A: "100 yıla kadar", B: "5 yıl", C: "10 yıl", D: "20 yıl" }, dogruCevap: "A" },
    { seviye: 323, kategori: "Canlılar", soru: "Hangi kuş türü penguenler gibi uçamaz?", secenekler: { A: "Deve Kuşu", B: "Albatros", C: "Pelikan", D: "Martı" }, dogruCevap: "A" },
    { seviye: 324, kategori: "Canlılar", soru: "Kelebeklerin kaç kanadı vardır?", secenekler: { A: "4", B: "2", C: "6", D: "8" }, dogruCevap: "A" },
    { seviye: 325, kategori: "Canlılar", soru: "Hangi hayvanın ismi Türkçede 'nehir atı' anlamına gelir?", secenekler: { A: "Su Aygırı", B: "Timsah", C: "Fok", D: "Denizatı" }, dogruCevap: "A" },
    { seviye: 326, kategori: "Canlılar", soru: "Karıncalar kışın ne yapar?", secenekler: { A: "Yerin altında kış uykusuna benzer bir döneme girer", B: "Ölürler", C: "Sıcak yerlere göç ederler", D: "Aynı şekilde çalışırlar" }, dogruCevap: "A" },
    { seviye: 327, kategori: "Canlılar", soru: "Hangi canlı türü ışık üretebilir (Biyolüminesans)?", secenekler: { A: "Ateş Böceği", B: "Sinek", C: "Arı", D: "Karınca" }, dogruCevap: "A" },
    { seviye: 328, kategori: "Canlılar", soru: "Filler birbirleriyle nasıl iletişim kurar?", secenekler: { A: "Düşük frekanslı sesler ve ayak sarsıntılarıyla", B: "Sadece bağırarak", C: "Dokunarak", D: "İletişim kurmazlar" }, dogruCevap: "A" },
    { seviye: 329, kategori: "Canlılar", soru: "Hangi hayvanın gözleri kafasının arkasını görebilir?", secenekler: { A: "Tavşan", B: "Kedi", C: "Köpek", D: "Kuş" }, dogruCevap: "A" },
    { seviye: 330, kategori: "Canlılar", soru: "Yunuslar uyurken neden bir gözleri açık kalır?", secenekler: { A: "Beyinlerinin yarısı uyanık kaldığı için", B: "Korktukları için", C: "Işığı sevdikleri için", D: "Yüzmek için" }, dogruCevap: "A" },
    { seviye: 331, kategori: "Canlılar", soru: "Hangi bitki böcek yiyerek beslenir?", secenekler: { A: "Venüs Sinek Kapanı", B: "Gül", C: "Papatya", D: "Kaktüs" }, dogruCevap: "A" },
    { seviye: 332, kategori: "Canlılar", soru: "Bambu ağacı günde ne kadar uzayabilir?", secenekler: { A: "90 cm'ye kadar", B: "1 cm", C: "10 cm", D: "5 metre" }, dogruCevap: "A" },
    { seviye: 333, kategori: "Canlılar", soru: "Hangi hayvanın dilleri mavidir?", secenekler: { A: "Zürafa", B: "Fil", C: "Aslan", D: "Köpek" }, dogruCevap: "A" },
    { seviye: 334, kategori: "Canlılar", soru: "Denizatı yavruları neye benzer?", secenekler: { A: "Yetişkinlerin minyatür haline", B: "Larvaya", C: "Balığa", D: "Yumurta sarısına" }, dogruCevap: "A" },
    { seviye: 335, kategori: "Canlılar", soru: "Hangi hayvanın kemikleri derisinin dışındadır?", secenekler: { A: "Kaplumbağa (Kabuk)", B: "Yılan", C: "Kertenkele", D: "Balık" }, dogruCevap: "A" },
    { seviye: 336, kategori: "Canlılar", soru: "Su samurları neden el ele tutuşur?", secenekler: { A: "Akıntıda ayrılmamak için", B: "Sevdikleri için", C: "Isınmak için", D: "Oyun için" }, dogruCevap: "A" },
    { seviye: 337, kategori: "Canlılar", soru: "Hangi kuş türü dünyanın en küçük kuşudur?", secenekler: { A: "Arı Sinek Kuşu", B: "Serçe", C: "Kanarya", D: "Saka" }, dogruCevap: "A" },
    { seviye: 338, kategori: "Canlılar", soru: "Yarasalar karanlıkta yollarını nasıl bulur?", secenekler: { A: "Ses dalgalarıyla (Ekolokasyon)", B: "Gözleriyle", C: "Kokuyla", D: "Isıyla" }, dogruCevap: "A" },
    { seviye: 339, kategori: "Canlılar", soru: "Hangi hayvanın kalbi kafasındadır?", secenekler: { A: "Karides", B: "Yengeç", C: "Istakoz", D: "Deniz Yıldızı" }, dogruCevap: "A" },
    { seviye: 340, kategori: "Canlılar", soru: "Deve kuşları tehlike anında kafalarını kuma gömerler mi?", secenekler: { A: "Hayır (Bu bir efsanedir)", B: "Evet", C: "Sadece yavrular", D: "Sadece uyurken" }, dogruCevap: "A" },
    { seviye: 341, kategori: "Canlılar", soru: "Hangi hayvanın dilleri bir insan vücudu kadar uzundur?", secenekler: { A: "Mavi Balina", B: "Zürafa", C: "Fil", D: "Dev Karıncayiyen" }, dogruCevap: "A" },
    { seviye: 342, kategori: "Canlılar", soru: "Kediler ne kadar yükseğe zıplayabilir?", secenekler: { A: "Boylarının 6 katına kadar", B: "1 metre", C: "Boyları kadar", D: "20 katına kadar" }, dogruCevap: "A" },
    { seviye: 343, kategori: "Canlılar", soru: "Hangi balık türü suyun dışında yaşayabilir?", secenekler: { A: "Akciğerli Balık", B: "Sazan", C: "Lüfer", D: "Hamsi" }, dogruCevap: "A" },
    { seviye: 344, kategori: "Canlılar", soru: "İpek böceği ne yer?", secenekler: { A: "Dut yaprağı", B: "Elma", C: "Ot", D: "Çiçek" }, dogruCevap: "A" },
    { seviye: 345, kategori: "Canlılar", soru: "Hangi hayvanın dilleri pütürlüdür ve zımpara gibidir?", secenekler: { A: "Kedi", B: "Köpek", C: "At", D: "İnek" }, dogruCevap: "A" },
    { seviye: 346, kategori: "Canlılar", soru: "Penguenler neden üşümez?", secenekler: { A: "Kalın yağ tabakası ve su geçirmez tüyleri sayesinde", B: "Sıcak kanlı oldukları için", C: "Tüyleri olmadığı için", D: "Sürekli hareket ettikleri için" }, dogruCevap: "A" },
    { seviye: 347, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'nehir ayısı' anlamına gelebilir?", secenekler: { A: "Su Aygırı (Bazı dillerde)", B: "Timsah", C: "Fok", D: "Kunduz" }, dogruCevap: "A" },
    { seviye: 348, kategori: "Canlılar", soru: "Kutup ayıları nerede yaşar?", secenekler: { A: "Kuzey Kutbu", B: "Güney Kutbu", C: "İzlanda", D: "Norveç" }, dogruCevap: "A" },
    { seviye: 349, kategori: "Canlılar", soru: "Hangi kuş türü en büyük yumurtaya sahiptir?", secenekler: { A: "Deve Kuşu", B: "Albatros", C: "Kartal", D: "Pelikan" }, dogruCevap: "A" },
    { seviye: 350, kategori: "Canlılar", soru: "Arıların kaç kanadı vardır?", secenekler: { A: "4", B: "2", C: "6", D: "0" }, dogruCevap: "A" },
    { seviye: 351, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile kulaklarını temizleyebildiği söylenir?", secenekler: { A: "Zürafa", B: "Kedi", C: "Köpek", D: "Fil" }, dogruCevap: "A" },
    { seviye: 352, kategori: "Canlılar", soru: "Yılanların dilleri neden çatallıdır?", secenekler: { A: "Daha iyi koku ve yön tayini için", B: "Daha iyi yemek yemek için", C: "Korkutmak için", D: "Ses çıkarmak için" }, dogruCevap: "A" },
    { seviye: 353, kategori: "Canlılar", soru: "Hangi canlı türü kendi ağırlığının 850 katını kaldırabilir?", secenekler: { A: "Gergedan Böceği", B: "Karınca", C: "Fil", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 354, kategori: "Canlılar", soru: "Hangi hayvanın midesi yoktur?", secenekler: { A: "Denizatı", B: "İnek", C: "Kedi", D: "Köpek" }, dogruCevap: "A" },
    { seviye: 355, kategori: "Canlılar", soru: "Kediler hayatlarının ne kadarını uyuyarak geçirir?", secenekler: { A: "%70", B: "%20", C: "%50", D: "%90" }, dogruCevap: "A" },
    { seviye: 356, kategori: "Canlılar", soru: "Hangi kuş türü kışın güneye göç etmez?", secenekler: { A: "Serçe", B: "Leylek", C: "Kırlangıç", D: "Turna" }, dogruCevap: "A" },
    { seviye: 357, kategori: "Canlılar", soru: "Balıkların göz kapakları var mıdır?", secenekler: { A: "Hayır", B: "Evet", C: "Sadece köpek balıklarında", D: "Sadece büyüklerde" }, dogruCevap: "A" },
    { seviye: 358, kategori: "Canlılar", soru: "Hangi hayvanın kalbi vücuduna göre en büyüğüdür?", secenekler: { A: "Sinek Kuşu", B: "Mavi Balina", C: "Fil", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 359, kategori: "Canlılar", soru: "Filler neden büyük kulaklara sahiptir?", secenekler: { A: "Vücut sıcaklığını dengelemek için", B: "Daha iyi duymak için", C: "Sinekleri kovmak için", D: "Uçmak için" }, dogruCevap: "A" },
    { seviye: 360, kategori: "Canlılar", soru: "Hangi hayvanın gözleri dilediği yöne bağımsız hareket eder?", secenekler: { A: "Bukalemun", B: "Baykuş", C: "Kedi", D: "At" }, dogruCevap: "A" },
    { seviye: 361, kategori: "Canlılar", soru: "Arı kuşu saniyede kaç kez kanat çırpar?", secenekler: { A: "80 kez", B: "10 kez", C: "20 kez", D: "200 kez" }, dogruCevap: "A" },
    { seviye: 362, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile tat alması imkansızdır?", secenekler: { A: "Timsah", B: "Kedi", C: "Kuş", D: "Yılan" }, dogruCevap: "A" },
    { seviye: 363, kategori: "Canlılar", soru: "Kargalar neden parlak nesneleri toplar?", secenekler: { A: "Yuva yapmak veya ilgi çekmek için", B: "Yemek sanırlar", C: "Uğur getirdiğine inanırlar", D: "Sadece oyun" }, dogruCevap: "A" },
    { seviye: 364, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'su domuzu' anlamına gelir?", secenekler: { A: "Kapibara", B: "Su Aygırı", C: "Fok", D: "Mors" }, dogruCevap: "A" },
    { seviye: 365, kategori: "Canlılar", soru: "Kedilerin kaç tane dişi vardır?", secenekler: { A: "30", B: "32", C: "20", D: "40" }, dogruCevap: "A" },
    { seviye: 366, kategori: "Canlılar", soru: "Hangi kuş türü en uzun süre havada kalabilir?", secenekler: { A: "Albatros", B: "Serçe", C: "Güvercin", D: "Kırlangıç" }, dogruCevap: "A" },
    { seviye: 367, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile ağaçları devirebildiği söylenir?", secenekler: { A: "Fil (Hortumuyla)", B: "Zürafa", C: "Aslan", D: "Ayı" }, dogruCevap: "A" },
    { seviye: 368, kategori: "Canlılar", soru: "Hangi canlı türü ışığa doğru uçar?", secenekler: { A: "Pervane Böceği", B: "Arı", C: "Karınca", D: "Sinek" }, dogruCevap: "A" },
    { seviye: 369, kategori: "Canlılar", soru: "Yılanların dilleri neden ıslaktır?", secenekler: { A: "Havadaki parçacıkları toplamak için", B: "Su içmek için", C: "Yemek yemek için", D: "Sıcak oldukları için" }, dogruCevap: "A" },
    { seviye: 370, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile kendisini temizlediği görülür?", secenekler: { A: "Kedi", B: "Fil", C: "Zürafa", D: "Kuş" }, dogruCevap: "A" },
    { seviye: 371, kategori: "Canlılar", soru: "Köpek balıkları kaç yıl yaşayabilir?", secenekler: { A: "Türe göre 20-400 yıl", B: "10 yıl", C: "50 yıl", D: "100 yıl" }, dogruCevap: "A" },
    { seviye: 372, kategori: "Canlılar", soru: "Hangi kuş türü şarkı söylemesiyle ünlüdür?", secenekler: { A: "Bülbül", B: "Karga", C: "Martı", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 373, kategori: "Canlılar", soru: "Arıların bal yapma amacı nedir?", secenekler: { A: "Kışın beslenmek için", B: "İnsanlar için", C: "Oyun için", D: "Yuva yapmak için" }, dogruCevap: "A" },
    { seviye: 374, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile yönünü bulduğu söylenir?", secenekler: { A: "Yılan", B: "Kedi", C: "Köpek", D: "Kuş" }, dogruCevap: "A" },
    { seviye: 375, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'yavaş yürüyen' anlamına gelir?", secenekler: { A: "Tembel Hayvan", B: "Kaplumbağa", C: "Salyangoz", D: "Koala" }, dogruCevap: "A" },
    { seviye: 376, kategori: "Canlılar", soru: "Kedilerin kuyruğu ne işe yarar?", secenekler: { A: "Denge sağlamaya", B: "Süs olarak", C: "Koku almaya", D: "Isınmaya" }, dogruCevap: "A" },
    { seviye: 377, kategori: "Canlılar", soru: "Hangi kuş türü postacılıkta kullanılmıştır?", secenekler: { A: "Güvercin", B: "Serçe", C: "Karga", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 378, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile ağaç kabuklarını soyduğu söylenir?", secenekler: { A: "Zürafa", B: "Fil", C: "Aslan", D: "Ayı" }, dogruCevap: "A" },
    { seviye: 379, kategori: "Canlılar", soru: "Arılar nasıl vızıldar?", secenekler: { A: "Kanatlarını çok hızlı çırparak", B: "Ağızlarıyla", C: "Ayaklarını sürterek", D: "Burnuyla" }, dogruCevap: "A" },
    { seviye: 380, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile yarasaları yakaladığı söylenir?", secenekler: { A: "Yılan", B: "Kedi", C: "Kuş", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 381, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'orman adamı' anlamına gelir?", secenekler: { A: "Orangutan", B: "Goril", C: "Şempanze", D: "Maymun" }, dogruCevap: "A" },
    { seviye: 382, kategori: "Canlılar", soru: "Kediler neden mırlar?", secenekler: { A: "Hepsi (Mutluluk, iyileşme, stres)", B: "Sadece mutlu olduklarında", C: "Sadece aç olduklarında", D: "Sadece korkunca" }, dogruCevap: "A" },
    { seviye: 383, kategori: "Canlılar", soru: "Hangi kuş türü renkli tüyleriyle ünlüdür?", secenekler: { A: "Papağan", B: "Karga", C: "Serçe", D: "Güvercin" }, dogruCevap: "A" },
    { seviye: 384, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile çiçek özlerini topladığı söylenir?", secenekler: { A: "Arı (Hortumuyla)", B: "Kuş", C: "Kelebek", D: "Sinek" }, dogruCevap: "A" },
    { seviye: 385, kategori: "Canlılar", soru: "Arıların zehri ne işe yarar?", secenekler: { A: "Kendilerini korumaya", B: "Beslenmeye", C: "Bal yapmaya", D: "Oyun oynamaya" }, dogruCevap: "A" },
    { seviye: 386, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile ağaçları oyduğu söylenir?", secenekler: { A: "Ağaçkakan (Gagasıyla)", B: "Zürafa", C: "Fil", D: "Ayı" }, dogruCevap: "A" },
    { seviye: 387, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'dik diken' anlamına gelebilir?", secenekler: { A: "Kirpi", B: "Domuz", C: "Fare", D: "Kedi" }, dogruCevap: "A" },
    { seviye: 388, kategori: "Canlılar", soru: "Kediler neden yüksekten düşerken dört ayak üstüne düşer?", secenekler: { A: "Doğrulma refleksi sayesinde", B: "Şanslı oldukları için", C: "Hafif oldukları için", D: "Uçabildikleri için" }, dogruCevap: "A" },
    { seviye: 389, kategori: "Canlılar", soru: "Hangi kuş türü suyun altına dalarak balık yakalar?", secenekler: { A: "Karabatak", B: "Serçe", C: "Güvercin", D: "Karga" }, dogruCevap: "A" },
    { seviye: 390, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile yavrularını taşıdığı söylenir?", secenekler: { A: "Timsah", B: "Kedi", C: "Aslan", D: "Ayı" }, dogruCevap: "A" },
    { seviye: 391, kategori: "Canlılar", soru: "Arılar kaç rekat... (Şaka: Arılar kaç kanatlıdır?)", secenekler: { A: "4", B: "2", C: "6", D: "0" }, dogruCevap: "A" },
    { seviye: 392, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile avını yakaladığı söylenir?", secenekler: { A: "Kurbağa", B: "Zürafa", C: "Fil", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 393, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'çöl gemisi'dir?", secenekler: { A: "Deve", B: "At", C: "Eşek", D: "Fil" }, dogruCevap: "A" },
    { seviye: 394, kategori: "Canlılar", soru: "Kediler neden gece daha iyi görür?", secenekler: { A: "Gözlerindeki özel tabaka (Tapetum lucidum) sayesinde", B: "Gözleri büyük olduğu için", C: "Gözleri parladığı için", D: "Gece yaşadıkları için" }, dogruCevap: "A" },
    { seviye: 395, kategori: "Canlılar", soru: "Hangi kuş türü çok uzak mesafelerden göç eder?", secenekler: { A: "Kuzey Sumrusu", B: "Serçe", C: "Güvercin", D: "Karga" }, dogruCevap: "A" },
    { seviye: 396, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile termitleri topladığı söylenir?", secenekler: { A: "Karıncayiyen", B: "Zürafa", C: "Fil", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 397, kategori: "Canlılar", soru: "Arılar nasıl bal yapar?", secenekler: { A: "Çiçek özlerini toplayıp mide enzimleriyle karıştırarak", B: "Çiçekleri yiyerek", C: "Su içerek", D: "Toprakla" }, dogruCevap: "A" },
    { seviye: 398, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile buzları yaladığı söylenir?", secenekler: { A: "Kutup Ayısı", B: "Zürafa", C: "Fil", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 399, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'deniz aslanı'dır?", secenekler: { A: "Deniz Aslanı", B: "Fok", C: "Mors", D: "Balina" }, dogruCevap: "A" },
    { seviye: 400, kategori: "Canlılar", soru: "Hangi kuş türü 'orman doktoru' olarak bilinir?", secenekler: { A: "Ağaçkakan", B: "Baykuş", C: "Kartal", D: "Serçe" }, dogruCevap: "A" },
    { seviye: 401, kategori: "Canlılar", soru: "Karıncalar koku almak için hangi organlarını kullanırlar?", secenekler: { A: "Antenlerini", B: "Bacaklarını", C: "Gözlerini", D: "Ağızlarını" }, dogruCevap: "A" },
    { seviye: 402, kategori: "Canlılar", soru: "Vücudunda kemik yerine sadece kıkırdak bulunan dev deniz canlısı?", secenekler: { A: "Balina Köpekbalığı", B: "Mavi Balina", C: "Yunus", D: "Kılıç Balığı" }, dogruCevap: "A" },
    { seviye: 403, kategori: "Canlılar", soru: "Hangi hayvanın dilleri mor veya mavimsi bir renktedir?", secenekler: { A: "Zürafa", B: "Fil", C: "Kaplan", D: "Su Aygırı" }, dogruCevap: "A" },
    { seviye: 404, kategori: "Canlılar", soru: "Gözleri vücuduna oranla en büyük olan memeli hangisidir?", secenekler: { A: "Tarsier (Uzun bacaklı makak)", B: "Kedi", C: "Fare", D: "Tavşan" }, dogruCevap: "A" },
    { seviye: 405, kategori: "Canlılar", soru: "Hangi hayvanın sütünün rengi parlak pembedir?", secenekler: { A: "Su Aygırı", B: "Zebra", C: "Gergedan", D: "Zürafa" }, dogruCevap: "A" },
    { seviye: 406, kategori: "Canlılar", soru: "Ahtapotların kaç tane beyni vardır?", secenekler: { A: "9", B: "1", C: "3", D: "5" }, dogruCevap: "A" },
    { seviye: 407, kategori: "Canlılar", soru: "Bitkilerin terleme yaptığı gözeneklere ne ad verilir?", secenekler: { A: "Stoma", B: "Kloroplast", C: "Koful", D: "Hücre Çeperi" }, dogruCevap: "A" },
    { seviye: 408, kategori: "Canlılar", soru: "Hangi canlı türü su altında en uzun süre nefes almadan kalabilir?", secenekler: { A: "İspermeçet Balinası", B: "Yunus", C: "Fok", D: "Deniz Kaplumbağası" }, dogruCevap: "A" },
    { seviye: 409, kategori: "Canlılar", soru: "Yılanların göz kapakları olmadığı için gözlerini ne korur?", secenekler: { A: "Şeffaf bir tabaka (Pul)", B: "Gözlük", C: "Tüyler", D: "Hiçbir şey" }, dogruCevap: "A" },
    { seviye: 410, kategori: "Canlılar", soru: "Bir bal arısı hayatı boyunca ne kadar bal üretebilir?", secenekler: { A: "Bir çay kaşığının 12'de biri kadar", B: "Bir kilo", C: "Bir kavanoz", D: "Bir yemek kaşığı" }, dogruCevap: "A" },
    { seviye: 411, kategori: "Canlılar", soru: "Hangi kuşun kanat açıklığı 3.5 metreyi bulabilir?", secenekler: { A: "Albatros", B: "Kartal", C: "Akbaba", D: "Leylek" }, dogruCevap: "A" },
    { seviye: 412, kategori: "Canlılar", soru: "Karasineklerin kaç tane gözü vardır?", secenekler: { A: "Yaklaşık 4000 (Petek göz)", B: "2", C: "4", D: "10" }, dogruCevap: "A" },
    { seviye: 413, kategori: "Canlılar", soru: "Hangi hayvanın dilleri kaba bir zımpara kağıdı gibidir?", secenekler: { A: "Kaplan", B: "Köpek", C: "At", D: "İnek" }, dogruCevap: "A" },
    { seviye: 414, kategori: "Canlılar", soru: "Denizatı hangi balık sınıfına girer?", secenekler: { A: "Kemikli Balıklar", B: "Memeliler", C: "Sürüngenler", D: "Yumuşakçalar" }, dogruCevap: "A" },
    { seviye: 415, kategori: "Canlılar", soru: "Dünyanın en zehirli deniz canlısı hangisidir?", secenekler: { A: "Kutu Deniz Anası", B: "Ahtapot", C: "Mürekkep Balığı", D: "Köpekbalığı" }, dogruCevap: "A" },
    { seviye: 416, kategori: "Canlılar", soru: "Kelebekler kışın ne yapar?", secenekler: { A: "Türüne göre göç eder veya kış uykusuna yatar", B: "Hepsi ölür", C: "Suda yaşarlar", D: "Besin toplarlar" }, dogruCevap: "A" },
    { seviye: 417, kategori: "Canlılar", soru: "Hangi kuş türü suda yürüyormuş gibi görünür?", secenekler: { A: "Jakana", B: "Ördek", C: "Kuğu", D: "Pelikan" }, dogruCevap: "A" },
    { seviye: 418, kategori: "Canlılar", soru: "Hangi canlı türü sadece okaliptüs yapraklarıyla beslenir?", secenekler: { A: "Koala", B: "Panda", C: "Kanguru", D: "Maymun" }, dogruCevap: "A" },
    { seviye: 419, kategori: "Canlılar", soru: "Tarantulalar tehlike anında ne yaparlar?", secenekler: { A: "Karınlarındaki tüyleri fırlatırlar", B: "Uçarlar", C: "Renk değiştirirler", D: "Ölü taklidi yaparlar" }, dogruCevap: "A" },
    { seviye: 420, kategori: "Canlılar", soru: "Arıların kaç kanadı vardır?", secenekler: { A: "4", B: "2", C: "6", D: "0" }, dogruCevap: "A" },
    { seviye: 421, kategori: "Canlılar", soru: "Fillerin hortumu kaç litre su alabilir?", secenekler: { A: "8-10 Litre", B: "1 Litre", C: "50 Litre", D: "100 Litre" }, dogruCevap: "A" },
    { seviye: 422, kategori: "Canlılar", soru: "Hangi kuşun gagası vücudundan daha uzun olabilir?", secenekler: { A: "Kılıç Gagalı Sinek Kuşu", B: "Pelikan", C: "Tukan", D: "Leylek" }, dogruCevap: "A" },
    { seviye: 423, kategori: "Canlılar", soru: "Köpeklerin burun izi neye benzer?", secenekler: { A: "İnsan parmak izi gibi eşsizdir", B: "Hepsi aynıdır", C: "Yaşlandıkça silinir", D: "Tüylüdür" }, dogruCevap: "A" },
    { seviye: 424, kategori: "Canlılar", soru: "Yarasalar neden baş aşağı uyurlar?", secenekler: { A: "Hafif kemikleri uçmaya daha kolay başlamak içindir", B: "Öyle sevdikleri için", C: "Düşmanları göremesin diye", D: "Kan akışı için" }, dogruCevap: "A" },
    { seviye: 425, kategori: "Canlılar", soru: "Hangi canlı türünün kanı yeşildir?", secenekler: { A: "Bazı kertenkele türleri", B: "Fare", C: "Tavşan", D: "Kuş" }, dogruCevap: "A" },
    { seviye: 426, kategori: "Canlılar", soru: "Zürafaların boyunlarındaki kemik sayısı kaçtır?", secenekler: { A: "7 (İnsanla aynı)", B: "20", C: "50", D: "100" }, dogruCevap: "A" },
    { seviye: 427, kategori: "Canlılar", soru: "Ateş böcekleri neden ışık yayarlar?", secenekler: { A: "Eş bulmak ve iletişim için", B: "Yolunu bulmak için", C: "Isınmak için", D: "Korkutmak için" }, dogruCevap: "A" },
    { seviye: 428, kategori: "Canlılar", soru: "Hangi balık türü geri geri yüzebilir?", secenekler: { A: "Tetik Balığı", B: "Hamsi", C: "Lüfer", D: "Sazan" }, dogruCevap: "A" },
    { seviye: 429, kategori: "Canlılar", soru: "Baykuşların kulakları neden asimetriktir?", secenekler: { A: "Sesin kaynağını tam bulmak için", B: "Doğuştan hatadır", C: "Daha iyi duymak için", D: "Rüzgarı engellemek için" }, dogruCevap: "A" },
    { seviye: 430, kategori: "Canlılar", soru: "Karıncaların ortalama ömrü ne kadardır?", secenekler: { A: "İşçiler birkaç ay, kraliçeler yıllarca", B: "1 gün", C: "100 yıl", D: "10 yıl" }, dogruCevap: "A" },
    { seviye: 431, kategori: "Canlılar", soru: "Penguenlerin sadece neresi tüysüzdür?", secenekler: { A: "Ayakları ve gagasının bir kısmı", B: "Kanatları", C: "Sırtı", D: "Karnı" }, dogruCevap: "A" },
    { seviye: 432, kategori: "Canlılar", soru: "Hangi hayvanın dilleri boyundan daha uzundur?", secenekler: { A: "Bukalemun", B: "Kedi", C: "Fare", D: "Köpek" }, dogruCevap: "A" },
    { seviye: 433, kategori: "Canlılar", soru: "Mavi balinalar günde kaç ton karides benzeri canlı (krill) yer?", secenekler: { A: "4 Ton", B: "100 Kilo", C: "10 Ton", D: "1 Ton" }, dogruCevap: "A" },
    { seviye: 434, kategori: "Canlılar", soru: "Bukalemunların dilleri avına ne kadar sürede ulaşır?", secenekler: { A: "Saniyenin 1/16'sında", B: "5 saniyede", C: "1 saniyede", D: "10 saniyede" }, dogruCevap: "A" },
    { seviye: 435, kategori: "Canlılar", soru: "Hangi kuş türü yuvasını çamurdan yapar?", secenekler: { A: "Kırlangıç", B: "Serçe", C: "Karga", D: "Güvercin" }, dogruCevap: "A" },
    { seviye: 436, kategori: "Canlılar", soru: "Balinalar neden suyun üzerine fırlarlar?", secenekler: { A: "Hepsi (Parazit dökmek, iletişim, oyun)", B: "Sadece oyun", C: "Sadece nefes almak", D: "Yıkanmak için" }, dogruCevap: "A" },
    { seviye: 437, kategori: "Canlılar", soru: "Deve kuşları saatte kaç km hızla koşabilir?", secenekler: { A: "70 km", B: "20 km", C: "40 km", D: "120 km" }, dogruCevap: "A" },
    { seviye: 438, kategori: "Canlılar", soru: "Bir ipek böceği kozasını örmek için ne kadar ip üretir?", secenekler: { A: "900 metre", B: "10 metre", C: "100 metre", D: "5 km" }, dogruCevap: "A" },
    { seviye: 439, kategori: "Canlılar", soru: "Hangi hayvanın dişleri kemikten değil, fildişinden oluşur?", secenekler: { A: "Fil", B: "Gergedan", C: "Aslan", D: "Ayı" }, dogruCevap: "A" },
    { seviye: 440, kategori: "Canlılar", soru: "Kedilerin kulaklarında kaç adet kas bulunur?", secenekler: { A: "32", B: "2", C: "10", D: "100" }, dogruCevap: "A" },
    { seviye: 441, kategori: "Canlılar", soru: "Hangi canlı türü dilleri ile su içmez, suyu derisiyle emer?", secenekler: { A: "Kurbağa", B: "Yılan", C: "Kertenkele", D: "Kuş" }, dogruCevap: "A" },
    { seviye: 442, kategori: "Canlılar", soru: "Hamam böcekleri radyasyona ne kadar dayanıklıdır?", secenekler: { A: "İnsandan 15 kat daha fazla", B: "Dayanıksızdır", C: "Hiç etkilenmez", D: "Sadece sıcakta dayanır" }, dogruCevap: "A" },
    { seviye: 443, kategori: "Canlılar", soru: "Hangi hayvanın gözleri beyninden daha ağırdır?", secenekler: { A: "Deve Kuşu", B: "Baykuş", C: "Kartal", D: "Dev Mürekkep Balığı" }, dogruCevap: "A" },
    { seviye: 444, kategori: "Canlılar", soru: "Yengeçler neden yan yürürler?", secenekler: { A: "Bacak eklemleri o yöne büküldüğü için", B: "Öyle sevdikleri için", C: "Daha hızlı gitmek için", D: "Dengede kalmak için" }, dogruCevap: "A" },
    { seviye: 445, kategori: "Canlılar", soru: "Hangi kuş türü havada asılı kalabilir?", secenekler: { A: "Sinek Kuşu", B: "Atmaca", C: "Kırlangıç", D: "Serçe" }, dogruCevap: "A" },
    { seviye: 446, kategori: "Canlılar", soru: "Karıncaların akciğerleri var mıdır?", secenekler: { A: "Hayır, vücutlarındaki deliklerden nefes alırlar", B: "Evet", C: "Sadece su altındayken", D: "Büyüyünce oluşur" }, dogruCevap: "A" },
    { seviye: 447, kategori: "Canlılar", soru: "Hangi canlı türü kendisini iyileştirmek için bitkileri kullanır?", secenekler: { A: "Şempanzeler", B: "Kediler", C: "Köpekler", D: "Kuşlar" }, dogruCevap: "A" },
    { seviye: 448, kategori: "Canlılar", soru: "Ahtapotlar kaç tane kalbe sahiptir?", secenekler: { A: "3", B: "1", C: "2", D: "5" }, dogruCevap: "A" },
    { seviye: 449, kategori: "Canlılar", soru: "Hangi balık türü yumurtalarını ağzında taşır?", secenekler: { A: "Ciklet Balığı", B: "Hamsi", C: "Palamut", D: "Sazan" }, dogruCevap: "A" },
    { seviye: 450, kategori: "Canlılar", soru: "Deniz kaplumbağalarının cinsiyetini ne belirler?", secenekler: { A: "Kumsalın sıcaklığı", B: "Yiyecekler", C: "Derinlik", D: "Rastgele" }, dogruCevap: "A" },
    { seviye: 451, kategori: "Canlılar", soru: "Hangi hayvanın dilleri bir insanın kolu kadar uzayabilir?", secenekler: { A: "Dev Karıncayiyen", B: "Zürafa", C: "Bukalemun", D: "Yılan" }, dogruCevap: "A" },
    { seviye: 452, kategori: "Canlılar", soru: "Fillerin hortumunda kaç tane kas vardır?", secenekler: { A: "Yaklaşık 40.000", B: "100", C: "1000", D: "10" }, dogruCevap: "A" },
    { seviye: 453, kategori: "Canlılar", soru: "Hangi kuş türü karda yuva yapar?", secenekler: { A: "İmparator Penguen", B: "Kar Baykuşu", C: "Martı", D: "Serçe" }, dogruCevap: "A" },
    { seviye: 454, kategori: "Canlılar", soru: "Yılanlar neden dillerini sürekli dışarı çıkarırlar?", secenekler: { A: "Havayı koklamak ve tatmak için", B: "Su içmek için", C: "Korkutmak için", D: "Sıcakladıkları için" }, dogruCevap: "A" },
    { seviye: 455, kategori: "Canlılar", soru: "Hangi balık türü ağaca tırmanabilir?", secenekler: { A: "Çamur Zıpzıpı", B: "Uçan Balık", C: "Sazan", D: "Lüfer" }, dogruCevap: "A" },
    { seviye: 456, kategori: "Canlılar", soru: "Hangi hayvanın midesi yoktur?", secenekler: { A: "Denizatı", B: "Fare", C: "İnek", D: "Köpek" }, dogruCevap: "A" },
    { seviye: 457, kategori: "Canlılar", soru: "Arılar balı neyden yaparlar?", secenekler: { A: "Çiçek nektarı", B: "Polen", C: "Yaprak", D: "Su" }, dogruCevap: "A" },
    { seviye: 458, kategori: "Canlılar", soru: "Hangi kuş türü en zeki kuşlardan biri sayılır?", secenekler: { A: "Karga", B: "Güvercin", C: "Tavuk", D: "Serçe" }, dogruCevap: "A" },
    { seviye: 459, kategori: "Canlılar", soru: "Kediler ne kadar uzağı görebilir?", secenekler: { A: "Uzağı bulanık, yakını çok net görürler", B: "Kartal gibidirler", C: "Görmezler", D: "İnsanla aynıdır" }, dogruCevap: "A" },
    { seviye: 460, kategori: "Canlılar", soru: "Hangi canlı türü dünyada en çok bulunan canlıdır?", secenekler: { A: "Nematodlar (Yuvarlak solucanlar)", B: "Karıncalar", C: "İnsanlar", D: "Balıklar" }, dogruCevap: "A" },
    { seviye: 461, kategori: "Canlılar", soru: "Atlar neden ayakta uyurlar?", secenekler: { A: "Tehlikelere karşı hızlı kaçabilmek için", B: "Yatamadıkları için", C: "Dizleri kitlendiği için", D: "Dinlenmek için" }, dogruCevap: "A" },
    { seviye: 462, kategori: "Canlılar", soru: "Hangi hayvanın parmak izi neredeyse insanla aynıdır?", secenekler: { A: "Koala", B: "Şempanze", C: "Ayı", D: "Rakun" }, dogruCevap: "A" },
    { seviye: 463, kategori: "Canlılar", soru: "Kelebeklerin tat alma organları nerededir?", secenekler: { A: "Ayaklarında", B: "Dillerinde", C: "Antenlerinde", D: "Kanatlarında" }, dogruCevap: "A" },
    { seviye: 464, kategori: "Canlılar", soru: "Hangi hayvan asla unutmamasıyla ünlüdür?", secenekler: { A: "Fil", B: "Karga", C: "Aslan", D: "Köpek" }, dogruCevap: "A" },
    { seviye: 465, kategori: "Canlılar", soru: "Tavşanların kaç tane dişi vardır?", secenekler: { A: "28", B: "4", C: "10", D: "32" }, dogruCevap: "A" },
    { seviye: 466, kategori: "Canlılar", soru: "Hangi canlı türü suyun üstünde koşabilir?", secenekler: { A: "Baziliski Kertenkelesi", B: "Kurbağa", C: "Yılan", D: "Fare" }, dogruCevap: "A" },
    { seviye: 467, kategori: "Canlılar", soru: "Arılar hangi renkleri görebilirler?", secenekler: { A: "Mavi, yeşil ve ultraviyole", B: "Siyah beyaz", C: "Sadece kırmızı", D: "Tüm renkler" }, dogruCevap: "A" },
    { seviye: 468, kategori: "Canlılar", soru: "Hangi kuşun kanatları yüzgeç görevi görür?", secenekler: { A: "Penguen", B: "Martı", C: "Pelikan", D: "Kuğu" }, dogruCevap: "A" },
    { seviye: 469, kategori: "Canlılar", soru: "Yunuslar neden birbirlerine ıslık çalarlar?", secenekler: { A: "Birbirlerine isimleriyle seslenmek için", B: "Kavga etmek için", C: "Yol bulmak için", D: "Şarkı söylemek için" }, dogruCevap: "A" },
    { seviye: 470, kategori: "Canlılar", soru: "Hangi hayvanın sütü dondurma yapımında kullanılmaz?", secenekler: { A: "Balina", B: "İnek", C: "Keçi", D: "Manda" }, dogruCevap: "A" },
    { seviye: 471, kategori: "Canlılar", soru: "Arı kuşu saniyede kaç kez kanat çırpar?", secenekler: { A: "80 kez", B: "10 kez", C: "200 kez", D: "5 kez" }, dogruCevap: "A" },
    { seviye: 472, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile kulaklarını temizlediği söylenir?", secenekler: { A: "Zürafa", B: "Fil", C: "Aslan", D: "Kedi" }, dogruCevap: "A" },
    { seviye: 473, kategori: "Canlılar", soru: "Karıncalar neden birbirini takip eder?", secenekler: { A: "Bırakılan feromon (koku) izini izledikleri için", B: "Gördükleri için", C: "Seslendikleri için", D: "Elele tutuştukları için" }, dogruCevap: "A" },
    { seviye: 474, kategori: "Canlılar", soru: "Hangi hayvanın kalbi kafasındadır?", secenekler: { A: "Karides", B: "Yengeç", C: "Istakoz", D: "Deniz Yıldızı" }, dogruCevap: "A" },
    { seviye: 475, kategori: "Canlılar", soru: "Baykuşlar başlarını kaç derece döndürebilir?", secenekler: { A: "270 derece", B: "180 derece", C: "360 derece", D: "90 derece" }, dogruCevap: "A" },
    { seviye: 476, kategori: "Canlılar", soru: "Hangi canlı türü yaşlandıkça küçülür?", secenekler: { A: "Bazı deniz anası türleri", B: "Fare", C: "Kuş", D: "Yılan" }, dogruCevap: "A" },
    { seviye: 477, kategori: "Canlılar", soru: "Iskozların kanı ne renktir?", secenekler: { A: "Mavi", B: "Kırmızı", C: "Sarı", D: "Şeffaf" }, dogruCevap: "A" },
    { seviye: 478, kategori: "Canlılar", soru: "Hangi hayvanın dilleri pütürlüdür?", secenekler: { A: "Kedi", B: "Köpek", C: "At", D: "İnek" }, dogruCevap: "A" },
    { seviye: 479, kategori: "Canlılar", soru: "Penguenler nerede yaşar?", secenekler: { A: "Güney Kutbu", B: "Kuzey Kutbu", C: "Ekvator", D: "Asya" }, dogruCevap: "A" },
    { seviye: 480, kategori: "Canlılar", soru: "Hangi kuş türü havada uyuyabilir?", secenekler: { A: "Ebabil", B: "Serçe", C: "Karga", D: "Güvercin" }, dogruCevap: "A" },
    { seviye: 481, kategori: "Canlılar", soru: "Zürafalar nasıl su içerler?", secenekler: { A: "Ön bacaklarını yanlara açarak", B: "Zıplayarak", C: "Yatarak", D: "Su içmezler" }, dogruCevap: "A" },
    { seviye: 482, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile ağaçları devirdiği söylenir?", secenekler: { A: "Fil (Hortumuyla)", B: "Zürafa", C: "Aslan", D: "Ayı" }, dogruCevap: "A" },
    { seviye: 483, kategori: "Canlılar", soru: "Arıların zehri ne içerir?", secenekler: { A: "Melittin", B: "Su", C: "Şeker", D: "Tuz" }, dogruCevap: "A" },
    { seviye: 484, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'nehir atı'dır?", secenekler: { A: "Su Aygırı", B: "Timsah", C: "Fok", D: "Balina" }, dogruCevap: "A" },
    { seviye: 485, kategori: "Canlılar", soru: "Hangi kuş türü yuva yapmaz?", secenekler: { A: "Guguk Kuşu", B: "Serçe", C: "Kırlangıç", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 486, kategori: "Canlılar", soru: "Hangi hayvanın dilleri mor renktedir?", secenekler: { A: "Zürafa", B: "Fil", C: "Kaplan", D: "Kedi" }, dogruCevap: "A" },
    { seviye: 487, kategori: "Canlılar", soru: "Kediler neden ot yerler?", secenekler: { A: "Midelerini temizlemek için", B: "Aç oldukları için", C: "Sevdikleri için", D: "Oyun için" }, dogruCevap: "A" },
    { seviye: 488, kategori: "Canlılar", soru: "Hangi hayvanın gözleri dilediği yöne hareket eder?", secenekler: { A: "Bukalemun", B: "Baykuş", C: "Kedi", D: "At" }, dogruCevap: "A" },
    { seviye: 489, kategori: "Canlılar", soru: "Arıların kaç gözü vardır?", secenekler: { A: "5", B: "2", C: "4", D: "10" }, dogruCevap: "A" },
    { seviye: 490, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'yavaş yürüyen'dir?", secenekler: { A: "Tembel Hayvan", B: "Kaplumbağa", C: "Salyangoz", D: "Koala" }, dogruCevap: "A" },
    { seviye: 491, kategori: "Canlılar", soru: "Hangi kuş türü renkli tüyleriyle ünlüdür?", secenekler: { A: "Papağan", B: "Karga", C: "Serçe", D: "Güvercin" }, dogruCevap: "A" },
    { seviye: 492, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile avını yakaladığı söylenir?", secenekler: { A: "Kurbağa", B: "Zürafa", C: "Fil", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 493, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'çöl gemisi'dir?", secenekler: { A: "Deve", B: "At", C: "Eşek", D: "Fil" }, dogruCevap: "A" },
    { seviye: 494, kategori: "Canlılar", soru: "Kediler neden mırlar?", secenekler: { A: "Mutluluk ve iyileşme için", B: "Korktukları için", C: "Aç oldukları için", D: "Oyun için" }, dogruCevap: "A" },
    { seviye: 495, kategori: "Canlılar", soru: "Hangi kuş türü çok uzaklara göç eder?", secenekler: { A: "Kuzey Sumrusu", B: "Serçe", C: "Güvercin", D: "Karga" }, dogruCevap: "A" },
    { seviye: 496, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile termitleri toplar?", secenekler: { A: "Karıncayiyen", B: "Zürafa", C: "Fil", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 497, kategori: "Canlılar", soru: "Arılar nasıl bal yapar?", secenekler: { A: "Nektarı midelerinde işleyerek", B: "Çiçekleri yiyerek", C: "Su içerek", D: "Toprakla" }, dogruCevap: "A" },
    { seviye: 498, kategori: "Canlılar", soru: "Hangi hayvanın dilleri ile buzları yalar?", secenekler: { A: "Kutup Ayısı", B: "Zürafa", C: "Fil", D: "Aslan" }, dogruCevap: "A" },
    { seviye: 499, kategori: "Canlılar", soru: "Hangi hayvanın ismi 'deniz aslanı'dır?", secenekler: { A: "Deniz Aslanı", B: "Fok", C: "Mors", D: "Balina" }, dogruCevap: "A" }
 
 

);
