window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Türkiye Fiziki Coğrafyası (Dağlar, Göller, Akarsular)
    { seviye: 1, kategori: "Coğrafya", soru: "Türkiye'nin başkenti neresidir?", secenekler: { A: "İstanbul", B: "Ankara", C: "İzmir", D: "Bursa" }, dogruCevap: "B" },
    { seviye: 2, kategori: "Coğrafya", soru: "Türkiye'nin en yüksek dağı hangisidir?", secenekler: { A: "Erciyes", B: "Süphan", C: "Ağrı Dağı", D: "Kaçkar" }, dogruCevap: "C" },
    { seviye: 3, kategori: "Coğrafya", soru: "Türkiye'nin yüzölçümü bakımından en büyük gölü hangisidir?", secenekler: { A: "Tuz Gölü", B: "Van Gölü", C: "Beyşehir Gölü", D: "Eğirdir Gölü" }, dogruCevap: "B" },
    { seviye: 4, kategori: "Coğrafya", soru: "Türkiye'nin en uzun nehri (tamamı ülke sınırları içinde) hangisidir?", secenekler: { A: "Fırat", B: "Dicle", C: "Kızılırmak", D: "Yeşilırmak" }, dogruCevap: "C" },
    { seviye: 5, kategori: "Coğrafya", soru: "Türkiye'nin en büyük deltası hangisidir?", secenekler: { A: "Çarşamba", B: "Bafra", C: "Çukurova", D: "Silifke" }, dogruCevap: "C" },
    { seviye: 6, kategori: "Coğrafya", soru: "Ege Bölgesi'nde dağlar denize nasıl uzanır?", secenekler: { A: "Paralel", B: "Dik", C: "Çapraz", D: "Kesik" }, dogruCevap: "B" },
    { seviye: 7, kategori: "Coğrafya", soru: "Türkiye'nin en büyük adası hangisidir?", secenekler: { A: "Bozcaada", B: "Gökçeada", C: "Büyükada", D: "Marmara Adası" }, dogruCevap: "B" },
    { seviye: 8, kategori: "Coğrafya", soru: "Nemrut Dağı ve üzerindeki dev heykeller hangi ilimizdedir?", secenekler: { A: "Adıyaman", B: "Malatya", C: "Şanlıurfa", D: "Bitlis" }, dogruCevap: "A" },
    { seviye: 9, kategori: "Coğrafya", soru: "Manyas (Kuş) Gölü hangi ilimiz sınırları içerisindedir?", secenekler: { A: "Bursa", B: "Balıkesir", C: "Çanakkale", D: "Manisa" }, dogruCevap: "B" },
    { seviye: 10, kategori: "Coğrafya", soru: "Türkiye'nin en kuzey noktası olan İnceburun hangi ilimizdedir?", secenekler: { A: "Sinop", B: "Kırklareli", C: "Artvin", D: "Kastamonu" }, dogruCevap: "A" },
    { seviye: 11, kategori: "Coğrafya", soru: "Dünyanın en büyük peribacaları oluşumları hangi bölgemizdedir?", secenekler: { A: "Ege", B: "İç Anadolu", C: "Doğu Anadolu", D: "Güneydoğu Anadolu" }, dogruCevap: "B" },
    { seviye: 12, kategori: "Coğrafya", soru: "Hangi ilimiz hem Asya hem de Avrupa kıtasında toprağa sahiptir?", secenekler: { A: "Çanakkale", B: "İstanbul", C: "Edirne", D: "Kocaeli" }, dogruCevap: "B" },
    { seviye: 13, kategori: "Coğrafya", soru: "Türkiye'nin en az yağış alan yöresi hangisidir?", secenekler: { A: "Iğdır Ovası", B: "Tuz Gölü Çevresi", C: "Güneydoğu Anadolu", D: "Ergene Havzası" }, dogruCevap: "B" },
    { seviye: 14, kategori: "Coğrafya", soru: "Toros Dağları hangi coğrafi bölgemizin karakteristik dağıdır?", secenekler: { A: "Ege", B: "Akdeniz", C: "Marmara", D: "Karadeniz" }, dogruCevap: "B" },
    { seviye: 15, kategori: "Coğrafya", soru: "Yedi Göller Milli Parkı hangi ilimizdedir?", secenekler: { A: "Bolu", B: "Düzce", C: "Karabük", D: "Zonguldak" }, dogruCevap: "A" },
    { seviye: 16, kategori: "Coğrafya", soru: "Türkiye'nin en batı ucu olan Avlaka Burnu hangi adadadır?", secenekler: { A: "Gökçeada", B: "Bozcaada", C: "Cunda", D: "Kefken" }, dogruCevap: "A" },
    { seviye: 17, kategori: "Coğrafya", soru: "Mavi Tünel Projesi hangi ovamızın sulanması için yapılmıştır?", secenekler: { A: "Konya Ovası", B: "Harran Ovası", C: "Iğdır Ovası", D: "Gediz Ovası" }, dogruCevap: "A" },
    { seviye: 18, kategori: "Coğrafya", soru: "Türkiye'de kış ılıklığının en belirgin olduğu bölge hangisidir?", secenekler: { A: "Akdeniz", B: "Ege", C: "Marmara", D: "Güneydoğu Anadolu" }, dogruCevap: "A" },
    { seviye: 19, kategori: "Coğrafya", soru: "Tortum Şelalesi hangi ilimizdedir?", secenekler: { A: "Erzurum", B: "Artvin", C: "Rize", D: "Trabzon" }, dogruCevap: "A" },
    { seviye: 20, kategori: "Coğrafya", soru: "Türkiye'nin 'Sakin Şehir' (Cittaslow) ünvanlı ilk ilçesi hangisidir?", secenekler: { A: "Seferihisar", B: "Akyaka", C: "Halfeti", D: "Taraklı" }, dogruCevap: "A" },
    { seviye: 21, kategori: "Coğrafya", soru: "Ihlara Vadisi hangi ilimiz sınırları içerisindedir?", secenekler: { A: "Aksaray", B: "Nevşehir", C: "Niğde", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 22, kategori: "Coğrafya", soru: "Türkiye'nin en güneyindeki il hangisidir?", secenekler: { A: "Mersin", B: "Antalya", C: "Hatay", D: "Muğla" }, dogruCevap: "C" },
    { seviye: 23, kategori: "Coğrafya", soru: "İzmir'de bulunan meşhur kuş cennetinin adı nedir?", secenekler: { A: "Gala", B: "Çamaltı", C: "Sultan Sazlığı", D: "Birecik" }, dogruCevap: "B" },
    { seviye: 24, kategori: "Coğrafya", soru: "Sakarya Nehri hangi denize dökülür?", secenekler: { A: "Marmara", B: "Ege", C: "Karadeniz", D: "Akdeniz" }, dogruCevap: "C" },
    { seviye: 25, kategori: "Coğrafya", soru: "Erciyes Dağı hangi ilimizdedir?", secenekler: { A: "Kayseri", B: "Konya", C: "Sivas", D: "Aksaray" }, dogruCevap: "A" },

    // 26-50: Türkiye Ekonomik Coğrafyası (Tarım, Sanayi, Madenler)
    { seviye: 26, kategori: "Coğrafya", soru: "Dünyada fındık üretiminde 1. sırada olan ülke hangisidir?", secenekler: { A: "İtalya", B: "Türkiye", C: "ABD", D: "Gürcistan" }, dogruCevap: "B" },
    { seviye: 27, kategori: "Coğrafya", soru: "Türkiye'de çay tarımı nerede yoğunlaşmıştır?", secenekler: { A: "Doğu Karadeniz", B: "Batı Karadeniz", C: "Ege", D: "Akdeniz" }, dogruCevap: "A" },
    { seviye: 28, kategori: "Coğrafya", soru: "Türkiye'de petrolün en çok çıkarıldığı il hangisidir?", secenekler: { A: "Batman", B: "Adıyaman", C: "Siirt", D: "Diyarbakır" }, dogruCevap: "A" },
    { seviye: 29, kategori: "Coğrafya", soru: "Zonguldak denilince akla gelen en önemli maden hangisidir?", secenekler: { A: "Linyit", B: "Taş Kömürü", C: "Demir", D: "Bakır" }, dogruCevap: "B" },
    { seviye: 30, kategori: "Coğrafya", soru: "Dünya bor rezervlerinin yaklaşık %70'inden fazlasına sahip ülke?", secenekler: { A: "Rusya", B: "Çin", C: "Türkiye", D: "ABD" }, dogruCevap: "C" },
    { seviye: 31, kategori: "Coğrafya", soru: "Türkiye'de pamuk üretiminde ilk sırada yer alan ilimiz?", secenekler: { A: "Adana", B: "Aydın", C: "Şanlıurfa", D: "Antalya" }, dogruCevap: "C" },
    { seviye: 32, kategori: "Coğrafya", soru: "Kayısı üretimiyle dünya çapında meşhur olan ilimiz?", secenekler: { A: "Malatya", B: "Elazığ", C: "Iğdır", D: "Erzincan" }, dogruCevap: "A" },
    { seviye: 33, kategori: "Coğrafya", soru: "Türkiye'de ipek böcekçiliği ve ipekli dokumada lider şehir?", secenekler: { A: "Bursa", B: "Diyarbakır", C: "Bilecik", D: "Sakarya" }, dogruCevap: "A" },
    { seviye: 34, kategori: "Coğrafya", soru: "Lüle taşı sadece hangi ilimizde çıkarılır?", secenekler: { A: "Eskişehir", B: "Erzurum", C: "Kütahya", D: "Afyon" }, dogruCevap: "A" },
    { seviye: 35, kategori: "Coğrafya", soru: "Oltu taşı hangi ilimizin simgesidir?", secenekler: { A: "Erzurum", B: "Erzincan", C: "Bayburt", D: "Gümüşhane" }, dogruCevap: "A" },
    { seviye: 36, kategori: "Coğrafya", soru: "Türkiye'de jeotermal enerjiden elektrik üretilen ilk yer?", secenekler: { A: "Sarayköy (Denizli)", B: "Germencik (Aydın)", C: "Soma (Manisa)", D: "Yatağan (Muğla)" }, dogruCevap: "A" },
    { seviye: 37, kategori: "Coğrafya", soru: "Hangi ilimiz 'Güller Diyarı' olarak bilinir?", secenekler: { A: "Isparta", B: "Burdur", C: "Afyon", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 38, kategori: "Coğrafya", soru: "Türkiye'nin en büyük demir-çelik fabrikası hangisidir?", secenekler: { A: "Erdemir", B: "Kardemir", C: "İsdemir", D: "Asil Çelik" }, dogruCevap: "A" },
    { seviye: 39, kategori: "Coğrafya", soru: "GAP (Güneydoğu Anadolu Projesi) kapsamındaki en büyük baraj?", secenekler: { A: "Atatürk Barajı", B: "Keban Barajı", C: "Karakaya Barajı", D: "Ilısu Barajı" }, dogruCevap: "A" },
    { seviye: 40, kategori: "Coğrafya", soru: "Türkiye'de muz üretiminin yapıldığı tek bölge hangisidir?", secenekler: { A: "Ege", B: "Akdeniz", C: "Marmara", D: "Güneydoğu Anadolu" }, dogruCevap: "B" },
    { seviye: 41, kategori: "Coğrafya", soru: "Ayçiçeği üretimi en çok hangi bölgemizde yapılır?", secenekler: { A: "İç Anadolu", B: "Marmara (Trakya)", C: "Ege", D: "Karadeniz" }, dogruCevap: "B" },
    { seviye: 42, kategori: "Coğrafya", soru: "Türkiye'de rüzgar enerjisi santrali (RES) ilk kez nerede kuruldu?", secenekler: { A: "İzmir (Alaçatı)", B: "Balıkesir", C: "Çanakkale", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 43, kategori: "Coğrafya", soru: "Turunçgil üretimi için kış ılıklığı şarttır. Hangi ilde bu üretim zordur?", secenekler: { A: "Adana", B: "Mersin", C: "Sivas", D: "Antalya" }, dogruCevap: "C" },
    { seviye: 44, kategori: "Coğrafya", soru: "Türkiye'nin en çok ithal (satın alma) ettiği enerji kaynağı?", secenekler: { A: "Petrol ve Doğalgaz", B: "Kömür", C: "Elektrik", D: "Güneş Paneli" }, dogruCevap: "A" },
    { seviye: 45, kategori: "Coğrafya", soru: "Sığla ağacı dünyada sadece nerede bulunur?", secenekler: { A: "Muğla (Köyceğiz)", B: "Antalya (Kaş)", C: "Rize", D: "Artvin" }, dogruCevap: "A" },
    { seviye: 46, kategori: "Coğrafya", soru: "Türkiye'de en çok mısır üretimi son yıllarda hangi bölgeye kaymıştır?", secenekler: { A: "Karadeniz", B: "Güneydoğu Anadolu", C: "Marmara", D: "Ege" }, dogruCevap: "B" },
    { seviye: 47, kategori: "Coğrafya", soru: "Kümes hayvancılığı neden büyük şehirlerin yakınında gelişmiştir?", secenekler: { A: "İklim uygunluğu", B: "Tüketici nüfus (pazar)", C: "Su kaynakları", D: "Yem fabrikaları" }, dogruCevap: "B" },
    { seviye: 48, kategori: "Coğrafya", soru: "Türkiye'nin en modern ve büyük konteyner limanı hangisidir?", secenekler: { A: "İstanbul Limanı", B: "İzmir Limanı", C: "Mersin Limanı", D: "Trabzon Limanı" }, dogruCevap: "C" },
    { seviye: 49, kategori: "Coğrafya", soru: "Zeytin üretimi en çok hangi bölgede yapılır?", secenekler: { A: "Ege", B: "Marmara", C: "Akdeniz", D: "Güneydoğu Anadolu" }, dogruCevap: "A" },
    { seviye: 50, kategori: "Coğrafya", soru: "Türkiye'nin ilk nükleer güç santrali nerede inşa edilmektedir?", secenekler: { A: "Sinop", B: "Mersin (Akkuyu)", C: "Kırklareli", D: "Adana" }, dogruCevap: "B" },

    // 51-75: Türkiye Beşeri Coğrafya, İller ve Sınırlar
    { seviye: 51, kategori: "Coğrafya", soru: "Türkiye'nin nüfus bakımından en büyük ili hangisidir?", secenekler: { A: "Ankara", B: "İstanbul", C: "İzmir", D: "Bursa" }, dogruCevap: "B" },
    { seviye: 52, kategori: "Coğrafya", soru: "Türkiye'nin en uzun sınır komşusu hangi ülkedir?", secenekler: { A: "Irak", B: "İran", C: "Suriye", D: "Yunanistan" }, dogruCevap: "C" },
    { seviye: 53, kategori: "Coğrafya", soru: "Nahçıvan üzerinden hangi ülke ile sınırımız vardır?", secenekler: { A: "Ermenistan", B: "Azerbaycan", C: "Gürcistan", D: "İran" }, dogruCevap: "B" },
    { seviye: 54, kategori: "Coğrafya", soru: "Türkiye'de nüfus yoğunluğu en az olan ilimiz genellikle hangisidir?", secenekler: { A: "Tunceli", B: "Bayburt", C: "Ardahan", D: "Gümüşhane" }, dogruCevap: "A" },
    { seviye: 55, kategori: "Coğrafya", soru: "Güneydoğu Anadolu'nun en gelişmiş sanayi şehri hangisidir?", secenekler: { A: "Diyarbakır", B: "Gaziantep", C: "Şanlıurfa", D: "Mardin" }, dogruCevap: "B" },
    { seviye: 56, kategori: "Coğrafya", soru: "Türkiye'de doğurganlık oranının en yüksek olduğu bölge hangisidir?", secenekler: { A: "Doğu Anadolu", B: "Güneydoğu Anadolu", C: "İç Anadolu", D: "Karadeniz" }, dogruCevap: "B" },
    { seviye: 57, kategori: "Coğrafya", soru: "Hangi ilimizin adı daha önce 'Maraş' iken değiştirilmiştir?", secenekler: { A: "Şanlıurfa", B: "Kahramanmaraş", C: "Gaziantep", D: "Afyonkarahisar" }, dogruCevap: "B" },
    { seviye: 58, kategori: "Coğrafya", soru: "Aşağıdakilerden hangisi bir sınır kapımız değildir?", secenekler: { A: "Habur", B: "Kapıkule", C: "Sarp", D: "Esenboğa" }, dogruCevap: "D" },
    { seviye: 59, kategori: "Coğrafya", soru: "Türkiye'nin en kalabalık 3. şehri hangisidir?", secenekler: { A: "Bursa", B: "İzmir", C: "Antalya", D: "Adana" }, dogruCevap: "B" },
    { seviye: 60, kategori: "Coğrafya", soru: "İpek Yolu'nun Anadolu'daki önemli duraklarından biri olan şehir?", secenekler: { A: "Erzurum", B: "Kayseri", C: "Konya", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 61, kategori: "Coğrafya", soru: "Dünyanın en eski yerleşimlerinden Çatalhöyük hangi ilimizdedir?", secenekler: { A: "Konya", B: "Çorum", C: "Aksaray", D: "Karaman" }, dogruCevap: "A" },
    { seviye: 62, kategori: "Coğrafya", soru: "Türkiye'nin kış turizminde önde gelen 'Palandöken' merkezi nerededir?", secenekler: { A: "Bursa", B: "Erzurum", C: "Kayseri", D: "Bolu" }, dogruCevap: "B" },
    { seviye: 63, kategori: "Coğrafya", soru: "Marmara ve Ege Denizi'ni birbirine bağlayan boğaz?", secenekler: { A: "İstanbul Boğazı", B: "Çanakkale Boğazı", C: "Cebelitarık Boğazı", D: "Korint Kanalı" }, dogruCevap: "B" },
    { seviye: 64, kategori: "Coğrafya", soru: "Türkiye'nin yüzölçümü en büyük ili hangisidir?", secenekler: { A: "Sivas", B: "Konya", C: "Ankara", D: "Erzurum" }, dogruCevap: "B" },
    { seviye: 65, kategori: "Coğrafya", soru: "Fındık ve Çay dışında 'Kivi' üretimiyle de öne çıkan bölgemiz?", secenekler: { A: "Karadeniz", B: "Marmara", C: "Akdeniz", D: "Ege" }, dogruCevap: "A" },
    { seviye: 66, kategori: "Coğrafya", soru: "Karadeniz ve Akdeniz'i birbirine bağlayacak olan tünel projeleri?", secenekler: { A: "Ovit", B: "Zigana", C: "Ecevit", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 67, kategori: "Coğrafya", soru: "Türkiye'nin tek fiyord tipi kıyısı nerededir?", secenekler: { A: "Sinop (Hamsilos)", B: "Antalya (Kaş)", C: "İzmir (Foça)", D: "Muğla (Fethiye)" }, dogruCevap: "A" },
    { seviye: 68, kategori: "Coğrafya", soru: "Göbeklitepe hangi ilimizde bulunmaktadır?", secenekler: { A: "Şanlıurfa", B: "Gaziantep", C: "Mardin", D: "Adıyaman" }, dogruCevap: "A" },
    { seviye: 69, kategori: "Coğrafya", soru: "Mardin'in mimarisiyle meşhur eski evleri hangi taştan yapılır?", secenekler: { A: "Kalker", B: "Sarı Kalker (Mardin Taşı)", C: "Granit", D: "Mermer" }, dogruCevap: "B" },
    { seviye: 70, kategori: "Coğrafya", soru: "Türkiye'nin pirinç üretim merkezi neresidir?", secenekler: { A: "Edirne (Meriç)", B: "Samsun", C: "Sinop", D: "Kastamonu" }, dogruCevap: "A" },
    { seviye: 71, kategori: "Coğrafya", soru: "Hangi ilimizde 'Kapadokya' benzeri 'Narman Peribacaları' bulunur?", secenekler: { A: "Erzurum", B: "Nevşehir", C: "Van", D: "Manisa" }, dogruCevap: "A" },
    { seviye: 72, kategori: "Coğrafya", soru: "Türkiye'de en çok göç veren bölge hangisidir?", secenekler: { A: "Karadeniz", B: "Doğu Anadolu", C: "İç Anadolu", D: "Ege" }, dogruCevap: "B" },
    { seviye: 73, kategori: "Coğrafya", soru: "Büyükşehir statüsünde olan en son ilimiz hangisidir?", secenekler: { A: "Ordu", B: "Mardin", C: "Muğla", D: "Tekirdağ" }, dogruCevap: "A" },
    { seviye: 74, kategori: "Coğrafya", soru: "Türkiye'nin en doğusu ile en batısı arasındaki zaman farkı?", secenekler: { A: "76 Dakika", B: "40 Dakika", C: "60 Dakika", D: "90 Dakika" }, dogruCevap: "A" },
    { seviye: 75, kategori: "Coğrafya", soru: "Hangi dağımızda buzul (glasiye) oluşumlarına rastlanmaz?", secenekler: { A: "Ağrı", B: "Cilo", C: "Yıldız Dağları", D: "Kaçkar" }, dogruCevap: "C" },

    // 76-100: Dünya Coğrafyası Genel Kültür
    { seviye: 76, kategori: "Coğrafya", soru: "Dünyanın en büyük okyanusu hangisidir?", secenekler: { A: "Pasifik", B: "Atlas", C: "Hint", D: "Kuzey Buz" }, dogruCevap: "A" },
    { seviye: 77, kategori: "Coğrafya", soru: "Dünyanın en yüksek noktası olan Everest hangi sıradağlardadır?", secenekler: { A: "Himalayalar", B: "Alpler", C: "Andlar", D: "Kayalık Dağları" }, dogruCevap: "A" },
    { seviye: 78, kategori: "Coğrafya", soru: "Dünyanın en uzun nehri hangisidir?", secenekler: { A: "Nil", B: "Amazon", C: "Mississipi", D: "Ganj" }, dogruCevap: "A" },
    { seviye: 79, kategori: "Coğrafya", soru: "Dünyanın en geniş yüzölçümüne sahip ülkesi?", secenekler: { A: "Rusya", B: "Kanada", C: "Çin", D: "ABD" }, dogruCevap: "A" },
    { seviye: 80, kategori: "Coğrafya", soru: "Güney Amerika'nın en büyük ülkesi hangisidir?", secenekler: { A: "Brezilya", B: "Arjantin", C: "Şili", D: "Kolombiya" }, dogruCevap: "A" },
    { seviye: 81, kategori: "Coğrafya", soru: "Afrika kıtasının en yüksek dağı hangisidir?", secenekler: { A: "Kilimanjaro", B: "Kenya Dağı", C: "Atlas Dağları", D: "Kongo Dağı" }, dogruCevap: "A" },
    { seviye: 82, kategori: "Coğrafya", soru: "Dünyanın en derin noktası Mariana Çukuru nerededir?", secenekler: { A: "Pasifik Okyanusu", B: "Hint Okyanusu", C: "Atlas Okyanusu", D: "Akdeniz" }, dogruCevap: "A" },
    { seviye: 83, kategori: "Coğrafya", soru: "Hangi ülke 'Yükselen Güneşin Ülkesi' olarak anılır?", secenekler: { A: "Japonya", B: "Çin", C: "Güney Kore", D: "Tayland" }, dogruCevap: "A" },
    { seviye: 84, kategori: "Coğrafya", soru: "Dünyanın en büyük çölü hangisidir?", secenekler: { A: "Sahra Çölü", B: "Gobi Çölü", C: "Kalahari", D: "Atacama" }, dogruCevap: "A" },
    { seviye: 85, kategori: "Coğrafya", soru: "Fransa ve İngiltere'yi deniz altından bağlayan tünel?", secenekler: { A: "Manş Tüneli", B: "Bering Tüneli", C: "Cebelitarık", D: "Süveyş" }, dogruCevap: "A" },
    { seviye: 86, kategori: "Coğrafya", soru: "Hangi kanal Akdeniz ile Kızıldeniz'i birbirine bağlar?", secenekler: { A: "Süveyş Kanalı", B: "Panama Kanalı", C: "Kanal İstanbul", D: "Korint Kanalı" }, dogruCevap: "A" },
    { seviye: 87, kategori: "Coğrafya", soru: "Dünyanın en kalabalık ülkesi (2024 verilerine göre)?", secenekler: { A: "Hindistan", B: "Çin", C: "ABD", D: "Endonezya" }, dogruCevap: "A" },
    { seviye: 88, kategori: "Coğrafya", soru: "Kanguruları ile ünlü olan kıta ülke?", secenekler: { A: "Avustralya", B: "Afrika", C: "Asya", D: "Antarktika" }, dogruCevap: "A" },
    { seviye: 90, kategori: "Coğrafya", soru: "Hangi ülke hem Asya hem Avrupa kıtasında yer alır?", secenekler: { A: "Türkiye ve Rusya", B: "Çin", C: "Hindistan", D: "Almanya" }, dogruCevap: "A" },
    { seviye: 91, kategori: "Coğrafya", soru: "Dünyanın en küçük yüzölçümlü ülkesi?", secenekler: { A: "Vatikan", B: "Monako", C: "San Marino", D: "Andorra" }, dogruCevap: "A" },
    { seviye: 92, kategori: "Coğrafya", soru: "İskandinav ülkeleri hangi kıtadadır?", secenekler: { A: "Avrupa", B: "Asya", C: "Amerika", D: "Afrika" }, dogruCevap: "A" },
    { seviye: 93, kategori: "Coğrafya", soru: "Amazon yağmur ormanları hangi kıtadadır?", secenekler: { A: "Güney Amerika", B: "Kuzey Amerika", C: "Afrika", D: "Asya" }, dogruCevap: "A" },
    { seviye: 94, kategori: "Coğrafya", soru: "İzlanda'da çok sayıda bulunan jeotermal oluşum?", secenekler: { A: "Gayzer", B: "Fiyord", C: "Obruk", D: "Delta" }, dogruCevap: "A" },
    { seviye: 95, kategori: "Coğrafya", soru: "Dünyanın en soğuk kıtası hangisidir?", secenekler: { A: "Antarktika", B: "Asya (Sibirya)", C: "Kuzey Amerika", D: "Avrupa" }, dogruCevap: "A" },
    { seviye: 96, kategori: "Coğrafya", soru: "Dünyanın en büyük tatlı su gölü hangisidir?", secenekler: { A: "Superior Gölü", B: "Hazar Denizi", C: "Baykal Gölü", D: "Victoria Gölü" }, dogruCevap: "A" },
    { seviye: 97, kategori: "Coğrafya", soru: "Hangi ülke topraklarında hiç nehir bulunmaz?", secenekler: { A: "Suudi Arabistan", B: "Mısır", C: "Irak", D: "Libya" }, dogruCevap: "A" },
    { seviye: 98, kategori: "Coğrafya", soru: "Ekvator çizgisinin geçtiği ülkelerden biri?", secenekler: { A: "Ekvador", B: "Meksika", C: "Arjantin", D: "Kanada" }, dogruCevap: "A" },
    { seviye: 99, kategori: "Coğrafya", soru: "Ganj Nehri hangi ülke için kutsal sayılır?", secenekler: { A: "Hindistan", B: "Çin", C: "Pakistan", D: "Mısır" }, dogruCevap: "A" },
    { seviye: 100, kategori: "Coğrafya", soru: "Dünya'nın kendi ekseni etrafında dönme hızı nerede en fazladır?", secenekler: { A: "Ekvator", B: "Kutuplar", C: "Yengeç Dönencesi", D: "Oğlak Dönencesi" }, dogruCevap: "A" }, 
    // 101-151: Dünya Coğrafyası, İklimler, Ülkeler ve Ekstrem Olaylar
    { seviye: 101, kategori: "Coğrafya", soru: "Dünyanın en derin noktası olan Mariana Çukuru hangi okyanustadır?", secenekler: { A: "Atlas Okyanusu", B: "Hint Okyanusu", C: "Büyük Okyanus (Pasifik)", D: "Arktik Okyanusu" }, dogruCevap: "C" },
    { seviye: 102, kategori: "Coğrafya", soru: "Yüzölçümü bakımından dünyanın en büyük ülkesi hangisidir?", secenekler: { A: "Kanada", B: "Çin", C: "ABD", D: "Rusya" }, dogruCevap: "D" },
    { seviye: 103, kategori: "Coğrafya", soru: "Yeryüzünde en çok yağış alan yer olarak bilinen Çerapunçi hangi ülkededir?", secenekler: { A: "Brezilya", B: "Hindistan", C: "Endonezya", D: "Kongo" }, dogruCevap: "B" },
    { seviye: 104, kategori: "Coğrafya", soru: "Dünyanın en uzun sıradağı hangisidir?", secenekler: { A: "Alpler", B: "Himalayalar", C: "And Dağları", D: "Kayalık Dağları" }, dogruCevap: "C" },
    { seviye: 105, kategori: "Coğrafya", soru: "İskandinav ülkelerinde buzulların aşındırmasıyla oluşan derin vadilere ne ad verilir?", secenekler: { A: "Kanyon", B: "Fiyort", C: "Obruk", D: "Delta" }, dogruCevap: "B" },
    { seviye: 106, kategori: "Coğrafya", soru: "Yüzölçümü en küçük olan kıta hangisidir?", secenekler: { A: "Avrupa", B: "Okyanusya (Avustralya)", C: "Antarktika", D: "Güney Amerika" }, dogruCevap: "B" },
    { seviye: 107, kategori: "Coğrafya", soru: "Dünyanın en büyük sıcak çölü hangisidir?", secenekler: { A: "Gobi Çölü", B: "Sahra Çölü", C: "Atacama Çölü", D: "Kalahari Çölü" }, dogruCevap: "B" },
    { seviye: 108, kategori: "Coğrafya", soru: "Süveyş Kanalı hangi iki denizi birbirine bağlar?", secenekler: { A: "Akdeniz - Kızıldeniz", B: "Akdeniz - Karadeniz", C: "Hazar Denizi - Karadeniz", D: "Umman Denizi - Kızıldeniz" }, dogruCevap: "A" },
    { seviye: 109, kategori: "Coğrafya", soru: "Dünyanın en yüksek şelalesi olan Angel Şelalesi hangi ülkededir?", secenekler: { A: "Brezilya", B: "Venezuela", C: "ABD", D: "Zambiya" }, dogruCevap: "B" },
    { seviye: 110, kategori: "Coğrafya", soru: "Dünyanın kendi ekseni etrafındaki dönüş hızı (çizgisel hız) nerede en fazladır?", secenekler: { A: "Kuzey Kutbu", B: "Ekvator", C: "Yengeç Dönencesi", D: "Güney Kutbu" }, dogruCevap: "B" },
    { seviye: 111, kategori: "Coğrafya", soru: "Haritalarda yükseltiyi göstermek için kullanılan, aynı yükseltiye sahip noktaları birleştiren eğrilere ne denir?", secenekler: { A: "İzobar", B: "İzoterm", C: "İzohips", D: "İzobat" }, dogruCevap: "C" },
    { seviye: 112, kategori: "Coğrafya", soru: "Atmosferin en alt ve hava olaylarının yaşandığı katmanı hangisidir?", secenekler: { A: "Stratosfer", B: "Mezosfer", C: "Troposfer", D: "Termosfer" }, dogruCevap: "C" },
    { seviye: 113, kategori: "Coğrafya", soru: "Akdeniz ikliminin karakteristik bitki örtüsü hangisidir?", secenekler: { A: "Bozkır", B: "Maki", C: "Tundra", D: "Savann" }, dogruCevap: "B" },
    { seviye: 114, kategori: "Coğrafya", soru: "Depremin büyüklüğünü ölçmek için kullanılan ölçeğin adı nedir?", secenekler: { A: "Fahrenheit", B: "Richter", C: "Barometre", D: "Anemometre" }, dogruCevap: "B" },
    { seviye: 115, kategori: "Coğrafya", soru: "Sıcaklık ve nemin yıl boyunca yüksek olduğu, her mevsimin yağışlı geçtiği iklim?", secenekler: { A: "Muson İklimi", B: "Çöl İklimi", C: "Ekvatoral İklim", D: "Savan İklimi" }, dogruCevap: "C" },
    { seviye: 116, kategori: "Coğrafya", soru: "Hangi ülke 'Yükselen Güneşin Ülkesi' olarak bilinir?", secenekler: { A: "Çin", B: "Güney Kore", C: "Japonya", D: "Tayland" }, dogruCevap: "C" },
    { seviye: 117, kategori: "Coğrafya", soru: "Dünyanın en yoğun nüfuslu kıtası hangisidir?", secenekler: { A: "Avrupa", B: "Afrika", C: "Asya", D: "Kuzey Amerika" }, dogruCevap: "C" },
    { seviye: 118, kategori: "Coğrafya", soru: "Bering Boğazı hangi iki kıtayı birbirine en çok yaklaştırır?", secenekler: { A: "Asya - Avrupa", B: "Asya - Kuzey Amerika", C: "Afrika - Avrupa", D: "Güney Amerika - Antarktika" }, dogruCevap: "B" },
    { seviye: 119, kategori: "Coğrafya", soru: "Yeryüzündeki tatlı su rezervlerinin en büyük kısmı nerede bulunur?", secenekler: { A: "Göller", B: "Yeraltı suları", C: "Buzullar", D: "Nehirler" }, dogruCevap: "C" },
    { seviye: 120, kategori: "Coğrafya", soru: "Arap Yarımadası ile Afrika arasında yer alan deniz hangisidir?", secenekler: { A: "Umman Denizi", B: "Kızıldeniz", C: "Basra Körfezi", D: "Aden Körfezi" }, dogruCevap: "B" },
    { seviye: 121, kategori: "Coğrafya", soru: "Dünya üzerindeki bir noktanın Ekvator'a olan uzaklığının açı cinsinden değerine ne denir?", secenekler: { A: "Boylam", B: "Enlem", C: "Yerel Saat", D: "Yörünge" }, dogruCevap: "B" },
    { seviye: 122, kategori: "Coğrafya", soru: "Hangi okyanusun kıyısı 'Pasifik Ateş Çemberi' olarak adlandırılan yoğun volkanik bölgedir?", secenekler: { A: "Atlas Okyanusu", B: "Hint Okyanusu", C: "Büyük Okyanus", D: "Güney Okyanusu" }, dogruCevap: "C" },
    { seviye: 123, kategori: "Coğrafya", soru: "İsviçre, Avusturya ve Fransa boyunca uzanan Avrupa'nın en büyük sıradağ sistemi?", secenekler: { A: "Pireneler", B: "Alpler", C: "Karpatlar", D: "Ural Dağları" }, dogruCevap: "B" },
    { seviye: 124, kategori: "Coğrafya", soru: "Dünyanın en kalabalık Müslüman nüfusuna sahip ülkesi hangisidir?", secenekler: { A: "Suudi Arabistan", B: "Mısır", C: "Endonezya", D: "Pakistan" }, dogruCevap: "C" },
    { seviye: 125, kategori: "Coğrafya", soru: "Amazon Nehri hangi okyanusa dökülür?", secenekler: { A: "Pasifik Okyanusu", B: "Atlas Okyanusu (Atlantik)", C: "Hint Okyanusu", D: "Arktik Okyanusu" }, dogruCevap: "B" },
    { seviye: 126, kategori: "Coğrafya", soru: "Kuzey ve Güney yarım küreleri birbirinden ayıran hayali çizgiye ne denir?", secenekler: { A: "Başlangıç Meridyeni", B: "Ekvator", C: "Oğlak Dönencesi", D: "Kutup Dairesi" }, dogruCevap: "B" },
    { seviye: 127, kategori: "Coğrafya", soru: "Atlas Okyanusu ile Büyük Okyanus'u birbirine bağlayan yapay kanal hangisidir?", secenekler: { A: "Süveyş Kanalı", B: "Panama Kanalı", C: "Kiel Kanalı", D: "Korint Kanalı" }, dogruCevap: "B" },
    { seviye: 128, kategori: "Coğrafya", soru: "Avrupa ve Afrika kıtalarını birbirine en çok yaklaştıran boğaz hangisidir?", secenekler: { A: "Cebelitarık Boğazı", B: "Hürmüz Boğazı", C: "Malakka Boğazı", D: "Babülmendep Boğazı" }, dogruCevap: "A" },
    { seviye: 129, kategori: "Coğrafya", soru: "Dünyanın en tuzlu denizi hangisidir?", secenekler: { A: "Akdeniz", B: "Kızıldeniz", C: "Manş Denizi", D: "Umman Denizi" }, dogruCevap: "B" },
    { seviye: 130, kategori: "Coğrafya", soru: "Güneydoğu Asya'da yaz aylarında bol yağış getiren rüzgarlara ne denir?", secenekler: { A: "Alizeler", B: "Batı Rüzgarları", C: "Muson Rüzgarları", D: "Fön Rüzgarları" }, dogruCevap: "C" },
    { seviye: 131, kategori: "Coğrafya", soru: "Dünyanın en büyük adası hangisidir?", secenekler: { A: "Madagaskar", B: "Grönland", C: "Borneo", D: "Yeni Gine" }, dogruCevap: "B" },
    { seviye: 132, kategori: "Coğrafya", soru: "Nüfus sayımını ve nüfusun özelliklerini inceleyen bilim dalı hangisidir?", secenekler: { A: "Jeoloji", B: "Demografi", C: "Kartografya", D: "Litoloji" }, dogruCevap: "B" },
    { seviye: 133, kategori: "Coğrafya", soru: "Avrupa'nın en uzun nehri hangisidir?", secenekler: { A: "Tuna", B: "Ren", C: "Volga", D: "Elbe" }, dogruCevap: "C" },
    { seviye: 134, kategori: "Coğrafya", soru: "Magmanın yeryüzüne çıktığı noktada oluşturduğu çukurluğa ne ad verilir?", secenekler: { A: "Mağara", B: "Krater", C: "Polye", D: "Lapyalar" }, dogruCevap: "B" },
    { seviye: 135, kategori: "Coğrafya", soru: "Kireç taşlarının (kalker) su ile erimesi sonucu oluşan yer şekillerine ne denir?", secenekler: { A: "Volkanik", B: "Karstik", C: "Buzul", D: "Rüzgar aşınımı" }, dogruCevap: "B" },
    { seviye: 136, kategori: "Coğrafya", soru: "Avustralya kıtasının en tanınmış yerli halkına ne ad verilir?", secenekler: { A: "İnka", B: "Aztek", C: "Aborjin", D: "Maori" }, dogruCevap: "C" },
    { seviye: 137, kategori: "Coğrafya", soru: "Hangi ülke toprakları üzerinde en çok zaman dilimi (saat farkı) barındırır?", secenekler: { A: "Çin", B: "Rusya", C: "Fransa (deniz aşırı toprakları dahil)", D: "ABD" }, dogruCevap: "C" },
    { seviye: 138, kategori: "Coğrafya", soru: "Kalıcı kar sınırının en yüksek olduğu bölge neresidir?", secenekler: { A: "Kutuplar", B: "Orta Kuşak", C: "Ekvator", D: "Dönenceler" }, dogruCevap: "C" },
    { seviye: 139, kategori: "Coğrafya", soru: "Kuzey ışıkları olarak da bilinen doğa olayının bilimsel adı nedir?", secenekler: { A: "Sirocco", B: "Aurora Borealis", C: "Tsunami", D: "Hortum" }, dogruCevap: "B" },
    { seviye: 140, kategori: "Coğrafya", soru: "Hangi kıtada aktif volkan bulunmaz?", secenekler: { A: "Antarktika", B: "Avustralya", C: "Avrupa", D: "Afrika" }, dogruCevap: "B" },
    { seviye: 141, kategori: "Coğrafya", soru: "Gel-git (med-cezir) olayının temel sebebi hangisidir?", secenekler: { A: "Rüzgarlar", B: "Ay'ın çekim gücü", C: "Okyanus akıntıları", D: "Dünyanın iç ısısı" }, dogruCevap: "B" },
    { seviye: 142, kategori: "Coğrafya", soru: "Yeryüzünde sıcaklık değerleri en düşük olan yerleşim birimleri hangi ülkededir?", secenekler: { A: "Kanada", B: "Rusya", C: "Norveç", D: "İzlanda" }, dogruCevap: "B" },
    { seviye: 143, kategori: "Coğrafya", soru: "Asya ile Avrupa'yı birbirinden ayıran doğal sınır kabul edilen dağlar?", secenekler: { A: "Ural Dağları", B: "Kafkas Dağları", C: "Toroslar", D: "Himalayalar" }, dogruCevap: "A" },
    { seviye: 144, kategori: "Coğrafya", soru: "Dünyanın en büyük mercan resifi sistemi hangi ülkenin kıyısındadır?", secenekler: { A: "Endonezya", B: "Avustralya", C: "Meksika", D: "Maldivler" }, dogruCevap: "B" },
    { seviye: 145, kategori: "Coğrafya", soru: "Deniz seviyesindeki atmosfer basıncı ortalama kaç milibardır?", secenekler: { A: "1000", B: "1013", C: "1025", D: "980" }, dogruCevap: "B" },
    { seviye: 146, kategori: "Coğrafya", soru: "Peri bacalarının oluşumunda iç kuvvetlerden hangisi etkilidir?", secenekler: { A: "Deprem", B: "Volkanizma", C: "Orojenez", D: "Epirojenez" }, dogruCevap: "B" },
    { seviye: 147, kategori: "Coğrafya", soru: "Dünyanın en küçük bağımsız devleti hangisidir?", secenekler: { A: "Monako", B: "Vatikan", C: "San Marino", D: "Liechtenstein" }, dogruCevap: "B" },
    { seviye: 148, kategori: "Coğrafya", soru: "Hangi rüzgar türü estiği yamaçta sıcaklığı artırarak kar erimelerine neden olur?", secenekler: { A: "Meltem", B: "Fön", C: "Mistral", D: "Poyraz" }, dogruCevap: "B" },
    { seviye: 149, kategori: "Coğrafya", soru: "Nil Nehri hangi denize dökülür?", secenekler: { A: "Kızıldeniz", B: "Akdeniz", C: "Hint Okyanusu", D: "Basra Körfezi" }, dogruCevap: "B" },
    { seviye: 150, kategori: "Coğrafya", soru: "Atmosferdeki ozon tabakasının temel görevi nedir?", secenekler: { A: "Yağışı başlatmak", B: "Zararlı güneş ışınlarını tutmak", C: "Sıcaklığı iletmek", D: "Oksijen üretmek" }, dogruCevap: "B" },
    { seviye: 151, kategori: "Coğrafya", soru: "Güney Yarım Küre'de en uzun gündüzün yaşandığı tarih hangisidir?", secenekler: { A: "21 Haziran", B: "21 Aralık", C: "21 Mart", D: "23 Eylül" }, dogruCevap: "B" },
    // 152-200: Türkiye Fiziki ve Beşeri Coğrafya Detayları
    { seviye: 152, kategori: "Coğrafya", soru: "Türkiye'nin en büyük kapalı havzası hangisidir?", secenekler: { A: "Van Gölü Havzası", B: "Tuz Gölü Havzası", C: "Konya Havzası", D: "Akarçay Havzası" }, dogruCevap: "B" },
    { seviye: 153, kategori: "Coğrafya", soru: "Kaçkar Dağları hangi sıradağlar içerisinde yer alır?", secenekler: { A: "Toroslar", B: "Doğu Karadeniz Dağları", C: "Canik Dağları", D: "Aydın Dağları" }, dogruCevap: "B" },
    { seviye: 154, kategori: "Coğrafya", soru: "Türkiye'nin en doğusundaki sınır kapısı hangisidir?", secenekler: { A: "Gürbulak", B: "Sarp", C: "Dilucu", D: "Esendere" }, dogruCevap: "C" },
    { seviye: 155, kategori: "Coğrafya", soru: "Manavgat Şelalesi hangi ilimizdedir?", secenekler: { A: "Mersin", B: "Muğla", C: "Antalya", D: "Burdur" }, dogruCevap: "C" },
    { seviye: 156, kategori: "Coğrafya", soru: "Türkiye'de rüzgar aşınım şekillerine en çok hangi bölgede rastlanır?", secenekler: { A: "Karadeniz", B: "Marmara", C: "İç Anadolu", D: "Ege" }, dogruCevap: "C" },
    { seviye: 157, kategori: "Coğrafya", soru: "Büyük Menderes ve Küçük Menderes nehirlerinin oluşturduğu kıyı tipi?", secenekler: { A: "Ria", B: "Dalmaçya", C: "Ege Tipi (Enine)", D: "Limanlı" }, dogruCevap: "C" },
    { seviye: 158, kategori: "Coğrafya", soru: "Türkiye'nin tek aktif volkanik arazisi olmayan ancak en genç volkanik alanı?", secenekler: { A: "Kula Tepeleri", B: "Erciyes", C: "Nemrut", D: "Tendürek" }, dogruCevap: "A" },
    { seviye: 159, kategori: "Coğrafya", soru: "Aşağıdakilerden hangisi bir tektonik göldür?", secenekler: { A: "Sapanca Gölü", B: "Mebre Gölü", C: "Çıldır Gölü", D: "Sera Gölü" }, dogruCevap: "A" },
    { seviye: 160, kategori: "Coğrafya", soru: "Kızılırmak nehrinin Karadeniz'e döküldüğü yerde oluşan delta?", secenekler: { A: "Çarşamba", B: "Bafra", C: "Silifke", D: "Meriç" }, dogruCevap: "B" },
    { seviye: 161, kategori: "Coğrafya", soru: "Türkiye'de taş kömürü ile çalışan ilk termik santral hangisidir?", secenekler: { A: "Soma", B: "Yatağan", C: "Çatalağzı", D: "Hamitabat" }, dogruCevap: "C" },
    { seviye: 162, kategori: "Coğrafya", soru: "Gökçeada ve Bozcaada hangi ilimize bağlıdır?", secenekler: { A: "Balıkesir", B: "İzmir", C: "Çanakkale", D: "Edirne" }, dogruCevap: "C" },
    { seviye: 163, kategori: "Coğrafya", soru: "Erzurum-Kars platosunda en yaygın toprak tipi hangisidir?", secenekler: { A: "Terra Rossa", B: "Çernezyom", C: "Laterit", D: "Podzol" }, dogruCevap: "B" },
    { seviye: 164, kategori: "Coğrafya", soru: "Türkiye'nin en uzun tüneli olan Ovit Dağı Tüneli hangi illeri bağlar?", secenekler: { A: "Rize - Erzurum", B: "Trabzon - Gümüşhane", C: "Artvin - Ardahan", D: "Bolu - Düzce" }, dogruCevap: "A" },
    { seviye: 165, kategori: "Coğrafya", soru: "İğneada Longoz Ormanları hangi ilimizdedir?", secenekler: { A: "Tekirdağ", B: "Kırklareli", C: "İstanbul", D: "Kocaeli" }, dogruCevap: "B" },
    { seviye: 166, kategori: "Coğrafya", soru: "Hangi maden Türkiye'nin ihracatında önemli bir paya sahiptir?", secenekler: { A: "Mermer", B: "Petrol", C: "Doğalgaz", D: "Platin" }, dogruCevap: "A" },
    { seviye: 167, kategori: "Coğrafya", soru: "Sultan Sazlığı Kuş Cenneti hangi ilimizdedir?", secenekler: { A: "Konya", B: "Kayseri", C: "Aksaray", D: "Kırşehir" }, dogruCevap: "B" },
    { seviye: 168, kategori: "Coğrafya", soru: "Türkiye'de demiryolu bağlantısı olmayan liman şehri?", secenekler: { A: "Samsun", B: "Zonguldak", C: "Trabzon", D: "İskenderun" }, dogruCevap: "C" },
    { seviye: 169, kategori: "Coğrafya", soru: "Akdeniz'de yer alan ve 'Güller Gölü' olarak da bilinen göl?", secenekler: { A: "Beyşehir", B: "Eğirdir", C: "Salda", D: "Burdur" }, dogruCevap: "B" },
    { seviye: 170, kategori: "Coğrafya", soru: "Türkiye'nin ilk kağıt fabrikası (SEKA) nerede kurulmuştur?", secenekler: { A: "Giresun", B: "İzmit", C: "Zonguldak", D: "Muğla" }, dogruCevap: "B" },
    { seviye: 171, kategori: "Coğrafya", soru: "Ankara'nın simgesi olan ve tiftiği ile meşhur hayvan?", secenekler: { A: "Ankara Tavşanı", B: "Ankara Keçisi", C: "Ankara Kedisi", D: "Van Kedisi" }, dogruCevap: "B" },
    { seviye: 172, kategori: "Coğrafya", soru: "Fırat ve Dicle nehirleri birleşerek hangi adı alır?", secenekler: { A: "Şattülarap", B: "Mezopotamya", C: "Kızıldeniz", D: "Aras" }, dogruCevap: "A" },
    { seviye: 173, kategori: "Coğrafya", soru: "Türkiye'nin Maldivler'i olarak bilinen göl?", secenekler: { A: "Van Gölü", B: "Salda Gölü", C: "Bafa Gölü", D: "Meke Gölü" }, dogruCevap: "B" },
    { seviye: 174, kategori: "Coğrafya", soru: "Türkiye'de güneş enerjisinden faydalanma potansiyeli en düşük bölge?", secenekler: { A: "Güneydoğu Anadolu", B: "Karadeniz", C: "Akdeniz", D: "İç Anadolu" }, dogruCevap: "B" },
    { seviye: 175, kategori: "Coğrafya", soru: "Kop Geçidi hangi iki il arasındadır?", secenekler: { A: "Erzurum - Bayburt", B: "Trabzon - Gümüşhane", C: "Antalya - Isparta", D: "Adana - Niğde" }, dogruCevap: "A" },
    { seviye: 176, kategori: "Coğrafya", soru: "Antalya kıyılarında görülen, adalarla kaplı kıyı tipi?", secenekler: { A: "Ria", B: "Dalmaçya", C: "Boyuna", D: "Fiyort" }, dogruCevap: "B" },
    { seviye: 177, kategori: "Coğrafya", soru: "Türkiye'nin en büyük yer altı barajı nerede yapılmıştır?", secenekler: { A: "İstanbul (Şile)", B: "Ankara (Kalecik)", C: "İzmir (Çeşme)", D: "Konya (Kulu)" }, dogruCevap: "A" },
    { seviye: 178, kategori: "Coğrafya", soru: "Tuz Gölü'nden sonra Türkiye'nin tuz ihtiyacını karşılayan deniz kaynağı?", secenekler: { A: "Çamaltı Tuzlası", B: "Ayvalık Tuzlası", C: "Mersin Tuzlası", D: "Fethiye Tuzlası" }, dogruCevap: "A" },
    { seviye: 179, kategori: "Coğrafya", soru: "Hangi ilimizde doğalgaz çıkarma işlemi yapılmaktadır?", secenekler: { A: "Kırklareli (Hamitabat)", B: "Zonguldak", C: "Batman", D: "Mardin" }, dogruCevap: "A" },
    { seviye: 180, kategori: "Coğrafya", soru: "Türkiye'nin kenevir üretim merkezi haline gelen ilimiz?", secenekler: { A: "Samsun", B: "Kastamonu", C: "Rize", D: "Amasya" }, dogruCevap: "A" },
    { seviye: 181, kategori: "Coğrafya", soru: "Zeytin ağacının yetişme sınırı hangi iklimin sınırını belirler?", secenekler: { A: "Karadeniz İklimi", B: "Akdeniz İklimi", C: "Step İklimi", D: "Sert Karasal" }, dogruCevap: "B" },
    { seviye: 182, kategori: "Coğrafya", soru: "Söke, Aydın ve Torbalı ovaları hangi akarsuyun havzasındadır?", secenekler: { A: "Gediz", B: "Büyük Menderes", C: "Bakırçay", D: "Sakarya" }, dogruCevap: "B" },
    { seviye: 183, kategori: "Coğrafya", soru: "Türkiye'nin en büyük şeker fabrikası nerededir?", secenekler: { A: "Uşak", B: "Konya", C: "Afyon", D: "Erzurum" }, dogruCevap: "B" },
    { seviye: 184, kategori: "Coğrafya", soru: "Bakır madeni denilince akla gelen 'Küre' yatakları hangi ildedir?", secenekler: { A: "Artvin", B: "Elazığ", C: "Kastamonu", D: "Rize" }, dogruCevap: "C" },
    { seviye: 185, kategori: "Coğrafya", soru: "Boksit (Alüminyum) madeninin çıkarıldığı 'Seydişehir' hangi ile bağlıdır?", secenekler: { A: "Antalya", B: "Konya", C: "Muğla", D: "Isparta" }, dogruCevap: "B" },
    { seviye: 186, kategori: "Coğrafya", soru: "Anzer Balı ile ünlü olan yayla hangi ilimizdedir?", secenekler: { A: "Artvin", B: "Rize", C: "Trabzon", D: "Giresun" }, dogruCevap: "B" },
    { seviye: 187, kategori: "Coğrafya", soru: "Dünyanın en büyük 'Mermer Antik Kenti' olan Aphrodisias hangi ildedir?", secenekler: { A: "Aydın", B: "Denizli", C: "Muğla", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 188, kategori: "Coğrafya", soru: "Türkiye'de fındık üretiminde Ordu'dan sonra ikinci gelen il?", secenekler: { A: "Giresun", B: "Samsun", C: "Trabzon", D: "Sakarya" }, dogruCevap: "A" },
    { seviye: 189, kategori: "Coğrafya", soru: "Yat turizminin en çok geliştiği 'Mavi Yolculuk' rotası hangi bölgedir?", secenekler: { A: "Güney Marmara", B: "Güney Ege - Batı Akdeniz", C: "Doğu Karadeniz", D: "Çukurova" }, dogruCevap: "B" },
    { seviye: 190, kategori: "Coğrafya", soru: "İskenderun'da demir-çelik sanayisinin kurulma sebebi nedir?", secenekler: { A: "Hammadde", B: "Ulaşım (Liman)", C: "Enerji kaynağı", D: "İş gücü" }, dogruCevap: "B" },
    { seviye: 191, kategori: "Coğrafya", soru: "Türkiye'de büyükbaş hayvancılığın (mera) en yoğun olduğu yer?", secenekler: { A: "Ege", B: "Marmara", C: "Erzurum-Kars Bölümü", D: "İç Anadolu" }, dogruCevap: "C" },
    { seviye: 192, kategori: "Coğrafya", soru: "GAP kapsamında sulamaya açılan ilk büyük ova?", secenekler: { A: "Harran Ovası", B: "Ceylanpınar Ovası", C: "Suruç Ovası", D: "Birecik Ovası" }, dogruCevap: "A" },
    { seviye: 193, kategori: "Coğrafya", soru: "Bitlis'te bulunan ve dünyanın ikinci büyük krater gölü olan yer?", secenekler: { A: "Meke", B: "Nemrut Krater Gölü", C: "Acıgöl", D: "Gölcük" }, dogruCevap: "B" },
    { seviye: 194, kategori: "Coğrafya", soru: "Türkiye'nin en büyük milli parkı hangisidir?", secenekler: { A: "Munzur Vadisi", B: "Ağrı Dağı Milli Parkı", C: "Beyşehir Gölü", D: "Küre Dağları" }, dogruCevap: "B" },
    { seviye: 195, kategori: "Coğrafya", soru: "Ülkemizde yerel saati en ileri olan ilimiz hangisidir?", secenekler: { A: "Iğdır", B: "Hakkari", C: "Artvin", D: "Van" }, dogruCevap: "A" },
    { seviye: 196, kategori: "Coğrafya", soru: "Türkiye'de kıyı uzunluğu en fazla olan bölgemiz?", secenekler: { A: "Karadeniz", B: "Akdeniz", C: "Ege", D: "Marmara" }, dogruCevap: "C" },
    { seviye: 197, kategori: "Coğrafya", soru: "İstanbul ve Çanakkale boğazları hangi jeolojik zamanda oluşmuştur?", secenekler: { A: "1. Zaman", B: "2. Zaman", C: "3. Zaman", D: "4. Zaman (Kuvaterner)" }, dogruCevap: "D" },
    { seviye: 198, kategori: "Coğrafya", soru: "Türkiye'de kışın en soğuk il genellikle hangisidir?", secenekler: { A: "Erzurum", B: "Kars", C: "Ardahan", D: "Ağrı" }, dogruCevap: "C" },
    { seviye: 199, kategori: "Coğrafya", soru: "Yaz turizmi sezonunun en erken açıldığı ilimiz?", secenekler: { A: "Muğla", B: "Antalya", C: "Mersin", D: "İzmir" }, dogruCevap: "B" },
    { seviye: 200, kategori: "Coğrafya", soru: "Porsuk Çayı hangi ilimizin içinden geçer?", secenekler: { A: "Kütahya", B: "Afyon", C: "Eskişehir", D: "Bilecik" }, dogruCevap: "C" },

    // 201-250: Dünya Ülkeleri, Başkentler ve Önemli Yerler
    { seviye: 201, kategori: "Coğrafya", soru: "Almanya'nın başkenti neresidir?", secenekler: { A: "Münih", B: "Frankfurt", C: "Berlin", D: "Hamburg" }, dogruCevap: "C" },
    { seviye: 202, kategori: "Coğrafya", soru: "Fransa'nın simgesi olan Eyfel Kulesi hangi şehirdedir?", secenekler: { A: "Lyon", B: "Marsilya", C: "Paris", D: "Nice" }, dogruCevap: "C" },
    { seviye: 203, kategori: "Coğrafya", soru: "İtalya'nın başkenti neresidir?", secenekler: { A: "Milano", B: "Venedik", C: "Roma", D: "Floransa" }, dogruCevap: "C" },
    { seviye: 204, kategori: "Coğrafya", soru: "İspanya'nın başkenti neresidir?", secenekler: { A: "Barselona", B: "Madrid", C: "Sevilla", D: "Valencia" }, dogruCevap: "B" },
    { seviye: 205, kategori: "Coğrafya", soru: "Rusya'nın başkenti neresidir?", secenekler: { A: "St. Petersburg", B: "Moskova", C: "Kazan", D: "Sibirya" }, dogruCevap: "B" },
    { seviye: 206, kategori: "Coğrafya", soru: "Mısır'daki ünlü piramitler hangi şehirdedir?", secenekler: { A: "İskenderiye", B: "Kahire (Gize)", C: "Luksor", D: "Asvan" }, dogruCevap: "B" },
    { seviye: 207, kategori: "Coğrafya", soru: "Amerika Birleşik Devletleri'nin (ABD) başkenti neresidir?", secenekler: { A: "New York", B: "Los Angeles", C: "Washington D.C.", D: "Chicago" }, dogruCevap: "C" },
    { seviye: 208, kategori: "Coğrafya", soru: "Kanada'nın başkenti neresidir?", secenekler: { A: "Toronto", B: "Montreal", C: "Ottawa", D: "Vancouver" }, dogruCevap: "C" },
    { seviye: 209, kategori: "Coğrafya", soru: "Çin'in başkenti neresidir?", secenekler: { A: "Şanghay", B: "Pekin", C: "Hong Kong", D: "Guangzhou" }, dogruCevap: "B" },
    { seviye: 210, kategori: "Coğrafya", soru: "Japonya'nın başkenti neresidir?", secenekler: { A: "Osaka", B: "Kyoto", C: "Tokyo", D: "Hiroşima" }, dogruCevap: "C" },
    { seviye: 211, kategori: "Coğrafya", soru: "Hindistan'ın başkenti neresidir?", secenekler: { A: "Mumbai", B: "Yeni Delhi", C: "Kalküta", D: "Bangalore" }, dogruCevap: "B" },
    { seviye: 212, kategori: "Coğrafya", soru: "Güney Kore'nin başkenti neresidir?", secenekler: { A: "Busan", B: "Seul", C: "Incheon", D: "Daegu" }, dogruCevap: "B" },
    { seviye: 213, kategori: "Coğrafya", soru: "Avustralya'nın başkenti neresidir?", secenekler: { A: "Sidney", B: "Melbourne", C: "Canberra", D: "Brisbane" }, dogruCevap: "C" },
    { seviye: 214, kategori: "Coğrafya", soru: "Brezilya'nın başkenti neresidir?", secenekler: { A: "Rio de Janeiro", B: "Sao Paulo", C: "Brasilia", D: "Salvador" }, dogruCevap: "C" },
    { seviye: 215, kategori: "Coğrafya", soru: "Arjantin'in başkenti neresidir?", secenekler: { A: "Buenos Aires", B: "Rosario", C: "Cordoba", D: "Mendoza" }, dogruCevap: "A" },
    { seviye: 216, kategori: "Coğrafya", soru: "Güney Afrika Cumhuriyeti'nin üç başkentinden biri hangisidir?", secenekler: { A: "Johannesburg", B: "Cape Town", C: "Durban", D: "Soweto" }, dogruCevap: "B" },
    { seviye: 217, kategori: "Coğrafya", soru: "İngiltere'nin (Birleşik Krallık) başkenti neresidir?", secenekler: { A: "Manchester", B: "Liverpool", C: "Londra", D: "Birmingham" }, dogruCevap: "C" },
    { seviye: 218, kategori: "Coğrafya", soru: "Yunanistan'ın başkenti neresidir?", secenekler: { A: "Selanik", B: "Atina", C: "Patras", D: "Girit" }, dogruCevap: "B" },
    { seviye: 219, kategori: "Coğrafya", soru: "İran'ın başkenti neresidir?", secenekler: { A: "Tebriz", B: "Meşhed", C: "Tahran", D: "İsfahan" }, dogruCevap: "C" },
    { seviye: 220, kategori: "Coğrafya", soru: "Irak'ın başkenti neresidir?", secenekler: { A: "Basra", B: "Musul", C: "Bağdat", D: "Erbil" }, dogruCevap: "C" },
    { seviye: 221, kategori: "Coğrafya", soru: "Suriye'nin başkenti neresidir?", secenekler: { A: "Halep", B: "Şam", C: "Humus", D: "Lazkiye" }, dogruCevap: "B" },
    { seviye: 222, kategori: "Coğrafya", soru: "Azerbaycan'ın başkenti neresidir?", secenekler: { A: "Gence", B: "Nahçıvan", C: "Bakü", D: "Sumgayıt" }, dogruCevap: "C" },
    { seviye: 223, kategori: "Coğrafya", soru: "Hollanda'nın başkenti neresidir?", secenekler: { A: "Rotterdam", B: "Lahey", C: "Amsterdam", D: "Utrecht" }, dogruCevap: "C" },
    { seviye: 224, kategori: "Coğrafya", soru: "Belçika'nın başkenti ve AB merkezi olan şehir?", secenekler: { A: "Anvers", B: "Gent", C: "Brüksel", D: "Brugge" }, dogruCevap: "C" },
    { seviye: 225, kategori: "Coğrafya", soru: "İsviçre'nin başkenti neresidir?", secenekler: { A: "Zürih", B: "Cenevre", C: "Bern", D: "Basel" }, dogruCevap: "C" },
    { seviye: 226, kategori: "Coğrafya", soru: "Avusturya'nın başkenti neresidir?", secenekler: { A: "Salzburg", B: "Viyana", C: "Innsbruck", D: "Graz" }, dogruCevap: "B" },
    { seviye: 227, kategori: "Coğrafya", soru: "Portekiz'in başkenti neresidir?", secenekler: { A: "Porto", B: "Lizbon", C: "Braga", D: "Coimbra" }, dogruCevap: "B" },
    { seviye: 228, kategori: "Coğrafya", soru: "İsveç'in başkenti neresidir?", secenekler: { A: "Göteborg", B: "Malmö", C: "Stokholm", D: "Uppsala" }, dogruCevap: "C" },
    { seviye: 229, kategori: "Coğrafya", soru: "Norveç'in başkenti neresidir?", secenekler: { A: "Bergen", B: "Oslo", C: "Trondheim", D: "Stavanger" }, dogruCevap: "B" },
    { seviye: 230, kategori: "Coğrafya", soru: "Finlandiya'nın başkenti neresidir?", secenekler: { A: "Tampere", B: "Turku", C: "Helsinki", D: "Espoo" }, dogruCevap: "C" },
    { seviye: 231, kategori: "Coğrafya", soru: "Danimarka'nın başkenti neresidir?", secenekler: { A: "Aarhus", B: "Odense", C: "Kopenhag", D: "Aalborg" }, dogruCevap: "C" },
    { seviye: 232, kategori: "Coğrafya", soru: "Macaristan'ın başkenti neresidir?", secenekler: { A: "Debrecen", B: "Budapeşte", C: "Szeged", D: "Miskolc" }, dogruCevap: "B" },
    { seviye: 233, kategori: "Coğrafya", soru: "Polonya'nın başkenti neresidir?", secenekler: { A: "Krakow", B: "Varşova", C: "Gdansk", D: "Wroclaw" }, dogruCevap: "B" },
    { seviye: 234, kategori: "Coğrafya", soru: "Ukrayna'nın başkenti neresidir?", secenekler: { A: "Harkiv", B: "Odessa", C: "Kiev", D: "Lviv" }, dogruCevap: "C" },
    { seviye: 235, kategori: "Coğrafya", soru: "Meksika'nın başkenti neresidir?", secenekler: { A: "Cancun", B: "Guadalajara", C: "Meksiko", D: "Monterrey" }, dogruCevap: "C" },
    { seviye: 236, kategori: "Coğrafya", soru: "Küba'nın başkenti neresidir?", secenekler: { A: "Santiago", B: "Havana", C: "Varadero", D: "Holguin" }, dogruCevap: "B" },
    { seviye: 237, kategori: "Coğrafya", soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Phuket", B: "Bangkok", C: "Pattaya", D: "Chiang Mai" }, dogruCevap: "B" },
    { seviye: 238, kategori: "Coğrafya", soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Ho Chi Minh", B: "Hanoi", C: "Da Nang", D: "Hue" }, dogruCevap: "B" },
    { seviye: 239, kategori: "Coğrafya", soru: "Suudi Arabistan'ın başkenti neresidir?", secenekler: { A: "Cidde", B: "Mekke", C: "Riyad", D: "Medine" }, dogruCevap: "C" },
    { seviye: 240, kategori: "Coğrafya", soru: "Birleşik Arap Emirlikleri'nin başkenti neresidir?", secenekler: { A: "Dubai", B: "Abu Dabi", C: "Şarika", D: "Acman" }, dogruCevap: "B" },
    { seviye: 241, kategori: "Coğrafya", soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Doha", B: "Al Wakrah", C: "Al Khor", D: "Lusail" }, dogruCevap: "A" },
    { seviye: 242, kategori: "Coğrafya", soru: "Fas'ın başkenti neresidir?", secenekler: { A: "Kazablanka", B: "Marakeş", C: "Rabat", D: "Fes" }, dogruCevap: "C" },
    { seviye: 243, kategori: "Coğrafya", soru: "Cezayir'in başkenti neresidir?", secenekler: { A: "Vahran", B: "Cezayir", C: "Konstantin", D: "Annaba" }, dogruCevap: "B" },
    { seviye: 244, kategori: "Coğrafya", soru: "Tunus'un başkenti neresidir?", secenekler: { A: "Susa", B: "Tunus", C: "Kayrevan", D: "Sfaks" }, dogruCevap: "B" },
    { seviye: 245, kategori: "Coğrafya", soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "Karaçi", B: "Lahor", C: "İslamabad", D: "Peşaver" }, dogruCevap: "C" },
    { seviye: 246, kategori: "Coğrafya", soru: "Kazakistan'ın başkenti (yeni adıyla) neresidir?", secenekler: { A: "Almatı", B: "Astana", C: "Çimkent", D: "Aktau" }, dogruCevap: "B" },
    { seviye: 247, kategori: "Coğrafya", soru: "Özbekistan'ın başkenti neresidir?", secenekler: { A: "Semerkant", B: "Buhara", C: "Taşkent", D: "Hiva" }, dogruCevap: "C" },
    { seviye: 248, kategori: "Coğrafya", soru: "Türkmenistan'ın başkenti neresidir?", secenekler: { A: "Merv", B: "Aşkabat", C: "Türkmenbaşı", D: "Daşoğuz" }, dogruCevap: "B" },
    { seviye: 249, kategori: "Coğrafya", soru: "Kırgızistan'ın başkenti neresidir?", secenekler: { A: "Oş", B: "Bişkek", C: "Celal-Abad", D: "Karakol" }, dogruCevap: "B" },
    { seviye: 250, kategori: "Coğrafya", soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Erdenet", B: "Ulan Batur", C: "Darhan", D: "Ölgiy" }, dogruCevap: "B" },

    // 251-301: Dünya Genel Kültür, Coğrafi Terimler ve Ekstrem Bilgiler
    { seviye: 251, kategori: "Coğrafya", soru: "Dünyanın en yüksek debili nehri hangisidir?", secenekler: { A: "Nil", B: "Mississippi", C: "Amazon", D: "Ganj" }, dogruCevap: "C" },
    { seviye: 252, kategori: "Coğrafya", soru: "Dünyanın en büyük gölü (yüzölçümü) hangisidir?", secenekler: { A: "Hazar Denizi", B: "Superior Gölü", C: "Victoria Gölü", D: "Baykal Gölü" }, dogruCevap: "A" },
    { seviye: 253, kategori: "Coğrafya", soru: "Hangi ülke en çok adaya sahiptir (yaklaşık 267.000)?", secenekler: { A: "Endonezya", B: "Filipinler", C: "İsveç", D: "Norveç" }, dogruCevap: "C" },
    { seviye: 254, kategori: "Coğrafya", soru: "Dünyanın en kurak çölü hangisidir?", secenekler: { A: "Sahra", B: "Atacama", C: "Gobi", D: "Kalahari" }, dogruCevap: "B" },
    { seviye: 255, kategori: "Coğrafya", soru: "Panama Kanalı hangi iki kıtayı ayırır?", secenekler: { A: "Asya - Avrupa", B: "Kuzey Amerika - Güney Amerika", C: "Afrika - Asya", D: "Avrupa - Afrika" }, dogruCevap: "B" },
    { seviye: 256, kategori: "Coğrafya", soru: "Dünyanın en geniş boğazı hangisidir?", secenekler: { A: "Cebelitarık", B: "Drake Boğazı", C: "Bering Boğazı", D: "Malakka" }, dogruCevap: "B" },
    { seviye: 257, kategori: "Coğrafya", soru: "Güneşin hiç batmadığı 'Gece Yarısı Güneşi' olayı nerede görülür?", secenekler: { A: "Ekvator", B: "Kutup Daireleri", C: "Dönenceler", D: "Orta Kuşak" }, dogruCevap: "B" },
    { seviye: 258, kategori: "Coğrafya", soru: "Hangi deniz tamamen kara ile çevrilidir (Limanı yoktur)?", secenekler: { A: "Kızıldeniz", B: "Hazar Denizi", C: "Umman Denizi", D: "Karadeniz" }, dogruCevap: "B" },
    { seviye: 259, kategori: "Coğrafya", soru: "Dünyanın en büyük yarımadası hangisidir?", secenekler: { A: "Hindistan", B: "İskandinavya", C: "Arap Yarımadası", D: "Anadolu" }, dogruCevap: "C" },
    { seviye: 260, kategori: "Coğrafya", soru: "Hangi ülkeye 'Bin Göller Ülkesi' denir?", secenekler: { A: "İsveç", B: "Kanada", C: "Finlandiya", D: "Norveç" }, dogruCevap: "C" },
    { seviye: 261, kategori: "Coğrafya", soru: "Dünyanın en yüksek başkenti (La Paz) hangi ülkededir?", secenekler: { A: "Peru", B: "Ekvador", C: "Bolivya", D: "Nepal" }, dogruCevap: "C" },
    { seviye: 262, kategori: "Coğrafya", soru: "Bering Boğazı hangi iki ülkeyi birbirinden ayırır?", secenekler: { A: "ABD - Rusya", B: "Kanada - Grönland", C: "İngiltere - Fransa", D: "Japonya - Çin" }, dogruCevap: "A" },
    { seviye: 263, kategori: "Coğrafya", soru: "Hangi nehir Avrupa'nın 10 ülkesinden geçerek Karadeniz'e dökülür?", secenekler: { A: "Ren", B: "Tuna", C: "Volga", D: "Elbe" }, dogruCevap: "B" },
    { seviye: 264, kategori: "Coğrafya", soru: "Machu Picchu antik kenti hangi ülkededir?", secenekler: { A: "Meksika", B: "Peru", C: "Şili", D: "Kolombiya" }, dogruCevap: "B" },
    { seviye: 265, kategori: "Coğrafya", soru: "Dünyanın en büyük mercan resifi hangisidir?", secenekler: { A: "Büyük Set Resifi", B: "Belize Resifi", C: "Andaman Resifi", D: "Kızıldeniz Resifi" }, dogruCevap: "A" },
    { seviye: 266, kategori: "Coğrafya", soru: "Hangi nehir üzerine kurulu Victoria Şelalesi ile ünlüdür?", secenekler: { A: "Kongo", B: "Zambezi", C: "Nil", D: "Nijer" }, dogruCevap: "B" },
    { seviye: 267, kategori: "Coğrafya", soru: "Dünyanın en büyük ormanlık alanı (Tayga) hangi ülkededir?", secenekler: { A: "Brezilya", B: "Kanada", C: "Rusya", D: "ABD" }, dogruCevap: "C" },
    { seviye: 268, kategori: "Coğrafya", soru: "Dünya nüfusunun yaklaşık yarısı hangi kıtada yaşar?", secenekler: { A: "Avrupa", B: "Afrika", C: "Asya", D: "Amerika" }, dogruCevap: "C" },
    { seviye: 269, kategori: "Coğrafya", soru: "Kilimanjaro Dağı hangi ülkededir?", secenekler: { A: "Kenya", B: "Tanzanya", C: "Etiyopya", D: "Uganda" }, dogruCevap: "B" },
    { seviye: 270, kategori: "Coğrafya", soru: "Hangi boğaz Basra Körfezi'ni Umman Denizi'ne bağlar ve petrol taşımacılığında kritiktir?", secenekler: { A: "Malakka", B: "Hürmüz", C: "Babülmendep", D: "Hürmüz" }, dogruCevap: "B" },
    { seviye: 271, kategori: "Coğrafya", soru: "Dünyanın en küçük okyanusu hangisidir?", secenekler: { A: "Hint", B: "Güney", C: "Arktik (Kuzey Buz)", D: "Atlas" }, dogruCevap: "C" },
    { seviye: 272, kategori: "Coğrafya", soru: "Hangi ülke iki kıtada toprağı olmasına rağmen Avrupa ülkesi sayılır?", secenekler: { A: "Türkiye", B: "Rusya", C: "Kazakistan", D: "Mısır" }, dogruCevap: "B" },
    { seviye: 273, kategori: "Coğrafya", soru: "İzlanda hangi okyanustadır?", secenekler: { A: "Pasifik", B: "Atlas", C: "Hint", D: "Arktik" }, dogruCevap: "B" },
    { seviye: 274, kategori: "Coğrafya", soru: "Dünyanın en derin gölü hangisidir?", secenekler: { A: "Hazar", B: "Tanganika", C: "Baykal", D: "Superior" }, dogruCevap: "C" },
    { seviye: 275, kategori: "Coğrafya", soru: "Ekvator çizgisi hangi kıtadan geçmez?", secenekler: { A: "Güney Amerika", B: "Afrika", C: "Asya", D: "Avrupa" }, dogruCevap: "D" },
    { seviye: 276, kategori: "Coğrafya", soru: "Hangi ülke topraklarında hiç dağ yoktur?", secenekler: { A: "Hollanda", B: "Maldivler", C: "Danimarka", D: "Katar" }, dogruCevap: "B" },
    { seviye: 277, kategori: "Coğrafya", soru: "Dünyanın en kalabalık adası hangisidir?", secenekler: { A: "Büyük Britanya", B: "Java", C: "Honshu", D: "Manhattan" }, dogruCevap: "B" },
    { seviye: 278, kategori: "Coğrafya", soru: "Everest Dağı'na tırmanan ilk kişiler kimlerdir?", secenekler: { A: "Edmund Hillary - Tenzing Norgay", B: "Neil Armstrong", C: "Marco Polo", D: "Christopher Columbus" }, dogruCevap: "A" },
    { seviye: 279, kategori: "Coğrafya", soru: "Hangi rüzgar türü sadece tropikal kuşakta görülür?", secenekler: { A: "Meltem", B: "Tayfun", C: "Mistral", D: "Poyraz" }, dogruCevap: "B" },
    { seviye: 280, kategori: "Coğrafya", soru: "Atlas Dağları hangi kıtadadır?", secenekler: { A: "Asya", B: "Afrika", C: "Avrupa", D: "Güney Amerika" }, dogruCevap: "B" },
    { seviye: 281, kategori: "Coğrafya", soru: "Dünyanın en büyük limanı (konteyner trafiği) hangisidir?", secenekler: { A: "Rotterdam", B: "Singapur", C: "Şanghay", D: "Dubai" }, dogruCevap: "C" },
    { seviye: 282, kategori: "Coğrafya", soru: "Hangi ülkeye 'Gökkuşağı Ulusu' denir?", secenekler: { A: "Brezilya", B: "Güney Afrika", C: "ABD", D: "Hindistan" }, dogruCevap: "B" },
    { seviye: 283, kategori: "Coğrafya", soru: "Dünyanın en uzun demiryolu hattı (Trans-Sibirya) nerededir?", secenekler: { A: "Çin", B: "Rusya", C: "ABD", D: "Kanada" }, dogruCevap: "B" },
    { seviye: 284, kategori: "Coğrafya", soru: "Kızıldeniz ile Hint Okyanusu'nu bağlayan boğaz?", secenekler: { A: "Hürmüz", B: "Babülmendep", C: "Malakka", D: "Süveyş" }, dogruCevap: "B" },
    { seviye: 285, kategori: "Coğrafya", soru: "Dünyanın en eski metrosu hangi şehirdedir?", secenekler: { A: "New York", B: "Londra", C: "Paris", D: "İstanbul" }, dogruCevap: "B" },
    { seviye: 286, kategori: "Coğrafya", soru: "Hangi ülke hem Akdeniz'e hem Atlas Okyanusu'na kıyısı vardır?", secenekler: { A: "İtalya", B: "Fransa", C: "Yunanistan", D: "Mısır" }, dogruCevap: "B" },
    { seviye: 287, kategori: "Coğrafya", soru: "Dünyanın en büyük buzulu hangi kıtadadır?", secenekler: { A: "Asya", B: "Avrupa", C: "Antarktika", D: "Kuzey Amerika" }, dogruCevap: "C" },
    { seviye: 288, kategori: "Coğrafya", soru: "Ölü Deniz (Lut Gölü) deniz seviyesinden yaklaşık kaç metre aşağıdadır?", secenekler: { A: "100m", B: "430m", C: "800m", D: "1200m" }, dogruCevap: "B" },
    { seviye: 289, kategori: "Coğrafya", soru: "Hangi nehir New York şehrinin içinden geçer?", secenekler: { A: "Hudson", B: "Thames", C: "Seine", D: "Danube" }, dogruCevap: "A" },
    { seviye: 290, kategori: "Coğrafya", soru: "Dünyanın en büyük kahve üreticisi hangisidir?", secenekler: { A: "Vietnam", B: "Kolombiya", C: "Brezilya", D: "Etiyopya" }, dogruCevap: "C" },
    { seviye: 291, kategori: "Coğrafya", soru: "Paskalya Adası hangi ülkeye bağlıdır?", secenekler: { A: "Ekvador", B: "Peru", C: "Şili", D: "Avustralya" }, dogruCevap: "C" },
    { seviye: 292, kategori: "Coğrafya", soru: "Hangi ülke topraklarında nehir olmamasına rağmen yeraltı suları ile tarım yapar?", secenekler: { A: "Mısır", B: "Suudi Arabistan", C: "Ürdün", D: "Umman" }, dogruCevap: "B" },
    { seviye: 293, kategori: "Coğrafya", soru: "Dünyanın en büyük çöllerinden biri olan Gobi Çölü hangi iki ülke arasındadır?", secenekler: { A: "Çin - Moğolistan", B: "Hindistan - Pakistan", C: "İran - Irak", D: "Mısır - Libya" }, dogruCevap: "A" },
    { seviye: 294, kategori: "Coğrafya", soru: "Madagaskar adası hangi okyanustadır?", secenekler: { A: "Pasifik", B: "Atlas", C: "Hint", D: "Güney" }, dogruCevap: "C" },
    { seviye: 295, kategori: "Coğrafya", soru: "Hangi kıta 'Karanlık Kıta' olarak adlandırılırdı?", secenekler: { A: "Antarktika", B: "Afrika", C: "Asya", D: "Avrupa" }, dogruCevap: "B" },
    { seviye: 296, kategori: "Coğrafya", soru: "Dünyanın en yüksek yanardağı hangisidir?", secenekler: { A: "Etna", B: "Vezüv", C: "Ojos del Salado", D: "Fuji" }, dogruCevap: "C" },
    { seviye: 297, kategori: "Coğrafya", soru: "Hangi boğaz Asya ve Avrupa'yı ayırırken aynı zamanda İstanbul'un kalbidir?", secenekler: { A: "Çanakkale Boğazı", B: "İstanbul Boğazı", C: "Hürmüz Boğazı", D: "Cebelitarık" }, dogruCevap: "B" },
    { seviye: 298, kategori: "Coğrafya", soru: "Dünyanın en büyük stadyumu olan Rungrado 1 Mayıs Stadyumu nerededir?", secenekler: { A: "Güney Kore", B: "Kuzey Kore", C: "Çin", D: "Brezilya" }, dogruCevap: "B" },
    { seviye: 299, kategori: "Coğrafya", soru: "Dünyanın en çok yağış alan adası (Hawaii'de) hangisidir?", secenekler: { A: "Kauai", B: "Oahu", C: "Maui", D: "Lana'i" }, dogruCevap: "A" },
    { seviye: 300, kategori: "Coğrafya", soru: "Türkiye'nin matematiksel konumu (paralel) hangisidir?", secenekler: { A: "26-45 Doğu", B: "36-42 Kuzey", C: "36-42 Güney", D: "26-45 Batı" }, dogruCevap: "B" },
    { seviye: 301, kategori: "Coğrafya", soru: "Dünya'nın şekli kutuplardan basık, ekvatordan şişkindir. Bu şekle ne denir?", secenekler: { A: "Elips", B: "Geoid", C: "Daire", D: "Küre" }, dogruCevap: "B" } 
 
);
 