// Eğer dizi yoksa oluştur, varsa içine ekle
window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-20: Türkiye Coğrafyası ve Şehirler
    { kategori: "Genel Kültür", seviye: 1, soru: "Türkiye'nin başkenti neresidir?", secenekler: { A: "İstanbul", B: "Ankara", C: "İzmir", D: "Bursa" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 2, soru: "Türkiye'nin en yüksek dağı hangisidir?", secenekler: { A: "Erciyes", B: "Ağrı Dağı", C: "Süphan", D: "Kaçkar" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 3, soru: "Ege Bölgesi'nin en kalabalık şehri hangisidir?", secenekler: { A: "Aydın", B: "Muğla", C: "Denizli", D: "İzmir" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 4, soru: "Türkiye'nin en büyük gölü hangisidir?", secenekler: { A: "Tuz Gölü", B: "Van Gölü", C: "Beyşehir Gölü", D: "Eğirdir Gölü" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 5, soru: "Yedi göller hangi ilimiz sınırları içerisindedir?", secenekler: { A: "Bolu", B: "Rize", C: "Trabzon", D: "Artvin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 6, soru: "Pamukkale Travertenleri hangi ilimizdedir?", secenekler: { A: "Denizli", B: "Afyon", C: "Uşak", D: "Manisa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 7, soru: "Türkiye'nin en uzun nehri hangisidir?", secenekler: { A: "Fırat", B: "Dicle", C: "Kızılırmak", D: "Sakarya" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 8, soru: "Güneydoğu Anadolu'nun 'Peygamberler Şehri' olarak bilinen ili hangisidir?", secenekler: { A: "Şanlıurfa", B: "Gaziantep", C: "Diyarbakır", D: "Mardin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 9, soru: "Peri Bacaları hangi turistik bölgemizde yer alır?", secenekler: { A: "Kapadokya", B: "Ihlara Vadisi", C: "Pamukkale", D: "Efes" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 10, soru: "Mevlana Müzesi hangi ilimizdedir?", secenekler: { A: "Ankara", B: "Konya", C: "Kayseri", D: "Sivas" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 11, soru: "Türkiye'nin üç tarafı denizlerle çevrili olması nedeniyle hangi coğrafi tanıma uyar?", secenekler: { A: "Ada", B: "Yarımada", C: "Körfez", D: "Vaha" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 12, soru: "Dünyanın en eski yerleşim yerlerinden biri olan Göbeklitepe hangi ilimizdedir?", secenekler: { A: "Şanlıurfa", B: "Adıyaman", C: "Hatay", D: "Batman" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 13, soru: "Aspendos Antik Tiyatrosu hangi ilimizdedir?", secenekler: { A: "Antalya", B: "Muğla", C: "İzmir", D: "Mersin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 14, soru: "Çay üretimiyle meşhur olan Karadeniz ilimiz hangisidir?", secenekler: { A: "Rize", B: "Artvin", C: "Giresun", D: "Ordu" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 15, soru: "Kayısısı ile ünlü ilimiz hangisidir?", secenekler: { A: "Malatya", B: "Elazığ", C: "Erzincan", D: "Kars" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 16, soru: "İstiklal Madalyası alan ilk ilçemiz hangisidir?", secenekler: { A: "İnebolu", B: "Kazan", C: "Polatlı", D: "Maraş" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 17, soru: "Çanakkale Boğazı ile İstanbul Boğazı arasındaki deniz hangisidir?", secenekler: { A: "Marmara Denizi", B: "Ege Denizi", C: "Karadeniz", D: "Akdeniz" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 18, soru: "Cumhuriyet döneminin ilk barajı hangisidir?", secenekler: { A: "Çubuk Barajı", B: "Atatürk Barajı", C: "Keban Barajı", D: "Hirfanlı Barajı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 19, soru: "Türkiye'nin en kuzey noktası olan İnceburun hangi ilimizdedir?", secenekler: { A: "Sinop", B: "Kırklareli", C: "Artvin", D: "Zonguldak" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 20, soru: "Ülkemizin en büyük adası hangisidir?", secenekler: { A: "Gökçeada", B: "Bozcaada", C: "Büyükada", D: "Cunda" }, dogruCevap: "A" },

    // 21-40: Türk Tarihi ve Milli Değerler
    { kategori: "Genel Kültür", seviye: 21, soru: "İstiklal Marşı'mızın şairi kimdir?", secenekler: { A: "Ziya Gökalp", B: "Namık Kemal", C: "Mehmet Akif Ersoy", D: "Yahya Kemal" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 22, soru: "Cumhuriyet kaç yılında ilan edilmiştir?", secenekler: { A: "1920", B: "1921", C: "1923", D: "1924" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 23, soru: "Anadolu'nun kapılarını Türklere açan savaş hangisidir?", secenekler: { A: "Miryokefalon", B: "Malazgirt", C: "Pasinler", D: "Dandanakan" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 24, soru: "İstanbul hangi yıl fethedilmiştir?", secenekler: { A: "1071", B: "1299", C: "1453", D: "1517" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 25, soru: "Osmanlı Devleti'nin kurucusu kimdir?", secenekler: { A: "Ertuğrul Gazi", B: "Osman Bey", C: "Orhan Bey", D: "Selçuk Bey" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 26, soru: "Türkiye Büyük Millet Meclisi (TBMM) hangi tarihte açılmıştır?", secenekler: { A: "29 Ekim 1923", B: "23 Nisan 1920", C: "19 Mayıs 1919", D: "30 Ağustos 1922" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 27, soru: "Mustafa Kemal Atatürk'ün nüfusa kayıtlı olduğu il hangisidir?", secenekler: { A: "Selanik", B: "İstanbul", C: "Ankara", D: "Gaziantep" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 28, soru: "Atatürk'ün ebedi istirahatgahı olan Anıtkabir hangi şehrimizdedir?", secenekler: { A: "Ankara", B: "İstanbul", C: "İzmir", D: "Samsun" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 29, soru: "Tarihte Türk adıyla kurulan ilk devlet hangisidir?", secenekler: { A: "Hunlar", B: "Göktürkler", C: "Uygurlar", D: "Selçuklular" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 30, soru: "Sivas Kongresi hangi binada yapılmıştır?", secenekler: { A: "Sivas Lisesi", B: "Hükümet Konağı", C: "Ulu Cami", D: "Gök Medrese" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 31, soru: "Çanakkale Zaferi hangi gün kutlanır?", secenekler: { A: "18 Mart", B: "19 Mayıs", C: "30 Ağustos", D: "29 Ekim" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 32, soru: "Osmanlı'nın ilk başkenti neresidir?", secenekler: { A: "Söğüt", B: "Bursa", C: "Edirne", D: "İznik" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 33, soru: "Hangi padişah 'Fatih' unvanını almıştır?", secenekler: { A: "II. Mehmet", B: "I. Selim", C: "I. Süleyman", D: "II. Abdülhamid" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 34, soru: "Türklere özgü, dünyanın en eski yaylı çalgılarından biri hangisidir?", secenekler: { A: "Kopuz", B: "Bağlama", C: "Ud", D: "Kanun" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 35, soru: "Orhun Abideleri günümüzde hangi ülke sınırları içerisindedir?", secenekler: { A: "Moğolistan", B: "Kazakistan", C: "Özbekistan", D: "Türkiye" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 36, soru: "Dede Korkut hikayeleri hangi Türk boyuna aittir?", secenekler: { A: "Oğuzlar", B: "Kıpçaklar", C: "Karluklar", D: "Uygurlar" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 37, soru: "Mimar Sinan'ın 'Ustalık Eserim' dediği cami hangisidir?", secenekler: { A: "Selimiye Camii", B: "Süleymaniye Camii", C: "Şehzade Camii", D: "Sultan Ahmet Camii" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 38, soru: "Lale Devri hangi padişah zamanında yaşanmıştır?", secenekler: { A: "III. Ahmed", B: "IV. Murad", C: "II. Mahmud", D: "Abdülaziz" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 39, soru: "Cumhuriyet tarihinin ilk kadın muhtarı kimdir?", secenekler: { A: "Gül Esin", B: "Sabiha Gökçen", C: "Afet İnan", D: "Türkan Saylan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 40, soru: "Türklerin kullandığı ilk takvim hangisidir?", secenekler: { A: "12 Hayvanlı Türk Takvimi", B: "Hicri Takvim", C: "Rumi Takvim", D: "Miladi Takvim" }, dogruCevap: "A" },

    // 41-60: Türk Edebiyatı ve Sanat
    { kategori: "Genel Kültür", seviye: 41, soru: "Şair-i Azam olarak bilinen şairimiz kimdir?", secenekler: { A: "Abdülhak Hamit Tarhan", B: "Tevfik Fikret", C: "Cahit Sıtkı Tarancı", D: "Nazım Hikmet" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 42, soru: "Mai ve Siyah romanı kime aittir?", secenekler: { A: "Halit Ziya Uşaklıgil", B: "Yakup Kadri", C: "Reşat Nuri", D: "Peyami Safa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 43, soru: "Hababam Sınıfı'nın yazarı kimdir?", secenekler: { A: "Rıfat Ilgaz", B: "Aziz Nesin", C: "Orhan Kemal", D: "Yaşar Kemal" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 44, soru: "Kuyucaklı Yusuf romanı kime aittir?", secenekler: { A: "Sabahattin Ali", B: "Peyami Safa", C: "Ahmet Hamdi Tanpınar", D: "Tarık Buğra" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 45, soru: "Vatan Şairi olarak bilinen yazarımız?", secenekler: { A: "Namık Kemal", B: "Ziya Paşa", C: "Mehmet Akif", D: "Necip Fazıl" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 46, soru: "Türkçenin ilk sözlüğü hangisidir?", secenekler: { A: "Divanü Lügati't-Türk", B: "Muhakemetü'l-Lügateyn", C: "Kamusu Türki", D: "Lehçe-i Osmani" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 47, soru: "Çalıkuşu romanının baş kahramanı kimdir?", secenekler: { A: "Feride", B: "Eylül", C: "Bihter", D: "Zehra" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 48, soru: "Türk edebiyatında ilk yerli roman hangisidir?", secenekler: { A: "Taaşşuk-ı Talat ve Fitnat", B: "İntibah", C: "Araba Sevdası", D: "Karabibik" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 49, soru: "Sinekli Bakkal romanı kime aittir?", secenekler: { A: "Halide Edip Adıvar", B: "Reşat Nuri", C: "Yakup Kadri", D: "Ömer Seyfettin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 50, soru: "Yaprak Dökümü romanı kime aittir?", secenekler: { A: "Reşat Nuri Güntekin", B: "Peyami Safa", C: "Tarık Buğra", D: "Kemal Tahir" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 51, soru: "Mesnevi eseri kime aittir?", secenekler: { A: "Mevlana", B: "Yunus Emre", C: "Hacı Bektaş Veli", D: "Ahmet Yesevi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 52, soru: "Risaletü'n-Nushiyye kime aittir?", secenekler: { A: "Yunus Emre", B: "Pir Sultan Abdal", C: "Kaygusuz Abdal", D: "Karacaoğlan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 53, soru: "Şerbetçi ve dondurmacı tiplemeleriyle ünlü Türk gölge oyunu?", secenekler: { A: "Karagöz ve Hacivat", B: "Meddah", C: "Orta Oyunu", D: "Köy Seyirlik Oyunları" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 54, soru: "Geleneksel Türk tiyatrosunda doğaçlama yapılan oyun?", secenekler: { A: "Orta Oyunu", B: "Trajedi", C: "Komedi", D: "Opera" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 55, soru: "Makber şiiri kime aittir?", secenekler: { A: "Abdülhak Hamit Tarhan", B: "Recaizade Mahmut Ekrem", C: "Muallim Naci", D: "Şinasi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 56, soru: "Modern Türk öykücülüğünün öncüsü kimdir?", secenekler: { A: "Sait Faik Abasıyanık", B: "Ömer Seyfettin", C: "Memduh Şevket Esendal", D: "Sabahattin Ali" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 57, soru: "Otuz Beş Yaş şiiriyle tanınan şairimiz?", secenekler: { A: "Cahit Sıtkı Tarancı", B: "Ahmet Muhip Dıranas", C: "Ziya Osman Saba", D: "Behçet Necatigil" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 58, soru: "İnce Memed romanı kime aittir?", secenekler: { A: "Yaşar Kemal", B: "Orhan Kemal", C: "Kemal Tahir", D: "Fakir Baykurt" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 59, soru: "Dokuzuncu Hariciye Koğuşu kime aittir?", secenekler: { A: "Peyami Safa", B: "Ahmet Hamdi Tanpınar", C: "Tarık Buğra", D: "Samiha Ayverdi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 60, soru: "Safahat eseri kime aittir?", secenekler: { A: "Mehmet Akif Ersoy", B: "Yahya Kemal", C: "Tevfik Fikret", D: "Ziya Gökalp" }, dogruCevap: "A" },

    // 61-80: Türk Kültürü, Gelenek ve Spor
    { kategori: "Genel Kültür", seviye: 61, soru: "Türklerin milli sporu olarak kabul edilen spor dalı?", secenekler: { A: "Güreş", B: "Okçuluk", C: "Cirit", D: "Binicilik" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 62, soru: "Dünyanın en eski güreş festivali hangisidir?", secenekler: { A: "Kırkpınar Yağlı Güreşleri", B: "Elmalı Güreşleri", C: "Kurtdere Güreşleri", D: "Karakucak Güreşleri" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 63, soru: "Türklere özgü, at üzerinde oynanan geleneksel spor?", secenekler: { A: "Cirit", B: "Matrak", C: "Gökbörü", D: "Tepük" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 64, soru: "Türk kahvesi pişirilirken kullanılan küçük saplı kaba ne denir?", secenekler: { A: "Cezve", B: "Güğüm", C: "İbrik", D: "Semaver" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 65, soru: "Erzurum ve çevresinde oynanan halk oyunu?", secenekler: { A: "Bar", B: "Zeybek", C: "Horon", D: "Halay" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 66, soru: "Ege Bölgesi ile özdeşleşmiş halk oyunu?", secenekler: { A: "Zeybek", B: "Horon", C: "Kaşık Oyunu", D: "Bengi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 67, soru: "Karadeniz bölgesine ait, kemençe eşliğinde oynanan oyun?", secenekler: { A: "Horon", B: "Halay", C: "Çayda Çıra", D: "Atabarı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 68, soru: "Trakya yöresine ait ünlü halk oyunu?", secenekler: { A: "Hora", B: "Bar", C: "Mengi", D: "Zeybek" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 69, soru: "Türk mutfağının vazgeçilmezi olan, fermente edilmiş süt ürünü?", secenekler: { A: "Yoğurt", B: "Peynir", C: "Krema", D: "Kefir" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 70, soru: "Türk mutfağında ince hamurdan yapılan, içi kıymalı veya patatesli yemek?", secenekler: { A: "Mantı", B: "Börek", C: "Lahmacun", D: "Pide" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 71, soru: "Keloğlan hangi Türk kültür ögesine aittir?", secenekler: { A: "Masal", B: "Destan", C: "Efsane", D: "Ağıt" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 72, soru: "Nasreddin Hoca fıkralarıyla ünlü şehrimiz?", secenekler: { A: "Akşehir", B: "Eskişehir", C: "Kütahya", D: "Afyon" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 73, soru: "Baharın müjdecisi olarak kutlanan Türk bayramı?", secenekler: { A: "Nevruz", B: "Hıdırellez", C: "Kurban Bayramı", D: "Ramazan Bayramı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 74, soru: "Geleneksel Türk ebru sanatında kullanılan ana malzeme?", secenekler: { A: "Kitre", B: "Yağ", C: "Alçı", D: "Kil" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 75, soru: "Hat sanatı ile uğraşan sanatçılara ne denir?", secenekler: { A: "Hattat", B: "Müzehhip", C: "Ebruli", D: "Nakkaş" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 76, soru: "Eski yazma kitapları süsleyen küçük resim sanatı?", secenekler: { A: "Minyatür", B: "Çini", C: "Tezhip", D: "Fresk" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 77, soru: "Çini sanatı ile dünyaca ünlü ilimiz?", secenekler: { A: "Kütahya", B: "İzmit", C: "Bursa", D: "Konya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 78, soru: "Dünyanın en eski askeri bandosu hangisidir?", secenekler: { A: "Mehter Takımı", B: "Bando Mızıka", C: "Orkestra", D: "Filarmoni" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 79, soru: "Türk bayrağındaki hilal ve yıldız neyi temsil eder (sembolik olarak)?", secenekler: { A: "Bağımsızlık", B: "Barış", C: "Bereket", D: "Adalet" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 80, soru: "Atatürk'ün 'En büyük eserim' dediği şey hangisidir?", secenekler: { A: "Türkiye Cumhuriyeti", B: "Nutuk", C: "Anıtkabir", D: "TBMM" }, dogruCevap: "A" },

    // 81-100: Dünya Genel Kültürü ve Karışık
    { kategori: "Genel Kültür", seviye: 81, soru: "Dünyanın en kalabalık ülkesi hangisidir?", secenekler: { A: "Hindistan", B: "Çin", C: "ABD", D: "Rusya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 82, soru: "En büyük yüzölçümüne sahip ülke hangisidir?", secenekler: { A: "Rusya", B: "Kanada", C: "Çin", D: "Brezilya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 83, soru: "Eyfel Kulesi hangi şehirdedir?", secenekler: { A: "Paris", B: "Londra", C: "Roma", D: "Berlin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 84, soru: "Pisa Kulesi hangi ülkededir?", secenekler: { A: "İtalya", B: "İspanya", C: "Fransa", D: "Yunanistan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 85, soru: "Kızıl Meydan hangi şehirdedir?", secenekler: { A: "Moskova", B: "Kiev", C: "Varşova", D: "Prag" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 86, soru: "Özgürlük Heykeli hangi ülkededir?", secenekler: { A: "ABD", B: "Fransa", C: "İngiltere", D: "Kanada" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 87, soru: "Kolezyum hangi şehirdedir?", secenekler: { A: "Roma", B: "Atina", C: "Venedik", D: "Floransa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 88, soru: "Piramitler hangi ülkededir?", secenekler: { A: "Mısır", B: "Meksika", C: "Peru", D: "Sudan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 89, soru: "Dünyanın en uzun nehri hangisidir?", secenekler: { A: "Nil", B: "Amazon", C: "Ganj", D: "Mississippi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 90, soru: "En derin okyanus hangisidir?", secenekler: { A: "Büyük Okyanus", B: "Atlas Okyanusu", C: "Hint Okyanusu", D: "Kuzey Buz Denizi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 91, soru: "Mona Lisa tablosu kime aittir?", secenekler: { A: "Leonardo da Vinci", B: "Picasso", C: "Van Gogh", D: "Salvador Dali" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 92, soru: "Telefonun mucidi kimdir?", secenekler: { A: "Graham Bell", B: "Edison", C: "Tesla", D: "Marconi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 93, soru: "Hangi ülke 'Güneşin Doğduğu Ülke' olarak bilinir?", secenekler: { A: "Japonya", B: "Çin", C: "Güney Kore", D: "Tayland" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 94, soru: "Dünya kupasını en çok kazanan ülke hangisidir?", secenekler: { A: "Brezilya", B: "Almanya", C: "İtalya", D: "Arjantin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 95, soru: "Kanarya Adaları hangi ülkeye bağlıdır?", secenekler: { A: "İspanya", B: "Portekiz", C: "Fas", D: "Fransa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 96, soru: "Avrupa Birliği'nin merkezi hangi şehirdir?", secenekler: { A: "Brüksel", B: "Strazburg", C: "Lüksemburg", D: "Cenevre" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 97, soru: "Dünyanın yedi harikasından biri olan Tac Mahal nerededir?", secenekler: { A: "Hindistan", B: "İran", C: "Pakistan", D: "Afganistan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 98, soru: "İnce Memed kimin eseridir?", secenekler: { A: "Yaşar Kemal", B: "Orhan Pamuk", C: "Zülfü Livaneli", D: "Elif Şafak" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 99, soru: "Güneş sistemindeki en küçük gezegen hangisidir?", secenekler: { A: "Merkür", B: "Mars", C: "Venüs", D: "Neptün" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 100, soru: "Türkiye'nin ilk yerli otomobilinin adı nedir?", secenekler: { A: "TOGG", B: "Devrim", C: "Anadol", D: "Şahin" }, dogruCevap: "A" }, 
    // 101-300: Yeni Genel Kültür Soruları
    { kategori: "Genel Kültür", seviye: 101, soru: "Oksijeni keşfeden bilim insanı kimdir?", secenekler: { A: "Joseph Priestley", B: "Isaac Newton", C: "Marie Curie", D: "Albert Einstein" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 102, soru: "İstiklal Marşı hangi yıl kabul edilmiştir?", secenekler: { A: "1921", B: "1920", C: "1923", D: "1924" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 103, soru: "Dünyanın en yüksek şelalesi hangisidir?", secenekler: { A: "Angel Şelalesi", B: "Niagara", C: "Victoria", D: "Iguazu" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 104, soru: "Sinekli Bakkal romanının yazarı kimdir?", secenekler: { A: "Halide Edip Adıvar", B: "Reşat Nuri Güntekin", C: "Yakup Kadri", D: "Peyami Safa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 105, soru: "Hangi gezegen 'Kızıl Gezegen' olarak bilinir?", secenekler: { A: "Mars", B: "Jüpiter", C: "Satürn", D: "Venüs" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 106, soru: "Aspirin'in hammaddesi olan ağaç hangisidir?", secenekler: { A: "Söğüt", B: "Meşe", C: "Çam", D: "Kavak" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 107, soru: "Türkiye'nin en büyük adası hangisidir?", secenekler: { A: "Gökçeada", B: "Bozcaada", C: "Büyükada", D: "Heybeliada" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 108, soru: "Kuduz aşısını bulan bilim insanı kimdir?", secenekler: { A: "Louis Pasteur", B: "Alexander Fleming", C: "Robert Koch", D: "Edward Jenner" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 109, soru: "İlk modern olimpiyatlar hangi yıl yapılmıştır?", secenekler: { A: "1896", B: "1900", C: "1912", D: "1920" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 110, soru: "İnce Memed romanı kime aittir?", secenekler: { A: "Yaşar Kemal", B: "Orhan Kemal", C: "Kemal Tahir", D: "Sait Faik" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 111, soru: "Dünyanın en küçük kıtası hangisidir?", secenekler: { A: "Avustralya", B: "Avrupa", C: "Antarktika", D: "Güney Amerika" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 112, soru: "Suyun kaldırma kuvvetini kim bulmuştur?", secenekler: { A: "Arşimet", B: "Newton", C: "Galileo", D: "Pascal" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 113, soru: "Fatih Sultan Mehmet'in hocası kimdir?", secenekler: { A: "Akşemseddin", B: "Molla Fenari", C: "Hacı Bayram Veli", D: "Ebu Suud Efendi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 114, soru: "Türkiye'nin en çok sınır komşusu olan ili hangisidir?", secenekler: { A: "Iğdır", B: "Edirne", C: "Hakkari", D: "Van" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 115, soru: "Nobel ödülleri hangi ülkede verilmektedir?", secenekler: { A: "İsveç", B: "Norveç", C: "İsviçre", D: "Danimarka" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 116, soru: "Satrancın ana vatanı neresidir?", secenekler: { A: "Hindistan", B: "İran", C: "Mısır", D: "Çin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 117, soru: "Damlataş Mağarası hangi ilimizdedir?", secenekler: { A: "Antalya", B: "Muğla", C: "Burdur", D: "Isparta" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 118, soru: "Kuzey Kutbu'nu keşfeden kişi kimdir?", secenekler: { A: "Robert Peary", B: "Roald Amundsen", C: "James Cook", D: "Christopher Columbus" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 119, soru: "Pi sayısının yaklaşık değeri kaçtır?", secenekler: { A: "3,14", B: "2,14", C: "3,16", D: "3,18" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 120, soru: "Osmanlı Devleti'nin son padişahı kimdir?", secenekler: { A: "Vahdettin", B: "Abdülhamid", C: "Reşat", D: "Abdülaziz" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 121, soru: "Dünyanın en büyük çölü hangisidir?", secenekler: { A: "Sahra Çölü", B: "Gobi Çölü", C: "Kalahari", D: "Atacama" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 122, soru: "Ulu Önder Atatürk'ün doğum yeri neresidir?", secenekler: { A: "Selanik", B: "Manastır", C: "İstanbul", D: "Sofya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 123, soru: "Fahrenheit ölçeğinde su kaç derecede donar?", secenekler: { A: "32", B: "0", C: "100", D: "212" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 124, soru: "Hangi ilimiz 'Güller Diyarı' olarak bilinir?", secenekler: { A: "Isparta", B: "Burdur", C: "Antalya", D: "Afyon" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 125, soru: "Sultan Ahmet Camii'nin mimarı kimdir?", secenekler: { A: "Sedefkar Mehmet Ağa", B: "Mimar Sinan", C: "Mimar Hayrettin", D: "Mimar Kemalettin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 126, soru: "İlk Türk kadın pilot kimdir?", secenekler: { A: "Sabiha Gökçen", B: "Bedriye Tahir Gökmen", C: "Leman Bozkurt", D: "Sabiha Rıfat" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 127, soru: "Güneş sistemindeki en büyük gezegen hangisidir?", secenekler: { A: "Jüpiter", B: "Satürn", C: "Neptün", D: "Dünya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 128, soru: "Türkiye'nin en büyük gölü hangisidir?", secenekler: { A: "Van Gölü", B: "Tuz Gölü", C: "Beyşehir Gölü", D: "Eğirdir Gölü" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 129, soru: "Ampulü kim icat etmiştir?", secenekler: { A: "Thomas Edison", B: "Nikola Tesla", C: "Alexander Graham Bell", D: "Benjamin Franklin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 130, soru: "Tuz Gölü hangi üç ilin sınırları içerisindedir?", secenekler: { A: "Ankara-Konya-Aksaray", B: "Ankara-Kırşehir-Niğde", C: "Konya-Aksaray-Niğde", D: "Kayseri-Nevşehir-Aksaray" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 131, soru: "DNA'nın yapısını keşfeden bilim insanlarından biri kimdir?", secenekler: { A: "James Watson", B: "Charles Darwin", C: "Gregor Mendel", D: "Louis Pasteur" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 132, soru: "Hangi hayvanın sütü pembe renklidir?", secenekler: { A: "Su aygırı", B: "Zürafa", C: "Fil", D: "Gergedan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 133, soru: "Ünlü 'Düşünen Adam' heykeli kime aittir?", secenekler: { A: "Auguste Rodin", B: "Michelangelo", C: "Donatello", D: "Bernini" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 134, soru: "Ankara hangi yıl başkent olmuştur?", secenekler: { A: "1923", B: "1920", C: "1924", D: "1922" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 135, soru: "Sineklerin kaç bacağı vardır?", secenekler: { A: "6", B: "4", C: "8", D: "10" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 136, soru: "Yüzölçümü en küçük olan ilimiz hangisidir?", secenekler: { A: "Yalova", B: "Bayburt", C: "Bilecik", D: "Bartın" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 137, soru: "Pusulayı kimler icat etmiştir?", secenekler: { A: "Çinliler", B: "Mısırlılar", C: "Yunanlar", D: "Araplar" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 138, soru: "Hangi elementin simgesi 'Au'dur?", secenekler: { A: "Altın", B: "Gümüş", C: "Bakır", D: "Alüminyum" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 139, soru: "Türkçenin ilk sözlüğü hangisidir?", secenekler: { A: "Divanü Lügati't-Türk", B: "Muhakemetü'l-Lügateyn", C: "Kamusu Türki", D: "Lehçe-i Osmani" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 140, soru: "Dünyanın en uzun duvarı hangisidir?", secenekler: { A: "Çin Seddi", B: "Ağlama Duvarı", C: "Berlin Duvarı", D: "Hadrian Duvarı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 141, soru: "İnsan vücudundaki en büyük organ hangisidir?", secenekler: { A: "Deri", B: "Karaciğer", C: "Akciğer", D: "Bağırsak" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 142, soru: "Nemrut Dağı heykelleri hangi ilimizdedir?", secenekler: { A: "Adıyaman", B: "Malatya", C: "Şanlıurfa", D: "Gaziantep" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 143, soru: "Fransız İhtilali hangi yıl gerçekleşmiştir?", secenekler: { A: "1789", B: "1776", C: "1815", D: "1848" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 144, soru: "Matbaayı ilk geliştiren kişi kimdir?", secenekler: { A: "Johannes Gutenberg", B: "Leonardo da Vinci", C: "Isaac Newton", D: "Galileo" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 145, soru: "Sümela Manastırı hangi ilimizdedir?", secenekler: { A: "Trabzon", B: "Rize", C: "Artvin", D: "Giresun" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 146, soru: "Futbol maçlarında bir devre kaç dakikadır?", secenekler: { A: "45", B: "40", C: "50", D: "35" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 147, soru: "Modern Hemşireliğin kurucusu kimdir?", secenekler: { A: "Florence Nightingale", B: "Marie Curie", C: "Virginia Woolf", D: "Rosa Parks" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 148, soru: "I. Dünya Savaşı hangi yıl başlamıştır?", secenekler: { A: "1914", B: "1912", C: "1918", D: "1910" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 149, soru: "En büyük memeli hayvan hangisidir?", secenekler: { A: "Mavi Balina", B: "Fil", C: "Zürafa", D: "Gergedan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 150, soru: "Safahat eseri kime aittir?", secenekler: { A: "Mehmet Akif Ersoy", B: "Yahya Kemal", C: "Namık Kemal", D: "Ziya Gökalp" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 151, soru: "Hangi ülke en çok adaya sahiptir?", secenekler: { A: "İsveç", B: "Norveç", C: "Endonezya", D: "Filipinler" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 152, soru: "Telefonun mucidi Graham Bell'in asıl mesleği nedir?", secenekler: { A: "Sağır öğretmeni", B: "Mühendis", C: "Doktor", D: "Fizikçi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 153, soru: "Türkiye'nin ilk kadın başbakanı kimdir?", secenekler: { A: "Tansu Çiller", B: "Meral Akşener", C: "Işılay Saygın", D: "Türkan Akyol" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 154, soru: "Bir gün kaç saniyedir?", secenekler: { A: "86400", B: "3600", C: "43200", D: "1440" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 155, soru: "Mimar Sinan'ın kalfalık eserim dediği cami hangisidir?", secenekler: { A: "Süleymaniye", B: "Selimiye", C: "Şehzade", D: "Mihrimah Sultan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 156, soru: "Limonun ekşi olmasının sebebi hangi asittir?", secenekler: { A: "Sitrik Asit", B: "Laktik Asit", C: "Asetik Asit", D: "Sülfürik Asit" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 157, soru: "Dünyanın en tuzlu denizi hangisidir?", secenekler: { A: "Lut Gölü (Ölü Deniz)", B: "Akdeniz", C: "Kızıldeniz", D: "Ege Denizi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 158, soru: "Arıların kaç gözü vardır?", secenekler: { A: "5", B: "2", C: "4", D: "6" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 159, soru: "Ayna hangi elementle kaplanır?", secenekler: { A: "Gümüş", B: "Altın", C: "Demir", D: "Bakır" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 160, soru: "Osmanlı'nın ilk deniz savaşı hangi devletle yapılmıştır?", secenekler: { A: "Venedik", B: "Bizans", C: "Ceneviz", D: "İspanya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 161, soru: "Hangi kuş uçamaz?", secenekler: { A: "Penguen", B: "Kartal", C: "Martı", D: "Şahin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 162, soru: "İnsan kalbi kaç odacıktan oluşur?", secenekler: { A: "4", B: "2", C: "3", D: "5" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 163, soru: "Türkiye'nin en uzun nehri hangisidir?", secenekler: { A: "Kızılırmak", B: "Fırat", C: "Dicle", D: "Sakarya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 164, soru: "Kan gruplarını keşfeden kimdir?", secenekler: { A: "Karl Landsteiner", B: "Gregor Mendel", C: "Alexander Fleming", D: "Louis Pasteur" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 165, soru: "Yedi Tepe üzerine kurulu olan şehrimiz hangisidir?", secenekler: { A: "İstanbul", B: "Ankara", C: "Bursa", D: "İzmir" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 166, soru: "Periyodik cetvelde 'H' hangi elementi temsil eder?", secenekler: { A: "Hidrojen", B: "Helyum", C: "Hafniyum", D: "Hıva" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 167, soru: "Çanakkale Boğazı'nın en dar yeri neresidir?", secenekler: { A: "Kilitbahir", B: "Eceabat", C: "Gelibolu", D: "Lapseki" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 168, soru: "Hangi dil en çok konuşulan dildir (ana dil olarak)?", secenekler: { A: "Çince (Mandarin)", B: "İngilizce", C: "İspanyolca", D: "Hintçe" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 169, soru: "Satrançta en güçlü taş hangisidir?", secenekler: { A: "Vezir", B: "Şah", C: "Kale", D: "At" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 170, soru: "Mona Lisa tablosu hangi müzededir?", secenekler: { A: "Louvre", B: "Prado", C: "British Museum", D: "Uffizi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 171, soru: "Aspirin'in hammaddesi hangisidir?", secenekler: { A: "Söğüt ağacı", B: "Çam ağacı", C: "Papatya", D: "Ihlamur" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 172, soru: "Osmanlı'da matbaayı kuran ilk kişi kimdir?", secenekler: { A: "İbrahim Müteferrika", B: "Sait Efendi", C: "Katip Çelebi", D: "Evliya Çelebi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 173, soru: "Hangi ilimizde demiryolu yoktur?", secenekler: { A: "Antalya", B: "Kayseri", C: "Eskişehir", D: "Sivas" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 174, soru: "Dünya'ya en yakın yıldız hangisidir?", secenekler: { A: "Güneş", B: "Sirius", C: "Proxima Centauri", D: "Polaris" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 175, soru: "Hangi ülkenin iki kıtada toprağı vardır?", secenekler: { A: "Türkiye", B: "Mısır", C: "Rusya", D: "Hepsi" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 176, soru: "Olimpiyat halkaları kaç tanedir?", secenekler: { A: "5", B: "6", C: "4", D: "7" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 177, soru: "İlk Selçuklu parası hangi padişah zamanında basılmıştır?", secenekler: { A: "Tuğrul Bey", B: "Alp Arslan", C: "Melikşah", D: "Sencer" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 178, soru: "Damlataş Mağarası nerededir?", secenekler: { A: "Alanya", B: "Bodrum", C: "Marmaris", D: "Fethiye" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 179, soru: "Suyun kimyasal formülü nedir?", secenekler: { A: "H2O", B: "CO2", C: "NaCl", D: "O2" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 180, soru: "Hangi organımız kanı temizler?", secenekler: { A: "Böbrek", B: "Kalp", C: "Mide", D: "Akciğer" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 181, soru: "Hangi spor dalında 'Servis' yoktur?", secenekler: { A: "Futbol", B: "Tenis", C: "Voleybol", D: "Masa Tenisi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 182, soru: "Dünyanın en büyük şelalesi hangisidir?", secenekler: { A: "Angel", B: "Niagara", C: "Victoria", D: "Düden" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 183, soru: "En çok uydusu olan gezegen hangisidir?", secenekler: { A: "Satürn", B: "Jüpiter", C: "Mars", D: "Venüs" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 184, soru: "Topkapı Sarayı'nı hangi padişah yaptırmıştır?", secenekler: { A: "Fatih Sultan Mehmet", B: "Kanuni Sultan Süleyman", C: "Yavuz Sultan Selim", D: "II. Abdülhamid" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 185, soru: "Ses hızı havada yaklaşık kaç m/s'dir?", secenekler: { A: "340", B: "300000", C: "100", D: "1200" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 186, soru: "Karagöz ile Hacivat hangi döneme aittir?", secenekler: { A: "Osmanlı", B: "Selçuklu", C: "Cumhuriyet", D: "Bizans" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 187, soru: "Hangi ilimizde kayak merkezi yoktur?", secenekler: { A: "Şanlıurfa", B: "Erzurum", C: "Bursa", D: "Kayseri" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 188, soru: "DNA testi için ne kullanılmaz?", secenekler: { A: "Parmak izi", B: "Saç teli", C: "Tükürük", D: "Kan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 189, soru: "Sultan Ahmet Camii'nin kaç minaresi vardır?", secenekler: { A: "6", B: "4", C: "2", D: "5" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 190, soru: "Dünyanın en küçük bağımsız devleti hangisidir?", secenekler: { A: "Vatikan", B: "Monako", C: "San Marino", D: "Malta" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 191, soru: "Hangi ülkenin bayrağı dikdörtgen değildir?", secenekler: { A: "Nepal", B: "İsviçre", C: "Belçika", D: "Japonya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 192, soru: "Panda hangi ülkenin sembolüdür?", secenekler: { A: "Çin", B: "Japonya", C: "Vietnam", D: "Tayland" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 193, soru: "İlk insanlı uzay uçuşunu kim yapmıştır?", secenekler: { A: "Yuri Gagarin", B: "Neil Armstrong", C: "Buzz Aldrin", D: "John Glenn" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 194, soru: "Hangi hayvan uyurken gözlerini kapatmaz?", secenekler: { A: "Balık", B: "Yılan", C: "Tavşan", D: "Hamster" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 195, soru: "Nobel Barış Ödülü hangi şehirde verilir?", secenekler: { A: "Oslo", B: "Stockholm", C: "Kopenhag", D: "Helsinki" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 196, soru: "Kız Kulesi hangi şehirdedir?", secenekler: { A: "İstanbul", B: "İzmir", C: "Antalya", D: "Çanakkale" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 197, soru: "Bir kilometrede kaç santimetre vardır?", secenekler: { A: "100.000", B: "10.000", C: "1.000", D: "1.000.000" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 198, soru: "Kuyruklu yıldızlar neyden oluşur?", secenekler: { A: "Buz ve toz", B: "Sadece taş", C: "Sıcak gaz", D: "Metal" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 199, soru: "Hangi kıtanın yerli halkına 'Aborjin' denir?", secenekler: { A: "Avustralya", B: "Afrika", C: "Asya", D: "Güney Amerika" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 200, soru: "Sherlock Holmes karakterinin yaratıcısı kimdir?", secenekler: { A: "Arthur Conan Doyle", B: "Agatha Christie", C: "Edgar Allan Poe", D: "Stephen King" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 201, soru: "Hangi kan grubu 'Genel Alıcı'dır?", secenekler: { A: "AB Pozitif", B: "0 Negatif", C: "A Pozitif", D: "B Negatif" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 202, soru: "Uçaklarda bulunan ve kaza anlarını kaydeden cihazın adı nedir?", secenekler: { A: "Kara Kutu", B: "GPS", C: "Radar", D: "Altometre" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 203, soru: "Eyfel Kulesi'nin mimarı kimdir?", secenekler: { A: "Gustave Eiffel", B: "Charles Garnier", C: "Le Corbusier", D: "Victor Hugo" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 204, soru: "Hangi elementin simgesi 'Fe'dir?", secenekler: { A: "Demir", B: "Fosfor", C: "Flor", D: "Fransiyum" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 205, soru: "Ata Demirer'in canlandırdığı ünlü karakter 'Hüseyin Badem' hangi film serisindedir?", secenekler: { A: "Eyyvah Eyvah", B: "Berlin Kaplanı", C: "Olanlar Oldu", D: "Hedefim Sensin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 206, soru: "İlk Türk devletlerinde ölen kişilerin mezarına ne denirdi?", secenekler: { A: "Kurgan", B: "Balbal", C: "Yuğ", D: "Şaman" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 207, soru: "Türkiye'nin en batı noktası hangisidir?", secenekler: { A: "Avlaka Burnu", B: "İnceburun", C: "Dilburnu", D: "Bababurnu" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 208, soru: "Aspirin hangi bitkiden elde edilir?", secenekler: { A: "Söğüt", B: "Nane", C: "Papatya", D: "Isırgan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 209, soru: "Yel değirmenleriyle ünlü olan ülke hangisidir?", secenekler: { A: "Hollanda", B: "Danimarka", C: "İsveç", D: "Belçika" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 210, soru: "Hangi hayvanın kalbi kafasındadır?", secenekler: { A: "Karides", B: "Istakoz", C: "Yengeç", D: "Ahtapot" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 211, soru: "Güneş sistemindeki en soğuk gezegen hangisidir?", secenekler: { A: "Neptün", B: "Uranüs", C: "Satürn", D: "Plüton" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 212, soru: "Tarihin babası olarak bilinen kişi kimdir?", secenekler: { A: "Heredot", B: "Hipokrat", C: "Sokrates", D: "Platon" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 213, soru: "Hangi ilimizde 'Peri Bacaları' yoktur?", secenekler: { A: "Ankara", B: "Nevşehir", C: "Aksaray", D: "Niğde" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 214, soru: "Futbolda ofsayt kuralı hangi yıl getirilmiştir?", secenekler: { A: "1863", B: "1900", C: "1925", D: "1950" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 215, soru: "En hafif element hangisidir?", secenekler: { A: "Hidrojen", B: "Helyum", C: "Lityum", D: "Azot" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 216, soru: "Türkiye'nin en derin gölü hangisidir?", secenekler: { A: "Salda Gölü", B: "Van Gölü", C: "Nemrut Gölü", D: "Bafa Gölü" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 217, soru: "Hangi meyvenin çekirdeği dışında bulunur?", secenekler: { A: "Çilek", B: "Böğürtlen", C: "Ahududu", D: "İncir" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 218, soru: "Gökkuşağının ortasındaki renk hangisidir?", secenekler: { A: "Yeşil", B: "Sarı", C: "Mavi", D: "Turuncu" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 219, soru: "Dünyanın en büyük kütüphanesi nerededir?", secenekler: { A: "Washington (Kongre Kütüphanesi)", B: "Londra", C: "Paris", D: "Moskova" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 220, soru: "Türkiye'de kaç tane coğrafi bölge vardır?", secenekler: { A: "7", B: "4", C: "5", D: "8" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 221, soru: "Pisa Kulesi neden eğiktir?", secenekler: { A: "Temelindeki yumuşak zemin yüzünden", B: "Mimari bir tercih", C: "Deprem yüzünden", D: "Savaş hasarı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 222, soru: "Hangi ilimiz 'İstiklal Madalyası'na sahip değildir?", secenekler: { A: "Adana", B: "Kahramanmaraş", C: "Gaziantep", D: "Şanlıurfa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 223, soru: "İnsan vücudunda kaç kemik bulunur (yetişkinlerde)?", secenekler: { A: "206", B: "106", C: "306", D: "406" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 224, soru: "Hangi gezegenin halkaları en belirgindir?", secenekler: { A: "Satürn", B: "Jüpiter", C: "Uranüs", D: "Neptün" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 225, soru: "Peyniriyle ünlü olan ilimiz hangisidir?", secenekler: { A: "Kars", B: "Ardahan", C: "Erzurum", D: "Hepsi" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 226, soru: "Mona Lisa'nın kaşları neden yoktur?", secenekler: { A: "O dönemde kaşları tıraş etmek modaydı", B: "Ressam unuttu", C: "Zamanla silindi", D: "Hiç olmadı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 227, soru: "Tavşanlar neyle beslenir?", secenekler: { A: "Havuç", B: "Et", C: "Süt", D: "Peynir" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 228, soru: "Hangi ilimizde 'Altın Portakal' film festivali yapılır?", secenekler: { A: "Antalya", B: "Adana", C: "İstanbul", D: "İzmir" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 229, soru: "Bir kilometrede kaç metre vardır?", secenekler: { A: "1000", B: "100", C: "10000", D: "10" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 230, soru: "Sinekler kaç kanatlıdır?", secenekler: { A: "2", B: "4", C: "6", D: "8" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 231, soru: "Arılar nasıl haberleşir?", secenekler: { A: "Dans ederek", B: "Ses çıkararak", C: "Dokunarak", D: "Kokuyla" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 232, soru: "Hangi ağaç kışın yaprak dökmez?", secenekler: { A: "Çam", B: "Meşe", C: "Gürgen", D: "Kavak" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 233, soru: "En büyük iç organımız hangisidir?", secenekler: { A: "Karaciğer", B: "Mide", C: "Bağırsak", D: "Dalak" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 234, soru: "Güneş bir nedir?", secenekler: { A: "Yıldız", B: "Gezegen", C: "Uydu", D: "Meteor" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 235, soru: "Hangi hayvan su içmez?", secenekler: { A: "Kanguru Faresi", B: "Deve", C: "Yılan", D: "Kertenkele" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 236, soru: "Aydede şarkısında Aydede nerede durur?", secenekler: { A: "Gökyüzünde", B: "Evinde", C: "Bahçede", D: "Yolda" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 237, soru: "İnsan vücudunda kaç litre kan bulunur?", secenekler: { A: "5-6", B: "2-3", C: "10-12", D: "1-2" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 238, soru: "Hangi ilimiz 'Kayısı' ile meşhurdur?", secenekler: { A: "Malatya", B: "Iğdır", C: "Elazığ", D: "Erzincan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 239, soru: "Tavuk mu yumurtadan çıkar yumurta mı tavuktan?", secenekler: { A: "Tavuk yumurtadan", B: "Yumurta tavuktan", C: "İkisi de doğru", D: "Bilinmiyor" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 240, soru: "Hangi meyve kış meyvesidir?", secenekler: { A: "Portakal", B: "Karpuz", C: "Kiraz", D: "Erik" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 241, soru: "Hangi hayvan kış uykusuna yatmaz?", secenekler: { A: "Kurt", B: "Ayı", C: "Yılan", D: "Kurbağa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 242, soru: "Gökkuşağı kaç renktir?", secenekler: { A: "7", B: "6", C: "8", D: "5" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 243, soru: "Türkiye'nin en kalabalık ilçesi hangisidir?", secenekler: { A: "Esenyurt", B: "Çankaya", C: "Keçiören", D: "Şahinbey" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 244, soru: "Sinekler neden vızıldar?", secenekler: { A: "Kanat çırptıkları için", B: "Ağızlarından ses çıkarırlar", C: "Ayaklarını sürterler", D: "Korktukları için" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 245, soru: "En yavaş hayvan hangisidir?", secenekler: { A: "Tembel Hayvan", B: "Kaplumbağa", C: "Salyangoz", D: "Koala" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 246, soru: "Hangi gezegenin uydusu yoktur?", secenekler: { A: "Venüs", B: "Mars", C: "Jüpiter", D: "Neptün" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 247, soru: "Pusulanın renkli ucu nereyi gösterir?", secenekler: { A: "Kuzey", B: "Güney", C: "Doğu", D: "Batı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 248, soru: "Hangi ilimiz Ege Bölgesi'ndedir?", secenekler: { A: "İzmir", B: "Antalya", C: "Mersin", D: "Bursa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 249, soru: "Örümceklerin kaç bacağı vardır?", secenekler: { A: "8", B: "6", C: "10", D: "4" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 250, soru: "Mıknatıs neyi çekmez?", secenekler: { A: "Bakır", B: "Demir", C: "Nikel", D: "Kobalt" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 251, soru: "Dünyanın çevresini ilk kez dolaşan kimdir?", secenekler: { A: "Macellan", B: "Kristof Kolomb", C: "Vasco da Gama", D: "Amerigo Vespucci" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 252, soru: "Hangi ülkenin bayrağında akçaağaç yaprağı vardır?", secenekler: { A: "Kanada", B: "Lübnan", C: "Kıbrıs", D: "Japonya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 253, soru: "Hangi gezegen halk arasında 'Çoban Yıldızı' olarak bilinir?", secenekler: { A: "Venüs", B: "Mars", C: "Merkür", D: "Jüpiter" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 254, soru: "Oksijeni kim keşfetti?", secenekler: { A: "Joseph Priestley", B: "Antoine Lavoisier", C: "Henry Cavendish", D: "Robert Boyle" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 255, soru: "Hangi spor dalı 'Grand Slam' turnuvalarıyla bilinir?", secenekler: { A: "Tenis", B: "Golf", C: "Beyzbol", D: "Kriket" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 256, soru: "Dünyanın en yüksek binası 'Burj Khalifa' hangi şehirdedir?", secenekler: { A: "Dubai", B: "Abu Dabi", C: "Doha", D: "Riyad" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 257, soru: "Zebra'nın çizgileri ne renktir?", secenekler: { A: "Siyah-Beyaz", B: "Lacivert-Beyaz", C: "Kahverengi-Sarı", D: "Gri-Siyah" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 258, soru: "Hangi kuşun yumurtası en büyüktür?", secenekler: { A: "Devekuşu", B: "Kartal", C: "Albatros", D: "Pelikan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 259, soru: "İnsan vücudunda en çok bulunan element hangisidir?", secenekler: { A: "Oksijen", B: "Karbon", C: "Hidrojen", D: "Azot" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 260, soru: "Hangi dil Birleşmiş Milletler'in resmi dillerinden biri değildir?", secenekler: { A: "Almanca", B: "Arapça", C: "Çince", D: "Rusça" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 261, soru: "En çok Nobel ödülü alan ülke hangisidir?", secenekler: { A: "ABD", B: "Almanya", C: "İngiltere", D: "Fransa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 262, soru: "Damlataş Mağarası nerededir?", secenekler: { A: "Alanya", B: "Bodrum", C: "Marmaris", D: "Fethiye" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 263, soru: "Satrançta kaç kare vardır?", secenekler: { A: "64", B: "48", C: "72", D: "81" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 264, soru: "Güneş ışığı dünyaya kaç dakikada ulaşır?", secenekler: { A: "8", B: "1", C: "15", D: "24" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 265, soru: "Hangi kıtada hiç aktif yanardağ yoktur?", secenekler: { A: "Avustralya", B: "Afrika", C: "Avrupa", D: "Asya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 266, soru: "Mona Lisa tablosunu kim yaptı?", secenekler: { A: "Leonardo da Vinci", B: "Michelangelo", C: "Raphael", D: "Donatello" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 267, soru: "Hangi ülkenin başkenti Tokyo'dur?", secenekler: { A: "Japonya", B: "Güney Kore", C: "Çin", D: "Tayland" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 268, soru: "Yılanlar nasıl duyar?", secenekler: { A: "Titreşimlerle", B: "Kulaklarıyla", C: "Gözleriyle", D: "Dilleriyle" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 269, soru: "Hangi kıta en büyüktür?", secenekler: { A: "Asya", B: "Afrika", C: "Amerika", D: "Avrupa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 270, soru: "Gökkuşağı ne zaman çıkar?", secenekler: { A: "Yağmurdan sonra güneş açınca", B: "Sadece yağmur yağarken", C: "Sadece güneşliyken", D: "Gece vakti" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 271, soru: "Arılar balı nereden yapar?", secenekler: { A: "Çiçek özlerinden", B: "Yapraklardan", C: "Su birikintilerinden", D: "Topraktan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 272, soru: "Hangi gezegen güneşe en yakındır?", secenekler: { A: "Merkür", B: "Venüs", C: "Dünya", D: "Mars" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 273, soru: "Türkiye'nin en kalabalık şehri hangisidir?", secenekler: { A: "İstanbul", B: "Ankara", C: "İzmir", D: "Bursa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 274, soru: "Kelebeklerin ömrü ne kadardır?", secenekler: { A: "Türüne göre değişir", B: "1 gün", C: "1 yıl", D: "1 hafta" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 275, soru: "Sıcaklık neyle ölçülür?", secenekler: { A: "Termometre", B: "Barometre", C: "Pusula", D: "Saat" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 276, soru: "En büyük okyanus hangisidir?", secenekler: { A: "Büyük Okyanus (Pasifik)", B: "Atlas Okyanusu", C: "Hint Okyanusu", D: "Antarktika Okyanusu" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 277, soru: "Hangi hayvanın yavrusuna 'enik' denir?", secenekler: { A: "Köpek", B: "Kedi", C: "At", D: "Koyun" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 278, soru: "Hangi ilimiz İç Anadolu Bölgesi'ndedir?", secenekler: { A: "Ankara", B: "İzmir", C: "Trabzon", D: "Diyarbakır" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 279, soru: "İnsanlar kaç dişle doğar?", secenekler: { A: "Dişsiz doğarlar", B: "20 dişle", C: "32 dişle", D: "10 dişle" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 280, soru: "Uçurtma neyle uçar?", secenekler: { A: "Rüzgarla", B: "Güneşle", C: "Yağmurla", D: "Kendi motoruyla" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 281, soru: "Kutup ayıları nerede yaşar?", secenekler: { A: "Kuzey Kutbu", B: "Güney Kutbu", C: "Ekvator", D: "Ormanlarda" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 282, soru: "Kangurular nerede yaşar?", secenekler: { A: "Avustralya", B: "Afrika", C: "Amerika", D: "Asya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 283, soru: "Ay'ın ışığı nereden gelir?", secenekler: { A: "Güneşten", B: "Kendi ışığıdır", C: "Dünyadan", D: "Yıldızlardan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 284, soru: "Kışın hangi kıyafeti giyeriz?", secenekler: { A: "Palto", B: "Şort", C: "Tişört", D: "Sandalet" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 285, soru: "Meyveleri yemeden önce ne yapmalıyız?", secenekler: { A: "Yıkamalıyız", B: "Pişirmeliyiz", C: "Kurutmalıyız", D: "Boyamalıyız" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 286, soru: "Dişlerimizi günde en az kaç kez fırçalamalıyız?", secenekler: { A: "2", B: "1", C: "5", D: "10" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 287, soru: "Hangi mevsimde okullar açılır?", secenekler: { A: "Sonbahar", B: "İlkbahar", C: "Yaz", D: "Kış" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 288, soru: "Güneş hangi yönden doğar?", secenekler: { A: "Doğu", B: "Batı", C: "Kuzey", D: "Güney" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 289, soru: "Atatürk'ün mezarı neresidir?", secenekler: { A: "Anıtkabir", B: "Dolmabahçe", C: "Topkapı", D: "Çankaya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 290, soru: "Ekmek neyden yapılır?", secenekler: { A: "Un", B: "Şeker", C: "Tuz", D: "Pirinç" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 291, soru: "Hangi hayvan havlar?", secenekler: { A: "Köpek", B: "Kedi", C: "Kuş", D: "Balık" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 292, soru: "Ateş neyle söndürülür?", secenekler: { A: "Su", B: "Benzin", C: "Kağıt", D: "Odun" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 293, soru: "Trafik lambasında hangi renk 'Dur' demektir?", secenekler: { A: "Kırmızı", B: "Yeşil", C: "Sarı", D: "Mavi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 294, soru: "Hangi organımızla duyarız?", secenekler: { A: "Kulak", B: "Göz", C: "Burun", D: "Ağız" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 295, soru: "Süt hangi hayvandan elde edilir?", secenekler: { A: "İnek", B: "Tavuk", C: "Kuş", D: "Balık" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 296, soru: "Yumurtayı hangi hayvan verir?", secenekler: { A: "Tavuk", B: "İnek", C: "Koyun", D: "Köpek" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 297, soru: "Kaç tane mevsim vardır?", secenekler: { A: "4", B: "3", C: "5", D: "12" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 298, soru: "Balığı kim yapar?", secenekler: { A: "Arı (Bal yapar, balık değil)", B: "Tavuk", C: "İnek", D: "Arı" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 299, soru: "Hangi gezegende yaşıyoruz?", secenekler: { A: "Dünya", B: "Mars", C: "Ay", D: "Güneş" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 300, soru: "Geceleri gökyüzünde ne görürüz?", secenekler: { A: "Ay ve Yıldızlar", B: "Güneş", C: "Gökkuşağı", D: "Bulutlar" }, dogruCevap: "A" },     // 351-550: Önemli Yerler (Türkiye ve Dünya)
    { seviye: 351, kategori: "Önemli Yerler", soru: "Fransa'nın başkenti Paris'in simgesi olan demir kule hangisidir?", secenekler: { A: "Eyfel Kulesi", B: "Pisa Kulesi", C: "Big Ben", D: "Özgürlük Anıtı" }, dogruCevap: "A" },
    { seviye: 352, kategori: "Önemli Yerler", soru: "İtalya'da bulunan ve 'Eğik Kule' olarak bilinen yapı hangisidir?", secenekler: { A: "Pisa Kulesi", B: "Kolezyum", C: "Venedik Kulesi", D: "Floransa Kulesi" }, dogruCevap: "A" },
    { seviye: 353, kategori: "Önemli Yerler", soru: "Hindistan'da Şah Cihan tarafından eşi için yaptırılan ünlü türbe?", secenekler: { A: "Tac Mahal", B: "Hümayun Türbesi", C: "Altın Tapınak", D: "Kızıl Kale" }, dogruCevap: "A" },
    { seviye: 354, kategori: "Önemli Yerler", soru: "ABD'nin New York şehrinde bulunan devasa heykel hangisidir?", secenekler: { A: "Özgürlük Anıtı", B: "Lincoln Anıtı", C: "Rushmore Anıtı", D: "Washington Anıtı" }, dogruCevap: "A" },
    { seviye: 355, kategori: "Önemli Yerler", soru: "Çin'i kuzeyden gelen akınlara karşı korumak için inşa edilen devasa yapı?", secenekler: { A: "Çin Seddi", B: "Yasak Şehir", C: "Toprak Askerler", D: "Cennet Tapınağı" }, dogruCevap: "A" },
    { seviye: 356, kategori: "Önemli Yerler", soru: "Antik Mısır'da inşa edilen en büyük piramit hangisidir?", secenekler: { A: "Keops Piramidi", B: "Kefren Piramidi", C: "Mikerinos Piramidi", D: "Sakkara Piramidi" }, dogruCevap: "A" },
    { seviye: 357, kategori: "Önemli Yerler", soru: "Ürdün'de bulunan ve kayalara oyulmuş antik kent hangisidir?", secenekler: { A: "Petra", B: "Palmira", C: "Efes", D: "Baalbek" }, dogruCevap: "A" },
    { seviye: 358, kategori: "Önemli Yerler", soru: "Peru'da İnka medeniyetine ait olan antik şehir?", secenekler: { A: "Machu Picchu", B: "Chichen Itza", C: "Tikal", D: "Cusco" }, dogruCevap: "A" },
    { seviye: 359, kategori: "Önemli Yerler", soru: "Brezilya'nın Rio de Janeiro şehrindeki dev İsa heykeli?", secenekler: { A: "Kurtarıcı İsa", B: "Aziz Petrus", C: "Kurtarıcı Meryem", D: "Aziz Paul" }, dogruCevap: "A" },
    { seviye: 360, kategori: "Önemli Yerler", soru: "Roma'da gladyatör dövüşlerinin yapıldığı antik amfitiyatro?", secenekler: { A: "Kolezyum", B: "Panteon", C: "Forum", D: "Karakalla Hamamları" }, dogruCevap: "A" },
    { seviye: 361, kategori: "Önemli Yerler", soru: "Atina'da Akropolis üzerinde bulunan ünlü tapınak?", secenekler: { A: "Parthenon", B: "Zeus Tapınağı", C: "Hera Tapınağı", D: "Erehteyon" }, dogruCevap: "A" },
    { seviye: 362, kategori: "Önemli Yerler", soru: "İngiltere'nin başkenti Londra'daki ünlü saat kulesi?", secenekler: { A: "Big Ben", B: "London Eye", C: "Tower Bridge", D: "The Shard" }, dogruCevap: "A" },
    { seviye: 363, kategori: "Önemli Yerler", soru: "Rusya'nın başkenti Moskova'daki ünlü meydan hangisidir?", secenekler: { A: "Kızıl Meydan", B: "Tahrir Meydanı", C: "Taksim Meydanı", D: "Times Meydanı" }, dogruCevap: "A" },
    { seviye: 364, kategori: "Önemli Yerler", soru: "Avustralya'nın Sidney şehrindeki ikonik yapı?", secenekler: { A: "Sidney Opera Evi", B: "Sidney Köprüsü", C: "Sky Tower", D: "Eureka Kulesi" }, dogruCevap: "A" },
    { seviye: 365, kategori: "Önemli Yerler", soru: "Dünyanın en yüksek şelalesi olan Angel Şelalesi nerededir?", secenekler: { A: "Venezuela", B: "Brezilya", C: "ABD", D: "Afrika" }, dogruCevap: "A" },
    { seviye: 366, kategori: "Önemli Yerler", soru: "Niagara Şelaleleri hangi iki ülke sınırındadır?", secenekler: { A: "ABD - Kanada", B: "Brezilya - Arjantin", C: "Zambiya - Zimbabve", D: "İsviçre - Fransa" }, dogruCevap: "A" },
    { seviye: 367, kategori: "Önemli Yerler", soru: "Dünyanın en büyük mercan kayalığı olan Büyük Set Resifi nerededir?", secenekler: { A: "Avustralya", B: "Meksika", C: "Endonezya", D: "Filipinler" }, dogruCevap: "A" },
    { seviye: 368, kategori: "Önemli Yerler", soru: "Dünyanın en derin noktası olan Mariana Çukuru hangi okyanustadır?", secenekler: { A: "Pasifik (Büyük)", B: "Atlantik", C: "Hint", D: "Arktik" }, dogruCevap: "A" },
    { seviye: 369, kategori: "Önemli Yerler", soru: "Dünyanın en yüksek dağı olan Everest hangi sıradağlar üzerindedir?", secenekler: { A: "Himalayalar", B: "And Dağları", C: "Alpler", D: "Kayalık Dağlar" }, dogruCevap: "A" },
    { seviye: 370, kategori: "Önemli Yerler", soru: "Büyük Kanyon (Grand Canyon) hangi ülkededir?", secenekler: { A: "ABD", B: "Meksika", C: "Avustralya", D: "Çin" }, dogruCevap: "A" },
    { seviye: 371, kategori: "Önemli Yerler", soru: "İstanbul'un en yüksek noktası kabul edilen tepe hangisidir?", secenekler: { A: "Çamlıca Tepesi", B: "Piyer Loti", C: "Yuşa Tepesi", D: "Aydos Tepesi" }, dogruCevap: "D" },
    { seviye: 372, kategori: "Önemli Yerler", soru: "Edirne'deki Mimar Sinan'ın 'Ustalık Eserim' dediği yapı?", secenekler: { A: "Selimiye Camii", B: "Süleymaniye Camii", C: "Şehzade Camii", D: "Üç Şerefeli Cami" }, dogruCevap: "A" },
    { seviye: 373, kategori: "Önemli Yerler", soru: "Bursa'nın simgesi olan tarihi cami?", secenekler: { A: "Ulu Cami", B: "Yeşil Cami", C: "Emir Sultan", D: "Muradiye" }, dogruCevap: "A" },
    { seviye: 374, kategori: "Önemli Yerler", soru: "İzmir'in sembolü olan tarihi yapı?", secenekler: { A: "Saat Kulesi", B: "Asansör", C: "Kadifekale", D: "Kordon" }, dogruCevap: "A" },
    { seviye: 375, kategori: "Önemli Yerler", soru: "Antalya'da bulunan dünyanın en iyi korunmuş antik tiyatrolarından biri?", secenekler: { A: "Aspendos", B: "Perge", C: "Termessos", D: "Phaselis" }, dogruCevap: "A" },
    { seviye: 376, kategori: "Önemli Yerler", soru: "Muğla'nın Bodrum ilçesindeki antik dünyanın yedi harikasından biri?", secenekler: { A: "Halikarnas Mozolesi", B: "Artemis Tapınağı", C: "Zeus Heykeli", D: "Rodos Heykeli" }, dogruCevap: "A" },
    { seviye: 377, kategori: "Önemli Yerler", soru: "Trabzon'da dik bir yamaca kurulu tarihi manastır?", secenekler: { A: "Sümela Manastırı", B: "Vazelon Manastırı", C: "Mor Gabriel", D: "Akdamar" }, dogruCevap: "A" },
    { seviye: 378, kategori: "Önemli Yerler", soru: "Van Gölü üzerinde bulunan ve Ermeni kilisesiyle ünlü ada?", secenekler: { A: "Akdamar Adası", B: "Çarpanak Adası", C: "Adır Adası", D: "Kuş Adası" }, dogruCevap: "A" },
    { seviye: 379, kategori: "Önemli Yerler", soru: "Denizli'deki beyaz travertenleriyle ünlü doğal güzellik?", secenekler: { A: "Pamukkale", B: "Hierapolis", C: "Laodikeia", D: "Afrodisias" }, dogruCevap: "A" },
    { seviye: 380, kategori: "Önemli Yerler", soru: "Nevşehir'de peri bacalarıyla ünlü bölge?", secenekler: { A: "Kapadokya", B: "Ihlara", C: "Derinkuyu", D: "Kaymaklı" }, dogruCevap: "A" },
    { seviye: 381, kategori: "Önemli Yerler", soru: "Adıyaman'daki dev heykellerin bulunduğu dağ?", secenekler: { A: "Nemrut Dağı", B: "Süphan Dağı", C: "Cudi Dağı", D: "Erciyes Dağı" }, dogruCevap: "A" },
    { seviye: 382, kategori: "Önemli Yerler", soru: "Çanakkale'de bulunan ve Homeros'un İlyada destanına konu olan antik kent?", secenekler: { A: "Truva", B: "Assos", C: "Parion", D: "Alexandria Troas" }, dogruCevap: "A" },
    { seviye: 383, kategori: "Önemli Yerler", soru: "Şanlıurfa'da bulunan 'Tarihin Sıfır Noktası' olarak bilinen yer?", secenekler: { A: "Göbeklitepe", B: "Harran", C: "Balıklıgöl", D: "Halfeti" }, dogruCevap: "A" },
    { seviye: 384, kategori: "Önemli Yerler", soru: "Mardin'in simgesi olan ve Mezopotamya ovasına bakan yapı?", secenekler: { A: "Zinciriye Medresesi", B: "Deyrulzafaran", C: "Kasımiye Medresesi", D: "Ulu Cami" }, dogruCevap: "C" },
    { seviye: 385, kategori: "Önemli Yerler", soru: "Erzurum'da Selçuklu döneminden kalan simge yapı?", secenekler: { A: "Çifte Minareli Medrese", B: "Yakutiye Medresesi", C: "Üç Kümbetler", D: "Aziziye Tabyası" }, dogruCevap: "A" },
    { seviye: 386, kategori: "Önemli Yerler", soru: "Sivas'taki UNESCO listesinde yer alan tıp merkezi ve cami?", secenekler: { A: "Divriği Ulu Cami ve Darüşşifası", B: "Gök Medrese", C: "Buruciye Medresesi", D: "Şifaiye Medresesi" }, dogruCevap: "A" },
    { seviye: 387, kategori: "Önemli Yerler", soru: "Kars yakınlarındaki tarihi İpekyolu şehri kalıntıları?", secenekler: { A: "Ani Harabeleri", B: "Çıldır", C: "Sarıkamış", D: "İshak Paşa" }, dogruCevap: "A" },
    { seviye: 388, kategori: "Önemli Yerler", soru: "Ağrı'nın Doğubayazıt ilçesindeki görkemli saray?", secenekler: { A: "İshak Paşa Sarayı", B: "Topkapı Sarayı", C: "Yıldız Sarayı", D: "Dolmabahçe Sarayı" }, dogruCevap: "A" },
    { seviye: 389, kategori: "Önemli Yerler", soru: "Karabük'te tarihi konaklarıyla ünlü ilçe?", secenekler: { A: "Safranbolu", B: "Eflani", C: "Yenice", D: "Ovacık" }, dogruCevap: "A" },
    { seviye: 390, kategori: "Önemli Yerler", soru: "Amasya'nın içinden geçen nehrin kenarındaki tarihi evler?", secenekler: { A: "Yalıboyu Evleri", B: "Odunpazarı Evleri", C: "Beypazarı Evleri", D: "Tarihi Amasya Evleri" }, dogruCevap: "A" },
    { seviye: 391, kategori: "Önemli Yerler", soru: "Bolu'da dört mevsim güzelliğiyle bilinen göl?", secenekler: { A: "Abant Gölü", B: "Gölcük", C: "Yedigöller", D: "Sünnet Gölü" }, dogruCevap: "A" },
    { seviye: 392, kategori: "Önemli Yerler", soru: "Rize'de bulunan ve Türkiye'nin en ünlü yaylası?", secenekler: { A: "Ayder Yaylası", B: "Anzer Yaylası", C: "Pokut Yaylası", D: "Gito Yaylası" }, dogruCevap: "A" },
    { seviye: 393, kategori: "Önemli Yerler", soru: "Artvin'de bulunan ve 'Türkiye'nin saklı cenneti' denilen göl?", secenekler: { A: "Karagöl", B: "Çıldır Gölü", C: "Tortum Gölü", D: "Nemrut Gölü" }, dogruCevap: "A" },
    { seviye: 394, kategori: "Önemli Yerler", soru: "Isparta'nın lavanta bahçeleriyle ünlü köyü?", secenekler: { A: "Kuyucak", B: "Eğirdir", C: "Yalvaç", D: "Aksu" }, dogruCevap: "A" },
    { seviye: 395, kategori: "Önemli Yerler", soru: "Burdur'daki 'Türkiye'nin Maldivleri' olarak bilinen göl?", secenekler: { A: "Salda Gölü", B: "Burdur Gölü", C: "Yarışlı Gölü", D: "Karataş Gölü" }, dogruCevap: "A" },
    { seviye: 396, kategori: "Önemli Yerler", soru: "Kastamonu'daki devasa kanyon?", secenekler: { A: "Valla Kanyonu", B: "Ihlara Vadisi", C: "Saklıkent", D: "Karanlık Kanyon" }, dogruCevap: "A" },
    { seviye: 397, kategori: "Önemli Yerler", soru: "Uşak'ta bulunan dünyanın en uzun kanyonlarından biri?", secenekler: { A: "Ulubey Kanyonu", B: "Köprülü Kanyon", C: "Şahinkaya", D: "İncesu" }, dogruCevap: "A" },
    { seviye: 398, kategori: "Önemli Yerler", soru: "Mersin'deki doğal oluşum çukurları?", secenekler: { A: "Cennet ve Cehennem", B: "Astım Mağarası", C: "Gilindire", D: "Narlıkuyu" }, dogruCevap: "A" },
    { seviye: 399, kategori: "Önemli Yerler", soru: "Hatay'daki dünyanın ilk mağara kilisesi?", secenekler: { A: "St. Pierre Kilisesi", B: "St. Nicolas", C: "Sümela", D: "Akdamar" }, dogruCevap: "A" },
    { seviye: 400, kategori: "Önemli Yerler", soru: "Gaziantep'teki dünyanın en büyük mozaik müzelerinden biri?", secenekler: { A: "Zeugma Mozaik Müzesi", B: "Hatay Arkeoloji", C: "Efes Müzesi", D: "Antalya Müzesi" }, dogruCevap: "A" },
    { seviye: 401, kategori: "Önemli Yerler", soru: "Dubai'de bulunan dünyanın en yüksek binası?", secenekler: { A: "Burj Khalifa", B: "Burj Al Arab", C: "Shanghai Tower", D: "Abraj Al Bait" }, dogruCevap: "A" },
    { seviye: 402, kategori: "Önemli Yerler", soru: "Suudi Arabistan'da Müslümanların kıblesi olan Kabe nerededir?", secenekler: { A: "Mekke", B: "Medine", C: "Cidde", D: "Riyad" }, dogruCevap: "A" },
    { seviye: 403, kategori: "Önemli Yerler", soru: "Kudüs'te bulunan ve İslamiyet'in ilk kıblesi olan yapı?", secenekler: { A: "Mescid-i Aksa", B: "Kubbetü's Sahra", C: "Kıyamet Kilisesi", D: "Ağlama Duvarı" }, dogruCevap: "A" },
    { seviye: 404, kategori: "Önemli Yerler", soru: "Rusya'nın St. Petersburg şehrindeki devasa müze?", secenekler: { A: "Ermitaj Müzesi", B: "Louvre Müzesi", C: "British Museum", D: "Prado Müzesi" }, dogruCevap: "A" },
    { seviye: 405, kategori: "Önemli Yerler", soru: "Paris'teki dünyanın en çok ziyaret edilen sanat müzesi?", secenekler: { A: "Louvre Müzesi", B: "Orsay Müzesi", C: "Pompidou Center", D: "Uffizi" }, dogruCevap: "A" },
    { seviye: 406, kategori: "Önemli Yerler", soru: "Madrid'deki en ünlü sanat müzesi hangisidir?", secenekler: { A: "Prado Müzesi", B: "Reina Sofia", C: "Guggenheim", D: "Rijksmuseum" }, dogruCevap: "A" },
    { seviye: 407, kategori: "Önemli Yerler", soru: "Amsterdam'da bulunan ulusal müze?", secenekler: { A: "Rijksmuseum", B: "Van Gogh Müzesi", C: "Anne Frank Evi", D: "Stedelijk" }, dogruCevap: "A" },
    { seviye: 408, kategori: "Önemli Yerler", soru: "New York'taki ünlü sanat müzesi (MET)?", secenekler: { A: "Metropolitan Sanat Müzesi", B: "MoMA", C: "Guggenheim", D: "Whitney" }, dogruCevap: "A" },
    { seviye: 409, kategori: "Önemli Yerler", soru: "Londra'daki devasa tarih ve kültür müzesi?", secenekler: { A: "British Museum", B: "National Gallery", C: "Tate Modern", D: "V&A Museum" }, dogruCevap: "A" },
    { seviye: 410, kategori: "Önemli Yerler", soru: "Atina'daki antik eserlerin sergilendiği müze?", secenekler: { A: "Ulusal Arkeoloji Müzesi", B: "Akropolis Müzesi", C: "Benaki Müzesi", D: "Bizans Müzesi" }, dogruCevap: "A" },
    { seviye: 411, kategori: "Önemli Yerler", soru: "Berlin'de bulunan ve içinde Bergama Sunağı'nın olduğu müze?", secenekler: { A: "Pergamon Müzesi", B: "Bode Müzesi", C: "Altes Museum", D: "Neues Museum" }, dogruCevap: "A" },
    { seviye: 412, kategori: "Önemli Yerler", soru: "Kahire'de bulunan ve Tutankamon'un hazinelerini barındıran müze?", secenekler: { A: "Mısır Müzesi", B: "İslam Sanatları Müzesi", C: "Kıpti Müzesi", D: "Gayer-Anderson" }, dogruCevap: "A" },
    { seviye: 413, kategori: "Önemli Yerler", soru: "Meksika'da Mayalara ait olan basamaklı piramit?", secenekler: { A: "Chichen Itza", B: "Teotihuacan", C: "Palenque", D: "Uxmal" }, dogruCevap: "A" },
    { seviye: 414, kategori: "Önemli Yerler", soru: "Kamboçya'da bulunan devasa tapınak kompleksi?", secenekler: { A: "Angkor Wat", B: "Bayon", C: "Borobudur", D: "Pagan" }, dogruCevap: "A" },
    { seviye: 415, kategori: "Önemli Yerler", soru: "Endonezya'da bulunan dünyanın en büyük Budist tapınağı?", secenekler: { A: "Borobudur", B: "Prambanan", C: "Tanah Lot", D: "Uluwatu" }, dogruCevap: "A" },
    { seviye: 416, kategori: "Önemli Yerler", soru: "Tayland'ın başkenti Bangkok'taki görkemli saray?", secenekler: { A: "Büyük Saray (Grand Palace)", B: "Yasak Şehir", C: "Gyeongbokgung", D: "Himeji Şatosu" }, dogruCevap: "A" },
    { seviye: 417, kategori: "Önemli Yerler", soru: "Japonya'nın Kyoto şehrindeki altın kaplamalı tapınak?", secenekler: { A: "Kinkaku-ji", B: "Ginkaku-ji", C: "Kiyomizu-dera", D: "Fushimi Inari" }, dogruCevap: "A" },
    { seviye: 418, kategori: "Önemli Yerler", soru: "Güney Kore'nin başkenti Seul'deki ana saray?", secenekler: { A: "Gyeongbokgung", B: "Changdeokgung", C: "Deoksugung", D: "Gyeonghuigung" }, dogruCevap: "A" },
    { seviye: 419, kategori: "Önemli Yerler", soru: "Çin'in başkenti Pekin'deki imparatorluk sarayı?", secenekler: { A: "Yasak Şehir", B: "Yazlık Saray", C: "Cennet Tapınağı", D: "Ming Mezarları" }, dogruCevap: "A" },
    { seviye: 420, kategori: "Önemli Yerler", soru: "Tibet'te bulunan Dalay Lama'nın eski kışlık sarayı?", secenekler: { A: "Potala Sarayı", B: "Norbulingka", C: "Jokhang Tapınağı", D: "Sera Manastırı" }, dogruCevap: "A" },
    { seviye: 421, kategori: "Önemli Yerler", soru: "İspanya'nın Granada şehrindeki Endülüs İslam mimarisi şaheseri?", secenekler: { A: "El Hamra Sarayı", B: "Kurtuba Camii", C: "Giralda", D: "Alcazar" }, dogruCevap: "A" },
    { seviye: 422, kategori: "Önemli Yerler", soru: "İspanya'nın Kurtuba (Cordoba) şehrindeki tarihi cami?", secenekler: { A: "Kurtuba Camii", B: "El Hamra", C: "Medinetü'z-Zehra", D: "Sevilla Ulu Cami" }, dogruCevap: "A" },
    { seviye: 423, kategori: "Önemli Yerler", soru: "Fas'ın Marakeş şehrindeki ünlü meydan?", secenekler: { A: "Jemaa el-Fnaa", B: "Tahrir", C: "Majorelle", D: "Kutubiye" }, dogruCevap: "A" },
    { seviye: 424, kategori: "Önemli Yerler", soru: "Özbekistan'ın Semerkant şehrindeki tarihi meydan?", secenekler: { A: "Registan Meydanı", B: "Gür-i Emir", C: "Bibi Hanım", D: "Şah-ı Zinde" }, dogruCevap: "A" },
    { seviye: 425, kategori: "Önemli Yerler", soru: "İran'ın İsfahan şehrindeki devasa meydan?", secenekler: { A: "Nakş-ı Cihan Meydanı", B: "Azadi Meydanı", C: "Tecriş", D: "İmam Meydanı" }, dogruCevap: "A" },
    { seviye: 426, kategori: "Önemli Yerler", soru: "Kazakistan'ın başkentindeki (Astana) simge kule?", secenekler: { A: "Bayterek Kulesi", B: "Han Çatırı", C: "Nur Alem", D: "Piramit" }, dogruCevap: "A" },
    { seviye: 427, kategori: "Önemli Yerler", soru: "Azerbaycan'ın başkenti Bakü'deki tarihi kule?", secenekler: { A: "Kız Kalesi", B: "Alev Kuleleri", C: "Şirvanşahlar Sarayı", D: "Haydar Aliyev Merkezi" }, dogruCevap: "A" },
    { seviye: 428, kategori: "Önemli Yerler", soru: "Türkmenistan'ın başkentindeki (Aşkabat) tarafsızlık anıtı?", secenekler: { A: "Tarafsızlık Arkı", B: "Bağımsızlık Anıtı", C: "Ruhname", D: "Türkmenbaşı Anıtı" }, dogruCevap: "A" },
    { seviye: 429, kategori: "Önemli Yerler", soru: "Bosna Hersek'in Mostar şehrindeki tarihi köprü?", secenekler: { A: "Mostar Köprüsü", B: "Drina Köprüsü", C: "Latinska Köprüsü", D: "Konjic Köprüsü" }, dogruCevap: "A" },
    { seviye: 430, kategori: "Önemli Yerler", soru: "Kuzey Makedonya'nın başkenti Üsküp'teki tarihi köprü?", secenekler: { A: "Taş Köprü", B: "Sanat Köprüsü", C: "Göz Köprüsü", D: "Özgürlük Köprüsü" }, dogruCevap: "A" },
    { seviye: 431, kategori: "Önemli Yerler", soru: "Arnavutluk'un başkenti Tiran'daki ana meydan?", secenekler: { A: "İskender Bey Meydanı", B: "Rahibe Teresa", C: "Ethem Bey", D: "Blloku" }, dogruCevap: "A" },
    { seviye: 432, kategori: "Önemli Yerler", soru: "Macaristan'ın başkenti Budapeşte'deki görkemli parlamento binası?", secenekler: { A: "Macaristan Parlamento Binası", B: "Buda Kalesi", C: "Balıkçı Tabyası", D: "Zincirli Köprü" }, dogruCevap: "A" },
    { seviye: 433, kategori: "Önemli Yerler", soru: "Çekya'nın başkenti Prag'daki tarihi köprü?", secenekler: { A: "Karl Köprüsü", B: "Charles Köprüsü", C: "Astronomik Saat", D: "Prag Kalesi" }, dogruCevap: "A" },
    { seviye: 434, kategori: "Önemli Yerler", soru: "Avusturya'nın başkenti Viyana'daki tarihi katedral?", secenekler: { A: "Aziz Stefan Katedrali", B: "Hofburg", C: "Schönbrunn", D: "Belvedere" }, dogruCevap: "A" },
    { seviye: 435, kategori: "Önemli Yerler", soru: "Polonya'nın başkenti Varşova'daki tarihi merkez?", secenekler: { A: "Eski Şehir (Old Town)", B: "Kültür ve Bilim Sarayı", C: "Lazienki", D: "Wilanow" }, dogruCevap: "A" },
    { seviye: 436, kategori: "Önemli Yerler", soru: "Danimarka'nın başkenti Kopenhag'daki küçük heykel?", secenekler: { A: "Küçük Deniz Kızı", B: "Gefion Çeşmesi", C: "Nyhavn", D: "Tivoli" }, dogruCevap: "A" },
    { seviye: 437, kategori: "Önemli Yerler", soru: "Norveç'te fiyortların başkenti olarak bilinen şehir?", secenekler: { A: "Bergen", B: "Oslo", C: "Stavanger", D: "Trondheim" }, dogruCevap: "A" },
    { seviye: 438, kategori: "Önemli Yerler", soru: "İzlanda'da bulunan ve 'Mavi Göl' olarak bilinen yer?", secenekler: { A: "Blue Lagoon", B: "Gullfoss", C: "Geysir", D: "Skogafoss" }, dogruCevap: "A" },
    { seviye: 439, kategori: "Önemli Yerler", soru: "İrlanda'nın batısındaki devasa uçurumlar?", secenekler: { A: "Moher Uçurumları", B: "Giant's Causeway", C: "Ring of Kerry", D: "Burren" }, dogruCevap: "A" },
    { seviye: 440, kategori: "Önemli Yerler", soru: "İskoçya'daki canavar efsanesiyle ünlü göl?", secenekler: { A: "Loch Ness", B: "Loch Lomond", C: "Loch Tay", D: "Loch Katrine" }, dogruCevap: "A" },
    { seviye: 441, kategori: "Önemli Yerler", soru: "İspanya'nın Barselona şehrindeki bitmeyen kilise?", secenekler: { A: "Sagrada Familia", B: "Park Güell", C: "Casa Batllo", D: "Montserrat" }, dogruCevap: "A" },
    { seviye: 442, kategori: "Önemli Yerler", soru: "Portekiz'in başkenti Lizbon'daki tarihi kule?", secenekler: { A: "Belem Kulesi", B: "Jerónimos Manastırı", C: "Sao Jorge Kalesi", D: "Pena Sarayı" }, dogruCevap: "A" },
    { seviye: 443, kategori: "Önemli Yerler", soru: "Cezayir'deki bağımsızlık anıtı?", secenekler: { A: "Makam El Chahid", B: "Kasbah", C: "Notre Dame d'Afrique", D: "Timgad" }, dogruCevap: "A" },
    { seviye: 444, kategori: "Önemli Yerler", soru: "Tunus'taki antik Fenike şehri?", secenekler: { A: "Kartaca", B: "Bardo", C: "Sidi Bou Said", D: "El Djem" }, dogruCevap: "A" },
    { seviye: 445, kategori: "Önemli Yerler", soru: "Güney Afrika'nın simgesi olan düz tepeli dağ?", secenekler: { A: "Masa Dağı (Table Mountain)", B: "Drakensberg", C: "Lion's Head", D: "Signal Hill" }, dogruCevap: "A" },
    { seviye: 446, kategori: "Önemli Yerler", soru: "Kenya ve Tanzanya arasındaki devasa milli park?", secenekler: { A: "Serengeti", B: "Maasai Mara", C: "Kruger", D: "Etosha" }, dogruCevap: "A" },
    { seviye: 447, kategori: "Önemli Yerler", soru: "Tanzanya'daki Afrika'nın en yüksek dağı?", secenekler: { A: "Kilimanjaro", B: "Kenya Dağı", C: "Ruwenzori", D: "Atlas Dağları" }, dogruCevap: "A" },
    { seviye: 448, kategori: "Önemli Yerler", soru: "Etiyopya'da kayalara oyulmuş kiliseleriyle ünlü yer?", secenekler: { A: "Lalibela", B: "Axum", C: "Gondar", D: "Harar" }, dogruCevap: "A" },
    { seviye: 449, kategori: "Önemli Yerler", soru: "Mali'deki çamurdan yapılmış dev cami?", secenekler: { A: "Djenne Büyük Camii", B: "Timbuktu", C: "Sankore", D: "Agadez" }, dogruCevap: "A" },
    { seviye: 450, kategori: "Önemli Yerler", soru: "Madagaskar'daki ünlü ağaçlı yol?", secenekler: { A: "Baobab Yolu", B: "Tsingy", C: "Isalo", D: "Nosy Be" }, dogruCevap: "A" },
    { seviye: 451, kategori: "Önemli Yerler", soru: "İstanbul'da Galata semtinde bulunan tarihi kule?", secenekler: { A: "Galata Kulesi", B: "Kız Kulesi", C: "Beyazıt Kulesi", D: "Adalet Kulesi" }, dogruCevap: "A" },
    { seviye: 452, kategori: "Önemli Yerler", soru: "Boğaz kıyısında bulunan ve Avrupa'nın en lüks saraylarından biri kabul edilen yapı?", secenekler: { A: "Dolmabahçe Sarayı", B: "Çırağan Sarayı", C: "Yıldız Sarayı", D: "Beylerbeyi Sarayı" }, dogruCevap: "A" },
    { seviye: 453, kategori: "Önemli Yerler", soru: "Mimar Sinan'ın İstanbul'daki en görkemli eseri hangisidir?", secenekler: { A: "Süleymaniye Camii", B: "Selimiye Camii", C: "Şehzade Camii", D: "Mihrimah Sultan" }, dogruCevap: "A" },
    { seviye: 454, kategori: "Önemli Yerler", soru: "Sultan Ahmet tarafından yaptırılan ve 'Mavi Cami' olarak bilinen yapı?", secenekler: { A: "Sultanahmet Camii", B: "Fatih Camii", C: "Yeni Cami", D: "Ortaköy Camii" }, dogruCevap: "A" },
    { seviye: 455, kategori: "Önemli Yerler", soru: "İstanbul'un fethi için Fatih Sultan Mehmet tarafından yaptırılan hisar?", secenekler: { A: "Rumeli Hisarı", B: "Anadolu Hisarı", C: "Yedikule Zindanları", D: "Kilitbahir" }, dogruCevap: "A" },
    { seviye: 456, kategori: "Önemli Yerler", soru: "Yıldırım Bayezid tarafından yaptırılan İstanbul'daki ilk hisar?", secenekler: { A: "Anadolu Hisarı", B: "Rumeli Hisarı", C: "Yoros Kalesi", D: "Aydos Kalesi" }, dogruCevap: "A" },
    { seviye: 457, kategori: "Önemli Yerler", soru: "İstanbul'da Bizans döneminden kalan dev sarnıç?", secenekler: { A: "Yerebatan Sarnıcı", B: "Binbirdirek Sarnıcı", C: "Şerefiye Sarnıcı", D: "Theodosius Sarnıcı" }, dogruCevap: "A" },
    { seviye: 458, kategori: "Önemli Yerler", soru: "Haliç üzerinde bulunan ve Karaköy ile Eminönü'nü bağlayan köprü?", secenekler: { A: "Galata Köprüsü", B: "Unkapanı Köprüsü", C: "Haliç Köprüsü", D: "Metro Köprüsü" }, dogruCevap: "A" },
    { seviye: 459, kategori: "Önemli Yerler", soru: "İstanbul'un en ünlü meydanı hangisidir?", secenekler: { A: "Taksim Meydanı", B: "Sultanahmet Meydanı", C: "Beyazıt Meydanı", D: "Beşiktaş Meydanı" }, dogruCevap: "A" },
    { seviye: 460, kategori: "Önemli Yerler", soru: "Taksim'den Tünel'e kadar uzanan tarihi cadde?", secenekler: { A: "İstiklal Caddesi", B: "Bağdat Caddesi", C: "Halaskargazi", D: "Vatan Caddesi" }, dogruCevap: "A" },
    { seviye: 461, kategori: "Önemli Yerler", soru: "Ankara'daki Anadolu'nun geçmişine ışık tutan büyük müze?", secenekler: { A: "Anadolu Medeniyetleri Müzesi", B: "Etnoğrafya Müzesi", C: "Kurtuluş Savaşı Müzesi", D: "Cumhuriyet Müzesi" }, dogruCevap: "A" },
    { seviye: 462, kategori: "Önemli Yerler", soru: "Ankara'da Hacı Bayram Veli Türbesi'nin yanında bulunan antik tapınak?", secenekler: { A: "Augustus Tapınağı", B: "Zeus Tapınağı", C: "Artemis Tapınağı", D: "Apollo Tapınağı" }, dogruCevap: "A" },
    { seviye: 463, kategori: "Önemli Yerler", soru: "İzmir'de Bergama ilçesinde bulunan antik sağlık merkezi?", secenekler: { A: "Asklepion", B: "Akropol", C: "Bazilika", D: "Kızıl Avlu" }, dogruCevap: "A" },
    { seviye: 464, kategori: "Önemli Yerler", soru: "İzmir'in Selçuk ilçesinde bulunan antik dünyanın yedi harikasından biri?", secenekler: { A: "Artemis Tapınağı", B: "Celsus Kütüphanesi", C: "Meryem Ana Evi", D: "Yedi Uyuyanlar" }, dogruCevap: "A" },
    { seviye: 465, kategori: "Önemli Yerler", soru: "Efes Antik Kenti'nin en simge yapısı olan kütüphane?", secenekler: { A: "Celsus Kütüphanesi", B: "İskenderiye Kütüphanesi", C: "Hadrian Kütüphanesi", D: "Pergamon Kütüphanesi" }, dogruCevap: "A" },
    { seviye: 466, kategori: "Önemli Yerler", soru: "Antalya'da bulunan ve suları doğrudan denize dökülen şelale?", secenekler: { A: "Düden Şelalesi", B: "Manavgat Şelalesi", C: "Kurşunlu Şelalesi", D: "Uçansu Şelalesi" }, dogruCevap: "A" },
    { seviye: 467, kategori: "Önemli Yerler", soru: "Antalya'nın Alanya ilçesindeki ünlü mağara?", secenekler: { A: "Damlataş Mağarası", B: "Karain Mağarası", C: "Dim Mağarası", D: "Altınbeşik Mağarası" }, dogruCevap: "A" },
    { seviye: 468, kategori: "Önemli Yerler", soru: "Muğla'nın Fethiye ilçesindeki dünyaca ünlü plaj?", secenekler: { A: "Ölüdeniz", B: "Kelebekler Vadisi", C: "Kabak Koyu", D: "Çalış Plajı" }, dogruCevap: "A" },
    { seviye: 469, kategori: "Önemli Yerler", soru: "Muğla'da bulunan ve antik Likya mezarlarıyla ünlü yer?", secenekler: { A: "Dalyan (Kaunos)", B: "Knidos", C: "Tlos", D: "Patara" }, dogruCevap: "A" },
    { seviye: 470, kategori: "Önemli Yerler", soru: "Muğla'nın Datça ilçesinde bulunan antik liman kenti?", secenekler: { A: "Knidos", B: "Stratonikeia", C: "Lagina", D: "Euromos" }, dogruCevap: "A" },
    { seviye: 471, kategori: "Önemli Yerler", soru: "Aydın'daki antik dönem felsefe ve sanat merkezi?", secenekler: { A: "Milet", B: "Didim", C: "Priene", D: "Tralleis" }, dogruCevap: "A" },
    { seviye: 472, kategori: "Önemli Yerler", soru: "Aydın'ın Didim ilçesindeki devasa tapınak?", secenekler: { A: "Apollon Tapınağı", B: "Artemis Tapınağı", C: "Zeus Tapınağı", D: "Hera Tapınağı" }, dogruCevap: "A" },
    { seviye: 473, kategori: "Önemli Yerler", soru: "Çanakkale'de Şehitler Abidesi hangi yarımada üzerindedir?", secenekler: { A: "Gelibolu Yarımadası", B: "Biga Yarımadası", C: "Lapseki", D: "Eceabat" }, dogruCevap: "A" },
    { seviye: 474, kategori: "Önemli Yerler", soru: "Çanakkale Boğazı'nın en dar noktasındaki kale?", secenekler: { A: "Kilitbahir Kalesi", B: "Çimenlik Kalesi", C: "Seddülbahir", D: "Bigalı Kalesi" }, dogruCevap: "A" },
    { seviye: 475, kategori: "Önemli Yerler", soru: "Balıkesir'de Ayvalık açıklarındaki turistik ada?", secenekler: { A: "Cunda (Alibey) Adası", B: "Avşa Adası", C: "Marmara Adası", D: "Paşalimanı" }, dogruCevap: "A" },
    { seviye: 476, kategori: "Önemli Yerler", soru: "Bursa'da Osmanlı'nın kuruluş yeri olan tarihi ilçe?", secenekler: { A: "İznik", B: "Mudanya", C: "Osmaneli", D: "Söğüt" }, dogruCevap: "A" },
    { seviye: 477, kategori: "Önemli Yerler", soru: "Bursa'da bulunan ve Hristiyanlık için önemli konsil kararlarının alındığı yer?", secenekler: { A: "İznik", B: "Trilye", C: "Gölyazı", D: "Cumalıkızık" }, dogruCevap: "A" },
    { seviye: 478, kategori: "Önemli Yerler", soru: "Konya'da Mevlana Müzesi'nin bulunduğu yer?", secenekler: { A: "Mevlana Dergahı", B: "Alaeddin Tepesi", C: "Karatay", D: "Meram" }, dogruCevap: "A" },
    { seviye: 479, kategori: "Önemli Yerler", soru: "Konya'daki Selçuklu döneminden kalan görkemli cami?", secenekler: { A: "Alaeddin Camii", B: "Aziziye Camii", C: "Selimiye Camii", D: "İplikçi Camii" }, dogruCevap: "A" },
    { seviye: 480, kategori: "Önemli Yerler", soru: "Kayseri'de bulunan İç Anadolu'nun en yüksek dağı?", secenekler: { A: "Erciyes Dağı", B: "Hasan Dağı", C: "Melendiz", D: "Yıldız Dağı" }, dogruCevap: "A" },
    { seviye: 481, kategori: "Önemli Yerler", soru: "Niğde'de bulunan ve mimarisiyle ünlü Selçuklu camisi?", secenekler: { A: "Alaeddin Camii", B: "Sungurbey", C: "Paşa Camii", D: "Dışarı Camii" }, dogruCevap: "A" },
    { seviye: 482, kategori: "Önemli Yerler", soru: "Aksaray'daki 14 km uzunluğundaki devasa vadi?", secenekler: { A: "Ihlara Vadisi", B: "Manastır Vadisi", C: "Soğanlı Vadisi", D: "Zelve Vadisi" }, dogruCevap: "A" },
    { seviye: 483, kategori: "Önemli Yerler", soru: "Eskişehir'de Porsuk Çayı kenarındaki turistik bölge?", secenekler: { A: "Adalar", B: "Odunpazarı", C: "Sazova", D: "Kentpark" }, dogruCevap: "A" },
    { seviye: 484, kategori: "Önemli Yerler", soru: "Samsun'da Kurtuluş Savaşı'nın başladığı anı simgeleyen yapı?", secenekler: { A: "Onur Anıtı", B: "Bandırma Vapuru", C: "İlkadım Anıtı", D: "Gazi Müzesi" }, dogruCevap: "A" },
    { seviye: 485, kategori: "Önemli Yerler", soru: "Sinop'ta bulunan Türkiye'nin en kuzey noktası?", secenekler: { A: "İnceburun", B: "Hamsilos", C: "Akliman", D: "Sarıkum" }, dogruCevap: "A" },
    { seviye: 486, kategori: "Önemli Yerler", soru: "Ordu'da şehri kuşbakışı gören ünlü tepe?", secenekler: { A: "Boztepe", B: "Yoros", C: "Çamlıca", D: "Zigana" }, dogruCevap: "A" },
    { seviye: 487, kategori: "Önemli Yerler", soru: "Rize'de Fırtına Deresi üzerinde bulunan tarihi köprülerden biri?", secenekler: { A: "Şenyuva Köprüsü", B: "Mikron Köprüsü", C: "Hala Köprüsü", D: "Taş Köprü" }, dogruCevap: "A" },
    { seviye: 488, kategori: "Önemli Yerler", soru: "Tokat'ta bulunan ve 'Dünyanın en görkemli mağaralarından biri' denilen yer?", secenekler: { A: "Ballıca Mağarası", B: "Karaca Mağarası", C: "Menzil", D: "İnsuyu" }, dogruCevap: "A" },
    { seviye: 489, kategori: "Önemli Yerler", soru: "Gümüşhane'de bulunan damlataş mağarası?", secenekler: { A: "Karaca Mağarası", B: "Akçakale", C: "Çal Mağarası", D: "Buzluk" }, dogruCevap: "A" },
    { seviye: 490, kategori: "Önemli Yerler", soru: "Erzincan'da bulunan ve doğa sporları için ünlü kanyon?", secenekler: { A: "Karanlık Kanyon", B: "Eğin", C: "Kemaliye", D: "Munzur" }, dogruCevap: "A" },
    { seviye: 491, kategori: "Önemli Yerler", soru: "Tunceli'de bulunan milli park?", secenekler: { A: "Munzur Vadisi Milli Parkı", B: "Pülümür", C: "Ovacık", D: "Mercan" }, dogruCevap: "A" },
    { seviye: 492, kategori: "Önemli Yerler", soru: "Elazığ'da bulunan antik kent kalıntıları?", secenekler: { A: "Harput", B: "Palu", C: "Hazar", D: "Keban" }, dogruCevap: "A" },
    { seviye: 493, kategori: "Önemli Yerler", soru: "Diyarbakır'da UNESCO listesinde yer alan tarihi surlar ve?", secenekler: { A: "Hevsel Bahçeleri", B: "Malabadi Köprüsü", C: "Ulu Cami", D: "On Gözlü Köprü" }, dogruCevap: "A" },
    { seviye: 494, kategori: "Önemli Yerler", soru: "Diyarbakır ile Batman arasında bulunan tarihi köprü?", secenekler: { A: "Malabadi Köprüsü", B: "On Gözlü Köprü", C: "Batman Köprüsü", D: "Hasankeyf Köprüsü" }, dogruCevap: "A" },
    { seviye: 495, kategori: "Önemli Yerler", soru: "Batman'da bulunan ve sular altında kalan antik yerleşim?", secenekler: { A: "Hasankeyf", B: "Zeynel Bey", C: "Mor Kiryakus", D: "Hallan Çemi" }, dogruCevap: "A" },
    { seviye: 496, kategori: "Önemli Yerler", soru: "Mardin'in Midyat ilçesindeki ünlü manastır?", secenekler: { A: "Mor Gabriel", B: "Deyrulzafaran", C: "Mor Behnam", D: "Meryem Ana" }, dogruCevap: "A" },
    { seviye: 497, kategori: "Önemli Yerler", soru: "Şanlıurfa'da bulunan ve Hz. İbrahim'in ateşe atıldığı yer olduğuna inanılan göl?", secenekler: { A: "Balıklıgöl", B: "Aynzeliha Gölü", C: "Harran", D: "Fırat" }, dogruCevap: "A" },
    { seviye: 498, kategori: "Önemli Yerler", soru: "Gaziantep'in simgesi olan tarihi kale?", secenekler: { A: "Gaziantep Kalesi", B: "Rumkale", C: "Ravanda", D: "Tilbaşar" }, dogruCevap: "A" },
    { seviye: 499, kategori: "Önemli Yerler", soru: "Fırat nehri kıyısındaki yarısı sular altında kalmış ilçe?", secenekler: { A: "Halfeti", B: "Birecik", C: "Yavuzeli", D: "Nizip" }, dogruCevap: "A" },
    { seviye: 500, kategori: "Önemli Yerler", soru: "Kahramanmaraş'ta bulunan meşhur yayla?", secenekler: { A: "Başkonuş Yaylası", B: "Yavşan", C: "Tekir", D: "Ekinözü" }, dogruCevap: "A" },
    { seviye: 501, kategori: "Önemli Yerler", soru: "İzlanda'da bulunan ve Avrupa'nın en güçlü şelalesi kabul edilen yer?", secenekler: { A: "Dettifoss", B: "Gullfoss", C: "Skogafoss", D: "Seljalandsfoss" }, dogruCevap: "A" },
    { seviye: 502, kategori: "Önemli Yerler", soru: "Hırvatistan'da bulunan ve gölleriyle ünlü milli park?", secenekler: { A: "Plitvice Gölleri", B: "Krka", C: "Dubrovnik", D: "Split" }, dogruCevap: "A" },
    { seviye: 503, kategori: "Önemli Yerler", soru: "Karadağ'da bulunan ve Avrupa'nın en güney fiyordu denilen yer?", secenekler: { A: "Kotor Körfezi", B: "Budva", C: "Perast", D: "Sveti Stefan" }, dogruCevap: "A" },
    { seviye: 504, kategori: "Önemli Yerler", soru: "İsviçre'de bulunan ve Avrupa'nın zirvesi denilen dağ geçidi?", secenekler: { A: "Jungfraujoch", B: "Matterhorn", C: "Mont Blanc", D: "St. Gotthard" }, dogruCevap: "A" },
    { seviye: 505, kategori: "Önemli Yerler", soru: "İtalya'da kanalları ve gondollarıyla ünlü şehir?", secenekler: { A: "Venedik", B: "Floransa", C: "Napoli", D: "Verona" }, dogruCevap: "A" },
    { seviye: 506, kategori: "Önemli Yerler", soru: "İtalya'da Rönesans'ın doğum yeri kabul edilen şehir?", secenekler: { A: "Floransa", B: "Roma", C: "Milano", D: "Venedik" }, dogruCevap: "A" },
    { seviye: 507, kategori: "Önemli Yerler", soru: "Roma'daki dünyanın en küçük bağımsız devleti?", secenekler: { A: "Vatikan", B: "San Marino", C: "Monako", D: "Andorra" }, dogruCevap: "A" },
    { seviye: 508, kategori: "Önemli Yerler", soru: "İspanya'da bulunan Mağribi kalesi?", secenekler: { A: "El Hamra", B: "Alcazar", C: "Giralda", D: "Sagrada" }, dogruCevap: "A" },
    { seviye: 509, kategori: "Önemli Yerler", soru: "Yunanistan'da bulunan 'Havada Asılı' manastırlar bölgesi?", secenekler: { A: "Meteora", B: "Aynaroz", C: "Delphi", D: "Olympia" }, dogruCevap: "A" },
    { seviye: 510, kategori: "Önemli Yerler", soru: "Almanya'daki masalsı Neuschwanstein Şatosu hangi eyalettedir?", secenekler: { A: "Bavyera", B: "Saksonya", C: "Hessen", D: "Berlin" }, dogruCevap: "A" },
    { seviye: 511, kategori: "Önemli Yerler", soru: "Berlin'deki tarihi şehir kapısı?", secenekler: { A: "Brandenburg Kapısı", B: "Zafer Takı", C: "Check Point Charlie", D: "Reichstag" }, dogruCevap: "A" },
    { seviye: 512, kategori: "Önemli Yerler", soru: "Fransa'daki ünlü sahil şeridi?", secenekler: { A: "Fransız Rivierası (Cote d'Azur)", B: "Normandiya", C: "Bretanya", D: "Bordeaux" }, dogruCevap: "A" },
    { seviye: 513, kategori: "Önemli Yerler", soru: "Belçika'nın başkenti Brüksel'deki dev atom modeli?", secenekler: { A: "Atomium", B: "Manneken Pis", C: "Grand Place", D: "Mini Europe" }, dogruCevap: "A" },
    { seviye: 514, kategori: "Önemli Yerler", soru: "Hollanda'daki yel değirmenleriyle ünlü tarihi yer?", secenekler: { A: "Zaanse Schans", B: "Kinderdijk", C: "Keukenhof", D: "Giethoorn" }, dogruCevap: "A" },
    { seviye: 515, kategori: "Önemli Yerler", soru: "Rusya'daki dünyanın en derin gölü?", secenekler: { A: "Baykal Gölü", B: "Hazar Denizi", C: "Ladoğa", D: "Onega" }, dogruCevap: "A" },
    { seviye: 516, kategori: "Önemli Yerler", soru: "Estonya'nın Orta Çağ dokusunu koruyan başkenti?", secenekler: { A: "Tallinn", B: "Riga", C: "Vilnius", D: "Helsinki" }, dogruCevap: "A" },
    { seviye: 517, kategori: "Önemli Yerler", soru: "Finlandiya'nın kuzeyindeki 'Noel Baba'nın köyü' nerededir?", secenekler: { A: "Rovaniemi", B: "Helsinki", C: "Tampere", D: "Turku" }, dogruCevap: "A" },
    { seviye: 518, kategori: "Önemli Yerler", soru: "İngiltere'de bulunan gizemli dikili taşlar?", secenekler: { A: "Stonehenge", B: "Avebury", C: "Hadrian Duvarı", D: "Bath" }, dogruCevap: "A" },
    { seviye: 519, kategori: "Önemli Yerler", soru: "ABD'de San Francisco'daki ünlü kırmızı köprü?", secenekler: { A: "Golden Gate Köprüsü", B: "Brooklyn Köprüsü", C: "Manhattan Köprüsü", D: "Bay Bridge" }, dogruCevap: "A" },
    { seviye: 520, kategori: "Önemli Yerler", soru: "ABD'de başkanların yüzlerinin oyulduğu dağ?", secenekler: { A: "Rushmore Dağı", B: "Rocky Dağları", C: "Appalachian", D: "Rainier" }, dogruCevap: "A" },
    { seviye: 521, kategori: "Önemli Yerler", soru: "Brezilya ve Arjantin sınırındaki dev şelale?", secenekler: { A: "Iguazu Şelaleleri", B: "Angel", C: "Niagara", D: "Victoria" }, dogruCevap: "A" },
    { seviye: 522, kategori: "Önemli Yerler", soru: "Şili'deki devasa taş heykelleriyle ünlü ada?", secenekler: { A: "Paskalya Adası", B: "Galapagos", C: "Fiji", D: "Bora Bora" }, dogruCevap: "A" },
    { seviye: 523, kategori: "Önemli Yerler", soru: "Ekvador'a bağlı olan ve Darwin'in evrim teorisini geliştirdiği adalar?", secenekler: { A: "Galapagos Adaları", B: "Maldivler", C: "Seyşeller", D: "Kanarya Adaları" }, dogruCevap: "A" },
    { seviye: 524, kategori: "Önemli Yerler", soru: "Mısır'daki dev kedi vücutlu insan başlı heykel?", secenekler: { A: "Büyük Sfenks", B: "Anubis", C: "Horus", D: "Osiris" }, dogruCevap: "A" },
    { seviye: 525, kategori: "Önemli Yerler", soru: "Mısır'da Nil nehri kıyısındaki devasa tapınak?", secenekler: { A: "Ebu Simbel", B: "Karnak", C: "Luksor", D: "Filai" }, dogruCevap: "A" },
    { seviye: 526, kategori: "Önemli Yerler", soru: "Zambiya ve Zimbabve sınırındaki dev şelale?", secenekler: { A: "Victoria Şelaleleri", B: "Niagara", C: "Angel", D: "Iguazu" }, dogruCevap: "A" },
    { seviye: 527, kategori: "Önemli Yerler", soru: "Lübnan'daki Roma döneminden kalan antik kent?", secenekler: { A: "Baalbek", B: "Byblos", C: "Sidon", D: "Tyre" }, dogruCevap: "A" },
    { seviye: 528, kategori: "Önemli Yerler", soru: "Suriye'deki 'Çölün Gelini' olarak bilinen antik kent?", secenekler: { A: "Palmira", B: "Hama", C: "Humus", D: "Halep" }, dogruCevap: "A" },
    { seviye: 529, kategori: "Önemli Yerler", soru: "Irak'ta bulunan antik dünyanın yedi harikasından biri?", secenekler: { A: "Babil'in Asma Bahçeleri", B: "İştar Kapısı", C: "Zigurat", D: "Ninova" }, dogruCevap: "A" },
    { seviye: 530, kategori: "Önemli Yerler", soru: "İran'daki Pers İmparatorluğu'nun başkenti?", secenekler: { A: "Persepolis", B: "Pasargad", C: "Susa", D: "Ekbatana" }, dogruCevap: "A" },
    { seviye: 531, kategori: "Önemli Yerler", soru: "Japonya'nın simgesi olan volkanik dağ?", secenekler: { A: "Fuji Dağı", B: "Aso", C: "Ontake", D: "Sakurajima" }, dogruCevap: "A" },
    { seviye: 532, kategori: "Önemli Yerler", soru: "Nepal'de bulunan 'Dünyanın Çatısı' lakaplı bölge?", secenekler: { A: "Himalayalar", B: "Everest", C: "Annapurna", D: "Katmandu" }, dogruCevap: "A" },
    { seviye: 533, kategori: "Önemli Yerler", soru: "Singapur'un simgesi olan yarı aslan yarı balık heykel?", secenekler: { A: "Merlion", B: "Sphinx", C: "Griffin", D: "Chimera" }, dogruCevap: "A" },
    { seviye: 534, kategori: "Önemli Yerler", soru: "Malezya'nın başkentindeki ikiz kuleler?", secenekler: { A: "Petronas Kuleleri", B: "KL Tower", C: "Menara", D: "Maybank" }, dogruCevap: "A" },
    { seviye: 535, kategori: "Önemli Yerler", soru: "Vietnam'daki binlerce kireçtaşı adacığından oluşan körfez?", secenekler: { A: "Ha Long Körfezi", B: "Da Nang", C: "Nha Trang", D: "Phu Quoc" }, dogruCevap: "A" },
    { seviye: 536, kategori: "Önemli Yerler", soru: "İstanbul'da Adalar içinde en büyüğü hangisidir?", secenekler: { A: "Büyükada", B: "Heybeliada", C: "Burgazada", D: "Kınalıada" }, dogruCevap: "A" },
    { seviye: 537, kategori: "Önemli Yerler", soru: "İzmir'de bulunan antik çağın en önemli kütüphanelerinden biri hangisidir?", secenekler: { A: "Celsus Kütüphanesi", B: "Bergama Kütüphanesi", C: "İskenderiye", D: "Hadrian" }, dogruCevap: "A" },
    { seviye: 538, kategori: "Önemli Yerler", soru: "Antalya'da bulunan ve Noel Baba olarak bilinen Aziz Nikolaos'un kilisesi nerededir?", secenekler: { A: "Demre", B: "Kaş", C: "Finike", D: "Kalkan" }, dogruCevap: "A" },
    { seviye: 539, kategori: "Önemli Yerler", soru: "Muğla'da bulunan ve 'Yeryüzü Cenneti' olarak adlandırılan koy?", secenekler: { A: "Gökova", B: "Hisarönü", C: "Fethiye", D: "Marmaris" }, dogruCevap: "A" },
    { seviye: 540, kategori: "Önemli Yerler", soru: "Nevşehir'de bulunan ve yerin 8 kat altına kadar inen antik şehir?", secenekler: { A: "Derinkuyu Yer altı Şehri", B: "Kaymaklı", C: "Özkonak", D: "Tatlarin" }, dogruCevap: "A" },
    { seviye: 541, kategori: "Önemli Yerler", soru: "Sivas'taki Divriği Ulu Cami'nin kapısındaki ünlü figür nedir?", secenekler: { A: "Namaz kılan insan gölgesi", B: "Çift başlı kartal", C: "Hayat ağacı", D: "Güneş kursu" }, dogruCevap: "A" },
    { seviye: 542, kategori: "Önemli Yerler", soru: "Edirne'de Meriç nehri üzerindeki tarihi köprü?", secenekler: { A: "Meriç Köprüsü", B: "Tunca Köprüsü", C: "Uzunköprü", D: "Ekmekçizade" }, dogruCevap: "A" },
    { seviye: 543, kategori: "Önemli Yerler", soru: "Kırklareli'ndeki Türkiye'nin en büyük longoz (subasar) ormanı?", secenekler: { A: "İğneada Longozu", B: "Acarlar Longozu", C: "Sarıkum", D: "Karacabey" }, dogruCevap: "A" },
    { seviye: 544, kategori: "Önemli Yerler", soru: "Sakarya'daki Türkiye'nin tek parça en büyük longoz ormanı?", secenekler: { A: "Acarlar Longozu", B: "İğneada", C: "Erikli", D: "Danişment" }, dogruCevap: "A" },
    { seviye: 545, kategori: "Önemli Yerler", soru: "Yalova'daki Türkiye'nin ilk canlı ağaç müzesi?", secenekler: { A: "Karaca Arboretumu", B: "Atatürk Arboretumu", C: "Nezahat Gökyiğit", D: "Baltalimanı" }, dogruCevap: "A" },
    { seviye: 546, kategori: "Önemli Yerler", soru: "Kocaeli'deki tarihi saat kulesi kimin adına yapılmıştır?", secenekler: { A: "II. Abdülhamit", B: "Abdülaziz", C: "Sultan Reşat", D: "Vahdettin" }, dogruCevap: "A" },
    { seviye: 547, kategori: "Önemli Yerler", soru: "Düzce'deki Karadeniz'in Efes'i denilen antik kent?", secenekler: { A: "Prusias ad Hypium", B: "Tyana", C: "Sagalassos", D: "Stratonikeia" }, dogruCevap: "A" },
    { seviye: 548, kategori: "Önemli Yerler", soru: "Zonguldak'taki Türkiye'nin ilk geziye açılan mağarası?", secenekler: { A: "Gökgöl Mağarası", B: "Cehennemağzı", C: "Ilıksu", D: "Kızılelma" }, dogruCevap: "B" },
    { seviye: 549, kategori: "Önemli Yerler", soru: "Sinop'taki fiyort benzeri oluşumuyla ünlü koy?", secenekler: { A: "Hamsilos Koyu", B: "Akliman", C: "İnceburun", D: "Sarıkum" }, dogruCevap: "A" },
    { seviye: 550, kategori: "Önemli Yerler", soru: "Bartın'ın tarihi dokusu ve deniziyle ünlü ilçesi?", secenekler: { A: "Amasra", B: "Kurucaşile", C: "Ulus", D: "Kozcağız" }, dogruCevap: "A" }
 
 
);
