window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    { seviye: 1, kategori: "İller ve Meşhurlar", soru: "Kayısısı ile dünya çapında ün yapmış ilimiz hangisidir?", secenekler: { A: "Malatya", B: "Elazığ", C: "Isparta", D: "Maraş" }, dogruCevap: "A" },
    { seviye: 2, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz dondurması ile meşhurdur?", secenekler: { A: "Kahramanmaraş", B: "Adana", C: "Gaziantep", D: "Mersin" }, dogruCevap: "A" },
    { seviye: 3, kategori: "İller ve Meşhurlar", soru: "Lületaşı işlemeciliği hangi ilimizle özdeşleşmiştir?", secenekler: { A: "Eskişehir", B: "Kütahya", C: "Afyon", D: "Bilecik" }, dogruCevap: "A" },
    { seviye: 4, kategori: "İller ve Meşhurlar", soru: "Gül ve gül ürünleri denilince akla gelen ilk şehrimiz hangisidir?", secenekler: { A: "Isparta", B: "Burdur", C: "Antalya", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 5, kategori: "İller ve Meşhurlar", soru: "Fıstığı ile meşhur olan 'Gazi' unvanlı ilimiz hangisidir?", secenekler: { A: "Gaziantep", B: "Şanlıurfa", C: "Siirt", D: "Kilis" }, dogruCevap: "A" },
    { seviye: 6, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin pişmaniyesi meşhurdur?", secenekler: { A: "Kocaeli", B: "Sakarya", C: "Bursa", D: "Yalova" }, dogruCevap: "A" },
    { seviye: 7, kategori: "İller ve Meşhurlar", soru: "Çay üretimi denilince akla gelen Karadeniz ilimiz hangisidir?", secenekler: { A: "Rize", B: "Trabzon", C: "Artvin", D: "Giresun" }, dogruCevap: "A" },
    { seviye: 8, kategori: "İller ve Meşhurlar", soru: "Kestane şekeri hangi ilimizin en meşhur lezzetidir?", secenekler: { A: "Bursa", B: "Balıkesir", C: "Bilecik", D: "Düzce" }, dogruCevap: "A" },
    { seviye: 9, kategori: "İller ve Meşhurlar", soru: "Oltu taşı işlemeciliği hangi ilimize aittir?", secenekler: { A: "Erzurum", B: "Erzincan", C: "Bayburt", D: "Kars" }, dogruCevap: "A" },
    { seviye: 10, kategori: "İller ve Meşhurlar", soru: "Kaymağı ile ünlü olan Ege-İç Anadolu geçişindeki ilimiz hangisidir?", secenekler: { A: "Afyonkarahisar", B: "Uşak", C: "Denizli", D: "Kütahya" }, dogruCevap: "A" },
    { seviye: 11, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin fındığı dünya piyasasında çok değerlidir?", secenekler: { A: "Giresun", B: "Ordu", C: "Samsun", D: "Düzce" }, dogruCevap: "A" },
    { seviye: 12, kategori: "İller ve Meşhurlar", soru: "Elması ile meşhur olan Karadeniz ilimiz hangisidir?", secenekler: { A: "Amasya", B: "Tokat", C: "Çorum", D: "Kastamonu" }, dogruCevap: "A" },
    { seviye: 13, kategori: "İller ve Meşhurlar", soru: "Mevlana Müzesi ve etli ekmeği ile bilinen ilimiz hangisidir?", secenekler: { A: "Konya", B: "Karaman", C: "Aksaray", D: "Niğde" }, dogruCevap: "A" },
    { seviye: 14, kategori: "İller ve Meşhurlar", soru: "Leblebisi ile meşhur olan ilimiz hangisidir?", secenekler: { A: "Çorum", B: "Yozgat", C: "Kırşehir", D: "Çankırı" }, dogruCevap: "A" },
    { seviye: 15, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz tantunisi ile meşhurdur?", secenekler: { A: "Mersin", B: "Adana", C: "Hatay", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 16, kategori: "İller ve Meşhurlar", soru: "Pastırması ve mantısı ile ünlü şehrimiz hangisidir?", secenekler: { A: "Kayseri", B: "Sivas", C: "Nevşehir", D: "Kırşehir" }, dogruCevap: "A" },
    { seviye: 17, kategori: "İller ve Meşhurlar", soru: "İskender kebabı hangi ilimize özgüdür?", secenekler: { A: "Bursa", B: "İstanbul", C: "Ankara", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 18, kategori: "İller ve Meşhurlar", soru: "Çini işlemeciliği ile dünyaca ünlü ilimiz hangisidir?", secenekler: { A: "Kütahya", B: "İznik", C: "Uşak", D: "Manisa" }, dogruCevap: "A" },
    { seviye: 19, kategori: "İller ve Meşhurlar", soru: "Kebap denilince akla gelen, acısı ile meşhur ilimiz hangisidir?", secenekler: { A: "Adana", B: "Urfa", C: "Antep", D: "Maraş" }, dogruCevap: "A" },
    { seviye: 20, kategori: "İller ve Meşhurlar", soru: "İğne oyası ile meşhur olan Bolu'nun ilçesi/ili hangisidir?", secenekler: { A: "Bolu (Göynük)", B: "Düzce", C: "Zonguldak", D: "Bartın" }, dogruCevap: "A" },
    { seviye: 21, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz zeytini ve zeytinyağı ile meşhurdur?", secenekler: { A: "Balıkesir (Ayvalık)", B: "İzmir", C: "Aydın", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 22, kategori: "İller ve Meşhurlar", soru: "Şeftalisi ile meşhur olan ilimiz hangisidir?", secenekler: { A: "Bursa", B: "Çanakkale", C: "İzmir", D: "Yalova" }, dogruCevap: "A" },
    { seviye: 23, kategori: "İller ve Meşhurlar", soru: "Mesir macunu hangi ilimizde her yıl şenliklerle dağıtılır?", secenekler: { A: "Manisa", B: "İzmir", C: "Aydın", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 24, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin üzümü meşhurdur?", secenekler: { A: "Manisa", B: "Elazığ", C: "Tekirdağ", D: "Nevşehir" }, dogruCevap: "A" },
    { seviye: 25, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz köftesi ile meşhurdur?", secenekler: { A: "Tekirdağ", B: "Edirne", C: "İzmit", D: "Bolu" }, dogruCevap: "A" },
    { seviye: 26, kategori: "İller ve Meşhurlar", soru: "Ciğer tavası ile meşhur olan sınır ilimiz hangisidir?", secenekler: { A: "Edirne", B: "Kırklareli", C: "Artvin", D: "Hakkari" }, dogruCevap: "A" },
    { seviye: 27, kategori: "İller ve Meşhurlar", soru: "İnciri ile dünya birincisi olan ilimiz hangisidir?", secenekler: { A: "Aydın", B: "İzmir", C: "Muğla", D: "Manisa" }, dogruCevap: "A" },
    { seviye: 28, kategori: "İller ve Meşhurlar", soru: "Anzer balı hangi ilimizin yaylalarında üretilir?", secenekler: { A: "Rize", B: "Artvin", C: "Trabzon", D: "Gümüşhane" }, dogruCevap: "A" },
    { seviye: 29, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz peyniri (özellikle tulum) ile meşhurdur?", secenekler: { A: "Erzincan", B: "Erzurum", C: "Kars", D: "Van" }, dogruCevap: "A" },
    { seviye: 30, kategori: "İller ve Meşhurlar", soru: "Sarımsağı ile ünlü olan ilimiz hangisidir?", secenekler: { A: "Kastamonu (Taşköprü)", B: "Sinop", C: "Çankırı", D: "Bolu" }, dogruCevap: "A" },
    { seviye: 31, kategori: "İller ve Meşhurlar", soru: "Tavuğu ve pirinci ile meşhur olan ilçesi bulunan ilimiz?", secenekler: { A: "Bolu (Mengen)", B: "Çorum (Osmancık)", C: "Edirne (İpsala)", D: "Samsun (Bafra)" }, dogruCevap: "B" },
    { seviye: 32, kategori: "İller ve Meşhurlar", soru: "Peynir helvası hangi ilimize özgüdür?", secenekler: { A: "Çanakkale", B: "Edirne", C: "Tekirdağ", D: "Balıkesir" }, dogruCevap: "A" },
    { seviye: 33, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin sucuğu ve pastırması meşhurdur?", secenekler: { A: "Afyonkarahisar", B: "Kayseri", C: "Sivas", D: "Erzurum" }, dogruCevap: "A" },
    { seviye: 34, kategori: "İller ve Meşhurlar", soru: "Halıcılığı ile ünlü olan İç Anadolu ilimiz hangisidir?", secenekler: { A: "Kayseri (Bünyan)", B: "Konya", C: "Niğde", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 35, kategori: "İller ve Meşhurlar", soru: "Taş köprüsü ve cezeryesi ile meşhur ilimiz?", secenekler: { A: "Adana", B: "Mersin", C: "Osmaniye", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 36, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz horozu ile meşhurdur?", secenekler: { A: "Denizli", B: "Aydın", C: "Muğla", D: "Uşak" }, dogruCevap: "A" },
    { seviye: 37, kategori: "İller ve Meşhurlar", soru: "Bakır işlemeciliği ve el sanatları ile ünlü ilimiz?", secenekler: { A: "Gaziantep", B: "Kahramanmaraş", C: "Şanlıurfa", D: "Diyarbakır" }, dogruCevap: "A" },
    { seviye: 38, kategori: "İller ve Meşhurlar", soru: "Künafe denilince akla gelen ilk ilimiz hangisidir?", secenekler: { A: "Hatay", B: "Mersin", C: "Adana", D: "Antep" }, dogruCevap: "A" },
    { seviye: 39, kategori: "İller ve Meşhurlar", soru: "Muz üretimi ile meşhur olan ilçemiz (Anamur) hangi ildedir?", secenekler: { A: "Mersin", B: "Antalya", C: "Muğla", D: "Adana" }, dogruCevap: "A" },
    { seviye: 40, kategori: "İller ve Meşhurlar", soru: "Simgesi 'Sato' ve inci kefali olan ilimiz?", secenekler: { A: "Van", B: "Bitlis", C: "Ağrı", D: "Hakkari" }, dogruCevap: "A" },
    { seviye: 41, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin kabak tatlısı meşhurdur?", secenekler: { A: "Sakarya", B: "Düzce", C: "Bolu", D: "Bilecik" }, dogruCevap: "A" },
    { seviye: 42, kategori: "İller ve Meşhurlar", soru: "Telkâri (Gümüş işleme) sanatı ile ünlü ilimiz hangisidir?", secenekler: { A: "Mardin", B: "Batman", C: "Siirt", D: "Şırnak" }, dogruCevap: "A" },
    { seviye: 43, kategori: "İller ve Meşhurlar", soru: "Çileği ile meşhur olan Karadeniz Ereğli hangi ildedir?", secenekler: { A: "Zonguldak", B: "Bartın", C: "Düzce", D: "Kastamonu" }, dogruCevap: "A" },
    { seviye: 44, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin yer fıstığı meşhurdur?", secenekler: { A: "Osmaniye", B: "Adana", C: "Hatay", D: "Maraş" }, dogruCevap: "A" },
    { seviye: 45, kategori: "İller ve Meşhurlar", soru: "Pestil ve köme denilince akla gelen ilimiz hangisidir?", secenekler: { A: "Gümüşhane", B: "Bayburt", C: "Erzincan", D: "Artvin" }, dogruCevap: "A" },
    { seviye: 46, kategori: "İller ve Meşhurlar", soru: "Sivas'ın nesi meşhurdur?", secenekler: { A: "Kangal Köpeği", B: "Van Kedisi", C: "Denizli Horozu", D: "Ankara Tavşanı" }, dogruCevap: "A" },
    { seviye: 47, kategori: "İller ve Meşhurlar", soru: "Büryan kebabı ve battaniyesi ile ünlü ilimiz?", secenekler: { A: "Siirt", B: "Bitlis", C: "Van", D: "Mardin" }, dogruCevap: "A" },
    { seviye: 48, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz boyozu ile meşhurdur?", secenekler: { A: "İzmir", B: "İstanbul", C: "Ankara", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 49, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz tulum peyniri ve bakırı ile meşhurdur?", secenekler: { A: "Erzincan", B: "Tokat", C: "Amasya", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 50, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz mermeri ile ünlüdür?", secenekler: { A: "Afyonkarahisar", B: "Bilecik", C: "Muğla", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 51, kategori: "İller ve Meşhurlar", soru: "Cevizli sucuğu ile meşhur olan ilimiz?", secenekler: { A: "Artvin", B: "Kahramanmaraş", C: "Gümüşhane", D: "Elazığ" }, dogruCevap: "B" },
    { seviye: 52, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz karpuzu ile meşhurdur?", secenekler: { A: "Diyarbakır", B: "Adana", C: "Tekirdağ", D: "Samsun" }, dogruCevap: "A" },
    { seviye: 53, kategori: "İller ve Meşhurlar", soru: "Kaşar peyniri ve balı ile ünlü sınır ilimiz?", secenekler: { A: "Kars", B: "Ardahan", C: "Iğdır", D: "Ağrı" }, dogruCevap: "A" },
    { seviye: 54, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz çekme helvası ile meşhurdur?", secenekler: { A: "Kastamonu", B: "Çankırı", C: "Bolu", D: "Karabük" }, dogruCevap: "A" },
    { seviye: 55, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin mısırı meşhurdur?", secenekler: { A: "Sakarya", B: "Samsun", C: "Adana", D: "Konya" }, dogruCevap: "A" },
    { seviye: 56, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz höşmerim tatlısı ile meşhurdur?", secenekler: { A: "Balıkesir", B: "Bursa", C: "Çanakkale", D: "Manisa" }, dogruCevap: "A" },
    { seviye: 57, kategori: "İller ve Meşhurlar", soru: "Tarhanası ile ünlü olan Ege ilimiz hangisidir?", secenekler: { A: "Uşak", B: "Aydın", C: "Manisa", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 58, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin kavunu (Kırkağaç) meşhurdur?", secenekler: { A: "Manisa", B: "Diyarbakır", C: "Ankara", D: "Konya" }, dogruCevap: "A" },
    { seviye: 59, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin ayvası (Geyve) meşhurdur?", secenekler: { A: "Sakarya", B: "Bursa", C: "Yalova", D: "Kocaeli" }, dogruCevap: "A" },
    { seviye: 60, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz simiti ile meşhurdur?", secenekler: { A: "Ankara", B: "İstanbul", C: "İzmir", D: "Samsun" }, dogruCevap: "A" },
    { seviye: 61, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz banduması ile meşhurdur?", secenekler: { A: "Kastamonu", B: "Sinop", C: "Bartın", D: "Zonguldak" }, dogruCevap: "A" },
    { seviye: 62, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz dondurması ve biberi ile meşhurdur?", secenekler: { A: "Kahramanmaraş", B: "Şanlıurfa", C: "Gaziantep", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 63, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz pirinci ile meşhurdur?", secenekler: { A: "Edirne", B: "Çorum", C: "Samsun", D: "Kastamonu" }, dogruCevap: "A" },
    { seviye: 64, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz bıçakları ile meşhurdur?", secenekler: { A: "Bursa", B: "Sürmene (Trabzon)", C: "Denizli (Yatağan)", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 65, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz zeytini ile meşhurdur?", secenekler: { A: "Bursa (Gemlik)", B: "Balıkesir", C: "Aydın", D: "Mersin" }, dogruCevap: "A" },
    { seviye: 66, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz üzüm şırası ve hardaliyesi ile meşhurdur?", secenekler: { A: "Kırklareli", B: "Edirne", C: "Tekirdağ", D: "Çanakkale" }, dogruCevap: "A" },
    { seviye: 67, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz tütünü ile meşhurdur?", secenekler: { A: "Adıyaman", B: "Samsun", C: "Manisa", D: "Bitlis" }, dogruCevap: "A" },
    { seviye: 68, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz ipeği ve havlusu ile meşhurdur?", secenekler: { A: "Bursa", B: "Denizli", C: "İstanbul", D: "Aydın" }, dogruCevap: "A" },
    { seviye: 69, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz mandalinası ile meşhurdur?", secenekler: { A: "İzmir (Seferihisar)", B: "Muğla (Bodrum)", C: "Antalya", D: "Mersin" }, dogruCevap: "B" },
    { seviye: 70, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz leblebisi ile meşhurdur?", secenekler: { A: "Kütahya (Tavşanlı)", B: "Çorum", C: "Denizli (Serinhisar)", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 71, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz taş evleri ve sabunu ile meşhurdur?", secenekler: { A: "Mardin", B: "Şanlıurfa", C: "Siirt", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 72, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz lokumu ile meşhurdur?", secenekler: { A: "Afyonkarahisar", B: "Isparta", C: "Safranbolu (Karabük)", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 73, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz kirazı ile meşhurdur?", secenekler: { A: "Afyonkarahisar", B: "Isparta", C: "Manisa", D: "Giresun" }, dogruCevap: "A" },
    { seviye: 74, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz köftesi (Islama) ile meşhurdur?", secenekler: { A: "Sakarya", B: "Tekirdağ", C: "İnegöl (Bursa)", D: "Akçaabat (Trabzon)" }, dogruCevap: "A" },
    { seviye: 75, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz şalgamı ile meşhurdur?", secenekler: { A: "Adana", B: "Mersin", C: "Hatay", D: "Osmaniye" }, dogruCevap: "A" },
    { seviye: 76, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz çiğ köftesi ile meşhurdur?", secenekler: { A: "Şanlıurfa", B: "Adıyaman", C: "Diyarbakır", D: "Mardin" }, dogruCevap: "A" },
    { seviye: 77, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz balığı (Hamsi) ile meşhurdur?", secenekler: { A: "Trabzon", B: "Rize", C: "Artvin", D: "Samsun" }, dogruCevap: "A" },
    { seviye: 78, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz tulumu ve kemençesi ile meşhurdur?", secenekler: { A: "Rize - Trabzon", B: "Artvin", C: "Giresun", D: "Ordu" }, dogruCevap: "A" },
    { seviye: 79, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz elması ile meşhurdur?", secenekler: { A: "Isparta", B: "Amasya", C: "Niğde", D: "Karaman" }, dogruCevap: "A" },
    { seviye: 80, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz narı ile meşhurdur?", secenekler: { A: "Antalya", B: "Muğla", C: "Denizli", D: "Aydın" }, dogruCevap: "A" },
    { seviye: 81, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz portakalı ile meşhurdur?", secenekler: { A: "Antalya (Finike)", B: "Adana", C: "Mersin", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 82, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz limonu ile meşhurdur?", secenekler: { A: "Mersin (Erdemli)", B: "Adana", C: "Antalya", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 83, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz pamuğu ile meşhurdur?", secenekler: { A: "Adana", B: "Şanlıurfa", C: "Aydın", D: "Hatay" }, dogruCevap: "B" },
    { seviye: 84, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz mercimeği ile meşhurdur?", secenekler: { A: "Şanlıurfa", B: "Mardin", C: "Gaziantep", D: "Yozgat" }, dogruCevap: "A" },
    { seviye: 85, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz nohutu ile meşhurdur?", secenekler: { A: "Uşak", B: "Kırşehir", C: "Ankara", D: "Yozgat" }, dogruCevap: "A" },
    { seviye: 86, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz fasulyesi ile meşhurdur?", secenekler: { A: "Niğde", B: "Konya", C: "Erzurum (İspir)", D: "Rize (İkizdere)" }, dogruCevap: "C" },
    { seviye: 87, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz cevizi ile meşhurdur?", secenekler: { A: "Kırşehir (Kaman)", B: "Bolu", C: "Kastamonu", D: "Bitlis" }, dogruCevap: "A" },
    { seviye: 88, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz fıstığı ile meşhurdur?", secenekler: { A: "Siirt", B: "Gaziantep", C: "Şanlıurfa", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 89, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz bükmesi ve ağzı açığı ile meşhurdur?", secenekler: { A: "Afyonkarahisar", B: "Kütahya", C: "Uşak", D: "Eskişehir" }, dogruCevap: "A" },
    { seviye: 90, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz çiğ böreği ile meşhurdur?", secenekler: { A: "Eskişehir", B: "Ankara", C: "Konya", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 91, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz testi kebabı ile meşhurdur?", secenekler: { A: "Nevşehir", B: "Yozgat", C: "Kayseri", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 92, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz saç tavası ile meşhurdur?", secenekler: { A: "Diyarbakır", B: "Mardin", C: "Batman", D: "Siirt" }, dogruCevap: "A" },
    { seviye: 93, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz cağ kebabı ile meşhurdur?", secenekler: { A: "Erzurum", B: "Erzincan", C: "Artvin", D: "Kars" }, dogruCevap: "A" },
    { seviye: 94, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz balı ile meşhurdur?", secenekler: { A: "Hakkari", B: "Rize", C: "Muğla", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 95, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz iğne oyası ile meşhurdur?", secenekler: { A: "Bolu", B: "Düzce", C: "Bartın", D: "Kocaeli" }, dogruCevap: "A" },
    { seviye: 96, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz çini ve seramiği ile meşhurdur?", secenekler: { A: "Kütahya", B: "Bilecik", C: "Uşak", D: "Eskişehir" }, dogruCevap: "A" },
    { seviye: 97, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz cam işlemeciliği ile meşhurdur?", secenekler: { A: "Denizli", B: "İstanbul", C: "İzmir", D: "Eskişehir" }, dogruCevap: "A" },
    { seviye: 98, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz havlusu ve bornozu ile meşhurdur?", secenekler: { A: "Denizli", B: "Bursa", C: "Aydın", D: "Uşak" }, dogruCevap: "A" },
    { seviye: 99, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz dokuması (Buldan) ile meşhurdur?", secenekler: { A: "Denizli", B: "Manisa", C: "Aydın", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 100, kategori: "İller ve Meşhurlar", soru: "Hangi ilimiz süpürgesi ile meşhurdur?", secenekler: { A: "Edirne", B: "Kırklareli", C: "Tekirdağ", D: "Çanakkale" }, dogruCevap: "A" }, 
    { seviye: 251, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Siron' yemeği meşhurdur?", secenekler: { A: "Gümüşhane", B: "Bayburt", C: "Artvin", D: "Giresun" }, dogruCevap: "A" },
    { seviye: 252, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Keşkek' yemeği düğünlerin vazgeçilmezidir?", secenekler: { A: "Aydın", B: "Afyonkarahisar", C: "Çorum", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 253, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şile Bezi' dokuması dünyaca ünlüdür?", secenekler: { A: "İstanbul", B: "Kocaeli", C: "Yalova", D: "Sakarya" }, dogruCevap: "A" },
    { seviye: 254, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Etli Ekmeği' tescillidir?", secenekler: { A: "Konya", B: "Sivas", C: "Kayseri", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 255, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ehram' dokuması kadın giyiminde kullanılır?", secenekler: { A: "Erzurum", B: "Bayburt", C: "Erzincan", D: "Kars" }, dogruCevap: "A" },
    { seviye: 256, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Fırın Kebabı' meşhurdur?", secenekler: { A: "Konya", B: "Isparta", C: "Afyonkarahisar", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 257, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tandır Kebabı' meşhurdur?", secenekler: { A: "Denizli", B: "Konya", C: "Akşehir", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 258, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yağlaması' (Şebit) meşhurdur?", secenekler: { A: "Kayseri", B: "Nevşehir", C: "Kırşehir", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 259, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Pöç' yemeği meşhurdur?", secenekler: { A: "Kayseri", B: "Niğde", C: "Aksaray", D: "Yozgat" }, dogruCevap: "A" },
    { seviye: 260, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yenidünya Kebabı' meyveli bir lezzettir?", secenekler: { A: "Gaziantep", B: "Şanlıurfa", C: "Kilis", D: "Mersin" }, dogruCevap: "A" },
    { seviye: 261, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Simit Kebabı' meşhurdur?", secenekler: { A: "Gaziantep", B: "Kahramanmaraş", C: "Adana", D: "Osmaniye" }, dogruCevap: "A" },
    { seviye: 262, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Patlıcan Kebabı' (Birecik) ünlüdür?", secenekler: { A: "Şanlıurfa", B: "Gaziantep", C: "Hatay", D: "Diyarbakır" }, dogruCevap: "A" },
    { seviye: 263, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Söğürmesi' közlenmiş patlıcanla yapılır?", secenekler: { A: "Şanlıurfa", B: "Hatay", C: "Kilis", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 264, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Analı Kızlı' çorbası/yemeği meşhurdur?", secenekler: { A: "Adana - Malatya", B: "Gaziantep", C: "Mersin", D: "Konya" }, dogruCevap: "A" },
    { seviye: 265, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yuvalama' çorbası bayramlarda yapılır?", secenekler: { A: "Gaziantep", B: "Kahramanmaraş", C: "Kilis", D: "Şanlıurfa" }, dogruCevap: "A" },
    { seviye: 266, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Beyran' çorbası sabahları içilir?", secenekler: { A: "Gaziantep", B: "Diyarbakır", C: "Siirt", D: "Adıyaman" }, dogruCevap: "A" },
    { seviye: 267, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Lebeniye' çorbası meşhurdur?", secenekler: { A: "Gaziantep - Şanlıurfa", B: "Mardin", C: "Adana", D: "Mersin" }, dogruCevap: "A" },
    { seviye: 268, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Düğün Çorbası' meşhurdur?", secenekler: { A: "Ankara", B: "Kırşehir", C: "Yozgat", D: "Çankırı" }, dogruCevap: "A" },
    { seviye: 269, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tarhana Çorbası' (Uşak Tarhanası) tescillidir?", secenekler: { A: "Uşak", B: "Maraş", C: "Bolu", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 270, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Dövme Tarhanası' (Cips Tarhana) ünlüdür?", secenekler: { A: "Kahramanmaraş", B: "Adana", C: "Osmaniye", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 271, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mumbar Dolması' meşhurdur?", secenekler: { A: "Adana - Diyarbakır - Siirt", B: "İzmir", C: "İstanbul", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 272, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şırdan Dolması' meşhurdur?", secenekler: { A: "Adana", B: "Mersin", C: "Gaziantep", D: "Kahramanmaraş" }, dogruCevap: "A" },
    { seviye: 273, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kabak Çiçeği Dolması' meşhurdur?", secenekler: { A: "Muğla - Aydın - İzmir", B: "Antalya", C: "Mersin", D: "Adana" }, dogruCevap: "A" },
    { seviye: 274, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yaprak Sarması' (Erbaa) tescillidir?", secenekler: { A: "Tokat", B: "Amasya", C: "Sivas", D: "Çorum" }, dogruCevap: "A" },
    { seviye: 275, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Hamsili Pilavı' meşhurdur?", secenekler: { A: "Trabzon - Rize", B: "Samsun", C: "Sinop", D: "Artvin" }, dogruCevap: "A" },
    { seviye: 276, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Perde Pilavı' meşhurdur?", secenekler: { A: "Siirt", B: "Batman", C: "Mardin", D: "Diyarbakır" }, dogruCevap: "A" },
    { seviye: 277, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Özbek Pilavı' meşhurdur?", secenekler: { A: "Ankara", B: "İstanbul", C: "İzmir", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 278, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'İçli Köftesi' (Haşlama/Kızartma) meşhurdur?", secenekler: { A: "Gaziantep - Kahramanmaraş", B: "Diyarbakır", C: "Malatya", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 279, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kiraz Yaprağı Sarması' meşhurdur?", secenekler: { A: "Malatya", B: "Elazığ", C: "Sivas", D: "Erzincan" }, dogruCevap: "A" },
    { seviye: 280, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kuru Patlıcan Dolması' meşhurdur?", secenekler: { A: "Gaziantep", B: "Şanlıurfa", C: "Kilis", D: "Adana" }, dogruCevap: "A" },
    { seviye: 281, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Babagannuş' mezesi meşhurdur?", secenekler: { A: "Hatay", B: "Adana", C: "Mersin", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 282, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Muhammara' mezesi meşhurdur?", secenekler: { A: "Hatay - Gaziantep", B: "Şanlıurfa", C: "Mardin", D: "Adıyaman" }, dogruCevap: "A" },
    { seviye: 283, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Humus' mezesi meşhurdur?", secenekler: { A: "Hatay - Mersin", B: "Antalya", C: "Adana", D: "Osmaniye" }, dogruCevap: "A" },
    { seviye: 284, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Piyazı' (Tahinli) meşhurdur?", secenekler: { A: "Antalya", B: "İzmir", C: "Muğla", D: "Aydın" }, dogruCevap: "A" },
    { seviye: 285, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Deniz Börülcesi' meşhurdur?", secenekler: { A: "İzmir - Aydın - Muğla", B: "Antalya", C: "Mersin", D: "Adana" }, dogruCevap: "A" },
    { seviye: 286, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Radika Salatası' meşhurdur?", secenekler: { A: "İzmir", B: "Muğla", C: "Aydın", D: "Balıkesir" }, dogruCevap: "A" },
    { seviye: 287, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şevketi Bostan' yemeği meşhurdur?", secenekler: { A: "İzmir", B: "Aydın", C: "Manisa", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 288, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Enginar' yemeği meşhurdur?", secenekler: { A: "İzmir", B: "Aydın", C: "İstanbul", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 289, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kumrusu' meşhurdur?", secenekler: { A: "İzmir (Çeşme)", B: "İstanbul", C: "Ankara", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 290, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Gevrek' (Simit) meşhurdur?", secenekler: { A: "İzmir", B: "İstanbul", C: "Ankara", D: "Samsun" }, dogruCevap: "A" },
    { seviye: 291, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Peynir Tatlısı' (Kemalpaşa) meşhurdur?", secenekler: { A: "Bursa", B: "Balıkesir", C: "Çanakkale", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 292, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Lor Tatlısı' meşhurdur?", secenekler: { A: "İzmir (Ayvalık)", B: "Bursa", C: "Çanakkale", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 293, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kabak Tatlısı' (Tahinli ve Cevizli) meşhurdur?", secenekler: { A: "Antalya - Sakarya", B: "Aydın", C: "Muğla", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 294, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ekmek Kadayıfı' meşhurdur?", secenekler: { A: "Afyonkarahisar", B: "Kütahya", C: "Uşak", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 295, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Revani' tatlısı meşhurdur?", secenekler: { A: "İzmir", B: "İstanbul", C: "Bursa", D: "Edirne" }, dogruCevap: "A" },
    { seviye: 296, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tulumba Tatlısı' meşhurdur?", secenekler: { A: "İstanbul", B: "Ankara", C: "Bursa", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 297, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Halka Tatlısı' meşhurdur?", secenekler: { A: "Adana", B: "Mersin", C: "Hatay", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 298, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şerbeti' (Demirhindi) meşhurdur?", secenekler: { A: "İstanbul", B: "Konya", C: "Bursa", D: "Edirne" }, dogruCevap: "A" },
    { seviye: 299, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Meyan Şerbeti' meşhurdur?", secenekler: { A: "Gaziantep - Şanlıurfa", B: "Kahramanmaraş", C: "Diyarbakır", D: "Mardin" }, dogruCevap: "A" },
    { seviye: 300, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Reyhan Şerbeti' meşhurdur?", secenekler: { A: "Diyarbakır", B: "Mardin", C: "Şanlıurfa", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 301, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Hardaliye' içeceği meşhurdur?", secenekler: { A: "Kırklareli", B: "Tekirdağ", C: "Edirne", D: "Çanakkale" }, dogruCevap: "A" },
    { seviye: 302, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şıra' içeceği meşhurdur?", secenekler: { A: "Bursa", B: "İstanbul", C: "İzmir", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 303, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kızılcık Şerbeti' meşhurdur?", secenekler: { A: "Bolu", B: "Kastamonu", C: "Karabük", D: "Düzce" }, dogruCevap: "A" },
    { seviye: 304, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Boza' içeceği (Vefa) meşhurdur?", secenekler: { A: "İstanbul", B: "Eskişehir", C: "Bilecik", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 305, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Boza' içeceği (Pazaryeri) meşhurdur?", secenekler: { A: "Bilecik", B: "Eskişehir", C: "Bursa", D: "Kütahya" }, dogruCevap: "A" },
    { seviye: 306, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Menengiç Kahvesi' meşhurdur?", secenekler: { A: "Gaziantep - Mardin", B: "Şanlıurfa", C: "Kahramanmaraş", D: "Diyarbakır" }, dogruCevap: "A" },
    { seviye: 307, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mırra' kahvesi meşhurdur?", secenekler: { A: "Şanlıurfa - Mardin", B: "Gaziantep", C: "Diyarbakır", D: "Adıyaman" }, dogruCevap: "A" },
    { seviye: 308, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Dibek Kahvesi' meşhurdur?", secenekler: { A: "İzmir - Aydın", B: "Çanakkale", C: "Muğla", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 309, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Damla Sakızlı Kahvesi' meşhurdur?", secenekler: { A: "İzmir (Çeşme)", B: "Muğla", C: "Aydın", D: "Balıkesir" }, dogruCevap: "A" },
    { seviye: 310, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kumda Kahvesi' meşhurdur?", secenekler: { A: "Ankara - İstanbul", B: "İzmir", C: "Antalya", D: "Konya" }, dogruCevap: "A" },
    { seviye: 311, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tuzlu Kahvesi' (Damat Kahvesi) bir kültürdür?", secenekler: { A: "Tüm Türkiye", B: "Sadece Ege", C: "Sadece Karadeniz", D: "Sadece Doğu" }, dogruCevap: "A" },
    { seviye: 312, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Semaver Çayı' meşhurdur?", secenekler: { A: "Samsun (Vezirköprü)", B: "Rize", C: "Trabzon", D: "Artvin" }, dogruCevap: "A" },
    { seviye: 313, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kaçak Çayı' meşhurdur?", secenekler: { A: "Şanlıurfa - Mardin - Diyarbakır", B: "Rize", C: "Trabzon", D: "Samsun" }, dogruCevap: "A" },
    { seviye: 314, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ayranı' (Eskil) meşhurdur?", secenekler: { A: "Aksaray", B: "Konya", C: "Niğde", D: "Kırşehir" }, dogruCevap: "A" },
    { seviye: 315, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kefiri' meşhurdur?", secenekler: { A: "Bolu", B: "Kastamonu", C: "Düzce", D: "Sakarya" }, dogruCevap: "A" },
    { seviye: 316, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yün Çorabı' meşhurdur?", secenekler: { A: "Erzurum - Kars", B: "Sivas", C: "Yozgat", D: "Kırşehir" }, dogruCevap: "A" },
    { seviye: 317, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yemenisi' meşhurdur?", secenekler: { A: "Gaziantep - Kilis", B: "Şanlıurfa", C: "Kahramanmaraş", D: "Mardin" }, dogruCevap: "A" },
    { seviye: 318, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Çarığı' meşhurdur?", secenekler: { A: "Kahramanmaraş - Gaziantep", B: "Denizli", C: "Aydın", D: "Manisa" }, dogruCevap: "A" },
    { seviye: 319, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bindallısı' meşhurdur?", secenekler: { A: "Bursa - Bilecik - Kütahya", B: "İstanbul", C: "Ankara", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 320, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kuşağı' (Trablus Kuşağı) meşhurdur?", secenekler: { A: "Trabzon", B: "Rize", C: "Artvin", D: "Giresun" }, dogruCevap: "A" },
    { seviye: 321, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Fesi' meşhurdur (Tarihi süreçte)?", secenekler: { A: "İstanbul", B: "Edirne", C: "Bursa", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 322, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şapkası' (Kastamonu Şapka Devrimi) meşhurdur?", secenekler: { A: "Kastamonu", B: "Ankara", C: "İstanbul", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 323, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yağmurluğu' (Kepenek) meşhurdur?", secenekler: { A: "Afyonkarahisar - Denizli", B: "Konya", C: "Kayseri", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 324, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şalvarı' meşhurdur?", secenekler: { A: "Adana - Mersin", B: "Gaziantep", C: "Şanlıurfa", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 325, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Poşusu' meşhurdur?", secenekler: { A: "Şanlıurfa - Mardin - Diyarbakır", B: "Gaziantep", C: "Adıyaman", D: "Siirt" }, dogruCevap: "A" },
    { seviye: 326, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'İğne Oyası' meşhurdur?", secenekler: { A: "Bursa (İnegöl) - Nallıhan (Ankara)", B: "İstanbul", C: "İzmir", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 327, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mekik Oyası' meşhurdur?", secenekler: { A: "Osmaniye - Kahramanmaraş", B: "Adana", C: "Mersin", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 328, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Firkete Oyası' meşhurdur?", secenekler: { A: "Konya - Karaman", B: "Ankara", C: "Eskişehir", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 329, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Boncuk Oyası' meşhurdur?", secenekler: { A: "Muğla - Aydın - Denizli", B: "Antalya", C: "Mersin", D: "Adana" }, dogruCevap: "A" },
    { seviye: 330, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Danteli' meşhurdur?", secenekler: { A: "İstanbul - İzmir", B: "Ankara", C: "Bursa", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 331, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kilimi' (Eşme) meşhurdur?", secenekler: { A: "Uşak", B: "Manisa", C: "Aydın", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 332, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kilimi' (Kızılcahamam) meşhurdur?", secenekler: { A: "Ankara", B: "Bolu", C: "Çankırı", D: "Kırşehir" }, dogruCevap: "A" },
    { seviye: 333, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kilimi' (Sarkışla) meşhurdur?", secenekler: { A: "Sivas", B: "Kayseri", C: "Yozgat", D: "Nevşehir" }, dogruCevap: "A" },
    { seviye: 334, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kilimi' (Obruk) meşhurdur?", secenekler: { A: "Konya", B: "Karaman", C: "Aksaray", D: "Niğde" }, dogruCevap: "A" },
    { seviye: 335, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Halısı' (Gördes) meşhurdur?", secenekler: { A: "Manisa", B: "İzmir", C: "Aydın", D: "Uşak" }, dogruCevap: "A" },
    { seviye: 336, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Halısı' (Kula) meşhurdur?", secenekler: { A: "Manisa", B: "Uşak", C: "Kütahya", D: "Afyonkarahisar" }, dogruCevap: "A" },
    { seviye: 337, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Halısı' (Demirci) meşhurdur?", secenekler: { A: "Manisa", B: "Balıkesir", C: "Bursa", D: "Kütahya" }, dogruCevap: "A" },
    { seviye: 338, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Halısı' (Milas) meşhurdur?", secenekler: { A: "Muğla", B: "Aydın", C: "İzmir", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 339, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Halısı' (Döşemealtı) meşhurdur?", secenekler: { A: "Antalya", B: "Muğla", C: "Burdur", D: "Isparta" }, dogruCevap: "A" },
    { seviye: 340, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Halısı' (Hereke) meşhurdur?", secenekler: { A: "Kocaeli", B: "Sakarya", C: "İstanbul", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 341, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bakır İşçiliği' meşhurdur?", secenekler: { A: "Gaziantep - Erzincan", B: "Kahramanmaraş", C: "Tokat", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 342, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Gümüş İşçiliği' meşhurdur?", secenekler: { A: "Mardin - Erzurum - Beypazarı", B: "İstanbul", C: "İzmir", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 343, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Altın İşçiliği' meşhurdur?", secenekler: { A: "İstanbul (Kapalıçarşı) - Kahramanmaraş", B: "Ankara", C: "İzmir", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 344, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Lületaşı' işçiliği meşhurdur?", secenekler: { A: "Eskişehir", B: "Kütahya", C: "Afyonkarahisar", D: "Uşak" }, dogruCevap: "A" },
    { seviye: 345, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Oltu Taşı' işçiliği meşhurdur?", secenekler: { A: "Erzurum", B: "Erzincan", C: "Bayburt", D: "Gümüşhane" }, dogruCevap: "A" },
    { seviye: 346, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mermer İşçiliği' meşhurdur?", secenekler: { A: "Afyonkarahisar - Muğla", B: "Denizli", C: "Bilecik", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 347, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ahşap İşçiliği' meşhurdur?", secenekler: { A: "Kastamonu - Bolu", B: "Zonguldak", C: "Bartın", D: "Düzce" }, dogruCevap: "A" },
    { seviye: 348, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bıçakçılığı' meşhurdur?", secenekler: { A: "Bursa - Sürmene - Yatağan", B: "İstanbul", C: "Ankara", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 349, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Nargilesi' meşhurdur?", secenekler: { A: "İstanbul", B: "İzmir", C: "Ankara", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 350, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Pargun' (Maden İşleme) sanatı meşhurdur?", secenekler: { A: "Trabzon", B: "Rize", C: "Artvin", D: "Giresun" }, dogruCevap: "A" },
    { seviye: 351, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Cirit' oyunu meşhurdur?", secenekler: { A: "Erzurum - Uşak", B: "Konya", C: "Ankara", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 352, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yağlı Güreşi' (Kırkpınar) meşhurdur?", secenekler: { A: "Edirne", B: "Kırklareli", C: "Tekirdağ", D: "Çanakkale" }, dogruCevap: "A" },
    { seviye: 353, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Deve Güreşi' meşhurdur?", secenekler: { A: "Aydın - İzmir - Muğla", B: "Antalya", C: "Mersin", D: "Adana" }, dogruCevap: "A" },
    { seviye: 354, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Boğa Güreşi' (Artvin Kafkasör) meşhurdur?", secenekler: { A: "Artvin", B: "Rize", C: "Trabzon", D: "Giresun" }, dogruCevap: "A" },
    { seviye: 355, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Atlı Okçuluğu' meşhurdur?", secenekler: { A: "Kayseri - Erzurum - Uşak", B: "Ankara", C: "İstanbul", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 356, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Zeybek' oyunu meşhurdur?", secenekler: { A: "Aydın - İzmir - Muğla - Denizli", B: "Antalya", C: "Mersin", D: "Adana" }, dogruCevap: "A" },
    { seviye: 357, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Horon' oyunu meşhurdur?", secenekler: { A: "Trabzon - Rize - Artvin - Giresun", B: "Samsun", C: "Ordu", D: "Sinop" }, dogruCevap: "A" },
    { seviye: 358, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Halay' oyunu meşhurdur?", secenekler: { A: "Diyarbakır - Gaziantep - Şanlıurfa", B: "Sivas", C: "Erzurum", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 359, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bar' oyunu meşhurdur?", secenekler: { A: "Erzurum", B: "Erzincan", C: "Bayburt", D: "Artvin" }, dogruCevap: "A" },
    { seviye: 360, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Hora' oyunu meşhurdur?", secenekler: { A: "Edirne - Tekirdağ - Kırklareli", B: "Çanakkale", C: "Balıkesir", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 361, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kaşık Oyunları' meşhurdur?", secenekler: { A: "Konya - Silifke (Mersin)", B: "Ankara", C: "Antalya", D: "Burdur" }, dogruCevap: "A" },
    { seviye: 362, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Teke Zortlatması' oyunu meşhurdur?", secenekler: { A: "Burdur - Isparta - Antalya", B: "Muğla", C: "Denizli", D: "Aydın" }, dogruCevap: "A" },
    { seviye: 363, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Semah' oyunu meşhurdur?", secenekler: { A: "Sivas - Tunceli - Tokat", B: "Ankara", C: "İstanbul", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 364, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Karagöz ve Hacivat'ı meşhurdur?", secenekler: { A: "Bursa", B: "İstanbul", C: "Edirne", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 365, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Meddah'ı meşhurdur?", secenekler: { A: "İstanbul", B: "Bursa", C: "Edirne", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 366, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Âşıklık Geleneği' meşhurdur?", secenekler: { A: "Kars - Erzurum - Sivas", B: "Ankara", C: "İstanbul", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 367, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Sıra Gecesi' meşhurdur?", secenekler: { A: "Şanlıurfa", B: "Mardin", C: "Diyarbakır", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 368, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yaren Gecesi' meşhurdur?", secenekler: { A: "Çankırı", B: "Kastamonu", C: "Bolu", D: "Çorum" }, dogruCevap: "A" },
    { seviye: 369, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ferfene Gecesi' meşhurdur?", secenekler: { A: "Ankara - Eskişehir - Afyonkarahisar", B: "Kayseri", C: "Konya", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 370, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Gezek' geleneği meşhurdur?", secenekler: { A: "Bursa", B: "İstanbul", C: "Edirne", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 371, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Helva Gecesi' meşhurdur?", secenekler: { A: "İstanbul - Edirne", B: "Bursa", C: "Ankara", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 372, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Sema Töreni' meşhurdur?", secenekler: { A: "Konya", B: "İstanbul", C: "Bursa", D: "Edirne" }, dogruCevap: "A" },
    { seviye: 373, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mesir Macunu Festivali' meşhurdur?", secenekler: { A: "Manisa", B: "İzmir", C: "Aydın", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 374, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kansız Boğa Güreşi' (Muğla) meşhurdur?", secenekler: { A: "Muğla", B: "Artvin", C: "Aydın", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 375, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kayısı Festivali' meşhurdur?", secenekler: { A: "Malatya", B: "Elazığ", C: "Iğdır", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 376, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Portakal Çiçeği Karnavalı' meşhurdur?", secenekler: { A: "Adana", B: "Antalya", C: "Mersin", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 377, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Altın Portakal Film Festivali' meşhurdur?", secenekler: { A: "Antalya", B: "Adana", C: "İstanbul", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 378, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Altın Koza Film Festivali' meşhurdur?", secenekler: { A: "Adana", B: "Antalya", C: "İstanbul", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 379, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Karpuz Festivali' meşhurdur?", secenekler: { A: "Diyarbakır", B: "Adana", C: "Tekirdağ", D: "Samsun" }, dogruCevap: "A" },
    { seviye: 380, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Zeytin Festivali' meşhurdur?", secenekler: { A: "Balıkesir (Ayvalık) - Bursa (Gemlik)", B: "İzmir", C: "Aydın", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 381, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bağ Bozumu Festivali' meşhurdur?", secenekler: { A: "Nevşehir - Tekirdağ - Elazığ", B: "İzmir", C: "Manisa", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 382, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kiraz Festivali' meşhurdur?", secenekler: { A: "Tekirdağ", B: "Afyonkarahisar", C: "Isparta", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 383, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Gül Festivali' meşhurdur?", secenekler: { A: "Isparta", B: "Burdur", C: "Antalya", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 384, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Büyük Evliya Günü' meşhurdur?", secenekler: { A: "Kastamonu", B: "Konya", C: "İstanbul", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 385, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Hacı Bektaş Veli Anma Törenleri' meşhurdur?", secenekler: { A: "Nevşehir", B: "Kırşehir", C: "Yozgat", D: "Aksaray" }, dogruCevap: "A" },
    { seviye: 386, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şeb-i Arus' törenleri meşhurdur?", secenekler: { A: "Konya", B: "İstanbul", C: "Bursa", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 387, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ertuğrul Gazi'yi Anma Törenleri' meşhurdur?", secenekler: { A: "Bilecik (Söğüt)", B: "Bursa", C: "Kütahya", D: "Eskişehir" }, dogruCevap: "A" },
    { seviye: 388, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yunus Emre Anma Etkinlikleri' meşhurdur?", secenekler: { A: "Eskişehir - Karaman", B: "Ankara", C: "Konya", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 389, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Nasreddin Hoca Şenlikleri' meşhurdur?", secenekler: { A: "Konya (Akşehir)", B: "Eskişehir", C: "Ankara", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 390, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ahi Evran Haftası' meşhurdur?", secenekler: { A: "Kırşehir", B: "Ankara", C: "Konya", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 391, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tantunisi' meşhurdur?", secenekler: { A: "Mersin", B: "Adana", C: "Hatay", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 392, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Cezeryesi' meşhurdur?", secenekler: { A: "Mersin", B: "Adana", C: "Osmaniye", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 393, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kerebiç' tatlısı meşhurdur?", secenekler: { A: "Mersin - Hatay", B: "Adana", C: "Gaziantep", D: "Kahramanmaraş" }, dogruCevap: "A" },
    { seviye: 394, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kayı Koruğu' suyu meşhurdur?", secenekler: { A: "Aydın - İzmir", B: "Muğla", C: "Antalya", D: "Mersin" }, dogruCevap: "A" },
    { seviye: 395, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Nar Ekşisi' meşhurdur?", secenekler: { A: "Hatay - Gaziantep", B: "Adana", C: "Mersin", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 396, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Salçası' meşhurdur?", secenekler: { A: "Gaziantep - Hatay - Bursa", B: "İstanbul", C: "Ankara", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 397, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kuruyemişi' meşhurdur?", secenekler: { A: "Denizli - Gaziantep", B: "Ankara", C: "İstanbul", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 398, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Pastırması' meşhurdur?", secenekler: { A: "Kayseri - Kastamonu", B: "Afyonkarahisar", C: "Sivas", D: "Erzurum" }, dogruCevap: "A" },
    { seviye: 399, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Sucuğu' meşhurdur?", secenekler: { A: "Afyonkarahisar - Kayseri", B: "İstanbul", C: "Ankara", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 400, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kavurması' meşhurdur?", secenekler: { A: "Rize - Erzurum", B: "Konya", C: "Ankara", D: "İzmir" }, dogruCevap: "A" }, 
    { seviye: 401, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Cizleme' (Akıtma) yemeği meşhurdur?", secenekler: { A: "Bolu", B: "Zonguldak", C: "Karabük", D: "Bartın" }, dogruCevap: "A" },
    { seviye: 402, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Banduma' yemeği meşhurdur?", secenekler: { A: "Kastamonu", B: "Sinop", C: "Samsun", D: "Ordu" }, dogruCevap: "A" },
    { seviye: 403, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mıhlama' (Kuymak) yemeği meşhurdur?", secenekler: { A: "Rize - Trabzon", B: "Artvin", C: "Giresun", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 404, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ançüez' (Hamsi Ezmesi) üretimi meşhurdur?", secenekler: { A: "Gelibolu (Çanakkale)", B: "Trabzon", C: "Rize", D: "Sinop" }, dogruCevap: "A" },
    { seviye: 405, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Lakerda' (Balık Salamurası) kültürü yaygındır?", secenekler: { A: "İstanbul - Sinop", B: "İzmir", C: "Antalya", D: "Mersin" }, dogruCevap: "A" },
    { seviye: 406, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kuru Bamya' yemeği meşhurdur?", secenekler: { A: "Amasya", B: "Konya", C: "Tokat", D: "Çorum" }, dogruCevap: "A" },
    { seviye: 407, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Çemen'i kahvaltılarda meşhurdur?", secenekler: { A: "Kayseri", B: "Sivas", C: "Yozgat", D: "Kırşehir" }, dogruCevap: "A" },
    { seviye: 408, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Acuka'sı meşhurdur?", secenekler: { A: "Bolu - Düzce", B: "İstanbul", C: "İzmir", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 409, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Müceddere' (Mercimekli Pilav) yemeği meşhurdur?", secenekler: { A: "Kilis", B: "Gaziantep", C: "Şanlıurfa", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 410, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kaytaz Böreği' meşhurdur?", secenekler: { A: "Hatay", B: "Adana", C: "Mersin", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 411, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ispanaklı Böreği' tescillidir?", secenekler: { A: "Isparta", B: "Burdur", C: "Antalya", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 412, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Talaş Böreği' meşhurdur?", secenekler: { A: "İstanbul", B: "Ankara", C: "İzmir", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 413, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kürt Böreği' (Sade Börek) meşhurdur?", secenekler: { A: "İstanbul", B: "Bingöl", C: "Diyarbakır", D: "Mardin" }, dogruCevap: "A" },
    { seviye: 414, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Su Böreği' tescillidir?", secenekler: { A: "Erzurum", B: "Kayseri", C: "Konya", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 415, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kol Böreği' meşhurdur?", secenekler: { A: "İstanbul (Sarıyer)", B: "Bursa", C: "İzmir", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 416, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Puf Böreği' meşhurdur?", secenekler: { A: "Eskişehir", B: "Ankara", C: "Bilecik", D: "Kütahya" }, dogruCevap: "A" },
    { seviye: 417, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Çiğ Böreği' (Çibörek) meşhurdur?", secenekler: { A: "Eskişehir", B: "Konya", C: "Kayseri", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 418, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Met Helvası' meşhurdur?", secenekler: { A: "Eskişehir", B: "Afyonkarahisar", C: "Kütahya", D: "Bilecik" }, dogruCevap: "A" },
    { seviye: 419, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Pişmaniyesi' meşhurdur?", secenekler: { A: "Kocaeli (İzmit)", B: "Sakarya", C: "Düzce", D: "Bolu" }, dogruCevap: "A" },
    { seviye: 420, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Saray Helvası' meşhurdur?", secenekler: { A: "Kocaeli - Bolu", B: "İstanbul", C: "Edirne", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 421, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kastamonu Çekme Helvası' meşhurdur?", secenekler: { A: "Kastamonu", B: "Sinop", C: "Çankırı", D: "Çorum" }, dogruCevap: "A" },
    { seviye: 422, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Peynir Helvası' meşhurdur?", secenekler: { A: "Çanakkale - Tekirdağ", B: "Edirne", C: "Balıkesir", D: "Kırklareli" }, dogruCevap: "A" },
    { seviye: 423, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Höşmerim' tatlısı meşhurdur?", secenekler: { A: "Balıkesir - Çanakkale - Ankara", B: "Konya", C: "Bursa", D: "Yozgat" }, dogruCevap: "A" },
    { seviye: 424, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şöbiyet' tatlısı meşhurdur?", secenekler: { A: "Gaziantep", B: "Şanlıurfa", C: "Adıyaman", D: "Kahramanmaraş" }, dogruCevap: "A" },
    { seviye: 425, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bülbül Yuvası' tatlısı meşhurdur?", secenekler: { A: "Gaziantep", B: "İstanbul", C: "Bursa", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 426, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Sütlü Nuriye' tatlısı meşhurdur?", secenekler: { A: "İstanbul", B: "Diyarbakır", C: "Gaziantep", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 427, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Burma Kadayıfı' meşhurdur?", secenekler: { A: "Diyarbakır", B: "Şanlıurfa", C: "Gaziantep", D: "Mardin" }, dogruCevap: "A" },
    { seviye: 428, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ekmek Kadayıfı' (Vişneli) meşhurdur?", secenekler: { A: "Afyonkarahisar", B: "Kütahya", C: "Uşak", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 429, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şekerparesi' meşhurdur?", secenekler: { A: "İstanbul", B: "Bursa", C: "Ankara", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 430, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Hanım Göbeği' tatlısı meşhurdur?", secenekler: { A: "İstanbul", B: "Edirne", C: "Bursa", D: "Konya" }, dogruCevap: "A" },
    { seviye: 431, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Vezir Parmağı' tatlısı meşhurdur?", secenekler: { A: "İstanbul", B: "Edirne", C: "Bursa", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 432, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Dilber Dudak' tatlısı meşhurdur?", secenekler: { A: "Amasya - Bursa", B: "Sivas", C: "Kayseri", D: "Tokat" }, dogruCevap: "A" },
    { seviye: 433, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Künefesi' meşhurdur?", secenekler: { A: "Hatay", B: "Mersin", C: "Adana", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 434, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Sütlü Tatlıları' (Muhallebi vb.) meşhurdur?", secenekler: { A: "İstanbul", B: "Bursa", C: "İzmir", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 435, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Keşkülü' meşhurdur?", secenekler: { A: "İstanbul", B: "Edirne", C: "Bursa", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 436, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kazandibi' tatlısı meşhurdur?", secenekler: { A: "İstanbul", B: "Bursa", C: "İzmir", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 437, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tavuk Göğsü' tatlısı meşhurdur?", secenekler: { A: "İstanbul", B: "Bursa", C: "Edirne", D: "Kocaeli" }, dogruCevap: "A" },
    { seviye: 438, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Sütlacı' (Hamsiköy) meşhurdur?", secenekler: { A: "Trabzon", B: "Rize", C: "Giresun", D: "Ordu" }, dogruCevap: "A" },
    { seviye: 439, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Laz Böreği' (Tatlıdır) meşhurdur?", secenekler: { A: "Rize - Artvin", B: "Trabzon", C: "Giresun", D: "Samsun" }, dogruCevap: "A" },
    { seviye: 440, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kabak Boranisi' meşhurdur?", secenekler: { A: "Hatay", B: "Adana", C: "Mersin", D: "Şanlıurfa" }, dogruCevap: "A" },
    { seviye: 441, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Semsek' (Kızartma İçli Köfte türü) meşhurdur?", secenekler: { A: "Şanlıurfa", B: "Gaziantep", C: "Diyarbakır", D: "Mardin" }, dogruCevap: "A" },
    { seviye: 442, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Borani' yemeği meşhurdur?", secenekler: { A: "Isparta - Hatay - Şanlıurfa", B: "İzmir", C: "Ankara", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 443, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Eli Böğründe' (Yanyana) meşhurdur?", secenekler: { A: "Kahramanmaraş", B: "Kilis", C: "Gaziantep", D: "Osmaniye" }, dogruCevap: "A" },
    { seviye: 444, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Sömelek Köftesi' meşhurdur?", secenekler: { A: "Kahramanmaraş", B: "Adana", C: "Osmaniye", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 445, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Abugannuş' (Söğürme) meşhurdur?", secenekler: { A: "Şanlıurfa", B: "Gaziantep", C: "Hatay", D: "Diyarbakır" }, dogruCevap: "A" },
    { seviye: 446, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tike Kebabı' meşhurdur?", secenekler: { A: "Adana", B: "Gaziantep", C: "Şanlıurfa", D: "Mardin" }, dogruCevap: "A" },
    { seviye: 447, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Küşlemesi' meşhurdur?", secenekler: { A: "Gaziantep", B: "Şanlıurfa", C: "Kilis", D: "Kahramanmaraş" }, dogruCevap: "A" },
    { seviye: 448, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Alinazik' kebabı meşhurdur?", secenekler: { A: "Gaziantep", B: "Hatay", C: "Şanlıurfa", D: "Adana" }, dogruCevap: "A" },
    { seviye: 449, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'İslim Kebabı' meşhurdur?", secenekler: { A: "Gaziantep - İstanbul", B: "Ankara", C: "Bursa", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 450, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Altı Ezmeli Kebabı' meşhurdur?", secenekler: { A: "Gaziantep", B: "Şanlıurfa", C: "Mardin", D: "Diyarbakır" }, dogruCevap: "A" },
    { seviye: 451, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Eli yüzünde' (İlçe yemeği) meşhurdur?", secenekler: { A: "Kastamonu", B: "Bolu", C: "Samsun", D: "Çankırı" }, dogruCevap: "A" },
    { seviye: 452, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Hasköy' simidi meşhurdur?", secenekler: { A: "Samsun", B: "İstanbul", C: "İzmir", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 453, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Terme Pidesi' meşhurdur?", secenekler: { A: "Samsun", B: "Ordu", C: "Giresun", D: "Trabzon" }, dogruCevap: "A" },
    { seviye: 454, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bafra Pidesi' meşhurdur?", secenekler: { A: "Samsun", B: "Sinop", C: "Kastamonu", D: "Zonguldak" }, dogruCevap: "A" },
    { seviye: 455, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yağlı Pidesi' (Görele) meşhurdur?", secenekler: { A: "Giresun", B: "Trabzon", C: "Ordu", D: "Rize" }, dogruCevap: "A" },
    { seviye: 456, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Peynirli Pidesi' (Sürmene) meşhurdur?", secenekler: { A: "Trabzon", B: "Rize", C: "Artvin", D: "Giresun" }, dogruCevap: "A" },
    { seviye: 457, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Nazilli Pidesi' meşhurdur?", secenekler: { A: "Aydın", B: "Denizli", C: "Muğla", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 458, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Cantık' pidesi meşhurdur?", secenekler: { A: "Bursa", B: "Bilecik", C: "Kütahya", D: "Eskişehir" }, dogruCevap: "A" },
    { seviye: 459, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tahini' (Korkuteli) meşhurdur?", secenekler: { A: "Antalya", B: "Burdur", C: "Isparta", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 460, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tahinli Pidesi' meşhurdur?", secenekler: { A: "Bursa - Aydın - Konya", B: "İstanbul", C: "Ankara", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 461, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Zerde' tatlısı düğünlerde meşhurdur?", secenekler: { A: "İstanbul - Edirne - Konya", B: "Ankara", C: "İzmir", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 462, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Aşuresi' meşhurdur?", secenekler: { A: "Tüm Türkiye", B: "Sadece İstanbul", C: "Sadece Bursa", D: "Sadece Konya" }, dogruCevap: "A" },
    { seviye: 463, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mesir Macunu' meşhurdur?", secenekler: { A: "Manisa", B: "İzmir", C: "Aydın", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 464, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Pestili' meşhurdur?", secenekler: { A: "Gümüşhane", B: "Artvin", C: "Erzincan", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 465, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kömesi' (Cevizli Sucuk) meşhurdur?", secenekler: { A: "Gümüşhane", B: "Bayburt", C: "Erzurum", D: "Erzincan" }, dogruCevap: "A" },
    { seviye: 466, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tulum Peyniri' (Şavak) meşhurdur?", secenekler: { A: "Elazığ - Erzincan", B: "Malatya", C: "Tunceli", D: "Bingöl" }, dogruCevap: "A" },
    { seviye: 467, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Sepet Peyniri' meşhurdur?", secenekler: { A: "Balıkesir (Ayvalık)", B: "Çanakkale", C: "İzmir", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 468, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Lor Peyniri' meşhurdur?", secenekler: { A: "Tüm Türkiye", B: "Sadece Ege", C: "Sadece Trakya", D: "Sadece Karadeniz" }, dogruCevap: "A" },
    { seviye: 469, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Keş' (Kurutulmuş yoğurt) peyniri meşhurdur?", secenekler: { A: "Bolu", B: "Kastamonu", C: "Sinop", D: "Çankırı" }, dogruCevap: "A" },
    { seviye: 470, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kurut' (Yoğurt kurusu) yemeği meşhurdur?", secenekler: { A: "Erzurum - Van - Hakkari", B: "Konya", C: "Kayseri", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 471, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Manda Yoğurdu' (Kandırı) meşhurdur?", secenekler: { A: "Kocaeli", B: "Sakarya", C: "Bolu", D: "Düzce" }, dogruCevap: "A" },
    { seviye: 472, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Silivri Yoğurdu' meşhurdur?", secenekler: { A: "İstanbul", B: "Tekirdağ", C: "Kırklareli", D: "Edirne" }, dogruCevap: "A" },
    { seviye: 473, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kanlıca Yoğurdu' meşhurdur?", secenekler: { A: "İstanbul", B: "Kocaeli", C: "Bursa", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 474, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yoğurdu' (Çaycuma) meşhurdur?", secenekler: { A: "Zonguldak", B: "Bartın", C: "Kastamonu", D: "Karabük" }, dogruCevap: "A" },
    { seviye: 475, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Turşusu' (Gedelek) meşhurdur?", secenekler: { A: "Bursa", B: "Ankara", C: "İstanbul", D: "Kocaeli" }, dogruCevap: "A" },
    { seviye: 476, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Turşusu' (Çubuk) meşhurdur?", secenekler: { A: "Ankara", B: "Çankırı", C: "Kırıkkale", D: "Yozgat" }, dogruCevap: "A" },
    { seviye: 477, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Zeytini' (Gemlik) meşhurdur?", secenekler: { A: "Bursa", B: "Balıkesir", C: "Çanakkale", D: "Manisa" }, dogruCevap: "A" },
    { seviye: 478, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Zeytini' (Edremit) meşhurdur?", secenekler: { A: "Balıkesir", B: "Bursa", C: "İzmir", D: "Çanakkale" }, dogruCevap: "A" },
    { seviye: 479, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Zeytinyağı' (Altınoluk) meşhurdur?", secenekler: { A: "Balıkesir", B: "İzmir", C: "Aydın", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 480, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Zeytinyağı' (Milas) meşhurdur?", secenekler: { A: "Muğla", B: "Aydın", C: "Denizli", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 481, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Çam Balı' meşhurdur?", secenekler: { A: "Muğla", B: "Antalya", C: "Aydın", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 482, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Anzer Balı' meşhurdur?", secenekler: { A: "Rize", B: "Artvin", C: "Trabzon", D: "Giresun" }, dogruCevap: "A" },
    { seviye: 483, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Cevizi' (Kaman) meşhurdur?", secenekler: { A: "Kırşehir", B: "Nevşehir", C: "Yozgat", D: "Aksaray" }, dogruCevap: "A" },
    { seviye: 484, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Cevizi' (Niksar) meşhurdur?", secenekler: { A: "Tokat", B: "Amasya", C: "Sivas", D: "Çorum" }, dogruCevap: "A" },
    { seviye: 485, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Cevizi' (Oğuzlar) meşhurdur?", secenekler: { A: "Çorum", B: "Çankırı", C: "Kastamonu", D: "Yozgat" }, dogruCevap: "A" },
    { seviye: 486, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Antep Fıstığı' meşhurdur?", secenekler: { A: "Gaziantep - Şanlıurfa", B: "Siirt", C: "Kahramanmaraş", D: "Adıyaman" }, dogruCevap: "A" },
    { seviye: 487, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Fıstığı' (Siirt Fıstığı) meşhurdur?", secenekler: { A: "Siirt", B: "Batman", C: "Mardin", D: "Diyarbakır" }, dogruCevap: "A" },
    { seviye: 488, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Çam Fıstığı' (Kozak) meşhurdur?", secenekler: { A: "İzmir (Bergama)", B: "Muğla", C: "Aydın", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 489, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yer Fıstığı' meşhurdur?", secenekler: { A: "Osmaniye - Adana", B: "Mersin", C: "Antalya", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 490, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Fındığı' meşhurdur?", secenekler: { A: "Ordu - Giresun", B: "Düzce - Sakarya", C: "Trabzon", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 491, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ayva'sı (Geyve) meşhurdur?", secenekler: { A: "Sakarya", B: "Bursa", C: "Bilecik", D: "Kocaeli" }, dogruCevap: "A" },
    { seviye: 492, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Elma'sı (Amasya Elması) meşhurdur?", secenekler: { A: "Amasya", B: "Isparta", C: "Niğde", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 493, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Elma'sı (Isparta Elması) meşhurdur?", secenekler: { A: "Isparta", B: "Burdur", C: "Antalya", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 494, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Armut'u (Deveci) meşhurdur?", secenekler: { A: "Bursa", B: "Ankara", C: "İstanbul", D: "Samsun" }, dogruCevap: "A" },
    { seviye: 495, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şeftali'si meşhurdur?", secenekler: { A: "Bursa", B: "Çanakkale", C: "İzmir", D: "Aydın" }, dogruCevap: "A" },
    { seviye: 496, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Üzümü' (Sultaniye) meşhurdur?", secenekler: { A: "Manisa", B: "İzmir", C: "Denizli", D: "Aydın" }, dogruCevap: "A" },
    { seviye: 497, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Üzümü' (Öküzgözü) meşhurdur?", secenekler: { A: "Elazığ", B: "Malatya", C: "Erzincan", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 498, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Üzümü' (Boğazkere) meşhurdur?", secenekler: { A: "Diyarbakır", B: "Mardin", C: "Siirt", D: "Şanlıurfa" }, dogruCevap: "A" },
    { seviye: 499, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kavun'u (Kırkağaç) meşhurdur?", secenekler: { A: "Manisa", B: "İzmir", C: "Balıkesir", D: "Aydın" }, dogruCevap: "A" },
    { seviye: 500, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kavun'u (Çumra) meşhurdur?", secenekler: { A: "Konya", B: "Aksaray", C: "Karaman", D: "Niğde" }, dogruCevap: "A" },
    { seviye: 501, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Karpuz'u meşhurdur?", secenekler: { A: "Diyarbakır - Adana", B: "Tekirdağ", C: "Samsun", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 502, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Muz'u meşhurdur?", secenekler: { A: "Antalya (Alanya) - Mersin (Anamur)", B: "Muğla", C: "Adana", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 503, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Çilek'i meşhurdur?", secenekler: { A: "Aydın - Mersin - Bursa", B: "İstanbul", C: "Ankara", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 504, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kiraz'ı (Napolyon) meşhurdur?", secenekler: { A: "Afyonkarahisar (Akşehir) - Isparta", B: "Konya", C: "İzmir", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 505, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Vişne'si meşhurdur?", secenekler: { A: "Afyonkarahisar - Kütahya", B: "Konya", C: "Ankara", D: "Eskişehir" }, dogruCevap: "A" },
    { seviye: 506, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Nar'ı meşhurdur?", secenekler: { A: "Antalya - Denizli - Mersin", B: "Aydın", C: "Muğla", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 507, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Pamuk'u meşhurdur?", secenekler: { A: "Şanlıurfa - Aydın - Adana", B: "Muğla", C: "İzmir", D: "Manisa" }, dogruCevap: "A" },
    { seviye: 508, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tütün'ü meşhurdur?", secenekler: { A: "Adıyaman - Samsun - Manisa", B: "İzmir", C: "Bursa", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 509, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Çay'ı meşhurdur?", secenekler: { A: "Rize - Artvin - Trabzon", B: "Giresun", C: "Ordu", D: "Samsun" }, dogruCevap: "A" },
    { seviye: 510, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Pirinç'i meşhurdur?", secenekler: { A: "Edirne - Samsun - Kastamonu", B: "Çorum", C: "Çankırı", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 511, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ayçiçeği' meşhurdur?", secenekler: { A: "Tekirdağ - Edirne - Konya", B: "Adana", C: "Samsun", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 512, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şeker Pancarı' meşhurdur?", secenekler: { A: "Konya - Kayseri - Aksaray", B: "Eskişehir", C: "Yozgat", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 513, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Gül'ü meşhurdur?", secenekler: { A: "Isparta", B: "Burdur", C: "Antalya", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 514, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Haşhaş'ı meşhurdur?", secenekler: { A: "Afyonkarahisar", B: "Kütahya", C: "Uşak", D: "Burdur" }, dogruCevap: "A" },
    { seviye: 515, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Salep'i meşhurdur?", secenekler: { A: "Burdur (Bucak)", B: "Kahramanmaraş", C: "Kastamonu", D: "Samsun" }, dogruCevap: "A" },
    { seviye: 516, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Anason'u meşhurdur?", secenekler: { A: "Burdur - Denizli", B: "Antalya", C: "Isparta", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 517, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Keten'i meşhurdur?", secenekler: { A: "Afyonkarahisar - Sinop", B: "Samsun", C: "Kastamonu", D: "Ordu" }, dogruCevap: "A" },
    { seviye: 518, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kenevir'i meşhurdur?", secenekler: { A: "Samsun - Kastamonu", B: "Sinop", C: "Amasya", D: "Çorum" }, dogruCevap: "A" },
    { seviye: 519, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ispanak'ı meşhurdur?", secenekler: { A: "Ankara - İzmir", B: "Antalya", C: "Bursa", D: "Adana" }, dogruCevap: "A" },
    { seviye: 520, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Pırasa'sı meşhurdur?", secenekler: { A: "İzmir - Bursa", B: "Antalya", C: "Muğla", D: "Samsun" }, dogruCevap: "A" },
    { seviye: 521, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Domates'i meşhurdur?", secenekler: { A: "Antalya - Bursa - Çanakkale", B: "İzmir", C: "Mersin", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 522, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Biber'i (İsot) meşhurdur?", secenekler: { A: "Şanlıurfa", B: "Gaziantep", C: "Kahramanmaraş", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 523, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Biber'i (Maraş Biberi) meşhurdur?", secenekler: { A: "Kahramanmaraş", B: "Gaziantep", C: "Şanlıurfa", D: "Kilis" }, dogruCevap: "A" },
    { seviye: 524, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Biber'i (Demre) meşhurdur?", secenekler: { A: "Antalya", B: "Mersin", C: "Muğla", D: "Aydın" }, dogruCevap: "A" },
    { seviye: 525, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Patlıcan'ı meşhurdur?", secenekler: { A: "Antalya - Aydın - Şanlıurfa", B: "Adana", C: "Mersin", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 526, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Sarımsak'ı meşhurdur?", secenekler: { A: "Kastamonu (Taşköprü)", B: "Gaziantep (Arabun)", C: "Kahramanmaraş", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 527, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Soğan'ı meşhurdur?", secenekler: { A: "Ankara (Polatlı) - Amasya", B: "Karaman", C: "Hatay", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 528, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Patates'i meşhurdur?", secenekler: { A: "Niğde - Nevşehir - Afyonkarahisar", B: "İzmir (Ödemiş)", C: "Bolu", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 529, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mercimek'i (Kırmızı) meşhurdur?", secenekler: { A: "Şanlıurfa - Diyarbakır - Mardin", B: "Gaziantep", C: "Siirt", D: "Adıyaman" }, dogruCevap: "A" },
    { seviye: 530, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mercimek'i (Yeşil) meşhurdur?", secenekler: { A: "Yozgat - Çorum - Ankara", B: "Konya", C: "Kayseri", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 531, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Nohut'u meşhurdur?", secenekler: { A: "Kırşehir - Ankara - Uşak", B: "Antalya", C: "Muğla", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 532, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Fasulye'si (İspir) meşhurdur?", secenekler: { A: "Erzurum", B: "Erzincan", C: "Bayburt", D: "Gümüşhane" }, dogruCevap: "A" },
    { seviye: 533, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Fasulye'si (Çalı) meşhurdur?", secenekler: { A: "Niğde", B: "Nevşehir", C: "Aksaray", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 534, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Fasulye'si (Dermason) meşhurdur?", secenekler: { A: "Karaman - Konya - Niğde", B: "Ankara", C: "Eskişehir", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 535, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bakla'sı meşhurdur?", secenekler: { A: "Aydın - İzmir", B: "Antalya", C: "Muğla", D: "Balıkesir" }, dogruCevap: "A" },
    { seviye: 536, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bezelye'si meşhurdur?", secenekler: { A: "Bursa - İzmir", B: "Antalya", C: "Samsun", D: "Kocaeli" }, dogruCevap: "A" },
    { seviye: 537, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bamya'sı meşhurdur?", secenekler: { A: "Amasya - Balıkesir - İzmir", B: "İstanbul", C: "Ankara", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 538, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Enginar'ı meşhurdur?", secenekler: { A: "İzmir - Aydın - İstanbul", B: "Bursa", C: "Antalya", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 539, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kuşkonmaz'ı meşhurdur?", secenekler: { A: "Eskişehir", B: "Muğla", C: "İzmir", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 540, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mantar'ı (İstiriye) meşhurdur?", secenekler: { A: "Korkuteli (Antalya)", B: "Bolu", C: "Kastamonu", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 441, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kanlıca Mantarı' meşhurdur?", secenekler: { A: "Kastamonu - Bolu", B: "Zonguldak", C: "Bartın", D: "Sinop" }, dogruCevap: "A" },
    { seviye: 542, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kestane'si meşhurdur?", secenekler: { A: "Aydın - Bursa - Kastamonu", B: "Sinop", C: "Zonguldak", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 543, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kestane Şekeri' meşhurdur?", secenekler: { A: "Bursa", B: "Kastamonu", C: "Aydın", D: "Kocaeli" }, dogruCevap: "A" },
    { seviye: 544, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Pişmaniye'si meşhurdur?", secenekler: { A: "Kocaeli", B: "Sakarya", C: "Düzce", D: "Bolu" }, dogruCevap: "A" },
    { seviye: 545, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Cevizli Sucuğu' meşhurdur?", secenekler: { A: "Elazığ - Gümüşhane - Kahramanmaraş", B: "Artvin", C: "Hepsi", D: "Hiçbiri" }, dogruCevap: "C" },
    { seviye: 546, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Pekmez'i (Zile) meşhurdur?", secenekler: { A: "Tokat", B: "Amasya", C: "Çorum", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 547, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tahini' meşhurdur?", secenekler: { A: "Antalya - Aydın - Manisa", B: "Muğla", C: "İzmir", D: "Konya" }, dogruCevap: "A" },
    { seviye: 548, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Lokumu' meşhurdur?", secenekler: { A: "Afyonkarahisar - Safranbolu - Isparta", B: "İstanbul", C: "Bursa", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 549, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Helvası' meşhurdur?", secenekler: { A: "Tüm Türkiye", B: "Sadece Ege", C: "Sadece İç Anadolu", D: "Sadece Trakya" }, dogruCevap: "A" },
    { seviye: 550, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şerbetli Tatlıları' meşhurdur?", secenekler: { A: "Gaziantep - İstanbul - Bursa", B: "İzmir", C: "Ankara", D: "Hepsi" }, dogruCevap: "D" }, 
    { seviye: 551, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tiridi' meşhurdur?", secenekler: { A: "Kastamonu - Samsun", B: "Konya", C: "Şanlıurfa", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 552, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Balık Ekmek' kültürü (Eminönü) dünyaca meşhurdur?", secenekler: { A: "İstanbul", B: "İzmir", C: "Çanakkale", D: "Trabzon" }, dogruCevap: "A" },
    { seviye: 553, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Islama Köftesi' meşhurdur?", secenekler: { A: "Sakarya", B: "Kocaeli", C: "Bursa", D: "Bilecik" }, dogruCevap: "A" },
    { seviye: 554, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Belen Kebabı' meşhurdur?", secenekler: { A: "Hatay", B: "Gaziantep", C: "Adana", D: "Mersin" }, dogruCevap: "A" },
    { seviye: 555, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kazan Kebabı' meşhurdur?", secenekler: { A: "Şanlıurfa", B: "Mardin", C: "Diyarbakır", D: "Batman" }, dogruCevap: "A" },
    { seviye: 556, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Simit Kebabı' meşhurdur?", secenekler: { A: "Gaziantep", B: "Kilis", C: "Hatay", D: "Adana" }, dogruCevap: "A" },
    { seviye: 557, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ekşili Köftesi' meşhurdur?", secenekler: { A: "Gaziantep - Malatya", B: "Konya", C: "Isparta", D: "Amasya" }, dogruCevap: "A" },
    { seviye: 558, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Analı Kızlı' yemeği meşhurdur?", secenekler: { A: "Adana - Malatya", B: "Kahramanmaraş", C: "Osmaniye", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 559, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mumbar Dolması' meşhurdur?", secenekler: { A: "Adana - Siirt - Diyarbakır", B: "İzmir", C: "Ankara", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 560, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şırdan' dolması meşhurdur?", secenekler: { A: "Adana", B: "Mersin", C: "Hatay", D: "Osmaniye" }, dogruCevap: "A" },
    { seviye: 561, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kelle Söğüş'ü meşhurdur?", secenekler: { A: "İzmir", B: "İstanbul", C: "Ankara", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 562, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kokoreç'i meşhurdur?", secenekler: { A: "İzmir - İstanbul", B: "Ankara", C: "Balıkesir", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 563, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Boyoz'u meşhurdur?", secenekler: { A: "İzmir", B: "Aydın", C: "Manisa", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 564, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Gevrek'i (Simit) meşhurdur?", secenekler: { A: "İzmir", B: "Ankara", C: "Samsun", D: "İstanbul" }, dogruCevap: "A" },
    { seviye: 565, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kumru' sandviçi meşhurdur?", secenekler: { A: "İzmir (Çeşme)", B: "Aydın", C: "Antalya", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 566, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yengen' sandviçi meşhurdur?", secenekler: { A: "İzmir", B: "İstanbul", C: "Ankara", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 567, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tost'u (Ayvalık) meşhurdur?", secenekler: { A: "Balıkesir", B: "İzmir", C: "Manisa", D: "Çanakkale" }, dogruCevap: "A" },
    { seviye: 568, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Tost'u (Susurluk) meşhurdur?", secenekler: { A: "Balıkesir", B: "Bursa", C: "Kocaeli", D: "Sakarya" }, dogruCevap: "A" },
    { seviye: 569, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ayran'ı (Susurluk) meşhurdur?", secenekler: { A: "Balıkesir", B: "Bursa", C: "Çanakkale", D: "Tekirdağ" }, dogruCevap: "A" },
    { seviye: 570, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Hardaliye' içeceği meşhurdur?", secenekler: { A: "Kırklareli", B: "Edirne", C: "Tekirdağ", D: "Çanakkale" }, dogruCevap: "A" },
    { seviye: 571, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Boza'sı meşhurdur?", secenekler: { A: "İstanbul (Vefa) - Bilecik (Pazaryeri)", B: "Eskişehir", C: "Ankara", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 572, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şalgam Suyu' meşhurdur?", secenekler: { A: "Adana - Mersin", B: "Hatay", C: "Osmaniye", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 573, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Meyyan Şerbeti' (Meyan Kökü) meşhurdur?", secenekler: { A: "Gaziantep - Şanlıurfa", B: "Adana", C: "Antalya", D: "Mersin" }, dogruCevap: "A" },
    { seviye: 574, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kızılcık Şerbeti' meşhurdur?", secenekler: { A: "Bolu", B: "Kastamonu", C: "Karabük", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 575, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Gül Suyu' meşhurdur?", secenekler: { A: "Isparta", B: "Burdur", C: "Antalya", D: "Konya" }, dogruCevap: "A" },
    { seviye: 576, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Limonatası' meşhurdur?", secenekler: { A: "İstanbul", B: "Bursa", C: "İzmir", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 577, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Turşu Suyu' meşhurdur?", secenekler: { A: "İstanbul", B: "Ankara", C: "Bursa", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 578, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Dibek Kahvesi' meşhurdur?", secenekler: { A: "Mardin - İzmir", B: "Çanakkale", C: "Aydın", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 579, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Menengiç Kahvesi' meşhurdur?", secenekler: { A: "Gaziantep - Şanlıurfa - Mardin", B: "Kahramanmaraş", C: "Siirt", D: "Adıyaman" }, dogruCevap: "A" },
    { seviye: 580, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mırra' kahvesi meşhurdur?", secenekler: { A: "Şanlıurfa - Mardin", B: "Diyarbakır", C: "Batman", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 581, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Oltu Taşı' işlemeciliği meşhurdur?", secenekler: { A: "Erzurum", B: "Erzincan", C: "Bayburt", D: "Kars" }, dogruCevap: "A" },
    { seviye: 582, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Lüle Taşı' işlemeciliği meşhurdur?", secenekler: { A: "Eskişehir", B: "Ankara", C: "Bilecik", D: "Kütahya" }, dogruCevap: "A" },
    { seviye: 583, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Telkari' (Gümüş işleme) sanatı meşhurdur?", secenekler: { A: "Mardin (Midyat)", B: "Erzurum", C: "Gaziantep", D: "Eskişehir" }, dogruCevap: "A" },
    { seviye: 584, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kazaziye' sanatı meşhurdur?", secenekler: { A: "Trabzon", B: "Rize", C: "Giresun", D: "Artvin" }, dogruCevap: "A" },
    { seviye: 585, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Hasır Bileziği' meşhurdur?", secenekler: { A: "Trabzon", B: "Samsun", C: "İstanbul", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 586, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bakırcılığı' meşhurdur?", secenekler: { A: "Gaziantep - Kahramanmaraş", B: "Erzincan", C: "Kastamonu", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 587, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Çiniciliği' meşhurdur?", secenekler: { A: "Kütahya - İznik", B: "Konya", C: "Sivas", D: "Edirne" }, dogruCevap: "A" },
    { seviye: 588, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Seramik' üretimi meşhurdur?", secenekler: { A: "Çanakkale - Bilecik - Kütahya", B: "Aydın", C: "Muğla", D: "Manisa" }, dogruCevap: "A" },
    { seviye: 589, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Halıcılığı' (Hereke) meşhurdur?", secenekler: { A: "Kocaeli", B: "Kayseri", C: "Isparta", D: "Uşak" }, dogruCevap: "A" },
    { seviye: 590, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Halıcılığı' (Bünyan) meşhurdur?", secenekler: { A: "Kayseri", B: "Sivas", C: "Nevşehir", D: "Niğde" }, dogruCevap: "A" },
    { seviye: 591, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kilimi' (Eşme) meşhurdur?", secenekler: { A: "Uşak", B: "Manisa", C: "Aydın", D: "Afyonkarahisar" }, dogruCevap: "A" },
    { seviye: 592, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kilimi' (Sharköy) meşhurdur?", secenekler: { A: "Tekirdağ", B: "Edirne", C: "Kırklareli", D: "Çanakkale" }, dogruCevap: "A" },
    { seviye: 593, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Bıçakçılığı' meşhurdur?", secenekler: { A: "Bursa - Sürmene - Yatağan", B: "Denizli", C: "Trabzon", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 594, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Cam İşlemeciliği' meşhurdur?", secenekler: { A: "İstanbul (Beykoz)", B: "Denizli", C: "Kocaeli", D: "Eskişehir" }, dogruCevap: "A" },
    { seviye: 595, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yemenisi' (Ayakkabı) meşhurdur?", secenekler: { A: "Gaziantep - Kahramanmaraş", B: "Kilis", C: "Şanlıurfa", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 596, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Şile Bezi' meşhurdur?", secenekler: { A: "İstanbul", B: "Kocaeli", C: "Sakarya", D: "Düzce" }, dogruCevap: "A" },
    { seviye: 597, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Buldan Bezi' meşhurdur?", secenekler: { A: "Denizli", B: "Aydın", C: "Uşak", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 598, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kandura Bezi' meşhurdur?", secenekler: { A: "Rize", B: "Artvin", C: "Trabzon", D: "Giresun" }, dogruCevap: "A" },
    { seviye: 599, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Elma Sirkesi' meşhurdur?", secenekler: { A: "Amasya", B: "Isparta", C: "Niğde", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 600, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Üzüm Pekmezi' meşhurdur?", secenekler: { A: "Nevşehir - Gaziantep - Elazığ", B: "Manisa", C: "İzmir", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 601, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Keçiboynuzu' (Harnup) üretimi meşhurdur?", secenekler: { A: "Antalya - Mersin", B: "Muğla", C: "Aydın", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 602, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'İncir'i meşhurdur?", secenekler: { A: "Aydın", B: "İzmir", C: "Bursa", D: "Mersin" }, dogruCevap: "A" },
    { seviye: 603, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kestane'si meşhurdur?", secenekler: { A: "Aydın - Bursa - Kastamonu", B: "Kırklareli", C: "Düzce", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 604, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ihlamur'u meşhurdur?", secenekler: { A: "Yalova - Bursa - Artvin", B: "Antalya", C: "Mersin", D: "Adana" }, dogruCevap: "A" },
    { seviye: 605, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kekiği' meşhurdur?", secenekler: { A: "Denizli", B: "Antalya", C: "Muğla", D: "Isparta" }, dogruCevap: "A" },
    { seviye: 606, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Defne Yaprağı' meşhurdur?", secenekler: { A: "Muğla - Mersin - Hatay", B: "Samsun", C: "Zonguldak", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 607, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kapari'si meşhurdur?", secenekler: { A: "Muğla - Antalya", B: "Aydın", C: "Denizli", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 608, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Sumak'ı meşhurdur?", secenekler: { A: "Kahramanmaraş - Gaziantep", B: "Şanlıurfa", C: "Mardin", D: "Siirt" }, dogruCevap: "A" },
    { seviye: 609, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kuru Üzüm'ü meşhurdur?", secenekler: { A: "Manisa", B: "İzmir", C: "Denizli", D: "Gaziantep" }, dogruCevap: "A" },
    { seviye: 610, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kuru Kayısı'sı meşhurdur?", secenekler: { A: "Malatya", B: "Elazığ", C: "Iğdır", D: "Mut (Mersin)" }, dogruCevap: "A" },
    { seviye: 611, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kuru İncir'i meşhurdur?", secenekler: { A: "Aydın", B: "İzmir", C: "Bursa", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 612, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kuru Dut'u meşhurdur?", secenekler: { A: "Erzincan - Malatya - Elazığ", B: "Konya", C: "Kayseri", D: "Ankara" }, dogruCevap: "A" },
    { seviye: 613, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kuru Erik'i meşhurdur?", secenekler: { A: "Kastamonu", B: "Amasya", C: "Tokat", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 614, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Pestil ve Köme'si meşhurdur?", secenekler: { A: "Gümüşhane", B: "Artvin", C: "Erzincan", D: "Bayburt" }, dogruCevap: "A" },
    { seviye: 615, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mürdüm Eriği' meşhurdur?", secenekler: { A: "Amasya - Tokat", B: "Bolu", C: "Kocaeli", D: "Bursa" }, dogruCevap: "A" },
    { seviye: 616, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Hünnap' meyvesi meşhurdur?", secenekler: { A: "Manisa - Amasya - Çanakkale", B: "Antalya", C: "Mersin", D: "Adana" }, dogruCevap: "A" },
    { seviye: 617, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kudret Narı' meşhurdur?", secenekler: { A: "Yalova - Bursa", B: "Antalya", C: "Muğla", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 618, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kekik Balı' meşhurdur?", secenekler: { A: "Muğla", B: "Antalya", C: "Aydın", D: "Sivas" }, dogruCevap: "A" },
    { seviye: 619, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ayçiçek Balı' meşhurdur?", secenekler: { A: "Tekirdağ - Edirne", B: "Kırklareli", C: "Çanakkale", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 620, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Narenciye Balı' meşhurdur?", secenekler: { A: "Antalya - Mersin - Adana", B: "İzmir", C: "Aydın", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 621, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kestane Balı' meşhurdur?", secenekler: { A: "Kastamonu - Zonguldak - Rize", B: "Artvin", C: "Yalova", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 622, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Meşe Balı' meşhurdur?", secenekler: { A: "Kırklareli", B: "Edirne", C: "Tekirdağ", D: "Bolu" }, dogruCevap: "A" },
    { seviye: 623, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Lavanta' üretimi meşhurdur?", secenekler: { A: "Isparta", B: "Burdur", C: "Afyonkarahisar", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 624, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Susam' üretimi meşhurdur?", secenekler: { A: "Antalya - Muğla - Manisa", B: "Aydın", C: "Mersin", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 625, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yerli Tohum' çalışmaları meşhurdur?", secenekler: { A: "Muğla - İzmir - Eskişehir", B: "Ankara", C: "İstanbul", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 626, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Közlenmiş Patlıcan' konservesi meşhurdur?", secenekler: { A: "Manisa - Aydın", B: "Bursa", C: "Balıkesir", D: "Çanakkale" }, dogruCevap: "A" },
    { seviye: 627, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Biber Salçası' meşhurdur?", secenekler: { A: "Gaziantep - Şanlıurfa - Hatay", B: "Adana", C: "Osmaniye", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 628, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Nar Ekşisi' meşhurdur?", secenekler: { A: "Hatay - Gaziantep - Mersin", B: "Antalya", C: "Muğla", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 629, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Koruk Suyu' meşhurdur?", secenekler: { A: "İzmir - Manisa - Çanakkale", B: "Aydın", C: "Muğla", D: "Denizli" }, dogruCevap: "A" },
    { seviye: 630, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kabak Çekirdeği' meşhurdur?", secenekler: { A: "Nevşehir - Kayseri - Aksaray", B: "Konya", C: "Denizli", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 631, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ay Çekirdeği' meşhurdur?", secenekler: { A: "Kahramanmaraş (Elbistan) - Tekirdağ", B: "Kayseri", C: "Aksaray", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 632, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Leblebi'si (Beyaz) meşhurdur?", secenekler: { A: "Denizli (Serinhisar)", B: "Çorum", C: "Kütahya", D: "Uşak" }, dogruCevap: "A" },
    { seviye: 633, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Leblebi'si (Sarı) meşhurdur?", secenekler: { A: "Çorum - Kütahya (Tavşanlı)", B: "Denizli", C: "Amasya", D: "Tokat" }, dogruCevap: "A" },
    { seviye: 634, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Acıbadem Kurabiyesi' meşhurdur?", secenekler: { A: "İstanbul - Çanakkale - Mersin", B: "İzmir", C: "Bursa", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 635, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kavala Kurabiyesi' meşhurdur?", secenekler: { A: "Edirne", B: "Kırklareli", C: "Tekirdağ", D: "Çanakkale" }, dogruCevap: "A" },
    { seviye: 636, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Portakal'ı meşhurdur?", secenekler: { A: "Antalya (Finike) - Adana", B: "Mersin", C: "Hatay", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 637, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Limon'u meşhurdur?", secenekler: { A: "Mersin (Erdemli) - Antalya", B: "Adana", C: "Muğla", D: "Aydın" }, dogruCevap: "A" },
    { seviye: 638, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mandalina'sı meşhurdur?", secenekler: { A: "Muğla (Bodrum) - İzmir (Seferihisar)", B: "Mersin", C: "Adana", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 639, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Greyfurt'u meşhurdur?", secenekler: { A: "Adana - Mersin", B: "Antalya", C: "Hatay", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 640, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Zencefil ve Zerdeçal' üretimi meşhurdur?", secenekler: { A: "Antalya (Gazipaşa)", B: "Mersin", C: "Adana", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 641, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Ejder Meyvesi' (Pitaya) meşhurdur?", secenekler: { A: "Mersin - Antalya", B: "Adana", C: "Muğla", D: "İzmir" }, dogruCevap: "A" },
    { seviye: 642, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Avokado'su meşhurdur?", secenekler: { A: "Antalya (Alanya) - Mersin", B: "Muğla", C: "Adana", D: "Hatay" }, dogruCevap: "A" },
    { seviye: 643, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Hurma'sı (Cennet Hurması) meşhurdur?", secenekler: { A: "Denizli - Adana - Hatay", B: "İzmir", C: "Aydın", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 644, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Kivi'si meşhurdur?", secenekler: { A: "Yalova - Rize - Ordu", B: "Kocaeli", C: "Giresun", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 645, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Çerezlik Ayçekirdeği' meşhurdur?", secenekler: { A: "Denizli - Kayseri - Aksaray", B: "Tekirdağ", C: "Edirne", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 646, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Arpa ve Buğday' üretimi meşhurdur?", secenekler: { A: "Konya - Ankara - Şanlıurfa", B: "Sivas", C: "Yozgat", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 647, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Sert Buğday'ı meşhurdur?", secenekler: { A: "Gaziantep - Şanlıurfa", B: "Diyarbakır", C: "Mardin", D: "Konya" }, dogruCevap: "A" },
    { seviye: 648, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Mısır'ı meşhurdur?", secenekler: { A: "Adana - Sakarya - Konya", B: "Mardin", C: "Şanlıurfa", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 649, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Yer Elması' meşhurdur?", secenekler: { A: "Hatay - Ankara - Kayseri", B: "İzmir", C: "Antalya", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 650, kategori: "İller ve Meşhurlar", soru: "Hangi ilimizin 'Karnabahar ve Brokoli'si meşhurdur?", secenekler: { A: "Bursa - İzmir - Antalya", B: "Muğla", C: "Aydın", D: "Hepsi" }, dogruCevap: "D" }
 
 
 
);
