window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Türk Futbol Tarihi ve Süper Lig
    { seviye: 1, kategori: "Spor", soru: "UEFA Kupası'nı kazanan tek Türk takımı hangisidir?", secenekler: { A: "Fenerbahçe", B: "Beşiktaş", C: "Galatasaray", D: "Trabzonspor" }, dogruCevap: "C" },
    { seviye: 2, kategori: "Spor", soru: "Süper Lig tarihinde en çok şampiyonluk yaşayan teknik direktör?", secenekler: { A: "Fatih Terim", B: "Mustafa Denizli", C: "Şenol Güneş", D: "Okan Buruk" }, dogruCevap: "A" },
    { seviye: 3, kategori: "Spor", soru: "Süper Lig'in 'Taçsız Kral' lakaplı efsane ismi kimdir?", secenekler: { A: "Metin Oktay", B: "Tanju Çolak", C: "Hakan Şükür", D: "Sergen Yalçın" }, dogruCevap: "A" },
    { seviye: 4, kategori: "Spor", soru: "Fenerbahçe'nin 'Ordinaryüs' lakaplı unutulmaz futbolcusu kimdir?", secenekler: { A: "Lefter Küçükandonyadis", B: "Can Bartu", C: "Rıdvan Dilmen", D: "Alex de Souza" }, dogruCevap: "A" },
    { seviye: 5, kategori: "Spor", soru: "Beşiktaş'ın simgesi olan 'Kara Kartal' lakabı nereden gelir?", secenekler: { A: "Bir taraftarın tezahüratından", B: "Kulüp tüzüğünden", C: "Bir balıkçının sözünden", D: "Kurucu başkanın isteğinden" }, dogruCevap: "A" },
    { seviye: 6, kategori: "Spor", soru: "Süper Lig tarihinde bir sezonda en çok gol atan (39 gol) futbolcu?", secenekler: { A: "Tanju Çolak", B: "Enner Valencia", C: "Mbaye Diagne", D: "Metin Oktay" }, dogruCevap: "A" },
    { seviye: 7, kategori: "Spor", soru: "Türk Milli Takımı, 2002 Dünya Kupası'nda hangi ülkeyi yenerek 3. olmuştur?", secenekler: { A: "Brezilya", B: "Güney Kore", C: "Senegal", D: "Japonya" }, dogruCevap: "B" },
    { seviye: 8, kategori: "Spor", soru: "Avrupa şampiyonalarında (Euro 2008) Türkiye yarı finalde hangi ülkeye elenmiştir?", secenekler: { A: "Almanya", B: "Hırvatistan", C: "Portekiz", D: "Çek Cumhuriyeti" }, dogruCevap: "A" },
    { seviye: 9, kategori: "Spor", soru: "A Milli Takım formasıyla en çok gol atan futbolcu kimdir?", secenekler: { A: "Hakan Şükür", B: "Burak Yılmaz", C: "Cenk Tosun", D: "Nihat Kahveci" }, dogruCevap: "A" },
    { seviye: 10, kategori: "Spor", soru: "Trabzonspor'un Süper Lig'deki ilk şampiyonluk dönemi hangi yıllar arasındadır?", secenekler: { A: "1970'ler", B: "1980'ler", C: "1990'ler", D: "2000'ler" }, dogruCevap: "A" },
    { seviye: 11, kategori: "Spor", soru: "Hem basketbol hem futbol milli takımında forma giyen efsane sporcu?", secenekler: { A: "Can Bartu", B: "Metin Oktay", C: "Turgay Şeren", D: "Lefter" }, dogruCevap: "A" },
    { seviye: 12, kategori: "Spor", soru: "Berlin Kaplanı lakaplı efsane Türk kaleci kimdir?", secenekler: { A: "Turgay Şeren", B: "Rüştü Reçber", C: "Volkan Demirel", D: "Muslera" }, dogruCevap: "A" },
    { seviye: 13, kategori: "Spor", soru: "Arda Güler hangi dünya devine transfer olarak göğsümüzü kabartmıştır?", secenekler: { A: "Real Madrid", B: "Barcelona", C: "Manchester City", D: "Bayern Münih" }, dogruCevap: "A" },
    { seviye: 14, kategori: "Spor", soru: "Süper Lig'de 'Dört Büyükler' dışında şampiyon olan ilk takım?", secenekler: { A: "Bursaspor", B: "Başakşehir", C: "Eskişehirspor", D: "Göztepe" }, dogruCevap: "A" },
    { seviye: 15, kategori: "Spor", soru: "A Milli Futbol Takımı'nın ilk maçı hangi ülkeye karşıdır?", secenekler: { A: "Romanya", B: "Yunanistan", C: "İtalya", D: "Bulgaristan" }, dogruCevap: "A" },
    { seviye: 16, kategori: "Spor", soru: "Süper Lig tarihinde '100'ler kulübü'ne giren ilk futbolcu?", secenekler: { A: "Metin Oktay", B: "Hakan Şükür", C: "Tanju Çolak", D: "Lefter" }, dogruCevap: "A" },
    { seviye: 17, kategori: "Spor", soru: "Beşiktaş'ın efsane başkanı 'Süleyman Seba' kaç yıl başkanlık yapmıştır?", secenekler: { A: "16", B: "10", C: "20", D: "8" }, dogruCevap: "A" },
    { seviye: 18, kategori: "Spor", soru: "Galatasaray'ın efsane kalecisi 'Muslera' hangi ülkelidir?", secenekler: { A: "Uruguay", B: "Arjantin", C: "Brezilya", D: "Şili" }, dogruCevap: "A" },
    { seviye: 19, kategori: "Spor", soru: "Fenerbahçe'nin stadyumu Şükrü Saracoğlu hangi semttedir?", secenekler: { A: "Kadıköy", B: "Beşiktaş", C: "Şişli", D: "Bakırköy" }, dogruCevap: "A" },
    { seviye: 20, kategori: "Spor", soru: "Türkiye Kupası'nı en çok kazanan takım hangisidir?", secenekler: { A: "Galatasaray", B: "Beşiktaş", C: "Fenerbahçe", D: "Trabzonspor" }, dogruCevap: "A" },

    // 26-50: Türk Güreşi, Halter ve Olimpiyat Başarıları
    { seviye: 26, kategori: "Spor", soru: "Olimpiyat tarihinde Türkiye'ye ilk altın madalyayı kazanan sporcu?", secenekler: { A: "Yaşar Erkan", B: "Naim Süleymanoğlu", C: "Hamza Yerlikaya", D: "Mete Gazoz" }, dogruCevap: "A" },
    { seviye: 27, kategori: "Spor", soru: "Cep Herkülü lakaplı, 3 kez olimpiyat şampiyonu haltercimiz?", secenekler: { A: "Naim Süleymanoğlu", B: "Halil Mutlu", C: "Taner Sağır", D: "Sedat Artunç" }, dogruCevap: "A" },
    { seviye: 28, kategori: "Spor", soru: "Asrın Güreşçisi unvanına sahip sporcumuz kimdir?", secenekler: { A: "Hamza Yerlikaya", B: "Rıza Kayaalp", C: "Taha Akgül", D: "Mahmut Demir" }, dogruCevap: "A" },
    { seviye: 29, kategori: "Spor", soru: "Mete Gazoz hangi branşta Olimpiyat Şampiyonu olmuştur?", secenekler: { A: "Okçuluk", B: "Atıcılık", C: "Eskrim", D: "Jimnastik" }, dogruCevap: "A" },
    { seviye: 30, kategori: "Spor", soru: "Kırkpınar Yağlı Güreşleri'nde üst üste 3 kez başpehlivan olana ne verilir?", secenekler: { A: "Altın Kemer", B: "Gümüş Madalya", C: "Kupa", D: "Pehlivan Beratı" }, dogruCevap: "A" },
    { seviye: 31, kategori: "Spor", soru: "Dünya ve Avrupa şampiyonu kadın boksörümüz kimdir?", secenekler: { A: "Busenaz Sürmeneli", B: "Buse Naz Çakıroğlu", C: "Nurcan Taylan", D: "İrem Yaman" }, dogruCevap: "A" },
    { seviye: 32, kategori: "Spor", soru: "Hangi sporcumuz 'Demir Bilek' olarak bilinir?", secenekler: { A: "Haydar Pazarlı", B: "Koca Yusuf", C: "Yaşar Doğu", D: "Adalı Halil" }, dogruCevap: "A" },
    { seviye: 33, kategori: "Spor", soru: "Türk spor tarihinde ilk dünya şampiyonu kadın halterci?", secenekler: { A: "Nurcan Taylan", B: "Sibel Özkan", C: "Şule Şahbaz", D: "Aylin Daşdelen" }, dogruCevap: "A" },
    { seviye: 34, kategori: "Spor", soru: "Rıza Kayaalp hangi spor dalında rekor sayıda Avrupa şampiyonu olmuştur?", secenekler: { A: "Güreş", B: "Halter", C: "Boks", D: "Tekvando" }, dogruCevap: "A" },
    { seviye: 35, kategori: "Spor", soru: "Olimpiyatlarda madalya kazanan ilk Türk kadın sporcu kimdir?", secenekler: { A: "Hülya Şenyurt", B: "Nurcan Taylan", C: "Hamide Bıççın", D: "Yasemin Adar" }, dogruCevap: "A" },
    { seviye: 36, kategori: "Spor", soru: "Koca Yusuf hangi güreş türüyle dünyada ün salmıştır?", secenekler: { A: "Yağlı Güreş / Karakucak", B: "Grekoromen", C: "Serbest Stil", D: "Sambo" }, dogruCevap: "A" },
    { seviye: 37, kategori: "Spor", soru: "Türkiye'nin kış olimpiyatlarındaki ilk sporcusu hangi branştadır?", secenekler: { A: "Kayak", B: "Buz Pateni", C: "Körling", D: "Buz Hokeyi" }, dogruCevap: "A" },
    { seviye: 38, kategori: "Spor", soru: "Tekvandoda Olimpiyat ikincisi olan ünlü kadın sporcumuz?", secenekler: { A: "Nur Tatar", B: "Servet Tazegül", C: "Merve Dinçel", D: "Hatice Kübra İlgün" }, dogruCevap: "A" },
    { seviye: 39, kategori: "Spor", soru: "Paralimpik oyunlarda altın madalya alan okçumuz?", secenekler: { A: "Öznur Cüre", B: "Gizem Girişmen", C: "Bahattin Hekimoğlu", D: "Yiğit Caner" }, dogruCevap: "B" },
    { seviye: 40, kategori: "Spor", soru: "Tarihi Elmalı Yağlı Güreşleri nerede düzenlenir?", secenekler: { A: "Antalya", B: "Edirne", C: "Balıkesir", D: "Manisa" }, dogruCevap: "A" },

    // 51-75: Türk Basketbolu ve Voleybolu
    { seviye: 51, kategori: "Spor", soru: "Türkiye Kadın Milli Voleybol Takımı'nın lakabı nedir?", secenekler: { A: "Filenin Sultanları", B: "Potanın Perileri", C: "12 Dev Adam", D: "Sultanlar" }, dogruCevap: "A" },
    { seviye: 52, kategori: "Spor", soru: "EuroLeague şampiyonu olan ilk Türk erkek basketbol takımı?", secenekler: { A: "Fenerbahçe", B: "Anadolu Efes", C: "Galatasaray", D: "Beşiktaş" }, dogruCevap: "A" },
    { seviye: 53, kategori: "Spor", soru: "Basketbolda '12 Dev Adam' lakabı hangi turnuvada verilmiştir?", secenekler: { A: "2001 Avrupa Şampiyonası", B: "2010 Dünya Şampiyonası", C: "2006 Dünya Şampiyonası", D: "1999 Avrupa Şampiyonası" }, dogruCevap: "A" },
    { seviye: 54, kategori: "Spor", soru: "NBA'de şampiyonluk yüzüğü takan ilk Türk basketbolcu?", secenekler: { A: "Mehmet Okur", B: "Hidayet Türkoğlu", C: "Alperen Şengün", D: "Cedi Osman" }, dogruCevap: "A" },
    { seviye: 55, kategori: "Spor", soru: "Eczacıbaşı ve VakıfBank hangi branşta dünya çapında başarıya sahiptir?", secenekler: { A: "Voleybol", B: "Hentbol", C: "Basketbol", D: "Yüzme" }, dogruCevap: "A" },
    { seviye: 56, kategori: "Spor", soru: "Dünya voleybolunda 'En Değerli Oyuncu' (MVP) seçilen milli sporcumuz?", secenekler: { A: "Melissa Vargas", B: "Eda Erdem", C: "Zehra Güneş", D: "Gizem Örge" }, dogruCevap: "A" },
    { seviye: 57, kategori: "Spor", soru: "NBA'de bir maçta en çok sayı atan Türk oyuncu (rekor)?", secenekler: { A: "Alperen Şengün", B: "Mehmet Okur", C: "Hidayet Türkoğlu", D: "Ersan İlyasova" }, dogruCevap: "A" },
    { seviye: 58, kategori: "Spor", soru: "Fenerbahçe Kadın Basketbol Takımı'nın Avrupa şampiyonluğu var mıdır?", secenekler: { A: "Evet (EuroLeague)", B: "Hayır", C: "Sadece EuroCup", D: "Sadece Türkiye Kupası" }, dogruCevap: "A" },
    { seviye: 59, kategori: "Spor", soru: "A Milli Erkek Basketbol Takımı, 2010 Dünya Şampiyonası'nda kaçıncı olmuştur?", secenekler: { A: "İkinci", B: "Üçüncü", C: "Dördüncü", D: "Şampiyon" }, dogruCevap: "A" },
    { seviye: 60, kategori: "Spor", soru: "Milli voleybolcumuz Eda Erdem'in heykeli hangi stadın önüne dikilmiştir?", secenekler: { A: "Ülker Stadyumu", B: "Vakıfbank Spor Sarayı", C: "Burhan Felek", D: "Sinan Erdem" }, dogruCevap: "A" },
    { seviye: 61, kategori: "Spor", soru: "Avrupa şampiyonu olan ilk Türk voleybol takımı?", secenekler: { A: "Eczacıbaşı", B: "Vakıfbank", C: "Arkas", D: "Halkbank" }, dogruCevap: "A" },
    { seviye: 62, kategori: "Spor", soru: "Potanın Perileri hangi milli takıma verilen isimdir?", secenekler: { A: "Kadın Basketbol", B: "Kadın Voleybol", C: "Kadın Hentbol", D: "Kadın Futbol" }, dogruCevap: "A" },
    { seviye: 63, kategori: "Spor", soru: "Türk basketbolunun 'Profesör' lakaplı efsane koçu kimdir?", secenekler: { A: "Aydın Örs", B: "Ergin Ataman", C: "Erman Kunter", D: "Çetin Yılmaz" }, dogruCevap: "A" },
    { seviye: 64, kategori: "Spor", soru: "Ergin Ataman, Panathinaikos'tan önce hangi Türk takımıyla 2 EuroLeague kazandı?", secenekler: { A: "Anadolu Efes", B: "Fenerbahçe", C: "Galatasaray", D: "Beşiktaş" }, dogruCevap: "A" },
    { seviye: 65, kategori: "Spor", soru: "Hidayet Türkoğlu NBA'de hangi takımda efsaneleşmiştir?", secenekler: { A: "Orlando Magic", B: "Sacramento Kings", C: "Toronto Raptors", D: "L.A. Clippers" }, dogruCevap: "A" },
    { seviye: 66, kategori: "Spor", soru: "Neslihan Demir hangi branşın 'Demir Leydi'si olarak bilinir?", secenekler: { A: "Voleybol", B: "Tenis", C: "Boks", D: "Eskrim" }, dogruCevap: "A" },
    { seviye: 67, kategori: "Spor", soru: "Vakıfbank Kadın Voleybol Takımı kaç kez CEV Şampiyonlar Ligi şampiyonu olmuştur?", secenekler: { A: "6", B: "3", C: "2", D: "1" }, dogruCevap: "A" },
    { seviye: 68, kategori: "Spor", soru: "Gözde Kırdar hangi takımın sembol voleybolcusudur?", secenekler: { A: "Vakıfbank", B: "Eczacıbaşı", C: "Fenerbahçe", D: "Galatasaray" }, dogruCevap: "A" },
    { seviye: 69, kategori: "Spor", soru: "Dünya Şampiyonası'nda 'Sayı Kralı' olan Türk basketbolcu?", secenekler: { A: "Erman Kunter", B: "Harun Erdenay", C: "İbrahim Kutluay", D: "Ömer Onan" }, dogruCevap: "A" },
    { seviye: 70, kategori: "Spor", soru: "Türkiye'nin en eski spor kulübü hangisidir?", secenekler: { A: "Beşiktaş (1903)", B: "Galatasaray (1905)", C: "Fenerbahçe (1907)", D: "İstanbulspor" }, dogruCevap: "A" },

    // 76-100: Dünya Sporundan Seçmeler
    { seviye: 76, kategori: "Spor", soru: "Dünya Kupası'nı en çok kazanan ülke hangisidir?", secenekler: { A: "Brezilya", B: "Almanya", C: "İtalya", D: "Arjantin" }, dogruCevap: "A" },
    { seviye: 77, kategori: "Spor", soru: "Ballon d'Or ödülünü en çok kazanan futbolcu kimdir?", secenekler: { A: "Lionel Messi", B: "C. Ronaldo", C: "Pele", D: "Zidane" }, dogruCevap: "A" },
    { seviye: 78, kategori: "Spor", soru: "Olimpiyat halkalarında toplam kaç renk bulunur?", secenekler: { A: "5", B: "6", C: "4", D: "7" }, dogruCevap: "A" },
    { seviye: 79, kategori: "Spor", soru: "Basketbolun mucidi kimdir?", secenekler: { A: "James Naismith", B: "David Stern", C: "Michael Jordan", D: "Phil Jackson" }, dogruCevap: "A" },
    { seviye: 80, kategori: "Spor", soru: "Maraton koşusunun mesafesi ne kadardır?", secenekler: { A: "42.195 m", B: "40.000 m", C: "21.000 m", D: "50.000 m" }, dogruCevap: "A" },
    { seviye: 81, kategori: "Spor", soru: "Formula 1'de 7 dünya şampiyonluğu olan pilotlar?", secenekler: { A: "Schumacher - Hamilton", B: "Senna - Prost", C: "Vettel - Alonso", D: "Verstappen - Leclerc" }, dogruCevap: "A" },
    { seviye: 82, kategori: "Spor", soru: "Teniste 'Toprak Kort' kralı kimdir?", secenekler: { A: "Rafael Nadal", B: "Roger Federer", C: "Novak Djokovic", D: "Carlos Alcaraz" }, dogruCevap: "A" },
    { seviye: 83, kategori: "Spor", soru: "NBA tarihinin en çok sayı atan oyuncusu?", secenekler: { A: "LeBron James", B: "Kareem Abdul-Jabbar", C: "Michael Jordan", D: "Kobe Bryant" }, dogruCevap: "A" },
    { seviye: 84, kategori: "Spor", soru: "Usain Bolt'un 100 metre dünya rekoru derecesi nedir?", secenekler: { A: "9.58", B: "9.69", C: "9.72", D: "9.80" }, dogruCevap: "A" },
    { seviye: 85, kategori: "Spor", soru: "Sumo güreşi hangi ülkenin milli sporudur?", secenekler: { A: "Japonya", B: "Çin", C: "Güney Kore", D: "Moğolistan" }, dogruCevap: "A" },
    { seviye: 86, kategori: "Spor", soru: "Modern Olimpiyatlar ilk kez nerede yapılmıştır?", secenekler: { A: "Atina", B: "Paris", C: "Londra", D: "Roma" }, dogruCevap: "A" },
    { seviye: 87, kategori: "Spor", soru: "Boksör Muhammed Ali'nin eski adı nedir?", secenekler: { A: "Cassius Clay", B: "Joe Frazier", C: "George Foreman", D: "Mike Tyson" }, dogruCevap: "A" },
    { seviye: 88, kategori: "Spor", soru: "Hangi ülke 2022 Dünya Kupası şampiyonu olmuştur?", secenekler: { A: "Arjantin", B: "Fransa", C: "Hırvatistan", D: "Fas" }, dogruCevap: "A" },
    { seviye: 89, kategori: "Spor", soru: "Teniste bir yıl içinde tüm Grand Slamleri kazanmaya ne denir?", secenekler: { A: "Grand Slam", B: "Golden Slam", C: "Masters", D: "Tie-Break" }, dogruCevap: "A" },
    { seviye: 90, kategori: "Spor", soru: "Olimpiyat meşalesi nerede yakılır?", secenekler: { A: "Olimpiya Dağı", B: "Atina Stadyumu", C: "Ev sahibi şehir", D: "Roma" }, dogruCevap: "A" },
    { seviye: 91, kategori: "Spor", soru: "Futbolda sarı ve kırmızı kart ilk kez hangi yıl kullanıldı?", secenekler: { A: "1970", B: "1966", C: "1974", D: "1960" }, dogruCevap: "A" },
    { seviye: 92, kategori: "Spor", soru: "Michael Phelps hangi branşta rekor madalya sahibidir?", secenekler: { A: "Yüzme", B: "Atletizm", C: "Jimnastik", D: "Kürek" }, dogruCevap: "A" },
    { seviye: 93, kategori: "Spor", soru: "Tour de France (Fransa Bisiklet Turu) lideri hangi renk mayo giyer?", secenekler: { A: "Sarı", B: "Pembe", C: "Kırmızı", D: "Yeşil" }, dogruCevap: "A" },
    { seviye: 94, kategori: "Spor", soru: "Badminton topuna ne ad verilir?", secenekler: { A: "Shuttlecock", B: "Puck", C: "Birdie", D: "A ve C" }, dogruCevap: "D" },
    { seviye: 95, kategori: "Spor", soru: "Amerikan futbolu final maçına ne ad verilir?", secenekler: { A: "Super Bowl", B: "World Series", C: "NBA Finals", D: "Stanley Cup" }, dogruCevap: "A" },
    { seviye: 96, kategori: "Spor", soru: "Eskrimde kullanılan üç silahtan biri?", secenekler: { A: "Flöre", B: "Ok", C: "Mızrak", D: "Süngü" }, dogruCevap: "A" },
    { seviye: 97, kategori: "Spor", soru: "Tiger Woods hangi sporda efsanedir?", secenekler: { A: "Golf", B: "Tenis", C: "Bilardo", D: "Yüzme" }, dogruCevap: "A" },
    { seviye: 98, kategori: "Spor", soru: "Körling (Curling) sporu nerede oynanır?", secenekler: { A: "Buz", B: "Çim", C: "Kum", D: "Su" }, dogruCevap: "A" },
    { seviye: 99, kategori: "Spor", soru: "Dünya Kupası tarihinde en çok gol atan oyuncu?", secenekler: { A: "Miroslav Klose", B: "Ronaldo", C: "Pele", D: "Messi" }, dogruCevap: "A" },
    { seviye: 100, kategori: "Spor", soru: "Satrançta bir maçta yapılabilecek en kısa mat kaç hamledir?", secenekler: { A: "2", B: "3", C: "4", D: "1" }, dogruCevap: "A" }, 
    // 101-150: Karışık Spor Dalları, Rekorlar ve Olimpiyatlar
    { seviye: 101, kategori: "Spor", soru: "Modern Olimpiyat Oyunları ilk kez hangi şehirde düzenlenmiştir?", secenekler: { A: "Atina", B: "Paris", C: "Londra", D: "Roma" }, dogruCevap: "A" },
    { seviye: 102, kategori: "Spor", soru: "Voleybolda sahada her takımdan kaç oyuncu bulunur?", secenekler: { A: "5", B: "6", C: "7", D: "11" }, dogruCevap: "B" },
    { seviye: 103, kategori: "Spor", soru: "Hangi ülke 2022 FIFA Dünya Kupası şampiyonu olmuştur?", secenekler: { A: "Fransa", B: "Brezilya", C: "Arjantin", D: "Fas" }, dogruCevap: "C" },
    { seviye: 104, kategori: "Spor", soru: "Teniste 'Grand Slam' kazanan ilk Türk tenisçi kimdir (Gençler kategorisi)?", secenekler: { A: "İpek Soylu", B: "Marsel İlhan", C: "Çağla Büyükakçay", D: "Melis Sezer" }, dogruCevap: "A" },
    { seviye: 105, kategori: "Spor", soru: "Basketbolda bir periyot NBA standartlarında kaç dakikadır?", secenekler: { A: "10", B: "12", C: "15", D: "8" }, dogruCevap: "B" },
    { seviye: 106, kategori: "Spor", soru: "Hangi spor dalında 'triple-double' terimi kullanılır?", secenekler: { A: "Voleybol", B: "Basketbol", C: "Hentbol", D: "Su Topu" }, dogruCevap: "B" },
    { seviye: 107, kategori: "Spor", soru: "Formula 1 tarihinde en çok şampiyonluk yaşayan iki pilottan biri hangisidir?", secenekler: { A: "Lewis Hamilton", B: "Max Verstappen", C: "Sebastian Vettel", D: "Fernando Alonso" }, dogruCevap: "A" },
    { seviye: 108, kategori: "Spor", soru: "Masa tenisinde bir set kaç sayıda biter?", secenekler: { A: "11", B: "15", C: "21", D: "25" }, dogruCevap: "A" },
    { seviye: 109, kategori: "Spor", soru: "Dünya Kupası'nı hem oyuncu hem teknik direktör olarak kazanan isimlerden biri hangisidir?", secenekler: { A: "Didier Deschamps", B: "Zinedine Zidane", C: "Diego Maradona", D: "Pele" }, dogruCevap: "A" },
    { seviye: 110, kategori: "Spor", soru: "Bisiklet sporunda dünyanın en prestijli yarışı hangisidir?", secenekler: { A: "Tour de France", B: "Giro d'Italia", C: "Vuelta a España", D: "Tour of Türkiye" }, dogruCevap: "A" },
    { seviye: 111, kategori: "Spor", soru: "2024 Olimpiyat Oyunları hangi şehirde düzenlenecektir?", secenekler: { A: "Tokyo", B: "Paris", C: "Los Angeles", D: "Brisbane" }, dogruCevap: "B" },
    { seviye: 112, kategori: "Spor", soru: "Hangi branş 'sporların anası' olarak kabul edilir?", secenekler: { A: "Yüzme", B: "Atletizm", C: "Jimnastik", D: "Güreş" }, dogruCevap: "B" },
    { seviye: 113, kategori: "Spor", soru: "Snooker (Bilardo) oyununda en yüksek puanlı top hangi renktir?", secenekler: { A: "Mavi", B: "Pembe", C: "Siyah", D: "Kırmızı" }, dogruCevap: "C" },
    { seviye: 114, kategori: "Spor", soru: "Türkiye'nin olimpiyatlarda kazandığı ilk altın madalya hangi branştadır?", secenekler: { A: "Güreş", B: "Halter", C: "Okçuluk", D: "Boks" }, dogruCevap: "A" },
    { seviye: 115, kategori: "Spor", soru: "NBA'de tüm zamanların en çok sayı atan oyuncusu kimdir?", secenekler: { A: "Kareem Abdul-Jabbar", B: "Michael Jordan", C: "LeBron James", D: "Kobe Bryant" }, dogruCevap: "C" },
    { seviye: 116, kategori: "Spor", soru: "Hentbolda bir maç kaç dakikadır?", secenekler: { A: "40", B: "50", C: "60", D: "90" }, dogruCevap: "C" },
    { seviye: 117, kategori: "Spor", soru: "Yüzmede 'kelebek' stili kaç metrelik yarışlarda başlar?", secenekler: { A: "50", B: "100", C: "200", D: "400" }, dogruCevap: "A" },
    { seviye: 118, kategori: "Spor", soru: "Dünya ağır sıklet boks şampiyonu 'Iron' lakaplı sporcu kimdir?", secenekler: { A: "Muhammad Ali", B: "Mike Tyson", C: "Anthony Joshua", D: "Tyson Fury" }, dogruCevap: "B" },
    { seviye: 119, kategori: "Spor", soru: "Voleybolda savunma oyuncusuna (farklı renk forma giyen) ne ad verilir?", secenekler: { A: "Libero", B: "Pasör", C: "Smaçör", D: "Orta Oyuncu" }, dogruCevap: "A" },
    { seviye: 120, kategori: "Spor", soru: "Buz hokeyinde oyunun oynandığı diske ne ad verilir?", secenekler: { A: "Top", B: "Puck", C: "Mermer", D: "Küre" }, dogruCevap: "B" },
    { seviye: 121, kategori: "Spor", soru: "Wimbledon Tenis Turnuvası hangi zemin üzerinde oynanır?", secenekler: { A: "Toprak", B: "Çim", C: "Sert", D: "Halı" }, dogruCevap: "B" },
    { seviye: 122, kategori: "Spor", soru: "Bir maraton koşusu tam olarak kaç kilometredir?", secenekler: { A: "42.195", B: "40", C: "45", D: "38.5" }, dogruCevap: "A" },
    { seviye: 123, kategori: "Spor", soru: "Okçulukta hedefin tam ortasına (10 puan) ne ad verilir?", secenekler: { A: "Göz", B: "Onluk", C: "Merkez", D: "Bulls-eye" }, dogruCevap: "D" },
    { seviye: 124, kategori: "Spor", soru: "Satrançta en güçlü taş hangisidir?", secenekler: { A: "Şah", B: "Vezir", C: "Kale", D: "At" }, dogruCevap: "B" },
    { seviye: 125, kategori: "Spor", soru: "Kış Olimpiyatları kaç yılda bir düzenlenir?", secenekler: { A: "2", B: "3", C: "4", D: "5" }, dogruCevap: "C" },
    { seviye: 126, kategori: "Spor", soru: "Brezilyalı efsane futbolcu Pele kaç kez Dünya Kupası kazanmıştır?", secenekler: { A: "1", B: "2", C: "3", D: "4" }, dogruCevap: "C" },
    { seviye: 127, kategori: "Spor", soru: "NBA takımlarından Chicago Bulls'un efsanevi 23 numaralı oyuncusu kimdir?", secenekler: { A: "Michael Jordan", B: "Scottie Pippen", C: "Dennis Rodman", D: "Derrick Rose" }, dogruCevap: "A" },
    { seviye: 128, kategori: "Spor", soru: "Sumo güreşi hangi ülkenin milli sporudur?", secenekler: { A: "Çin", B: "Japonya", C: "Güney Kore", D: "Tayland" }, dogruCevap: "B" },
    { seviye: 129, kategori: "Spor", soru: "Golfte topun deliğe girmesi için yapılan son vuruşa ne denir?", secenekler: { A: "Drive", B: "Swing", C: "Putt", D: "Chip" }, dogruCevap: "C" },
    { seviye: 130, kategori: "Spor", soru: "2008 Pekin Olimpiyatları'nda 8 altın madalya kazanan efsane yüzücü kimdir?", secenekler: { A: "Michael Phelps", B: "Ian Thorpe", C: "Ryan Lochte", D: "Caeleb Dressel" }, dogruCevap: "A" },
    { seviye: 131, kategori: "Spor", soru: "Hangi futbolcu daha fazla Ballon d'Or ödülüne sahiptir?", secenekler: { A: "Lionel Messi", B: "Cristiano Ronaldo", C: "Johan Cruyff", D: "Michel Platini" }, dogruCevap: "A" },
    { seviye: 132, kategori: "Spor", soru: "Eskrimde hangi silah türü tüm vücudu hedef olarak kabul eder?", secenekler: { A: "Flöre", B: "Epe", C: "Sable", D: "Kılıç" }, dogruCevap: "B" },
    { seviye: 133, kategori: "Spor", soru: "Türkiye'nin ilk yerli yarış otomobilinin adı nedir?", secenekler: { A: "Anadol", B: "Devrim", C: "Etox", D: "Volkicar" }, dogruCevap: "D" },
    { seviye: 134, kategori: "Spor", soru: "Hangi branşta 'smaç' terimi kullanılmaz?", secenekler: { A: "Voleybol", B: "Basketbol", C: "Tenis", D: "Futbol" }, dogruCevap: "D" },
    { seviye: 135, kategori: "Spor", soru: "Beyzbolda bir takımın tüm kaleleri dolaşarak kazandığı puana ne denir?", secenekler: { A: "Home Run", B: "Touchdown", C: "Goal", D: "Strike" }, dogruCevap: "A" },
    { seviye: 136, kategori: "Spor", soru: "Amerikan Futbolu'nda bir 'Touchdown' kaç puandır?", secenekler: { A: "3", B: "6", C: "7", D: "2" }, dogruCevap: "B" },
    { seviye: 137, kategori: "Spor", soru: "Hangi tenis turnuvası 'Toprak Kortun Kralı' olarak bilinen Rafael Nadal ile özdeşleşmiştir?", secenekler: { A: "Roland Garros", B: "Australian Open", C: "US Open", D: "Wimbledon" }, dogruCevap: "A" },
    { seviye: 138, kategori: "Spor", soru: "Bowlingde tüm lobutları tek seferde devirmeye ne denir?", secenekler: { A: "Spare", B: "Strike", C: "Split", D: "Perfect" }, dogruCevap: "B" },
    { seviye: 139, kategori: "Spor", soru: "Hangi ülke futbol milli takımı 'Gök Mavililer' (Azzurri) lakabıyla anılır?", secenekler: { A: "İtalya", B: "Fransa", C: "Arjantin", D: "Uruguay" }, dogruCevap: "A" },
    { seviye: 140, kategori: "Spor", soru: "Su topunda bir takım kaleci dahil kaç oyuncudan oluşur?", secenekler: { A: "6", B: "7", C: "8", D: "11" }, dogruCevap: "B" },
    { seviye: 141, kategori: "Spor", soru: "Körling (Curling) sporu nerede oynanır?", secenekler: { A: "Çim", B: "Kum", C: "Buz", D: "Su" }, dogruCevap: "C" },
    { seviye: 142, kategori: "Spor", soru: "Usain Bolt'un 100 metre dünya rekoru derecesi kaçtır?", secenekler: { A: "9.58", B: "9.69", C: "9.72", D: "9.81" }, dogruCevap: "A" },
    { seviye: 143, kategori: "Spor", soru: "Hangi branşta 'servis' ile oyuna başlanmaz?", secenekler: { A: "Voleybol", B: "Tenis", C: "Badminton", D: "Basketbol" }, dogruCevap: "D" },
    { seviye: 144, kategori: "Spor", soru: "Jimnastikte denge aleti üzerinde hangi sporcular yarışır?", secenekler: { A: "Sadece Erkekler", B: "Sadece Kadınlar", C: "Hem Erkek hem Kadın", D: "Karma Takımlar" }, dogruCevap: "B" },
    { seviye: 145, kategori: "Spor", soru: "Türkiye'nin Avrupa Şampiyonu olan Kadın Voleybol Milli Takımı'nın lakabı?", secenekler: { A: "Filenin Sultanları", B: "Potanın Perileri", C: "Demir Pençeler", D: "Altın Kızlar" }, dogruCevap: "A" },
    { seviye: 146, kategori: "Spor", soru: "Bir boks maçında nakavt için hakem kaça kadar sayar?", secenekler: { A: "5", B: "8", C: "10", D: "12" }, dogruCevap: "C" },
    { seviye: 147, kategori: "Spor", soru: "Hangi ülke Ragbi sporunun ana vatanı kabul edilir?", secenekler: { A: "ABD", B: "İngiltere", C: "Yeni Zelanda", D: "Avustralya" }, dogruCevap: "B" },
    { seviye: 148, kategori: "Spor", soru: "Bilardoda beyaz topa vurulan sopaya ne denir?", secenekler: { A: "Istaka", B: "Raket", C: "Sopa", D: "Kulüp" }, dogruCevap: "A" },
    { seviye: 149, kategori: "Spor", soru: "Mete Gazoz hangi branşta Olimpiyat Şampiyonu olmuştur?", secenekler: { A: "Jimnastik", B: "Okçuluk", C: "Atıcılık", D: "Eskrim" }, dogruCevap: "B" },
    { seviye: 150, kategori: "Spor", soru: "Hangi spor dalında 'ofsait' kuralı yoktur?", secenekler: { A: "Futbol", B: "Buz Hokeyi", C: "Basketbol", D: "Çim Hokeyi" }, dogruCevap: "C" }, 
    // 149-318: Yeni Spor Soruları
    { seviye: 149, kategori: "Spor", soru: "Modern Olimpiyat Oyunları ilk kez hangi yıl düzenlenmiştir?", secenekler: { A: "1896", B: "1900", C: "1912", D: "1924" }, dogruCevap: "A" },
    { seviye: 150, kategori: "Spor", soru: "Basketbolda bir periyot kaç dakikadır (NBA hariç)?", secenekler: { A: "8", B: "10", C: "12", D: "15" }, dogruCevap: "B" },
    { seviye: 151, kategori: "Spor", soru: "Hangi ülke 2022 FIFA Dünya Kupası'nı kazanmıştır?", secenekler: { A: "Fransa", B: "Arjantin", C: "Hırvatistan", D: "Fas" }, dogruCevap: "B" },
    { seviye: 152, kategori: "Spor", soru: "Tenis maçlarında 'Sıfır' puanı hangi kelimeyle ifade edilir?", secenekler: { A: "Love", B: "Zero", C: "Nil", D: "Void" }, dogruCevap: "A" },
    { seviye: 153, kategori: "Spor", soru: "Formula 1'de en çok şampiyonluk yaşayan (7 kez) iki pilot kimdir?", secenekler: { A: "M. Schumacher - L. Hamilton", B: "A. Senna - S. Vettel", C: "N. Lauda - M. Verstappen", D: "F. Alonso - K. Raikkonen" }, dogruCevap: "A" },
    { seviye: 154, kategori: "Spor", soru: "Hentbol maçında bir takım kaç oyuncuyla sahada yer alır?", secenekler: { A: "5", B: "6", C: "7", D: "11" }, dogruCevap: "C" },
    { seviye: 155, kategori: "Spor", soru: "Süper Lig tarihinde en çok gol atan futbolcu kimdir?", secenekler: { A: "Tanju Çolak", B: "Hakan Şükür", C: "Hami Mandıralı", D: "Metin Oktay" }, dogruCevap: "B" },
    { seviye: 156, kategori: "Spor", soru: "Voleybolda bir set kaç sayıda biter (Netice seti hariç)?", secenekler: { A: "15", B: "21", C: "25", D: "30" }, dogruCevap: "C" },
    { seviye: 157, kategori: "Spor", soru: "Hangi tenis turnuvası toprak kortta oynanır?", secenekler: { A: "Wimbledon", B: "Roland Garros", C: "Avustralya Açık", D: "US Open" }, dogruCevap: "B" },
    { seviye: 158, kategori: "Spor", soru: "Türkiye'nin ilk dünya şampiyonu kadın güreşçisi kimdir?", secenekler: { A: "Yasemin Adar", B: "Buse Tosun", C: "Evrim Akın", D: "Melek Hu" }, dogruCevap: "A" },
    { seviye: 159, kategori: "Spor", soru: "NBA tarihinde tüm zamanların en çok sayı atan oyuncusu kimdir?", secenekler: { A: "Kareem Abdul-Jabbar", B: "Michael Jordan", C: "LeBron James", D: "Kobe Bryant" }, dogruCevap: "C" },
    { seviye: 160, kategori: "Spor", soru: "Buz hokeyi maçları kaç devreden oluşur?", secenekler: { A: "2", B: "3", C: "4", D: "1" }, dogruCevap: "B" },
    { seviye: 161, kategori: "Spor", soru: "Okçulukta hedefin en orta noktasının rengi nedir?", secenekler: { A: "Kırmızı", B: "Mavi", C: "Sarı", D: "Siyah" }, dogruCevap: "C" },
    { seviye: 162, kategori: "Spor", soru: "Hangi futbolcu 8 kez Ballon d'Or ödülünü kazanmıştır?", secenekler: { A: "Cristiano Ronaldo", B: "Lionel Messi", C: "Luka Modric", D: "Karim Benzema" }, dogruCevap: "B" },
    { seviye: 163, kategori: "Spor", soru: "Güreşte müsabaka yapılan alanın adı nedir?", secenekler: { A: "Ring", B: "Tatami", C: "Minder", D: "Kort" }, dogruCevap: "C" },
    { seviye: 164, kategori: "Spor", soru: "Bir beyzbol takımı kaç oyuncudan oluşur?", secenekler: { A: "9", B: "11", C: "7", D: "5" }, dogruCevap: "A" },
    { seviye: 165, kategori: "Spor", soru: "Hangi Türk basketbolcu NBA'de şampiyonluk yaşayan ilk Türk olmuştur?", secenekler: { A: "Hidayet Türkoğlu", B: "Mehmet Okur", C: "Ersan İlyasova", D: "Alperen Şengün" }, dogruCevap: "B" },
    { seviye: 166, kategori: "Spor", soru: "Olimpiyat bayrağındaki beş halka neyi temsil eder?", secenekler: { A: "Beş Kıtayı", B: "Beş Büyük Branşı", C: "Beş Okyanusu", D: "Beş Kurucu Ülkeyi" }, dogruCevap: "A" },
    { seviye: 167, kategori: "Spor", soru: "Türkiye'nin en eski spor kulübü hangisidir?", secenekler: { A: "Beşiktaş JK", B: "Galatasaray SK", C: "Fenerbahçe SK", D: "İstanbulspor" }, dogruCevap: "A" },
    { seviye: 168, kategori: "Spor", soru: "Su topu maçında bir devre kaç dakikadır?", secenekler: { A: "8", B: "10", C: "12", D: "15" }, dogruCevap: "A" },
    { seviye: 169, kategori: "Spor", soru: "Hangi ülke kriket sporunun ana vatanıdır?", secenekler: { A: "İngiltere", B: "Hindistan", C: "Avustralya", D: "Güney Afrika" }, dogruCevap: "A" },
    { seviye: 170, kategori: "Spor", soru: "Usain Bolt'un 100 metre dünya rekoru derecesi kaçtır?", secenekler: { A: "9.58", B: "9.69", C: "9.72", D: "9.81" }, dogruCevap: "A" },
    { seviye: 171, kategori: "Spor", soru: "Satrançta 'L' şeklinde hareket eden taş hangisidir?", secenekler: { A: "Kale", B: "Fil", C: "At", D: "Vezir" }, dogruCevap: "C" },
    { seviye: 172, kategori: "Spor", soru: "Voleybolda sadece savunma yapan ve farklı renk forma giyen oyuncu?", secenekler: { A: "Pasör", B: "Smaçör", C: "Libero", D: "Orta Oyuncu" }, dogruCevap: "C" },
    { seviye: 173, kategori: "Spor", soru: "Hangi futbol takımı 'Kırmızı Şeytanlar' lakabıyla bilinir?", secenekler: { A: "Manchester United", B: "Liverpool", C: "AC Milan", D: "Bayern Münih" }, dogruCevap: "A" },
    { seviye: 174, kategori: "Spor", soru: "Masa tenisinde bir set kaç sayıda biter?", secenekler: { A: "11", B: "15", C: "21", D: "25" }, dogruCevap: "A" },
    { seviye: 175, kategori: "Spor", soru: "Bisiklette 'Fransa Turu'nun liderinin giydiği formanın rengi nedir?", secenekler: { A: "Sarı", B: "Pembe", C: "Kırmızı", D: "Yeşil" }, dogruCevap: "A" },
    { seviye: 176, kategori: "Spor", soru: "Eskrimde kaç farklı silah türü vardır?", secenekler: { A: "2", B: "3", C: "4", D: "5" }, dogruCevap: "B" },
    { seviye: 177, kategori: "Spor", soru: "Badminton maçında kullanılan tüylü topun adı nedir?", secenekler: { A: "Shuttlecock", B: "Puck", C: "Birdie", D: "Smasher" }, dogruCevap: "A" },
    { seviye: 178, kategori: "Spor", soru: "NFL hangi spor dalının profesyonel ligidir?", secenekler: { A: "Amerikan Futbolu", B: "Beyzbol", C: "Buz Hokeyi", D: "Basketbol" }, dogruCevap: "A" },
    { seviye: 179, kategori: "Spor", soru: "Wimbledon Tenis Turnuvası hangi ülkede düzenlenir?", secenekler: { A: "İngiltere", B: "ABD", C: "Fransa", D: "Avustralya" }, dogruCevap: "A" },
    { seviye: 180, kategori: "Spor", soru: "Golfte topun deliğe girmesi için yapılan son vuruşa ne denir?", secenekler: { A: "Drive", B: "Swing", C: "Putt", D: "Chip" }, dogruCevap: "C" },
    { seviye: 181, kategori: "Spor", soru: "Hangi Türk teknik direktör 'İmparator' lakabıyla anılır?", secenekler: { A: "Fatih Terim", B: "Mustafa Denizli", C: "Şenol Güneş", D: "Aykut Kocaman" }, dogruCevap: "A" },
    { seviye: 182, kategori: "Spor", soru: "Bilardoda kaç tane delik vardır?", secenekler: { A: "4", B: "6", C: "8", D: "10" }, dogruCevap: "B" },
    { seviye: 183, kategori: "Spor", soru: "Boks ringi hangi şekildedir?", secenekler: { A: "Kare", B: "Daire", C: "Altıgen", D: "Sekizgen" }, dogruCevap: "A" },
    { seviye: 184, kategori: "Spor", soru: "Sumo güreşi hangi ülkenin milli sporudur?", secenekler: { A: "Çin", B: "Japonya", C: "Güney Kore", D: "Moğolistan" }, dogruCevap: "B" },
    { seviye: 185, kategori: "Spor", soru: "Michael Jordan kariyerinin büyük bölümünde hangi numaralı formayı giymiştir?", secenekler: { A: "23", B: "45", Secenek: "32", D: "33" }, dogruCevap: "A" },
    { seviye: 186, kategori: "Spor", soru: "Atletizmde 'Dekatlon' kaç farklı branştan oluşur?", secenekler: { A: "5", B: "7", C: "10", D: "12" }, dogruCevap: "C" },
    { seviye: 187, kategori: "Spor", soru: "Yüzmede 'Kurbağalama' stilinin İngilizcesi nedir?", secenekler: { A: "Freestyle", B: "Backstroke", C: "Breaststroke", D: "Butterfly" }, dogruCevap: "C" },
    { seviye: 188, kategori: "Spor", soru: "EuroLeague'i en çok kazanan (11 kez) basketbol takımı hangisidir?", secenekler: { A: "Real Madrid", B: "CSKA Moskova", C: "Panathinaikos", D: "Fenerbahçe" }, dogruCevap: "A" },
    { seviye: 189, kategori: "Spor", soru: "Hangi futbolcuya 'Kara İnci' lakabı verilmiştir?", secenekler: { A: "Pele", B: "Maradona", C: "Eusebio", D: "Garrincha" }, dogruCevap: "A" },
    { seviye: 190, kategori: "Spor", soru: "Voleybolda servis atışını karşılayan oyuncuya ne denir?", secenekler: { A: "Manşetçi", B: "Pasör çaprazı", C: "Libero", D: "Blokçu" }, dogruCevap: "A" },
    { seviye: 191, kategori: "Spor", soru: "Snooker bilardosunda en yüksek puanlı top hangi renktir?", secenekler: { A: "Siyah", B: "Pembe", C: "Mavi", D: "Kırmızı" }, dogruCevap: "A" },
    { seviye: 192, kategori: "Spor", soru: "Hangi spor dalında 'Puck' adı verilen sert lastik bir disk kullanılır?", secenekler: { A: "Buz Hokeyi", B: "Lacrosse", C: "Curling", D: "Su Topu" }, dogruCevap: "A" },
    { seviye: 193, kategori: "Spor", soru: "Beşiktaş'ın efsanevi 'Metin-Ali-Feyyaz' üçlüsündeki Feyyaz'ın soyadı nedir?", secenekler: { A: "Uçar", B: "Güler", C: "Tekin", D: "Korkmaz" }, dogruCevap: "A" },
    { seviye: 194, kategori: "Spor", soru: "Bir basketbol maçı berabere biterse uzatma süresi kaç dakikadır?", secenekler: { A: "3", B: "5", C: "10", D: "15" }, dogruCevap: "B" },
    { seviye: 195, kategori: "Spor", soru: "Okçulukta yay ile ok arasındaki gergin ipe ne denir?", secenekler: { A: "Kiriş", B: "Yay", C: "Ok", D: "Nişangah" }, dogruCevap: "A" },
    { seviye: 196, kategori: "Spor", soru: "Hangi ülke futbolda 'Sambacılar' olarak bilinir?", secenekler: { A: "Brezilya", B: "Arjantin", C: "Portekiz", D: "İspanya" }, dogruCevap: "A" },
    { seviye: 197, kategori: "Spor", soru: "Bowlingde tüm labutları ilk atışta devirmeye ne denir?", secenekler: { A: "Spare", B: "Strike", C: "Split", D: "Double" }, dogruCevap: "B" },
    { seviye: 198, kategori: "Spor", soru: "Hangi Türk güreşçi 'Yüzyılın Sporcusu' unvanına sahiptir?", secenekler: { A: "Hamza Yerlikaya", B: "Naim Süleymanoğlu", C: "Taha Akgül", D: "Rıza Kayaalp" }, dogruCevap: "A" },
    { seviye: 199, kategori: "Spor", soru: "Wimbledon'da maç sırasında oyuncuların giymesi zorunlu olan renk?", secenekler: { A: "Beyaz", B: "Sarı", C: "Mavi", D: "Kırmızı" }, dogruCevap: "A" },
    { seviye: 200, kategori: "Spor", soru: "Futbolda kale direkleri arasındaki mesafe kaç metredir?", secenekler: { A: "7.32", B: "7.50", C: "8.00", D: "7.00" }, dogruCevap: "A" },
    { seviye: 201, kategori: "Spor", soru: "Sualtı Ragbisi kaç metre derinlikte oynanır?", secenekler: { A: "1-2 metre", B: "3-5 metre", C: "7-10 metre", D: "15-20 metre" }, dogruCevap: "B" },
    { seviye: 202, kategori: "Spor", soru: "Hangi tenisçi 'Toprağın Kralı' lakabıyla bilinir?", secenekler: { A: "Roger Federer", B: "Rafael Nadal", C: "Novak Djokovic", D: "Andy Murray" }, dogruCevap: "B" },
    { seviye: 203, kategori: "Spor", soru: "Beşli ganyan oyununda kaç koşunun birincisini bilmek gerekir?", secenekler: { A: "4", B: "5", C: "6", D: "3" }, dogruCevap: "B" },
    { seviye: 204, kategori: "Spor", soru: "Judoda en yüksek kuşak rengi hangisidir?", secenekler: { A: "Siyah", B: "Kırmızı", C: "Beyaz", D: "Kahverengi" }, dogruCevap: "B" },
    { seviye: 205, kategori: "Spor", soru: "Kış Olimpiyatları kaç yılda bir düzenlenir?", secenekler: { A: "2", B: "4", C: "5", D: "6" }, dogruCevap: "B" },
    { seviye: 206, kategori: "Spor", soru: "Futbolda bir takımın oyuncu değişikliği hakkı kural olarak kaçtır (Güncel)?", secenekler: { A: "3", B: "5", C: "6", D: "4" }, dogruCevap: "B" },
    { seviye: 207, kategori: "Spor", soru: "Hangi NBA takımı 'The Lakers' lakabını kullanır?", secenekler: { A: "Chicago", B: "Los Angeles", C: "Miami", D: "Boston" }, dogruCevap: "B" },
    { seviye: 208, kategori: "Spor", soru: "Bir golf sahasında standart olarak kaç delik bulunur?", secenekler: { A: "9", B: "12", C: "18", D: "24" }, dogruCevap: "C" },
    { seviye: 209, kategori: "Spor", soru: "At yarışlarında jokeylerin bindiği erkek ata ne denir?", secenekler: { A: "Aygır", B: "Kısrak", C: "Tay", D: "Beygir" }, dogruCevap: "A" },
    { seviye: 210, kategori: "Spor", soru: "Hangi spor dalında 'Yedi metre atışı' cezası vardır?", secenekler: { A: "Basketbol", B: "Hentbol", C: "Futbol", D: "Su Topu" }, dogruCevap: "B" },
    { seviye: 211, kategori: "Spor", soru: "Türkiye Basketbol Ligi'nin en çok şampiyon olan takımı?", secenekler: { A: "Anadolu Efes", B: "Fenerbahçe", C: "Galatasaray", D: "Eczacıbaşı" }, dogruCevap: "A" },
    { seviye: 212, kategori: "Spor", soru: "Hangi futbolcu 'El Pibe de Oro' (Altın Çocuk) lakabıyla bilinir?", secenekler: { A: "Maradona", B: "Messi", C: "Pele", D: "Ronaldo" }, dogruCevap: "A" },
    { seviye: 213, kategori: "Spor", soru: "Sörf sporunun ana vatanı neresidir?", secenekler: { A: "Hawaii", B: "Avustralya", C: "Brezilya", D: "Güney Afrika" }, dogruCevap: "A" },
    { seviye: 214, kategori: "Spor", soru: "Masa tenisinde topun ağırlığı yaklaşık kaç gramdır?", secenekler: { A: "2.7", B: "5.0", C: "10.0", D: "1.5" }, dogruCevap: "A" },
    { seviye: 215, kategori: "Spor", soru: "Körling (Curling) sporunda zeminde ne kullanılır?", secenekler: { A: "Buz", B: "Çim", C: "Kum", D: "Toprak" }, dogruCevap: "A" },
    { seviye: 216, kategori: "Spor", soru: "Bir maraton koşusunun tam mesafesi nedir?", secenekler: { A: "42.195 km", B: "40.000 km", C: "21.100 km", D: "50.000 km" }, dogruCevap: "A" },
    { seviye: 217, kategori: "Spor", soru: "Hangi spor branşında 'İp, Çember, Top, Labut ve Kurdele' kullanılır?", secenekler: { A: "Ritmik Jimnastik", B: "Artistik Jimnastik", C: "Bale", D: "Senkronize Yüzme" }, dogruCevap: "A" },
    { seviye: 218, kategori: "Spor", soru: "Süper Lig'de 'Dört Büyükler' dışında şampiyon olan ilk takım?", secenekler: { A: "Trabzonspor", B: "Bursaspor", C: "Başakşehir", D: "Eskişehirspor" }, dogruCevap: "A" },
    { seviye: 219, kategori: "Spor", soru: "Badmintonda maça nasıl başlanır?", secenekler: { A: "Servis ile", B: "Hava atışı ile", C: "Kale seçimi ile", D: "Pas ile" }, dogruCevap: "A" },
    { seviye: 220, kategori: "Spor", soru: "Karate sporunda kullanılan kıyafetin adı nedir?", secenekler: { A: "Karategi", B: "Kimono", C: "Hakam", D: "Dobok" }, dogruCevap: "A" },
    { seviye: 221, kategori: "Spor", soru: "Hangi futbolcu 'Uçan Hollandalı' lakabıyla bilinir?", secenekler: { A: "Johan Cruyff", B: "Marco van Basten", C: "Robin van Persie", D: "Arjen Robben" }, dogruCevap: "A" },
    { seviye: 222, kategori: "Spor", soru: "Bilardoda 'Bant' neye denir?", secenekler: { A: "Masanın kenarlarına", B: "Istakanın ucuna", C: "Topların rengine", D: "Deliğin içine" }, dogruCevap: "A" },
    { seviye: 223, kategori: "Spor", soru: "Amerikan Futbolu maçları kaç çeyrekten oluşur?", secenekler: { A: "4", B: "2", C: "3", D: "1" }, dogruCevap: "A" },
    { seviye: 224, kategori: "Spor", soru: "Bir voleybol file yüksekliği (Erkekler için) kaç metredir?", secenekler: { A: "2.43", B: "2.24", C: "2.50", D: "2.35" }, dogruCevap: "A" },
    { seviye: 225, kategori: "Spor", soru: "Hangi spor dalında 'Caddie' adı verilen yardımcılar vardır?", secenekler: { A: "Golf", B: "Tenis", C: "Polo", D: "Kriket" }, dogruCevap: "A" },
    { seviye: 226, kategori: "Spor", soru: "Patenli sürat pateni yarışları nerede yapılır?", secenekler: { A: "Velodrom", B: "Pist", C: "Ring", D: "Oval" }, dogruCevap: "D" },
    { seviye: 227, kategori: "Spor", soru: "Hangi takım NBA'de en çok şampiyonluk kazanan (18 kez) takımdır?", secenekler: { A: "Boston Celtics", B: "LA Lakers", C: "Golden State", D: "Chicago Bulls" }, dogruCevap: "A" },
    { seviye: 228, kategori: "Spor", soru: "Taekwondo'da 'Dobok' neyi ifade eder?", secenekler: { A: "Kıyafet", B: "Kuşak", C: "Tekme", D: "Selam" }, dogruCevap: "A" },
    { seviye: 229, kategori: "Spor", soru: "Su topunda kalecinin bone rengi genellikle nedir?", secenekler: { A: "Kırmızı", B: "Mavi", C: "Beyaz", D: "Sarı" }, dogruCevap: "A" },
    { seviye: 230, kategori: "Spor", soru: "Formula 1'de damalı bayrak ne anlama gelir?", secenekler: { A: "Yarışın bittiği", B: "Tehlike olduğu", C: "Pite girilmesi gerektiği", D: "Geçiş yasağı" }, dogruCevap: "A" },
    { seviye: 231, kategori: "Spor", soru: "Bir futbol maçında topun tamamı kale çizgisini geçerse ne olur?", secenekler: { A: "Gol", B: "Aut", C: "Korner", D: "Devam" }, dogruCevap: "A" },
    { seviye: 232, kategori: "Spor", soru: "Hangi şehir 3 kez Yaz Olimpiyatları'na ev sahipliği yapmıştır?", secenekler: { A: "Londra", B: "Paris", C: "Atina", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 233, kategori: "Spor", soru: "Zinedine Zidane aslen hangi ülke kökenlidir?", secenekler: { A: "Cezayir", B: "Fas", C: "Tunus", D: "Mısır" }, dogruCevap: "A" },
    { seviye: 234, kategori: "Spor", soru: "Hangi spor dalında 'Double-Double' terimi kullanılır?", secenekler: { A: "Basketbol", B: "Tenis", C: "Voleybol", D: "Futbol" }, dogruCevap: "A" },
    { seviye: 235, kategori: "Spor", soru: "Okçulukta okun arkasındaki tüylere ne ad verilir?", secenekler: { A: "Yele", B: "Kanat", C: "Fletch", D: "Süper" }, dogruCevap: "C" },
    { seviye: 236, kategori: "Spor", soru: "Krikette topu vuran oyuncuya ne denir?", secenekler: { A: "Batsman", B: "Bowler", C: "Keeper", D: "Fielder" }, dogruCevap: "A" },
    { seviye: 237, kategori: "Spor", soru: "Hangi Türk güreşçi 'Boğazın Boğası' lakabıyla tanınır?", secenekler: { A: "Sinan Şamil Sam", B: "Selçuk Çebi", C: "Rıza Kayaalp", D: "Hamza Yerlikaya" }, dogruCevap: "A" },
    { seviye: 238, kategori: "Spor", soru: "Bilardoda beyaz topa ne ad verilir?", secenekler: { A: "Cue Ball", B: "Striker", C: "Master", D: "Hedef" }, dogruCevap: "A" },
    { seviye: 239, kategori: "Spor", soru: "Bir hentbol maçının süresi ne kadardır?", secenekler: { A: "30+30 dk", B: "45+45 dk", C: "20+20 dk", D: "15x4 dk" }, dogruCevap: "A" },
    { seviye: 240, kategori: "Spor", soru: "Hangi futbol takımı 'Panzerler' olarak bilinir?", secenekler: { A: "Almanya", B: "Hollanda", C: "Belçika", D: "İsveç" }, dogruCevap: "A" },
    { seviye: 241, kategori: "Spor", soru: "Voleybolda bir takımın toplam kaç mola hakkı vardır (Set başı)?", secenekler: { A: "2", B: "1", C: "3", D: "4" }, dogruCevap: "A" },
    { seviye: 242, kategori: "Spor", soru: "Eskrimde kullanılan giysinin rengi nedir?", secenekler: { A: "Beyaz", B: "Siyah", C: "Gri", D: "Mavi" }, dogruCevap: "A" },
    { seviye: 243, kategori: "Spor", soru: "Teniste 'Deuce' ne anlama gelir?", secenekler: { A: "40-40 Beraberlik", B: "Oyun Sonu", C: "Hatalı Servis", D: "Set Sonu" }, dogruCevap: "A" },
    { seviye: 244, kategori: "Spor", soru: "Hangi sporda 'Handikap' terimi sıkça kullanılır?", secenekler: { A: "At Yarışı", B: "Yüzme", C: "Okçuluk", D: "Eskrim" }, dogruCevap: "A" },
    { seviye: 245, kategori: "Spor", soru: "Türkiye'nin ilk kadın Olimpiyat şampiyonu kimdir?", secenekler: { A: "Hülya Şenyurt", B: "Nurcan Taylan", C: "Yasemin Adar", D: "Merve Dizdar" }, dogruCevap: "B" },
    { seviye: 246, kategori: "Spor", soru: "Buz pateninde 'Triple Axel' hareketi kaç tur dönüş içerir?", secenekler: { A: "3.5", B: "3", C: "2.5", D: "4" }, dogruCevap: "A" },
    { seviye: 247, kategori: "Spor", soru: "Futbolda korner atışı nereden kullanılır?", secenekler: { A: "Köşe gönderinden", B: "Ceza sahasından", C: "Taç çizgisinden", D: "Kale arkasından" }, dogruCevap: "A" },
    { seviye: 248, kategori: "Spor", soru: "Hangi ülke beyzbol sporunun merkezidir?", secenekler: { A: "ABD", B: "Küba", C: "Japonya", D: "Kanada" }, dogruCevap: "A" },
    { seviye: 249, kategori: "Spor", soru: "Dama oyununda taşlar nasıl hareket eder?", secenekler: { A: "İleri", B: "Çapraz", C: "L şeklinde", D: "Geri" }, dogruCevap: "A" },
    { seviye: 250, kategori: "Spor", soru: "Hangi Türk basketbolcu NBA'de All-Star seçilen ilk Türk olmuştur?", secenekler: { A: "Mehmet Okur", B: "Hidayet Türkoğlu", C: "Alperen Şengün", D: "Cedi Osman" }, dogruCevap: "A" },
    { seviye: 251, kategori: "Spor", soru: "Dinamit lakaplı futbolcu kimdir?", secenekler: { A: "Hami Mandıralı", B: "Roberto Carlos", C: "Ronald Koeman", D: "Sinan Kaloğlu" }, dogruCevap: "A" },
    { seviye: 252, kategori: "Spor", soru: "Olimpiyatlarda altın madalya gerçekte neyden yapılır?", secenekler: { A: "Gümüş üzerine altın kaplama", B: "Saf altın", C: "Bakır ve altın karışımı", D: "Çelik üzerine altın" }, dogruCevap: "A" },
    { seviye: 253, kategori: "Spor", soru: "Hangi tenisçi 'Ekselansları' lakabıyla anılır?", secenekler: { A: "Roger Federer", B: "Bjorn Borg", C: "Andre Agassi", D: "Pete Sampras" }, dogruCevap: "A" },
    { seviye: 254, kategori: "Spor", soru: "Süper Lig'de en çok gol kralı olan futbolcu kimdir?", secenekler: { A: "Metin Oktay", B: "Tanju Çolak", C: "Hakan Şükür", D: "Burak Yılmaz" }, dogruCevap: "A" },
    { seviye: 255, kategori: "Spor", soru: "Badmintonda file yüksekliği yaklaşık kaç metredir?", secenekler: { A: "1.55", B: "2.00", C: "1.20", D: "1.80" }, dogruCevap: "A" },
    { seviye: 256, kategori: "Spor", soru: "Karate'de 'Sensei' kime denir?", secenekler: { A: "Öğretmen", B: "Öğrenci", C: "Hakem", D: "Rakip" }, dogruCevap: "A" },
    { seviye: 257, kategori: "Spor", soru: "Hangi branşta 'Mavi Kart' uygulaması (geçici oyun dışı) vardır?", secenekler: { A: "Hentbol", B: "Basketbol", C: "Voleybol", D: "Futbol" }, dogruCevap: "A" },
    { seviye: 258, kategori: "Spor", soru: "Bir maratonu 2 saatin altında koşan ilk atlet kimdir?", secenekler: { A: "Eliud Kipchoge", B: "Haile Gebrselassie", C: "Usain Bolt", D: "Mo Farah" }, dogruCevap: "A" },
    { seviye: 259, kategori: "Spor", soru: "Bilardoda topları dağıtmak için kullanılan üçgenin adı?", secenekler: { A: "Rack", B: "Triangle", C: "Frame", D: "Set" }, dogruCevap: "A" },
    { seviye: 260, kategori: "Spor", soru: "Hangi futbolcu 'Sarı Fare' lakabıyla bilinir?", secenekler: { A: "Johan Cruyff", B: "Pavel Nedved", C: "Fernando Torres", D: "Guti" }, dogruCevap: "A" },
    { seviye: 261, kategori: "Spor", soru: "NBA'de bir takımın hücum süresi kaç saniyedir?", secenekler: { A: "24", B: "14", C: "30", D: "35" }, dogruCevap: "A" },
    { seviye: 262, kategori: "Spor", soru: "Hangi spor branşı 'Kuvvet, Çeviklik ve Esneklik' üzerine kuruludur?", secenekler: { A: "Jimnastik", B: "Güreş", C: "Boks", D: "Hentbol" }, dogruCevap: "A" },
    { seviye: 263, kategori: "Spor", soru: "Snooker'da kaç tane kırmızı top vardır?", secenekler: { A: "15", B: "10", C: "21", D: "6" }, dogruCevap: "A" },
    { seviye: 264, kategori: "Spor", soru: "Atıcılıkta kullanılan silahın mermisine ne denir?", secenekler: { A: "Saçma", B: "Kurşun", C: "Ok", D: "Pelet" }, dogruCevap: "D" },
    { seviye: 265, kategori: "Spor", soru: "Hangi futbol takımı 'Kuzeyin Kralı' lakabını kullanır?", secenekler: { A: "Rosenborg", B: "Malmö", C: "FC Copenhagen", D: "Zenit" }, dogruCevap: "A" },
    { seviye: 266, kategori: "Spor", soru: "Bir sumo güreşçisine ne ad verilir?", secenekler: { A: "Rikishi", B: "Yokozuna", C: "Sensei", D: "Dojo" }, dogruCevap: "A" },
    { seviye: 267, kategori: "Spor", soru: "Sörf tahtasının üzerine sürülerek kaymayı önleyen madde?", secenekler: { A: "Vaks (Wax)", B: "Yağ", C: "Pudra", D: "Reçine" }, dogruCevap: "A" },
    { seviye: 268, kategori: "Spor", soru: "Hangi tenis turnuvası her yıl New York'ta düzenlenir?", secenekler: { A: "Amerika Açık", B: "Wimbledon", C: "Fransa Açık", D: "Miami Açık" }, dogruCevap: "A" },
    { seviye: 269, kategori: "Spor", soru: "Güreşte 'Tuş' neyi ifade eder?", secenekler: { A: "Müsabakanın bitmesini", B: "Puan almayı", C: "Faul yapmayı", D: "Devre arasını" }, dogruCevap: "A" },
    { seviye: 270, kategori: "Spor", soru: "Hangi spor dalında 'Triple-Double' yapılamaz?", secenekler: { A: "Futbol", B: "Basketbol", C: "Voleybol", D: "Hepsi" }, dogruCevap: "A" },
    { seviye: 271, kategori: "Spor", soru: "Atatürk'ün 'Ben sporcunun zeki, çevik ve aynı zamanda ... severim' sözündeki boşluk?", secenekler: { A: "Ahlaklısını", B: "Dürüstünü", C: "Çalışkanını", D: "Saygılısını" }, dogruCevap: "A" },
    { seviye: 272, kategori: "Spor", soru: "Voleybolda saha ölçüleri kaç metredir?", secenekler: { A: "9x18", B: "10x20", C: "8x16", D: "12x24" }, dogruCevap: "A" },
    { seviye: 273, kategori: "Spor", soru: "Hangi futbolcuya 'Örümcek' lakabı verilmiştir (Kaleci)?", secenekler: { A: "Lev Yaşin", B: "Buffon", C: "Casillas", D: "Neuer" }, dogruCevap: "A" },
    { seviye: 274, kategori: "Spor", soru: "Bisiklet sporunda 'Sprint' ne demektir?", secenekler: { A: "Hızlı bitiriş", B: "Yavaş sürüş", C: "Yokuş çıkma", D: "Mola verme" }, dogruCevap: "A" },
    { seviye: 275, kategori: "Spor", soru: "Körling oyununda buzu süpürmek neyi sağlar?", secenekler: { A: "Taşın daha uzağa gitmesini", B: "Taşın durmasını", C: "Taşın yön değiştirmesini", D: "Buzun parlamasını" }, dogruCevap: "A" },
    { seviye: 276, kategori: "Spor", soru: "Hangi basketbolcu 'The Black Mamba' lakabıyla bilinir?", secenekler: { A: "Kobe Bryant", B: "Shaquille O'Neal", C: "Allen Iverson", D: "Kevin Durant" }, dogruCevap: "A" },
    { seviye: 277, kategori: "Spor", soru: "Boks maçlarında dişleri koruyan aparatın adı nedir?", secenekler: { A: "Dişlik", B: "Kask", C: "Eldiven", D: "Bandaj" }, dogruCevap: "A" },
    { seviye: 278, kategori: "Spor", soru: "Hangi ülke futbol milli takımı 'Gök Mavililer' (Azzurri) olarak anılır?", secenekler: { A: "İtalya", B: "Fransa", C: "Yunanistan", D: "Uruguay" }, dogruCevap: "A" },
    { seviye: 279, kategori: "Spor", soru: "Yüzmede 'Kelebek' stilinde kollar nasıl hareket eder?", secenekler: { A: "Aynı anda ileri", B: "Sırayla ileri", C: "Sadece suyun altından", D: "Hareket etmez" }, dogruCevap: "A" },
    { seviye: 280, kategori: "Spor", soru: "Golfte 'Birdie' ne demektir?", secenekler: { A: "Par altı 1 vuruş", B: "Par üzeri 1 vuruş", C: "Deliğe girmesi", D: "Topun kaybolması" }, dogruCevap: "A" },
    { seviye: 281, kategori: "Spor", soru: "Hangi Türk takımı basketbolda üst üste 2 kez EuroLeague şampiyonu olmuştur?", secenekler: { A: "Anadolu Efes", B: "Fenerbahçe", C: "Galatasaray", D: "Beşiktaş" }, dogruCevap: "A" },
    { seviye: 282, kategori: "Spor", soru: "Masa tenisi raketinin her iki yüzü aynı renk olabilir mi?", secenekler: { A: "Hayır (Biri siyah biri kırmızı)", B: "Evet", C: "Sadece profesyonel liglerde", D: "Hakem onaylarsa" }, dogruCevap: "A" },
    { seviye: 283, kategori: "Spor", soru: "Hangi spor branşında 'İp atlamak' antrenmanın temelidir?", secenekler: { A: "Boks", B: "Futbol", C: "Basketbol", D: "Yüzme" }, dogruCevap: "A" },
    { seviye: 284, kategori: "Spor", soru: "Rugby topu ne şekildedir?", secenekler: { A: "Oval", B: "Yuvarlak", C: "Kare", D: "Üçgen" }, dogruCevap: "A" },
    { seviye: 285, kategori: "Spor", soru: "Hangi futbolcuya 'Profesör' lakabı takılmıştır?", secenekler: { A: "Arsene Wenger", B: "Andrea Pirlo", C: "Clarence Seedorf", D: "Pep Guardiola" }, dogruCevap: "A" },
    { seviye: 286, kategori: "Spor", soru: "Bowlingde en ağır top kaç 'pound' (libre) olabilir?", secenekler: { A: "16", B: "10", C: "20", D: "25" }, dogruCevap: "A" },
    { seviye: 287, kategori: "Spor", soru: "Okçulukta 'Sadak' nedir?", secenekler: { A: "Okların konulduğu torba", B: "Yayın adı", C: "Hedef tahtası", D: "Parmak koruyucu" }, dogruCevap: "A" },
    { seviye: 288, kategori: "Spor", soru: "Hangi tenis turnuvası sezonun ilk Grand Slam'idir?", secenekler: { A: "Avustralya Açık", B: "Fransa Açık", C: "Wimbledon", D: "US Open" }, dogruCevap: "A" },
    { seviye: 289, kategori: "Spor", soru: "Voleybolda bir setin 'tie-break'e (netice) gitmesi için skor ne olmalıdır?", secenekler: { A: "2-2 set beraberliği", B: "24-24 puan beraberliği", C: "1-1 set beraberliği", D: "Mola kalmaması" }, dogruCevap: "A" },
    { seviye: 290, kategori: "Spor", soru: "Hangi Türk güreşçi Olimpiyatlarda en çok madalya (3) kazanan güreşçimizdir?", secenekler: { A: "Rıza Kayaalp", B: "Hamza Yerlikaya", C: "Mithat Bayrak", D: "Mustafa Dağıstanlı" }, dogruCevap: "A" },
    { seviye: 291, kategori: "Spor", soru: "Bilardoda 'Istaka' nedir?", secenekler: { A: "Vuruş yapılan sopa", B: "Masadaki delik", C: "Beyaz top", D: "Masadaki tebeşir" }, dogruCevap: "A" },
    { seviye: 292, kategori: "Spor", soru: "Hangi futbol takımı 'Horozlar' lakabıyla bilinir?", secenekler: { A: "Fransa", B: "Portekiz", C: "Belçika", D: "Denizlispor" }, dogruCevap: "A" },
    { seviye: 293, kategori: "Spor", soru: "Bir basketbol sahası kaç metre uzunluğundadır?", secenekler: { A: "28", B: "30", C: "25", D: "32" }, dogruCevap: "A" },
    { seviye: 294, kategori: "Spor", soru: "Hangi spor dalında 'Servis' atılırken topu elden çıkarmak zorunludur?", secenekler: { A: "Tenis", B: "Voleybol", C: "Masa Tenisi", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 295, kategori: "Spor", soru: "Dama oyununda kaç taşla başlanır?", secenekler: { A: "16", B: "12", C: "20", D: "24" }, dogruCevap: "A" },
    { seviye: 296, kategori: "Spor", soru: "Hangi spor dalında 'Ofsayt' kuralı yoktur?", secenekler: { A: "Basketbol", B: "Futbol", C: "Buz Hokeyi", D: "Hentbol" }, dogruCevap: "A" },
    { seviye: 297, kategori: "Spor", soru: "Atletizmde 'Finiş' ne demektir?", secenekler: { A: "Bitiş çizgisi", B: "Başlangıç", C: "Bayrak yarışı", D: "Engel" }, dogruCevap: "A" },
    { seviye: 298, kategori: "Spor", soru: "Hangi dövüş sanatı 'Yumuşaklık Yolu' anlamına gelir?", secenekler: { A: "Judo", B: "Karate", C: "Kung-Fu", D: "Kick-Boks" }, dogruCevap: "A" },
    { seviye: 299, kategori: "Spor", soru: "Süper Lig'de 'Yüzler Kulübü'ne giren ilk yabancı futbolcu?", secenekler: { A: "Alex de Souza", B: "Gheorghe Hagi", C: "Bafetimbi Gomis", D: "Elvir Boliç" }, dogruCevap: "A" },
    { seviye: 300, kategori: "Spor", soru: "Dünyanın en yüksek seyirci kapasiteli stadı hangi ülkededir?", secenekler: { A: "Kuzey Kore", B: "Brezilya", C: "İspanya", D: "ABD" }, dogruCevap: "A" },
    { seviye: 301, kategori: "Spor", soru: "Formula 1'de pit stop sırasında tekerlek değiştiren ekibe ne denir?", secenekler: { A: "Pit ekibi", B: "Servis ekibi", C: "Hız ekibi", D: "Lastikçiler" }, dogruCevap: "A" },
    { seviye: 302, kategori: "Spor", soru: "Hangi spor dalında 'Eagles' (Kartallar) adında bir NFL takımı vardır?", secenekler: { A: "Amerikan Futbolu", B: "Basketbol", C: "Beyzbol", D: "Hokey" }, dogruCevap: "A" },
    { seviye: 303, kategori: "Spor", soru: "Voleybolda bir maç en fazla kaç set oynanabilir?", secenekler: { A: "5", B: "3", C: "4", D: "7" }, dogruCevap: "A" },
    { seviye: 304, kategori: "Spor", soru: "Hangi spor branşında 'Hava atışı' ile başlanır?", secenekler: { A: "Basketbol", B: "Voleybol", C: "Hentbol", D: "Futbol" }, dogruCevap: "A" },
    { seviye: 305, kategori: "Spor", soru: "Snooker'da pembe topun puan değeri kaçtır?", secenekler: { A: "6", B: "5", C: "7", D: "4" }, dogruCevap: "A" },
    { seviye: 306, kategori: "Spor", soru: "Hangi Türk halterci 'Cep Herkülü' olarak bilinir?", secenekler: { A: "Naim Süleymanoğlu", B: "Halil Mutlu", C: "Taner Sağır", D: "Nurcan Taylan" }, dogruCevap: "A" },
    { seviye: 307, kategori: "Spor", soru: "Bir tenis maçı en fazla kaç set sürer (Erkekler Grand Slam)?", secenekler: { A: "5", B: "3", C: "4", D: "7" }, dogruCevap: "A" },
    { seviye: 308, kategori: "Spor", soru: "Hangi ülke futbol milli takımı 'Boğalar' lakabıyla anılır?", secenekler: { A: "İspanya", B: "İtalya", C: "Meksika", D: "Arjantin" }, dogruCevap: "A" },
    { seviye: 309, kategori: "Spor", soru: "Golfte topun çimler üzerindeki yerine ne denir?", secenekler: { A: "Fairway", B: "Green", C: "Rough", D: "Tee" }, dogruCevap: "A" },
    { seviye: 310, kategori: "Spor", soru: "Hangi spor dalında 'Smaç' (Slam Dunk) terimi kullanılır?", secenekler: { A: "Basketbol", B: "Hentbol", C: "Futbol", D: "Masa Tenisi" }, dogruCevap: "A" },
    { seviye: 311, kategori: "Spor", soru: "Beşiktaş'ın stadı olan Vodafone Park'ın şimdiki adı nedir?", secenekler: { A: "Tüpraş Stadyumu", B: "Beşiktaş Park", C: "İnönü Stadı", D: "Dolmabahçe Stadı" }, dogruCevap: "A" },
    { seviye: 312, kategori: "Spor", soru: "Hangi ülke 2024 Avrupa Futbol Şampiyonası'na ev sahipliği yapmıştır?", secenekler: { A: "Almanya", B: "İngiltere", C: "Fransa", D: "İtalya" }, dogruCevap: "A" },
    { seviye: 313, kategori: "Spor", soru: "Eskrimde hedef bölgesi sadece gövde olan silah?", secenekler: { A: "Flöre", B: "Epe", C: "Sabre", D: "Kılıç" }, dogruCevap: "A" },
    { seviye: 314, kategori: "Spor", soru: "Su topu kalesi kaç metre genişliğindedir?", secenekler: { A: "3", B: "2", C: "4", D: "5" }, dogruCevap: "A" },
    { seviye: 315, kategori: "Spor", soru: "Hangi futbolcuya 'Küçük Dev Adam' denirdi?", secenekler: { A: "Rıdvan Dilmen", B: "Emre Belözoğlu", C: "Okan Buruk", D: "Sergen Yalçın" }, dogruCevap: "A" },
    { seviye: 316, kategori: "Spor", soru: "NBA'de bir çeyrek kaç dakikadır?", secenekler: { A: "12", B: "10", C: "15", D: "8" }, dogruCevap: "A" },
    { seviye: 317, kategori: "Spor", soru: "Hangi spor branşında 'Kırkpınar' turnuvası düzenlenir?", secenekler: { A: "Yağlı Güreş", B: "Cirit", C: "Okçuluk", D: "Binicilik" }, dogruCevap: "A" },
    { seviye: 318, kategori: "Spor", soru: "Dünyanın en çok izlenen spor organizasyonu hangisidir?", secenekler: { A: "Olimpiyatlar", B: "Dünya Kupası", C: "Super Bowl", D: "F1" }, dogruCevap: "B" }
 

);
 